static const char *const k2SeqplayStringsDOSCDCzech[104] = {
	"Kyrandia miz""\xC3\xAD""!",
	"K""\xC3\xA1""men za kamenem...",
	"...a strom za stromem.",
	"Kyrandia p""\xC5\x99""est""\xC3\xA1""v""\xC3\xA1"" existovat!",
	"Kr""\xC3\xA1""lov""\xC5\xA1""t""\xC3\xAD"" mistikov""\xC3\xA9"" jsou zmaten""\xC3\xAD"".",
	"Ka""\xC5\xBE""d""\xC3\xBD"" odkaz byl konzultov""\xC3\xA1""n.",
	"Dokonce i Marko a jeho nov""\xC3\xBD"" sluha byli vpu\xC5\xA1t\xC4\x9Bni na konferenci.",
	"Na""\xC5\xA1""t""\xC4\x9B""st""\xC3\xAD"" byla Ruka v t""\xC4\x9B""chto z""\xC3\xA1""le""\xC5\xBE""itostech zku""\xC5\xA1""en""\xC3\xA1"".",
	"A nakonec byl schv""\xC3\xA1""len pl""\xC3\xA1""n...",
	"...kter""\xC3\xBD"" vy""\xC5\xBE""adoval magick""\xC3\xBD"" Kotevn""\xC3\xAD"" k""\xC3\xA1""men...",
	"...kter""\xC3\xBD"" m""\xC4\x9B""l b""\xC3\xBD""t z""\xC3\xAD""sk""\xC3\xA1""n ze st""\xC5\x99""edu sv""\xC4\x9B""ta.",
	"Zanthia, nejmlad""\xC5\xA1""""\xC3\xAD"" z kyrandijsk""\xC3\xBD""ch mystik""\xC5\xAF"", byla vybr""\xC3\xA1""na, aby z""\xC3\xAD""skala K""\xC3\xA1""men.",
	"D""\xC4\x9B""kujeme, ""\xC5\xBE""e jste hr""\xC3\xA1""li Ruku osudu.",
	"Toto by m""\xC4\x9B""lo b""\xC3\xBD""t dost bor""\xC5\xAF""vek, k otev""\xC5\x99""en""\xC3\xAD"" port""\xC3\xA1""lu do st""\xC5\x99""edu sv""\xC4\x9B""ta.",
	" DUMMY STRING... ",
	" DUMMY STRING... ",
	"Hej! V""\xC5\xA1""echno moje vybaven""\xC3\xAD"" bylo ukradeno!",
	" DUMMY STRING... ",
	"Jestli si mysl""\xC3\xAD"", ""\xC5\xBE""e celou tu cestu dol""\xC5\xAF"" p""\xC5\xAF""jdu p""\xC4\x9B""""\xC5\xA1""ky, tak jsou to cvoci!",
	" DUMMY STRING... ",
	" DUMMY STRING... ",
	"Posp""\xC4\x9B""""\xC5\xA1"" si Faune!",
	"Uf, to bylo o fous!",
	"To m""\xC3\xA1""""\xC5\xA1"" pravdu, k""\xC3\xA1""mo. J""\xC3\xA1"" osobn""\xC4\x9B"" u""\xC5\xBE"" nikdy nep""\xC5\xAF""jdu lovit!",
	"Ribbit.",
	"Kolikr""\xC3\xA1""t ti to m""\xC3\xA1""m je""\xC5\xA1""t""\xC4\x9B"" opakovat? Jsi ropucha.",
	"Ach, ne! Do""\xC5\xA1""el n""\xC3\xA1""m s""\xC3\xBD""r!",
	"Zkusme tento u""\xC5\xA1""n""\xC3\xAD"" maz. Je oran""\xC5\xBE""ov""\xC3\xBD"".",
	"Mami, kdy dostanu b""\xC5\x99""e""\xC4\x8D""""\xC5\xA5""an?",
	"Vypadni odsud!",
	"Ty ""\xC5\x99""e""\xC5\xBE""e""\xC5\xA1"" a j""\xC3\xA1"" vyb""\xC3\xAD""r""\xC3\xA1""m.",
	"Ne. Ty ""\xC5\x99""e""\xC5\xBE""e""\xC5\xA1"" a j""\xC3\xA1"" vyb""\xC3\xAD""r""\xC3\xA1""m.",
	"St""\xC3\xA1""le ""\xC5\x99""""\xC3\xAD""k""\xC3\xA1""m, ""\xC5\xBE""e to byla odvozen""\xC3\xA1"" blbost.",
	"Ach, st""\xC3\xA1""le bys nepoznal jambick""\xC3\xBD"" pentametr, i kdyby t""\xC4\x9B"" kousl do zadku!",
	"V""\xC3\xBD""konn""\xC3\xBD"" producent",
	"Brett W. Sperry",
	"Re""\xC5\xBE""ie & Design",
	"Rick Gush",
	"Hlavn""\xC3\xAD"" program""\xC3\xA1""tor",
	"Michael Legg",
	"Vizu""\xC3\xA1""ln""\xC3\xAD"" management",
	"Louis Castle",
	"Joseph B. Hewitt IV",
	"Vedouc""\xC3\xAD"" grafik",
	"Rick Parks",
	"Dodate""\xC4\x8D""n""\xC3\xA9"" programov""\xC3\xA1""n""\xC3\xAD""",
	"Philip W. Gorrow",
	"Mike Grayford",
	"Mark McCubbin",
	"Grafici",
	"Cameron Chun",
	"Cary Averett",
	"Cindy Chinn",
	"Elie Arabian",
	"Fei Cheng",
	"Ferby Miguel",
	"Frank Mendeola",
	"Jack Martin",
	"Jerry Moore",
	"DUMMY STRING... ",
	"Judith Peterson",
	"Larry Miller",
	"Lenny Lee",
	"Louise Sandoval",
	"Ren Olsen",
	"Hudba & Zvuky",
	"Paul Mudra",
	"Frank Klepacki",
	"Dwight Okahara",
	"Pat Collins",
	"Kontrola kvality",
	"Glenn Sperry",
	"Michael Lightner",
	"William Foster",
	"Jesse Clemit",
	"Jeff Fillhaber",
	"Manu""\xC3\xA1""l, Design balen""\xC3\xAD""",
	"& Expedice",
	"Eydie Laramore",
	"Lisa Marcinko",
	"Lauren Rifkin",
	"Gratulace!",
	"D""\xC4\x9B""kujeme, ""\xC5\xBE""e hrajete Ruku osudu!",
	"Extern""\xC3\xAD"" programov""\xC3\xA1""n""\xC3\xAD""",
	"Koordin""\xC3\xA1""tor s produkc""\xC3\xAD""",
	"Scott Duckett",
	"Irvine teste""\xC5\x99""i",
	"Chris McFarland",
	"Paul Moore",
	"Chad Soares",
	"Jared Brinkley",
	"Jon Willliams",
	"Chris Toft",
	"Vlasy Joe Kucana od",
	"Theodore A. Morrise",
	"Nahr""\xC3\xA1""n""\xC3\xAD"" pozice",
	"""\xC3\x9A""vodn""\xC3\xAD"" intro",
	"Zah""\xC3\xA1""jit novou hru",
	"Ukon""\xC4\x8D""it hru",
	"Speci""\xC3\xA1""ln""\xC3\xAD"" pod""\xC4\x9B""kov""\xC3\xA1""n""\xC3\xAD"" pro",
	"Sake Joe Bostic-san",
	"Tim Fritz",
	"Kenny Dunne",
	"D""\xC4\x9B""kujeme, ""\xC5\xBE""e hrajete \"Ruku osudu.\"\n"
};

static const StringListProvider k2SeqplayStringsDOSCDCzechProvider = { ARRAYSIZE(k2SeqplayStringsDOSCDCzech), k2SeqplayStringsDOSCDCzech };

static const char *const k2SeqplayTlkFilesDOSCDCzech[14] = {
	"EINTRO1",
	"EINTRO2",
	"EINTRO3",
	"EINTRO4",
	"EINTRO5",
	"EINTRO6",
	"EINTRO7",
	"EINTRO8",
	"EINTRO9",
	"EINTRO10",
	"EINTRO11",
	"EINTRO12",
	"EGLOW",
	""
};

static const StringListProvider k2SeqplayTlkFilesDOSCDCzechProvider = { ARRAYSIZE(k2SeqplayTlkFilesDOSCDCzech), k2SeqplayTlkFilesDOSCDCzech };
