static const char *const k2SeqplayStringsDOSSpanish[103] = {
	"Kyrandia esta desapareciendo!",
	"Roca tras roca...",
	"...y ""\xA0""rbol tras ""\xA0""rbol.",
	"Kyrandia deja de existir!",
	"Los M""\xA1""sticos Reales estan desconcertados.",
	"Todas las referencia han sido consultadas",
	"Incluso Marko y su nuevo ayudante han sido invitados a la conferencia.",
	"Por suerte, la Mano tenia experiencia en estos asuntos.",
	"Y finalmente un plan ha sido aprovado...",
	"...este requiere que una m""\xA0""gica Piedra Ancla...",
	"...deba ser extraida del centro del mundo.",
	"Zanthia, la mas joven de los M""\xA1""sticos de Kyrandia, ha sido elegida para recoger la Piedra.",
	"Gracias por jugar The Hand of Fate.",
	"Estos ar""\xA0""ndanos deber""\xA1""an bastar parar abrir un portal al centro del mundo.",
	" DUMMY STRING... ",
	" DUMMY STRING... ",
	"Hey! Me han robado todo mi equipo!",
	" DUMMY STRING... ",
	"Si piensan que voy a ir caminando hasta ah""\xA1"" est""\xA0""n locos!",
	" DUMMY STRING... ",
	" DUMMY STRING... ",
	"Vamos Faun!",
	"Chico, eso estuvo cerca!",
	"Me lo dijiste. Por mi parte, no pienso volver a cazar jamas!",
	"Ribbit.",
	"Cuantas veces tengo que repetirtelo? Eres un sapo.",
	"Oh no! Nos hemos quedado sin queso!",
	"Probemos este cerumen. Es naranja.",
	"Mama, cuando tendr""\x82"" la hiedra?",
	"Fuera de aqu""\xA1"", Uhhh!",
	"Tu cortas, y yo elijo.",
	"No. TU cortas y YO elijo.",
	"Sigo diciendo que no tenia ni idea de lo que hablaba.",
	"No reconocerias un pent""\xA0""metro y""\xA0""mbico ni aunque te picara en el trasero!",
	"Productor Ejecutivo",
	"Brett W. Sperry",
	"Direccion y Diseno",
	"Rick Gush",
	"Programador Principal",
	"Michael Legg",
	"Gestion artistica",
	"Louis Castle",
	"Joseph B. Hewitt IV",
	"Artista principal",
	"Rick Parks",
	"Programacion adicional",
	"Philip W. Gorrow",
	"Mike Grayford",
	"Mark McCubbin",
	"Artistas",
	"Cameron Chun",
	"Cary Averett",
	"Cindy Chinn",
	"Elie Arabian",
	"Fei Cheng",
	"Ferby Miguel",
	"Frank Mendeola",
	"Jack Martin",
	"Jerry Moore",
	"",
	"Judith Peterson",
	"Larry Miller",
	"Lenny Lee",
	"Louise Sandoval",
	"Ren Olsen",
	"Musica y Sonidos",
	"Paul Mudra",
	"Frank Klepacki",
	"Dwight Okahara",
	"Pat Collins",
	"Asesores de calidad",
	"Glenn Sperry",
	"Michael Lightner",
	"William Foster",
	"Jesse Clemit",
	"Jeff Fillhaber",
	"Manual, Diseno",
	"y Empaquetado",
	"Eydie Laramore",
	"Lisa Marcinko",
	"Lauren Rifkin",
	"Felicidades!",
	"Gracias por jugar The Hand of Fate!",
	"Programadores externos",
	"Producer Liaison",
	"Scott Duckett",
	"Irvine Testers",
	"Chris McFarland",
	"Paul Moore",
	"Chad Soares",
	"Jared Brinkley",
	"Jon Willliams",
	"Chris Toft",
	"Joe Kucan's Hair by",
	"Theodore A. Morris",
	"Cargar Partida",
	"Introducci""\xA2""n",
	"Empezar nueva partida",
	"Salir del juego",
	"Agradecimientos especiales",
	"Sake Joe Bostic-san",
	"Tim Fritz",
	"Kenny Dunne"
};

static const StringListProvider k2SeqplayStringsDOSSpanishProvider = { ARRAYSIZE(k2SeqplayStringsDOSSpanish), k2SeqplayStringsDOSSpanish };
