static const char *const k2SeqplayStringsDOSCDCzech[104] = {
	"Kyrandia mizi!",
	"Kamen za kamenem...",
	"...a strom za stromem.",
	"Kyrandia prestava existovat!",
	"Kralovsti mystikove jsou zmateni.",
	"Kazdy odkaz byl konzultovan.",
	"Dokonce i Marko a jeho novy sluha byli vpusteni na konferenci.",
	"Nastesti byla Ruka v techto zalezitostech zkusena.",
	"A nakonec byl schvalen plan...",
	"...ktery vyzadoval magicky Kotevni kamen...",
	"...ktery mel byt ziskan ze stredu sveta.",
	"Zanthia, nejmladsi z kyrandijskych mystiku, byla vybrana, aby ziskala Kamen.",
	"Dekujeme, ze jste hrali Ruku osudu.",
	"Toto by melo byt dost boruvek, k otevreni portalu do stredu sveta.",
	" DUMMY STRING... ",
	" DUMMY STRING... ",
	"Hej! Vsechno moje vybaveni bylo ukradeno!",
	" DUMMY STRING... ",
	"Jestli si mysli, ze celou tu cestu dolu pujdu pesky, tak jsou to cvoci!",
	" DUMMY STRING... ",
	" DUMMY STRING... ",
	"Pospes si Faune!",
	"Uf, to bylo o fous!",
	"To mas pravdu, kamo. Ja osobne uz nikdy nepujdu lovit!",
	"Ribbit.",
	"Kolikrat ti to mam jeste opakovat? Jsi ropucha.",
	"Ach, ne! Dosel nam syr!",
	"Zkusme tento usni maz. Je oranzovy.",
	"Mami, kdy dostanu brectan?",
	"Vypadni odsud!",
	"Ty rezes a ja vybiram.",
	"Ne. Ty rezes a ja vybiram.",
	"Stale rikam, ze to byla odvozena blbost.",
	"Ach, stale bys nepoznal jambicky pentametr, i kdyby te kousl do zadku!",
	"Vykonny producent",
	"Brett W. Sperry",
	"Rezie & Design",
	"Rick Gush",
	"Hlavni programator",
	"Michael Legg",
	"Vizualni management",
	"Louis Castle",
	"Joseph B. Hewitt IV",
	"Vedouci grafik",
	"Rick Parks",
	"Dodatecne programovani",
	"Philip W. Gorrow",
	"Mike Grayford",
	"Mark McCubbin",
	"Grafici",
	"Cameron Chun",
	"Cary Averett",
	"Cindy Chinn",
	"Elie Arabian",
	"Fei Cheng",
	"Ferby Miguel",
	"Frank Mendeola",
	"Jack Martin",
	"Jerry Moore",
	"DUMMY STRING... ",
	"Judith Peterson",
	"Larry Miller",
	"Lenny Lee",
	"Louise Sandoval",
	"Ren Olsen",
	"Hudba & Zvuky",
	"Paul Mudra",
	"Frank Klepacki",
	"Dwight Okahara",
	"Pat Collins",
	"Kontrola kvality",
	"Glenn Sperry",
	"Michael Lightner",
	"William Foster",
	"Jesse Clemit",
	"Jeff Fillhaber",
	"Manual, Design baleni",
	"& Expedice",
	"Eydie Laramore",
	"Lisa Marcinko",
	"Lauren Rifkin",
	"Gratulace!",
	"Dekujeme, ze hrajete Ruku osudu!",
	"Externi programovani",
	"Koordinator s produkci",
	"Scott Duckett",
	"Irvine testeri",
	"Chris McFarland",
	"Paul Moore",
	"Chad Soares",
	"Jared Brinkley",
	"Jon Willliams",
	"Chris Toft",
	"Vlasy Joe Kucana od",
	"Theodore A. Morrise",
	"Nahr""\xA0""n""\xA1"" pozice",
	"""\xDA""vodn""\xA1"" intro",
	"Zah""\xA0""jit novou hru",
	"Ukon""\xE8""it hru",
	"Specialni podekovani pro",
	"Sake Joe Bostic-san",
	"Tim Fritz",
	"Kenny Dunne",
	"Dekujeme, ze hrajete \"Ruku osudu.\"\n"
};

static const StringListProvider k2SeqplayStringsDOSCDCzechProvider = { ARRAYSIZE(k2SeqplayStringsDOSCDCzech), k2SeqplayStringsDOSCDCzech };

static const char *const k2SeqplayTlkFilesDOSCDCzech[14] = {
	"EINTRO1",
	"EINTRO2",
	"EINTRO3",
	"EINTRO4",
	"EINTRO5",
	"EINTRO6",
	"EINTRO7",
	"EINTRO8",
	"EINTRO9",
	"EINTRO10",
	"EINTRO11",
	"EINTRO12",
	"EGLOW",
	""
};

static const StringListProvider k2SeqplayTlkFilesDOSCDCzechProvider = { ARRAYSIZE(k2SeqplayTlkFilesDOSCDCzech), k2SeqplayTlkFilesDOSCDCzech };
