MODULE := engines/bagel

MODULE_OBJS = \
	bagel.o \
	metaengine.o \
	music.o \
	boflib/cache.o \
	boflib/cursor_data.o \
	boflib/error.o \
	boflib/event_loop.o \
	boflib/file_functions.o \
	boflib/llist.o \
	boflib/log.o \
	boflib/misc.o \
	boflib/palette.o \
	boflib/queue.o \
	boflib/sound.o \
	boflib/string.o \
	boflib/string_functions.o \
	mfc/afx.o \
	mfc/bitmap.o \
	mfc/bitmap_button.o \
	mfc/brush.o \
	mfc/button.o \
	mfc/cmd_target.o \
	mfc/dialog.o \
	mfc/dc.o \
	mfc/doc_manager.o \
	mfc/doc_template.o \
	mfc/document.o \
	mfc/edit.o \
	mfc/file.o \
	mfc/font.o \
	mfc/frame_wnd.o \
	mfc/gdi_object.o \
	mfc/global_functions.o \
	mfc/ifstream.o \
	mfc/joystickapi.o \
	mfc/listbox.o \
	mfc/menu.o \
	mfc/object.o \
	mfc/paint_dc.o \
	mfc/palette.o \
	mfc/pen.o \
	mfc/rgn.o \
	mfc/scroll_view.o \
	mfc/scrollbar.o \
	mfc/single_doc_template.o \
	mfc/static.o \
	mfc/string.o \
	mfc/view.o \
	mfc/win_app.o \
	mfc/win_thread.o \
	mfc/wingdi.o \
	mfc/wnd.o \
	mfc/gfx/blitter.o \
	mfc/gfx/surface.o \
	mfc/gfx/cursor.o \
	mfc/gfx/dialog_template.o \
	mfc/gfx/fonts.o \
	mfc/gfx/palette_map.o \
	mfc/gfx/text_render.o \
	mfc/libs/event_loop.o \
	mfc/libs/events.o \
	mfc/libs/resources.o \
	mfc/libs/settings.o \
	spacebar/baglib/area_object.o \
	spacebar/baglib/bagel.o \
	spacebar/baglib/base_pda.o \
	spacebar/baglib/bmp_object.o \
	spacebar/baglib/button_object.o \
	spacebar/baglib/character_object.o \
	spacebar/baglib/chat_wnd.o \
	spacebar/baglib/command_object.o \
	spacebar/baglib/cursor.o \
	spacebar/baglib/dev_dlg.o \
	spacebar/baglib/dossier_object.o \
	spacebar/baglib/event_sdev.o \
	spacebar/baglib/exam.o \
	spacebar/baglib/expression.o \
	spacebar/baglib/expression_object.o \
	spacebar/baglib/fmovie.o \
	spacebar/baglib/help.o \
	spacebar/baglib/ifstream.o \
	spacebar/baglib/inv.o \
	spacebar/baglib/link_object.o \
	spacebar/baglib/log_msg.o \
	spacebar/baglib/master_win.o \
	spacebar/baglib/menu_dlg.o \
	spacebar/baglib/moo.o \
	spacebar/baglib/movie_object.o \
	spacebar/baglib/object.o \
	spacebar/baglib/paint_table.o \
	spacebar/baglib/pan_bitmap.o \
	spacebar/baglib/pan_window.o \
	spacebar/baglib/parse_object.o \
	spacebar/baglib/pda.o \
	spacebar/baglib/rp_object.o \
	spacebar/baglib/save_game_file.o \
	spacebar/baglib/sound_object.o \
	spacebar/baglib/sprite_object.o \
	spacebar/baglib/storage_dev_bmp.o \
	spacebar/baglib/storage_dev_win.o \
	spacebar/baglib/text_object.o \
	spacebar/baglib/time_object.o \
	spacebar/baglib/var.o \
	spacebar/baglib/variable_object.o \
	spacebar/baglib/wield.o \
	spacebar/baglib/zoom_pda.o \
	spacebar/boflib/app.o \
	spacebar/boflib/crc.o \
	spacebar/boflib/dat_file.o \
	spacebar/boflib/debug.o \
	spacebar/boflib/file.o \
	spacebar/boflib/options.o \
	spacebar/boflib/res.o \
	spacebar/boflib/timer.o \
	spacebar/boflib/vector.o \
	spacebar/boflib/gfx/bitmap.o \
	spacebar/boflib/gfx/cursor.o \
	spacebar/boflib/gfx/sprite.o \
	spacebar/boflib/gfx/text.o \
	spacebar/boflib/gui/button.o \
	spacebar/boflib/gui/dialog.o \
	spacebar/boflib/gui/edit_text.o \
	spacebar/boflib/gui/list_box.o \
	spacebar/boflib/gui/movie.o \
	spacebar/boflib/gui/scroll_bar.o \
	spacebar/boflib/gui/text_box.o \
	spacebar/boflib/gui/window.o \
	spacebar/dialogs/credits_dialog.o \
	spacebar/dialogs/next_cd_dialog.o \
	spacebar/dialogs/opt_window.o \
	spacebar/dialogs/quit_dialog.o \
	spacebar/dialogs/restart_dialog.o \
	spacebar/dialogs/restore_dialog.o \
	spacebar/dialogs/save_dialog.o \
	spacebar/dialogs/start_dialog.o \
	spacebar/spacebar.o \
	spacebar/bib_odds_wnd.o \
	spacebar/bibble_window.o \
	spacebar/computer.o \
	spacebar/console.o \
	spacebar/filter.o \
	spacebar/full_wnd.o \
	spacebar/main_link_object.o \
	spacebar/main_window.o \
	spacebar/master_win.o \
	spacebar/nav_window.o \
	spacebar/slot_wnd.o \
	spacebar/sraf_computer.o \
	spacebar/thud.o \
	spacebar/vid_wnd.o \
	hodjnpodj/hodjnpodj.o \
	hodjnpodj/console.o \
	hodjnpodj/gfx/bold_font.o \
	hodjnpodj/gfx/palette.o \
	hodjnpodj/hnplibs/audiocfg.o \
	hodjnpodj/hnplibs/bitmaps.o \
	hodjnpodj/hnplibs/button.o \
	hodjnpodj/hnplibs/cbofdlg.o \
	hodjnpodj/hnplibs/cmessbox.o \
	hodjnpodj/hnplibs/dibapi.o \
	hodjnpodj/hnplibs/dibdoc.o \
	hodjnpodj/hnplibs/dibfile.o \
	hodjnpodj/hnplibs/lzss.o \
	hodjnpodj/hnplibs/mainmenu.o \
	hodjnpodj/hnplibs/rules.o \
	hodjnpodj/hnplibs/sprite.o \
	hodjnpodj/hnplibs/text.o \
	hodjnpodj/libs/vector.o \
	hodjnpodj/metagame/bgen/backpack.o \
	hodjnpodj/metagame/bgen/bbt.o \
	hodjnpodj/metagame/bgen/bdbg.o \
	hodjnpodj/metagame/bgen/bgb.o \
	hodjnpodj/metagame/bgen/bgenut.o \
	hodjnpodj/metagame/bgen/bsutl.o \
	hodjnpodj/metagame/bgen/btimeut.o \
	hodjnpodj/metagame/bgen/c1btndlg.o \
	hodjnpodj/metagame/bgen/c2btndlg.o \
	hodjnpodj/metagame/bgen/invent.o \
	hodjnpodj/metagame/bgen/item.o \
	hodjnpodj/metagame/bgen/mgstat.o \
	hodjnpodj/metagame/bgen/note.o \
	hodjnpodj/metagame/bgen/notebook.o \
	hodjnpodj/metagame/demo/app.o \
	hodjnpodj/metagame/demo/hodjpodj.o \
	hodjnpodj/metagame/frame/app.o \
	hodjnpodj/metagame/frame/hodjpodj.o \
	hodjnpodj/metagame/frame/maindlg.o \
	hodjnpodj/metagame/frame/movytmpl.o \
	hodjnpodj/metagame/frame/msudlg.o \
	hodjnpodj/metagame/grand_tour/init.o \
	hodjnpodj/metagame/grand_tour/dialogs.o \
	hodjnpodj/metagame/grand_tour/grand_tour.o \
	hodjnpodj/metagame/gtl/init.o \
	hodjnpodj/metagame/gtl/citemdlg.o \
	hodjnpodj/metagame/gtl/cmapdlg.o \
	hodjnpodj/metagame/gtl/cturndlg.o \
	hodjnpodj/metagame/gtl/encount.o \
	hodjnpodj/metagame/gtl/gtl.o \
	hodjnpodj/metagame/gtl/gtlcmp.o \
	hodjnpodj/metagame/gtl/gtlcpl.o \
	hodjnpodj/metagame/gtl/gtldoc.o \
	hodjnpodj/metagame/gtl/gtlfrm.o \
	hodjnpodj/metagame/gtl/gtllex.o \
	hodjnpodj/metagame/gtl/gtlmanp.o \
	hodjnpodj/metagame/gtl/gtlmgm.o \
	hodjnpodj/metagame/gtl/gtlmve.o \
	hodjnpodj/metagame/gtl/gtlui.o \
	hodjnpodj/metagame/gtl/gtlview.o \
	hodjnpodj/metagame/gtl/optdlg.o \
	hodjnpodj/metagame/gtl/pawn.o \
	hodjnpodj/metagame/gtl/rules.o \
	hodjnpodj/metagame/gtl/spinner.o \
	hodjnpodj/metagame/gtl/store.o \
	hodjnpodj/metagame/saves/savegame.o \
	hodjnpodj/metagame/saves/savegame_info.o \
	hodjnpodj/metagame/saves/restdlg.o \
	hodjnpodj/metagame/saves/savedlg.o \
	hodjnpodj/metagame/zoom/init.o \
	hodjnpodj/metagame/zoom/zoommap.o \
	hodjnpodj/archeroids/init.o \
	hodjnpodj/archeroids/main.o \
	hodjnpodj/artparts/init.o \
	hodjnpodj/artparts/artparts.o \
	hodjnpodj/artparts/optndlg.o \
	hodjnpodj/archeroids/usercfg.o \
	hodjnpodj/barbershop/animate.o \
	hodjnpodj/barbershop/init.o \
	hodjnpodj/barbershop/barb.o \
	hodjnpodj/barbershop/board.o \
	hodjnpodj/barbershop/card.o \
	hodjnpodj/barbershop/deck.o \
	hodjnpodj/barbershop/jay.o \
	hodjnpodj/barbershop/logic.o \
	hodjnpodj/barbershop/main.o \
	hodjnpodj/barbershop/paint.o \
	hodjnpodj/barbershop/stack.o \
	hodjnpodj/barbershop/stats.o \
	hodjnpodj/barbershop/undo.o \
	hodjnpodj/barbershop/usercfg.o \
	hodjnpodj/battlefish/init.o \
	hodjnpodj/battlefish/bfish.o \
	hodjnpodj/battlefish/usercfg.o \
	hodjnpodj/beacon/init.o \
	hodjnpodj/beacon/beacon.o \
	hodjnpodj/beacon/optndlg.o \
	hodjnpodj/crypt/init.o \
	hodjnpodj/crypt/crypt.o \
	hodjnpodj/crypt/main.o \
	hodjnpodj/crypt/optn.o \
	hodjnpodj/crypt/pnt_gram.o \
	hodjnpodj/crypt/rec.o \
	hodjnpodj/crypt/stats.o \
	hodjnpodj/dfa/init.o \
	hodjnpodj/dfa/dfa.o \
	hodjnpodj/dfa/msgdlg.o \
	hodjnpodj/dfa/optdlg.o \
	hodjnpodj/fuge/init.o \
	hodjnpodj/fuge/fuge.o \
	hodjnpodj/fuge/usercfg.o \
	hodjnpodj/garfunkle/init.o \
	hodjnpodj/garfunkle/garfunkle.o \
	hodjnpodj/garfunkle/note.o \
	hodjnpodj/garfunkle/optndlg.o \
	hodjnpodj/life/init.o \
	hodjnpodj/life/game.o \
	hodjnpodj/life/grid.o \
	hodjnpodj/life/life.o \
	hodjnpodj/life/usercfg.o \
	hodjnpodj/mankala/init.o \
	hodjnpodj/mankala/bgenut.o \
	hodjnpodj/mankala/btimeut.o \
	hodjnpodj/mankala/mnk.o \
	hodjnpodj/mankala/mnklog.o \
	hodjnpodj/mankala/mnkopt.o \
	hodjnpodj/mankala/mnkui.o \
	hodjnpodj/mazedoom/init.o \
	hodjnpodj/mazedoom/mod.o \
	hodjnpodj/mazedoom/optndlg.o \
	hodjnpodj/novacancy/init.o \
	hodjnpodj/novacancy/main.o \
	hodjnpodj/packrat/init.o \
	hodjnpodj/packrat/msgdlg.o \
	hodjnpodj/packrat/optdlg.o \
	hodjnpodj/packrat/packrat.o \
	hodjnpodj/pdq/init.o \
	hodjnpodj/pdq/game.o \
	hodjnpodj/pdq/guess.o \
	hodjnpodj/pdq/main.o \
	hodjnpodj/pdq/usercfg.o \
	hodjnpodj/peggle/init.o \
	hodjnpodj/peggle/game.o \
	hodjnpodj/peggle/gameinit.o \
	hodjnpodj/peggle/options.o \
	hodjnpodj/peggle/optndlg.o \
	hodjnpodj/peggle/optsub.o \
	hodjnpodj/poker/init.o \
	hodjnpodj/poker/amtdlg.o \
	hodjnpodj/poker/c1btndlg.o \
	hodjnpodj/poker/optdlg.o \
	hodjnpodj/poker/poffsdlg.o \
	hodjnpodj/poker/poker.o \
	hodjnpodj/poker/uwondlg.o \
	hodjnpodj/riddles/init.o \
	hodjnpodj/riddles/riddles.o \
	hodjnpodj/riddles/usercfg.o \
	hodjnpodj/wordsearch/init.o \
	hodjnpodj/wordsearch/c1btndlg.o \
	hodjnpodj/wordsearch/clongdlg.o \
	hodjnpodj/wordsearch/msgdlg.o \
	hodjnpodj/wordsearch/optdlg.o \
	hodjnpodj/wordsearch/wordlist.o \
	hodjnpodj/wordsearch/wordsearch.o

# This module can be built as a plugin
ifeq ($(ENABLE_BAGEL), DYNAMIC_PLUGIN)
PLUGIN := 1
endif

# Include common rules
include $(srcdir)/rules.mk

# Detection objects
DETECT_OBJS += $(MODULE)/detection.o
