#
# FreeSCI/DOS Makefile
#
# 19991220              rink            created this file
#
#
TARGET  :       scicore.a

FILES   =       console.o tools.o resource.o decompress0.o decompress1.o \
                script.o vocab.o vocab_debug.o  old_objects.o sci_dos.o
		
CC	= gcc
CFLAGS	= -g -c -I../include -I../.. -D_DOS -DHAVE_LIBPNG -DHAVE_UNISTD_H

clean:
		del *.o *.a

scicore.a:      ${FILES}
		ar r scicore.a ${FILES}
