#ifndef STARTERRSC_H
#define STARTERRSC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 23:38:58  on dimanche 19 décembre 2004
//
//	Generated for file: Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"ScummVM"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainCardsButton                           1003	//(Left Origin = 135, Top Origin = 1, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 0, Font = Standard)
#define MainAboutButton                           1012	//(Left Origin = 148, Top Origin = 1, Width = 12, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainMSBitMap                              1100	//(Left Origin = 135, Top Origin = 1, Bitmap Resource ID = 1100, Usable = 0)
#define MainMSNoneBitMap                          1110	//(Left Origin = 135, Top Origin = 1, Bitmap Resource ID = 1110, Usable = 0)
#define MainUnnamed1010BitMap                     2000	//(Left Origin = 148, Top Origin = 1, Bitmap Resource ID = 2000, Usable = 1)

//	Resource: tFRM 1300
#define HelpForm                                  1300	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)

//	Resource: tFRM 1200
#define SkinsForm                                 1200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1203)
#define SkinsOKButton                             1202	//(Left Origin = 5, Top Origin = 139, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SkinsCancelButton                         1203	//(Left Origin = 43, Top Origin = 139, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SkinsDeleteButton                         1205	//(Left Origin = 119, Top Origin = 139, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SkinsBeamButton                           1206	//(Left Origin = 81, Top Origin = 139, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SkinsSoundClickCheckbox                   1204	//(Left Origin = 5, Top Origin = 118, Width = 93, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define SkinsSkinList                             1201	//(Left Origin = 5, Top Origin = 17, Width = 146, Usable = 1, Font = Standard, Visible Items = 9)

//	Resource: tFRM 1500
#define CardSlotForm                              1500	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CardSlotOkButton                          1501	//(Left Origin = 5, Top Origin = 138, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CardSlotCancelButton                      1508	//(Left Origin = 46, Top Origin = 138, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CardSlotMoveCheckbox                      1503	//(Left Origin = 4, Top Origin = 87, Width = 143, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define CardSlotDeleteCheckbox                    1505	//(Left Origin = 4, Top Origin = 99, Width = 142, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define CardSlotConfirmCheckbox                   1506	//(Left Origin = 4, Top Origin = 111, Width = 152, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define CardSlotUnnamed1504Label                  1504	//(Left Origin = 4, Top Origin = 74, Usable = 1, Font = Bold)
#define CardSlotUnnamed1507Label                  1507	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define CardSlotSlotList                          1502	//(Left Origin = 5, Top Origin = 30, Width = 146, Usable = 1, Font = Standard, Visible Items = 3)

//	Resource: tFRM 2700
#define MiscForm                                  2700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MiscOKButton                              2710	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MiscCancelButton                          2711	//(Left Origin = 46, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)

//	Resource: tFRM 2000
#define ConvertForm                               2000	//(Left Origin = 34, Top Origin = 64, Width = 91, Height = 32, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ConvertUnnamed2001Label                   2001	//(Left Origin = 7, Top Origin = 4, Usable = 1, Font = Standard)
#define ConvertUnnamed2002Label                   2002	//(Left Origin = 16, Top Origin = 16, Usable = 1, Font = Bold)

//	Resource: tFRM 2100
#define BeamForm                                  2100	//(Left Origin = 2, Top Origin = 72, Width = 156, Height = 86, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define BeamSendButton                            2105	//(Left Origin = 5, Top Origin = 69, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeamCancelButton                          2106	//(Left Origin = 47, Top Origin = 69, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeamMathlibCheckbox                       2101	//(Left Origin = 4, Top Origin = 28, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define BeamGamesCheckbox                         2103	//(Left Origin = 4, Top Origin = 40, Width = 86, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define BeamSkinCheckbox                          2104	//(Left Origin = 4, Top Origin = 52, Width = 84, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define BeamUnnamed2102Label                      2102	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)

//	Resource: tFRM 2200
#define MusicForm                                 2200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MusicOKButton                             2210	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MusicCancelButton                         2211	//(Left Origin = 46, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)

//	Resource: tFRM 2300
#define TabMusicForm                              2300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 85, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabMusicMusicCheckbox                     2301	//(Left Origin = 4, Top Origin = 24, Width = 100, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define TabMusicMultiMidiCheckbox                 2308	//(Left Origin = 4, Top Origin = 12, Width = 110, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabMusicTempoField                        2302	//(Left Origin = 54, Top Origin = 48, Width = 16, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 3, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabMusicTitleLabel                        2303	//(Left Origin = 6, Top Origin = 0, Usable = 1, Font = Bold)
#define TabMusicUnnamed2304Label                  2304	//(Left Origin = 21, Top Origin = 36, Usable = 1, Font = Standard)
#define TabMusicUnnamed2306Label                  2306	//(Left Origin = 19, Top Origin = 48, Usable = 1, Font = Standard)
#define TabMusicUnnamed2307Label                  2307	//(Left Origin = 72, Top Origin = 48, Usable = 1, Font = Standard)
#define TabMusicDriverList                        2331	//(Left Origin = 54, Top Origin = 14, Width = 65, Usable = 0, Font = Standard, Visible Items = 4)
#define TabMusicDriverPopTrigger                  2330	//(Left Origin = 54, Top Origin = 36, Width = 65, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2331)

//	Resource: tFRM 2400
#define TabSoundForm                              2400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 80, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabSoundSoundCheckbox                     2402	//(Left Origin = 4, Top Origin = 12, Width = 100, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define TabSoundUnnamed2401Label                  2401	//(Left Origin = 6, Top Origin = 0, Usable = 1, Font = Bold)
#define TabSoundUnnamed2403Label                  2403	//(Left Origin = 22, Top Origin = 24, Usable = 1, Font = Standard)
#define TabSoundRateList                          2405	//(Left Origin = 47, Top Origin = 24, Width = 55, Usable = 0, Font = Standard, Visible Items = 3)
#define TabSoundRatePopTrigger                    2404	//(Left Origin = 47, Top Origin = 24, Width = 55, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2405)

//	Resource: tFRM 2500
#define TabAudioCDForm                            2500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 95, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabAudioCDMP3Checkbox                     2502	//(Left Origin = 4, Top Origin = 12, Width = 90, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabAudioCDLengthSecsField                 2504	//(Left Origin = 112, Top Origin = 60, Width = 16, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 3, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabAudioCDFirstTrackField                 2507	//(Left Origin = 112, Top Origin = 50, Width = 16, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabAudioCDUnnamed2501Label                2501	//(Left Origin = 6, Top Origin = 0, Usable = 1, Font = Bold)
#define TabAudioCDUnnamed2503Label                2503	//(Left Origin = 20, Top Origin = 60, Usable = 1, Font = Standard)
#define TabAudioCDUnnamed2505Label                2505	//(Left Origin = 130, Top Origin = 61, Usable = 1, Font = Standard)
#define TabAudioCDUnnamed2506Label                2506	//(Left Origin = 21, Top Origin = 48, Usable = 1, Font = Standard)
#define TabAudioCDUnnamed2508Label                2508	//(Left Origin = 25, Top Origin = 24, Usable = 1, Font = Standard)
#define TabAudioCDUnnamed2511Label                2511	//(Left Origin = 21, Top Origin = 36, Usable = 1, Font = Standard)
#define TabAudioCDDriverList                      2510	//(Left Origin = 58, Top Origin = 24, Width = 90, Usable = 0, Font = Standard, Visible Items = 3)
#define TabAudioCDFormatList                      2513	//(Left Origin = 58, Top Origin = 36, Width = 70, Usable = 0, Font = Standard, Visible Items = 2)
#define TabAudioCDDriverPopTrigger                2509	//(Left Origin = 58, Top Origin = 24, Width = 90, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2510)
#define TabAudioCDFormatPopTrigger                2512	//(Left Origin = 58, Top Origin = 36, Width = 70, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2513)

//	Resource: tFRM 2600
#define TabVolumeForm                             2600	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 90, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabVolumeUnnamed2603Label                 2603	//(Left Origin = 6, Top Origin = 0, Usable = 1, Font = Bold)
#define TabVolumeUnnamed2605Label                 2605	//(Left Origin = 18, Top Origin = 12, Usable = 1, Font = Standard)
#define TabVolumeUnnamed2606Label                 2606	//(Left Origin = 26, Top Origin = 27, Usable = 1, Font = Standard)
#define TabVolumeUnnamed2607Label                 2607	//(Left Origin = 12, Top Origin = 42, Usable = 1, Font = Standard)
#define TabVolumeUnnamed2608Label                 2608	//(Left Origin = 20, Top Origin = 57, Usable = 1, Font = Standard)
#define TabVolumeUnnamed2610Label                 2610	//(Left Origin = 14, Top Origin = 72, Usable = 1, Font = Standard)
#define TabVolumeMasterSliderControl              2601	//(Left Origin = 58, Top Origin = 9, Width = 93, Height = 15, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 255, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define TabVolumeMusicSliderControl               2602	//(Left Origin = 58, Top Origin = 24, Width = 93, Height = 15, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 255, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define TabVolumeSfxSliderControl                 2604	//(Left Origin = 58, Top Origin = 39, Width = 93, Height = 15, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 255, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define TabVolumeSpeechSliderControl              2609	//(Left Origin = 58, Top Origin = 54, Width = 93, Height = 15, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 255, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define TabVolumeAudioCDSliderControl             2611	//(Left Origin = 58, Top Origin = 69, Width = 93, Height = 15, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 100, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)

//	Resource: tFRM 2800
#define TabPalmOSForm                             2800	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 100, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabPalmOSVibratorCheckbox                 2802	//(Left Origin = 4, Top Origin = 12, Width = 128, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSNoAutoOffCheckbox                2803	//(Left Origin = 4, Top Origin = 24, Width = 152, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSStdPaletteCheckbox               2804	//(Left Origin = 4, Top Origin = 36, Width = 146, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSLargerStackCheckbox              2805	//(Left Origin = 4, Top Origin = 48, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSARMCheckbox                      2806	//(Left Origin = 4, Top Origin = 72, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSLightspeedCheckbox               2807	//(Left Origin = 4, Top Origin = 84, Width = 95, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSExitLauncherCheckbox             2810	//(Left Origin = 4, Top Origin = 60, Width = 150, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabPalmOSTabTitlePalmLabel                2801	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabPalmOSLightspeedList                   2809	//(Left Origin = 96, Top Origin = 62, Width = 50, Usable = 0, Font = Standard, Visible Items = 3)
#define TabPalmOSLightspeedPopTrigger             2808	//(Left Origin = 96, Top Origin = 84, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2809)

//	Resource: tFRM 2900
#define TabScummVMForm                            2900	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 90, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabScummVMDebugCheckbox                   2904	//(Left Origin = 4, Top Origin = 12, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabScummVMDemoCheckbox                    2905	//(Left Origin = 4, Top Origin = 24, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabScummVMCopyProtectionCheckbox          2906	//(Left Origin = 4, Top Origin = 36, Width = 120, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabScummVMAltIntroCheckbox                2908	//(Left Origin = 4, Top Origin = 48, Width = 120, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabScummVMDebugLevelField                 2907	//(Left Origin = 103, Top Origin = 12, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 1, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabScummVMTabTitleScummLabel              2901	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)

//	Resource: tFRM 3000
#define GameEditForm                              3000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1411)
#define GameEditOKButton                          3020	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GameEditCancelButton                      3021	//(Left Origin = 46, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GameEditDeleteButton                      3023	//(Left Origin = 109, Top Origin = 139, Width = 42, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GameEditUnnamed3022GraffitiShift          3022	//(Left Origin = 87, Top Origin = 140)

//	Resource: tFRM 3100
#define TabGameInfoForm                           3100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 100, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabGameInfoEntryNameField                 3102	//(Left Origin = 4, Top Origin = 12, Width = 151, Height = 24, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define TabGameInfoPathField                      3104	//(Left Origin = 37, Top Origin = 38, Width = 118, Height = 24, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 150, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define TabGameInfoGameField                      3106	//(Left Origin = 37, Top Origin = 64, Width = 52, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 15, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define TabGameInfoUnnamed3101Label               3101	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabGameInfoUnnamed3103Label               3103	//(Left Origin = 11, Top Origin = 38, Usable = 1, Font = Standard)
#define TabGameInfoUnnamed3105Label               3105	//(Left Origin = 6, Top Origin = 64, Usable = 1, Font = Standard)
#define TabGameInfoUnnamed3107Label               3107	//(Left Origin = 4, Top Origin = 79, Usable = 1, Font = Standard)
#define TabGameInfoEngineList                     3109	//(Left Origin = 37, Top Origin = 57, Width = 115, Usable = 0, Font = Standard, Visible Items = 3)
#define TabGameInfoEnginePopTrigger               3108	//(Left Origin = 37, Top Origin = 79, Width = 115, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 3109)

//	Resource: tFRM 3200
#define TabGameDisplayForm                        3200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 80, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabGameDisplayFilterCheckbox              3205	//(Left Origin = 4, Top Origin = 36, Width = 80, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define TabGameDisplayFullscreenCheckbox          3206	//(Left Origin = 4, Top Origin = 24, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameDisplayAspectRatioCheckbox         3207	//(Left Origin = 4, Top Origin = 48, Width = 120, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameDisplayUnnamed3201Label            3201	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabGameDisplayUnnamed3208Label            3208	//(Left Origin = 4, Top Origin = 12, Usable = 1, Font = Standard)
#define TabGameDisplayGfxListList                 3204	//(Left Origin = 32, Top Origin = 12, Width = 75, Usable = 0, Font = Standard, Visible Items = 4)
#define TabGameDisplayGfxPopupPopTrigger          3203	//(Left Origin = 33, Top Origin = 12, Width = 75, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 3204)

//	Resource: tFRM 3300
#define TabGameOptionsForm                        3300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabGameOptionsLoadSlotCheckbox            3302	//(Left Origin = 4, Top Origin = 24, Width = 85, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameOptionsStartRoomCheckbox           3303	//(Left Origin = 4, Top Origin = 36, Width = 84, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameOptionsAmigaCheckbox               3306	//(Left Origin = 4, Top Origin = 48, Width = 81, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameOptionsSubtitlesCheckbox           3307	//(Left Origin = 4, Top Origin = 60, Width = 82, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameOptionsTalkSpeedCheckbox           3308	//(Left Origin = 4, Top Origin = 12, Width = 66, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define TabGameOptionsLoadSlotField               3304	//(Left Origin = 92, Top Origin = 24, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabGameOptionsStartRoomField              3305	//(Left Origin = 92, Top Origin = 36, Width = 18, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabGameOptionsTalkSpeedField              3309	//(Left Origin = 92, Top Origin = 12, Width = 18, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 3, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TabGameOptionsUnnamed3301Label            3301	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabGameOptionsUnnamed3314Label            3314	//(Left Origin = 88, Top Origin = 24, Usable = 1, Font = Standard)
#define TabGameOptionsUnnamed3315Label            3315	//(Left Origin = 88, Top Origin = 36, Usable = 1, Font = Standard)
#define TabGameOptionsUnnamed3316Label            3316	//(Left Origin = 88, Top Origin = 12, Usable = 1, Font = Standard)
#define TabGameOptionsUnnamed3317Label            3317	//(Left Origin = 88, Top Origin = 48, Usable = 1, Font = Standard)
#define TabGameOptionsUnnamed3318Label            3318	//(Left Origin = 88, Top Origin = 60, Usable = 1, Font = Standard)
#define TabGameOptionsLanguageList                3311	//(Left Origin = 92, Top Origin = 15, Width = 64, Usable = 0, Font = Standard, Visible Items = 5)
#define TabGameOptionsPlatformList                3313	//(Left Origin = 92, Top Origin = 14, Width = 52, Usable = 0, Font = Standard, Visible Items = 4)
#define TabGameOptionsLanguagePopTrigger          3310	//(Left Origin = 90, Top Origin = 60, Width = 65, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 3311)
#define TabGameOptionsPlatformPopTrigger          3312	//(Left Origin = 90, Top Origin = 48, Width = 65, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 3313)

//	Resource: tFRM 3400
#define ImportForm                                3400	//(Left Origin = 34, Top Origin = 64, Width = 91, Height = 32, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ImportUnnamed3401Label                    3401	//(Left Origin = 4, Top Origin = 4, Usable = 1, Font = Standard)
#define ImportUnnamed3402Label                    3402	//(Left Origin = 16, Top Origin = 16, Usable = 1, Font = Bold)

//	Resource: tFRM 1400
#define EngineForm                                1400	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define Engine0Button                             1401	//(Left Origin = 13, Top Origin = 30, Width = 130, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Engine1Button                             1402	//(Left Origin = 13, Top Origin = 45, Width = 130, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Engine2Button                             1403	//(Left Origin = 13, Top Origin = 60, Width = 130, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Engine3Button                             1404	//(Left Origin = 13, Top Origin = 75, Width = 130, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Engine4Button                             1405	//(Left Origin = 13, Top Origin = 90, Width = 130, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EngineCancelButton                        1420	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EngineUnnamed1407Label                    1407	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)

//	Resource: tFRM 4000
#define InfoForm                                  4000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define InfoOKButton                              4020	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)

//	Resource: tFRM 4100
#define TabInfoAboutForm                          4100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 125, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabInfoAboutTabTitleAboutLabel            4101	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabInfoAboutUnnamed4103Label              4103	//(Left Origin = 23, Top Origin = 58, Usable = 1, Font = Bold)
#define TabInfoAboutUnnamed4104Label              4104	//(Left Origin = 34, Top Origin = 70, Usable = 1, Font = Standard)
#define TabInfoAboutUnnamed4105Label              4105	//(Left Origin = 8, Top Origin = 82, Usable = 1, Font = Bold)

//	Resource: tFRM 4200
#define TabInfoVersionForm                        4200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 100, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabInfoVersionTabTitleAboutLabel          4201	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabInfoVersionUnnamed4202Label            4202	//(Left Origin = 10, Top Origin = 12, Usable = 1, Font = Standard)
#define TabInfoVersionUnnamed4203Label            4203	//(Left Origin = 24, Top Origin = 24, Usable = 1, Font = Standard)
#define TabInfoVersionUnnamed4204Label            4204	//(Left Origin = 4, Top Origin = 42, Usable = 1, Font = Bold)
#define TabInfoVersionUnnamed4205Label            4205	//(Left Origin = 5, Top Origin = 53, Usable = 1, Font = Standard)
#define TabInfoVersionUnnamed4206Label            4206	//(Left Origin = 4, Top Origin = 72, Usable = 1, Font = Bold)
#define TabInfoVersionUnnamed4207Label            4207	//(Left Origin = 4, Top Origin = 84, Usable = 1, Font = Standard)

//	Resource: tFRM 4300
#define TabInfoSystemForm                         4300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 100, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TabInfoSystemTabTitleAboutLabel           4301	//(Left Origin = 4, Top Origin = 0, Usable = 1, Font = Bold)
#define TabInfoSystemUnnamed4302Label             4302	//(Left Origin = 10, Top Origin = 12, Usable = 1, Font = Standard)
#define TabInfoSystemUnnamed4303Label             4303	//(Left Origin = 13, Top Origin = 24, Usable = 1, Font = Standard)
#define TabInfoSystemUnnamed4304Label             4304	//(Left Origin = 5, Top Origin = 36, Usable = 1, Font = Standard)
#define TabInfoSystemUnnamed4305Label             4305	//(Left Origin = 96, Top Origin = 0, Usable = 1, Font = Standard)
#define TabInfoSystemUnnamed4306Label             4306	//(Left Origin = 132, Top Origin = 0, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define FrmWarnAlert                              1000
#define FrmWarnOK                                 0

//	Resource: Talt 1100
#define FrmErrorAlert                             1100
#define FrmErrorCancel                            0

//	Resource: Talt 1300
#define FrmConfirmAlert                           1300
#define FrmConfirmYes                             0
#define FrmConfirmNo                              1

//	Resource: Talt 1400
#define FrmInfoAlert                              1400
#define FrmInfoOK                                 0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsMisc                           1000	//  Command Key: I
#define MainOptionsSkins                          1001
#define MainOptionsBeam                           1003
#define MainOptionsAbout                          1005

//	Resource: MENU 1100
#define MainGamesMenu                             1100
#define MainGamesNewEdit                          1100	//  Command Key: E
#define MainGamesMusicSound                       1101	//  Command Key: M
#define MainGamesMemoryCard                       1103	//  Command Key: C


//	Resource: tSTR 9991
#define ClieCatString                             9991	// "32779"

//	Resource: tSTR 9990
#define ClieDescString                            9990	// "Play your favorite Point'n'Click games"


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018

//	Resource: PICT 2000
#define infoBitmap                                2000

//	Resource: PICT 1100
#define msOnBitmap                                1100

//	Resource: PICT 1009
#define Bitmap7                                   1009

//	Resource: PICT 1010
#define Bitmap8                                   1010

//	Resource: PICT 1110
#define msNoneBitmap                              1110

//	Resource: PICT 1020
#define BitmapID1020Bitmap                        1020

//	Resource: PICT 1019
#define BitmapID1019Bitmap                        1019

//	Resource: PICT 1200
#define msOnD2Bitmap                              1200

//	Resource: PICT 1300
#define msNoneD2Bitmap                            1300

//	Resource: PICT 2100
#define infoD2Bitmap                              2100

//	Resource: PICT 1501
#define ScummVMlogoD1Bitmap                       1501

//	Resource: PICT 1502
#define ScummVMlogoD2Bitmap                       1502


//	Resource: tbmf 1000
#define Icon_infoBitmapFamily                     1000

//	Resource: tbmf 1100
#define MsOnBitmapFamily                          1100

//	Resource: tbmf 2000
#define InfoBitmapFamily                          2000

//	Resource: tbmf 1110
#define MsNoneBitmapFamily                        1110

//	Resource: tbmf 1200
#define LogoBitmapFamily                          1200


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001


#endif // STARTERRSC_H
