/* ScummVM - Graphic Adventure Engine
 *
 * Alfred Pelrock Library Book Database
 * Extracted from ALFRED.7 offset 0x309E0 to 0x33F05
 *
 * This file was auto-generated by extract_alfred7_books_full.py
 * DO NOT EDIT MANUALLY
 *
 * Book format in ALFRED.7 (108 bytes per entry):
 *   - Title:        55 bytes (space-padded)
 *   - Author:       30 bytes (space-padded)
 *   - Genre:        20 bytes (space-padded)
 *   - Shelf Letter:  1 byte (A-Z or space if catalog-only)
 *   - Shelf Row:     1 byte (1-3 or space)
 *   - Status:        1 byte (0x01=catalog only, 0x02=physical copy)
 */

#ifndef PELROCK_LIBRARY_BOOKS_H
#define PELROCK_LIBRARY_BOOKS_H

#include "common/scummsys.h"

namespace Pelrock {

// Book data location in ALFRED.7
static const uint32 kBookDataOffset = 0x309E0;
static const uint32 kBookDataEnd = 0x33F05;
static const int kBookEntrySize = 108;  // 55 + 30 + 20 + 1 + 1 + 1

// Field sizes
static const int kBookTitleSize = 55;
static const int kBookAuthorSize = 30;
static const int kBookGenreSize = 20;

// Status byte values
static const byte kBookStatusCatalogOnly = 0x01;  // No physical copy
static const byte kBookStatusPhysical = 0x02;     // Has physical copy on shelf

struct LibraryBook {
    Common::String title; //55 bytes for title
    Common::String author; //30 bytes for author
    Common::String genre; //20 bytes for genre
    byte inventoryIndex;
    byte shelf;       // 1-3 for row number, 0 if catalog-only
    bool available;  // true = can be found on shelf, false = catalog only
};

const LibraryBook noBook = {"", "", "", 0, 0, false};


// static const int kLibraryBookCount = 125;

// static const LibraryBook kLibraryBooks[] = {
//     // Book 1: Los hombres: ¡ Como caparlos !
//     {"Los hombres: ¡ Como caparlos !", "Herminia Gutierrez", "Feminismo", ' ', 0, false},
//     // Book 2: Mujeres del mundo: ¡ No os depileis las ...
//     {"Mujeres del mundo: ¡ No os depileis las axilas !", "Herminia Gutierrez", "Feminismo", ' ', 0, false},
//     // Book 3: Gato por liebre
//     {"Gato por liebre", "Karlos Arguiñano", "Cocina", 'I', 1, true},
//     // Book 4: Hamlet
//     {"Hamlet", "William Shakespeare", "Teatro", ' ', 0, false},
//     // Book 5: Fausto
//     {"Fausto", "Goethe", "Novela", ' ', 0, false},
//     // Book 6: Enrique de Ofterdingen
//     {"Enrique de Ofterdingen", "Novalis", "Novela", 'J', 1, true},
//     // Book 7: Guia de desobediencia civica
//     {"Guia de desobediencia civica", "Azagra", "Ensayo", ' ', 0, false},
//     // Book 8: Literatura en la edad de piedra: cuestio...
//     {"Literatura en la edad de piedra: cuestion de fuerza", "Profesor Cebollo", "Ensayo", ' ', 0, false},
//     // Book 9: Turbo C ++ con Intratex
//     {"Turbo C ++ con Intratex", "Programadores reunidos", "Informatica", ' ', 0, false},
//     // Book 10: Codigo Maquina a pelo
//     {"Codigo Maquina a pelo", "Programadores reunidos", "Informatica", 'K', 1, true},
//     // Book 11: Asesino por vocacion
//     {"Asesino por vocacion", "Chema Ton", "Novela negra", ' ', 0, false},
//     // Book 12: Poemas rebuscados
//     {"Poemas rebuscados", "Ramon Rodriguez", "Poesia", ' ', 0, false},
//     // Book 13: El parto de las tortugas: Un proceso len...
//     {"El parto de las tortugas: Un proceso lento", "Profesor Lorin Colorado", "Biologia", ' ', 0, false},
//     // Book 14: Te parto la cara ¡ Capuyo !
//     {"Te parto la cara ¡ Capuyo !", "Jhonny Rapper", "Critica Social", 'L', 3, true},
//     // Book 15: En los tugurios del Himalaya
//     {"En los tugurios del Himalaya", "Coronel Tapioca", "Aventuras", ' ', 0, false},
//     // Book 16: En las callejuelas del amazonas
//     {"En las callejuelas del amazonas", "Coronel Tapioca", "Aventuras", ' ', 0, false},
//     // Book 17: En las selvas de Londres
//     {"En las selvas de Londres", "Coronel Tapioca", "Aventuras", 'M', 1, true},
//     // Book 18: Sueños binarios
//     {"Sueños binarios", "Doctor Chip", "Ciencia ficcion", ' ', 0, false},
//     // Book 19: Cien cuentos cortisimos
//     {"Cien cuentos cortisimos", "Billi el rapido", "Novela", ' ', 0, false},
//     // Book 20: Teoria de la relatividad
//     {"Teoria de la relatividad", "Alfred Einstein", "Ciencia", ' ', 0, false},
//     // Book 21: El ultimo paso para la cuadratura del ci...
//     {"El ultimo paso para la cuadratura del circulo", "Anonimo", "Filosofia", 'N', 1, true},
//     // Book 22: Correlacion entre el sentido de los colo...
//     {"Correlacion entre el sentido de los colores y sonidos", "Anonimo", "Filosofia", ' ', 0, false},
//     // Book 23: Los cuatro evangelios: Interpretados por...
//     {"Los cuatro evangelios: Interpretados por ordenador", "Doctor Chip", "Teologia", ' ', 0, false},
//     // Book 24: Enciclopedia de bolsillo
//     {"Enciclopedia de bolsillo", "Profesor Lumbreras", "Enciclopedia", 'O', 1, true},
//     // Book 25: Sigueme y revienta
//     {"Sigueme y revienta", "M. Indurain", "Deporte", 'P', 3, true},
//     // Book 26: Me duele too...
//     {"Me duele too...", "Carmen Opausica", "Ensayo", ' ', 0, false},
//     // Book 27: El Perro de Sam Rocker si tiene rabo
//     {"El Perro de Sam Rocker si tiene rabo", "El Perro de Sam Rocker", "Biografia", ' ', 0, false},
//     // Book 28: Donde estara mi carro ?
//     {"Donde estara mi carro ?", "Manolo Escobar", "Aventuras", ' ', 0, false},
//     // Book 29: Oh tu, bella flor del jardin
//     {"Oh tu, bella flor del jardin", "La abeja Maya", "Poesia", 'Q', 2, true},
//     // Book 30: Yogui, ¡ Bajate de esa motoneta !
//     {"Yogui, ¡ Bajate de esa motoneta !", "Bubu", "Filosofia", ' ', 0, false},
//     // Book 31: Odio a muerte a loh mardito rohedore !
//     {"Odio a muerte a loh mardito rohedore !", "Er gato Yin", "Zoologia", ' ', 0, false},
//     // Book 32: Pissi, Dissi, ¡ Sargan de su aguhero !
//     {"Pissi, Dissi, ¡ Sargan de su aguhero !", "Er gato Yin", "Zoologia", ' ', 0, false},
//     // Book 33: Mardito sea ... ¡ Er queso !
//     {"Mardito sea ... ¡ Er queso !", "Er gato Yin", "Zoologia", ' ', 0, false},
//     // Book 34: La mate porque era mia
//     {"La mate porque era mia", "Loquillo", "Novela", ' ', 0, false},
//     // Book 35: Los gallos: Esos desconocidos
//     {"Los gallos: Esos desconocidos", "Paco rico", "Zoologia", ' ', 0, false},
//     // Book 36: Cuentos corrientes
//     {"Cuentos corrientes", "Pepe Lopez", "Novela", 'R', 1, true},
//     // Book 37: Mas madera
//     {"Mas madera", "R. Gepetto", "Bricolage", 'S', 2, true},
//     // Book 38: Cuentos del Lejano Oriente
//     {"Cuentos del Lejano Oriente", "Jhonny Mc. Dowall", "Novela", ' ', 0, false},
//     // Book 39: Saca el guiski cheli
//     {"Saca el guiski cheli", "Manolo lailo", "Cronica Social", ' ', 0, false},
//     // Book 40: Ta totao !
//     {"Ta totao !", "Lao Tse", "Filosofia", ' ', 0, false},
//     // Book 41: Mis conversaciones con el señor Roca
//     {"Mis conversaciones con el señor Roca", "Francisca Gando", "Epistolar", 'T', 2, true},
//     // Book 42: Guia para la supervivencia
//     {"Guia para la supervivencia", "Robinson Crusoe", "Manual", ' ', 0, false},
//     // Book 43: No esperes a ser la segunda: ¡ Engaña a ...
//     {"No esperes a ser la segunda: ¡ Engaña a tu marido !", "Herminia Gutierrez", "Feminismo", ' ', 0, false},
//     // Book 44: Yoga Sutras
//     {"Yoga Sutras", "Patanjali", "Filosofia", 'X', 3, true},
//     // Book 45: El juego de los Abalorios
//     {"El juego de los Abalorios", "Herman Hesse", "Novela", ' ', 0, false},
//     // Book 46: Tienes suerte de ser tan pequeño, ¡ mard...
//     {"Tienes suerte de ser tan pequeño, ¡ mardito roedo !", "Er gato Yin", "Novela", ' ', 0, false},
//     // Book 47: Como hacerse rico en diez minutos
//     {"Como hacerse rico en diez minutos", "El Dioni", "Manual", 'Y', 1, true},
//     // Book 48: Te querre a pesar de tu madre
//     {"Te querre a pesar de tu madre", "Corin Tellado", "Novela rosa", ' ', 0, false},
//     // Book 49: Hasta que el mando a distancia nos separ...
//     {"Hasta que el mando a distancia nos separe", "Corin Tellado", "Novela rosa", ' ', 0, false},
//     // Book 50: Una pasion ostentorea
//     {"Una pasion ostentorea", "Corin Tellado y Jesus Gil", "Novela rosa", 'Z', 3, true},
//     // Book 51: Por mi, como si te la machacas
//     {"Por mi, como si te la machacas", "Seneca", "Filosofia", ' ', 0, false},
//     // Book 52: Conversaciones con mi caballo
//     {"Conversaciones con mi caballo", "Jesus Gil", "Humor", ' ', 0, false},
//     // Book 53: El poder curativo de la mierda comun
//     {"El poder curativo de la mierda comun", "Sri Ramachrinaraska", "Esoterismo", ' ', 1, true},
//     // Book 54: La liberacion mediante la eneriga de los...
//     {"La liberacion mediante la eneriga de los pedos", "Sri Ramachrinaraska", "Esoterismo", ' ', 0, false},
//     // Book 55: Sobre la imperceptibilidad de lo imperce...
//     {"Sobre la imperceptibilidad de lo imperceptible", "Perogrullo", "Ensayo", ' ', 0, false},
//     // Book 56: Piojos; como educarlos sin traumas
//     {"Piojos; como educarlos sin traumas", "Franz Franzfrenz", "Psicologia", ' ', 0, false},
//     // Book 57: I Ching
//     {"I Ching", "Richard Willem", "Filosofia", ' ', 0, false},
//     // Book 58: No se nada, ni me importa
//     {"No se nada, ni me importa", "Socrates", "Filosofia", 'U', 2, true},
//     // Book 59: No he sido yo, ¡ Lo juro !
//     {"No he sido yo, ¡ Lo juro !", "Juan Jose Gil", "Biografia", ' ', 0, false},
//     // Book 60: Relatos cortos
//     {"Relatos cortos", "Tachenko", "Novela de ficcion", 'V', 3, true},
//     // Book 61: El martillo como elemento cognitivo
//     {"El martillo como elemento cognitivo", "Friedrich Nietzsche", "Filosofia", ' ', 0, false},
//     // Book 62: La maravillosa vida del escarabajo pelot...
//     {"La maravillosa vida del escarabajo pelotero (v. I)", "Dr. Federico Ñazo", "Botanica", ' ', 0, false},
//     // Book 63: La maravillosa vida del escarabajo pelot...
//     {"La maravillosa vida del escarabajo pelotero (v. II)", "Dr. Federico Ñazo", "Botanica", ' ', 0, false},
//     // Book 64: La maravillosa vida del escarabajo pelot...
//     {"La maravillosa vida del escarabajo pelotero (v. III)", "Dr. Federico Ñazo", "Botanica", ' ', 0, false},
//     // Book 65: La maravillosa vida del escarabajo pelot...
//     {"La maravillosa vida del escarabajo pelotero (v. IV)", "Dr. Federico Ñazo", "Botanica", ' ', 0, false},
//     // Book 66: La maravillosa vida del escarabajo pelot...
//     {"La maravillosa vida del escarabajo pelotero (v. V)", "Dr. Federico Ñazo", "Botanica", ' ', 0, false},
//     // Book 67: Tu eliges: Tu madre o yo
//     {"Tu eliges: Tu madre o yo", "Anonimo", "Psicologia aplicada", 'W', 3, true},
//     // Book 68: Mi lucha
//     {"Mi lucha", "Adolf Hitler", "Humor negro", ' ', 0, false},
//     // Book 69: Cuentos de amor y desidia
//     {"Cuentos de amor y desidia", "Jardiel Poncela", "Teatro", ' ', 1, true},
//     // Book 70: Nuevas andanzas de Zaratustra
//     {"Nuevas andanzas de Zaratustra", "Anonimo", "Aventuras", ' ', 2, true},
//     // Book 71: Me se cuadre ¡ Coño !
//     {"Me se cuadre ¡ Coño !", "Sargento Cienfuegos", "Etica militar", ' ', 2, true},
//     // Book 72: Gatos: solos o con Ketchup
//     {"Gatos: solos o con Ketchup", "El perro de Sam Rocker", "Cocina", ' ', 1, true},
//     // Book 73: Querida Adelaida: mi marido NO ha dejado...
//     {"Querida Adelaida: mi marido NO ha dejado de roncar", "Maruja Mones", "Epistolar", ' ', 0, false},
//     // Book 74: Sobre el papel de El Lepe en el nuevo Or...
//     {"Sobre el papel de El Lepe en el nuevo Orden Mundial", "General Sintacha", "Estrategia", ' ', 0, false},
//     // Book 75: Aqui no hay nadie que se acueste sin cen...
//     {"Aqui no hay nadie que se acueste sin cenar (v. I)", "Fidel Castro", "Politica", ' ', 1, true},
//     // Book 76: Aqui no hay nadie que se acueste sin cen...
//     {"Aqui no hay nadie que se acueste sin cenar (v. II)", "Fidel Castro", "Politica", ' ', 0, false},
//     // Book 77: Aqui no hay nadie que se acueste sin cen...
//     {"Aqui no hay nadie que se acueste sin cenar (v. III)", "Fidel Castro", "Politica", ' ', 0, false},
//     // Book 78: Aqui no hay nadie que se acueste sin cen...
//     {"Aqui no hay nadie que se acueste sin cenar (v. IV)", "Fidel Castro", "Politica", ' ', 0, false},
//     // Book 79: Aqui no hay nadie que se acueste sin cen...
//     {"Aqui no hay nadie que se acueste sin cenar (v. V)", "Fidel Castro", "Politica", ' ', 0, false},
//     // Book 80: Domine la metafisica en 5 dias
//     {"Domine la metafisica en 5 dias", "Profesor Pinocho", "Manual", ' ', 1, true},
//     // Book 81: Domine el ensamblador en 5 dias
//     {"Domine el ensamblador en 5 dias", "Profesor Pinocho", "Manual", ' ', 1, true},
//     // Book 82: Dominese a si mismo en 5 dias
//     {"Dominese a si mismo en 5 dias", "Profesor Pinocho", "Manual", ' ', 1, true},
//     // Book 83: Piernas de Ciertopelo
//     {"Piernas de Ciertopelo", "Chichi Mondongo", "Erotica", ' ', 2, true},
//     // Book 84: Otra vuelta de tuerca
//     {"Otra vuelta de tuerca", "Pepe, el fontanero", "Bricolage", ' ', 2, true},
//     // Book 85: La Tierra: ¡ Planeta limpio !
//     {"La Tierra: ¡ Planeta limpio !", "Juan, el basurero", "Ciencia Ficcion", ' ', 2, true},
//     // Book 86: Liberad a Brian !
//     {"Liberad a Brian !", "Roger Rabitt", "Historica", ' ', 2, true},
//     // Book 87: La vida es una mierda
//     {"La vida es una mierda", "Juanjo Dido", "Ensayo", ' ', 2, true},
//     // Book 88: No era eso lo que yo di a entender
//     {"No era eso lo que yo di a entender", "Jesus de Nazaret", "Religion", ' ', 2, true},
//     // Book 89: Castigos a Piratas Informaticos
//     {"Castigos a Piratas Informaticos", "Torquemada", "Inquisicion", ' ', 1, true},
//     // Book 90: Confiesa, bruja asquerosa
//     {"Confiesa, bruja asquerosa", "Troquemada", "Inquisicion", ' ', 1, true},
//     // Book 91: El cocherito lere
//     {"El cocherito lere", "Paco costas", "Automovilismo", ' ', 1, true},
//     // Book 92: La musica amansa a las fieras
//     {"La musica amansa a las fieras", "Wagner", "Musica", ' ', 2, true},
//     // Book 93: Pinocho en el Parlamento
//     {"Pinocho en el Parlamento", "Carmen Tirosa", "Cronica Social", ' ', 0, false},
//     // Book 94: Hagase famoso gracias a la energia de la...
//     {"Hagase famoso gracias a la energia de las petunias", "Carmelo Cuelo", "Esoterismo", ' ', 0, false},
//     // Book 95: Dios mio, ¡ Que cruz !
//     {"Dios mio, ¡ Que cruz !", "Jesus de Nazaret", "Autobiografia", ' ', 0, false},
//     // Book 96: Psicologia de la motivacion inmotivada
//     {"Psicologia de la motivacion inmotivada", "Dr. Chemi", "Psicologia", ' ', 2, true},
//     // Book 97: Magia rosa para iniciados
//     {"Magia rosa para iniciados", "Manolo Lailo", "Esoterismo", ' ', 0, false},
//     // Book 98: Un mundo Feliz
//     {"Un mundo Feliz", "Aldous Huxley", "Novela", ' ', 0, false},
//     // Book 99: Sexo oral y por escrito
//     {"Sexo oral y por escrito", "Franz Masturmann", "Sexologia", ' ', 3, true},
//     // Book 100: El contrato social de aprendizaje
//     {"El contrato social de aprendizaje", "Rousseau", "Ensayo", ' ', 1, true},
//     // Book 101: Vida sexual del escarabajo de la Patagon...
//     {"Vida sexual del escarabajo de la Patagonia", "Dr. Tedio Plomez", "Botanica", ' ', 3, true},
//     // Book 102: Manual del necrofago
//     {"Manual del necrofago", "Jesus Gil", "Manual", ' ', 0, false},
//     // Book 103: Canticos espirituales en formato *.ZIP
//     {"Canticos espirituales en formato *.ZIP", "Doctor Chip", "Poesia", 'B', 1, true},
//     // Book 104: Novela erotica en formato *.MAS
//     {"Novela erotica en formato *.MAS", "Doctor Chip", "Erotica", ' ', 0, false},
//     // Book 105: Plopuestas colelacionales en coyuntulas ...
//     {"Plopuestas colelacionales en coyuntulas bilatelales", "Senadol Chan Chu Yo", "Politica", ' ', 0, false},
//     // Book 106: Ereh un fistro
//     {"Ereh un fistro", "Chiquito de la casa", "Humor", ' ', 0, false},
//     // Book 107: El hacedor de la Lluvia
//     {"El hacedor de la Lluvia", "Herman Hesse", "Cuentos", ' ', 0, false},
//     // Book 108: Pasiones recalcitrantes
//     {"Pasiones recalcitrantes", "Corin Tellado", "Novela rosa", 'C', 2, true},
//     // Book 109: No me mates con tomate
//     {"No me mates con tomate", "Karlos Arguiñano", "Cocina", ' ', 0, false},
//     // Book 110: El valenciano en los albores del siglo X...
//     {"El valenciano en los albores del siglo XXI", "Jaume i Pascual", "Nacionalismo", 'D', 1, true},
//     // Book 111: El valenciano es la lengua del futuro
//     {"El valenciano es la lengua del futuro", "Jaume i Pascual", "Nacionalismo", ' ', 0, false},
//     // Book 112: Valencia: mes que mai
//     {"Valencia: mes que mai", "Jaume i Pascual", "Nacionalismo", ' ', 0, false},
//     // Book 113: Sistema inmunitario de los cefalopodos (...
//     {"Sistema inmunitario de los cefalopodos (v. I)", "Dr. Tedio Plomez", "Biologia", 'E', 3, true},
//     // Book 114: Sistema inmunitario de los cefalopodos (...
//     {"Sistema inmunitario de los cefalopodos (v. II)", "Dr. Tedio Plomez", "Biologia", ' ', 0, false},
//     // Book 115: Sistema inmunitario de los cefalopodos (...
//     {"Sistema inmunitario de los cefalopodos (v. III)", "Dr. Tedio Plomez", "Biologia", ' ', 0, false},
//     // Book 116: Sistema inmunitario de los cefalopodos (...
//     {"Sistema inmunitario de los cefalopodos (v. IV)", "Dr. Tedio Plomez", "Biologia", ' ', 0, false},
//     // Book 117: Sistema inmunitario de los cefalopodos (...
//     {"Sistema inmunitario de los cefalopodos (v. V)", "Dr. Tedio Plomez", "Biologia", ' ', 0, false},
//     // Book 118: Dos mas dos son cinco
//     {"Dos mas dos son cinco", "Joan Josep Climent Colomer", "Matematicas", 'F', 1, true},
//     // Book 119: El algebra es la base de la programacion
//     {"El algebra es la base de la programacion", "Joan Josep Climent Colomer", "Humor absurdo", ' ', 0, false},
//     // Book 120: Autobiografia de una miseria humana
//     {"Autobiografia de una miseria humana", "Joan Josep Climent Colomer", "Esperpento", ' ', 0, false},
//     // Book 121: El arte mundial antes y despues de mi
//     {"El arte mundial antes y despues de mi", "Nacho Taulet Perman", "Arte", ' ', 0, false},
//     // Book 122: La parte Creativa
//     {"La parte Creativa", "Nacho Taulet Perman", "Arte", 'G', 2, true},
//     // Book 123: Llamame cuando se muera tu abuelo
//     {"Llamame cuando se muera tu abuelo", "Jose Bart Carrion", "Teatro", ' ', 0, false},
//     // Book 124: Soy un incomprendido
//     {"Soy un incomprendido", "Jose Bart Carrion", "Autobiografia", ' ', 0, false},
//     // Book 125: El arte de limpiar botijos por dentro
//     {"El arte de limpiar botijos por dentro", "Varios autores", "Manualidades", ' ', 0, false},
// };

} // namespace Pelrock

#endif // PELROCK_LIBRARY_BOOKS_H
