#ifndef PRIVATE_DETECTION_H
#define PRIVATE_DETECTION_H

#define GAMEOPTION_SFX_SUBTITLES GUIO_GAMEOPTIONS1
#define GAMEOPTION_HIGHLIGHT_MASKS GUIO_GAMEOPTIONS2
#define GAMEOPTION_READING_MATERIAL_CONTRAST GUIO_GAMEOPTIONS3

#endif // PRIVATE_DETECTION_H
