/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#include "macs2/hotspot_names.h"
#include "macs2/macs2.h"

namespace Macs2 {

struct SceneHotspotNameEntry {
	uint16 sceneIndex;
	uint16 hotspotIndex;
	Graphics::HotspotType type;
	const char *name;
};

const SceneHotspotNameEntry kSceneHotspotNames[] = {
	{ 2, 1, Graphics::kHotspotObject, "Wand" },
	{ 2, 2, Graphics::kHotspotObject, "Spiegel" },
	{ 2, 3, Graphics::kHotspotObject, "Schrank" },
	{ 2, 5, Graphics::kHotspotObject, "Tisch" },
	{ 2, 6, Graphics::kHotspotObject, "Bett" },
	{ 2, 7, Graphics::kHotspotObject, "Stuhl" },
	{ 2, 8, Graphics::kHotspotObject, "Raum" },
	{ 2, 9, Graphics::kHotspotObject, "Kaj" "\x81" "te" },
	{ 2, 10, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 6, 1, Graphics::kHotspotObject, "Wolken" },
	{ 6, 2, Graphics::kHotspotObject, "Berge" },
	{ 6, 4, Graphics::kHotspotObject, "Winde" },
	{ 6, 5, Graphics::kHotspotObject, "Planken" },
	{ 6, 6, Graphics::kHotspotObject, "Brett" },
	{ 6, 7, Graphics::kHotspotObject, "Witterung" },
	{ 6, 8, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 6, 9, Graphics::kHotspotObject, "Ladung" },
	{ 6, 10, Graphics::kHotspotObject, "Kiste" },
	{ 9, 1, Graphics::kHotspotObject, "Fracht" },
	{ 9, 2, Graphics::kHotspotObject, "Aufbauten" },
	{ 9, 3, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 9, 5, Graphics::kHotspotObject, "Fenster" },
	{ 9, 6, Graphics::kHotspotObject, "Kahn" },
	{ 10, 1, Graphics::kHotspotObject, "Tintenfass" },
	{ 10, 2, Graphics::kHotspotObject, "Tasse" },
	{ 10, 3, Graphics::kHotspotObject, "Barmann" },
	{ 10, 4, Graphics::kHotspotObject, "Bar" },
	{ 10, 5, Graphics::kHotspotObject, "Raum" },
	{ 10, 6, Graphics::kHotspotObject, "Fenster" },
	{ 10, 7, Graphics::kHotspotObject, "Tapete" },
	{ 10, 8, Graphics::kHotspotObject, "Wand" },
	{ 10, 9, Graphics::kHotspotObject, "Leuchter" },
	{ 10, 10, Graphics::kHotspotObject, "Spiegel" },
	{ 10, 11, Graphics::kHotspotObject, "Verkleidung" },
	{ 10, 12, Graphics::kHotspotObject, "Fenster" },
	{ 12, 1, Graphics::kHotspotObject, "Raum" },
	{ 12, 2, Graphics::kHotspotExit, "Leiter" },
	{ 12, 3, Graphics::kHotspotObject, "Sch" "\x84" "tze" },
	{ 12, 4, Graphics::kHotspotObject, "Heizkessel" },
	{ 12, 5, Graphics::kHotspotObject, "Kohlen" },
	{ 12, 6, Graphics::kHotspotObject, "Kohlen" },
	{ 12, 7, Graphics::kHotspotObject, "Kohlen" },
	{ 12, 8, Graphics::kHotspotObject, "Ofen" },
	{ 12, 10, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 12, 11, Graphics::kHotspotObject, "Boden" },
	{ 14, 1, Graphics::kHotspotExit, "Kaj" "\x81" "te" },
	{ 14, 2, Graphics::kHotspotExit, "Kabine" },
	{ 14, 3, Graphics::kHotspotObject, "Kabine" },
	{ 14, 4, Graphics::kHotspotObject, "Hund" },
	{ 14, 5, Graphics::kHotspotObject, "Kabine" },
	{ 14, 6, Graphics::kHotspotExit, "Treppe" },
	{ 14, 7, Graphics::kHotspotObject, "Aufbauten" },
	{ 14, 8, Graphics::kHotspotObject, "Bildrand" },
	{ 14, 9, Graphics::kHotspotObject, "Boden" },
	{ 14, 10, Graphics::kHotspotObject, "Gel" "\x84" "nder" },
	{ 14, 11, Graphics::kHotspotObject, "Seil" },
	{ 14, 13, Graphics::kHotspotObject, "Wolken" },
	{ 17, 1, Graphics::kHotspotObject, "Baum" },
	{ 17, 2, Graphics::kHotspotObject, "Felsen" },
	{ 17, 3, Graphics::kHotspotObject, "Kiselsteine" },
	{ 17, 4, Graphics::kHotspotObject, "Schilf" },
	{ 17, 5, Graphics::kHotspotObject, "Baum" },
	{ 17, 6, Graphics::kHotspotObject, "Felsen" },
	{ 17, 7, Graphics::kHotspotObject, "Ruhig" },
	{ 17, 8, Graphics::kHotspotObject, "Fluss" },
	{ 17, 10, Graphics::kHotspotObject, "Himmel" },
	{ 17, 11, Graphics::kHotspotObject, "Busch" },
	{ 17, 12, Graphics::kHotspotObject, "Busch" },
	{ 17, 13, Graphics::kHotspotObject, "Boden" },
	{ 17, 14, Graphics::kHotspotObject, "Weg" },
	{ 18, 2, Graphics::kHotspotObject, "Bl" "\x84" "tterdach" },
	{ 18, 3, Graphics::kHotspotObject, "Felsen" },
	{ 18, 5, Graphics::kHotspotObject, "Ufer" },
	{ 18, 6, Graphics::kHotspotObject, "Stelle" },
	{ 18, 7, Graphics::kHotspotObject, "Deckung" },
	{ 18, 8, Graphics::kHotspotObject, "Lagerfeuer" },
	{ 18, 10, Graphics::kHotspotObject, "Busch" },
	{ 19, 1, Graphics::kHotspotObject, "Wald" },
	{ 19, 2, Graphics::kHotspotObject, "Stein" },
	{ 19, 3, Graphics::kHotspotObject, "Weg" },
	{ 19, 4, Graphics::kHotspotObject, "Wand" },
	{ 19, 6, Graphics::kHotspotObject, "Weg" },
	{ 20, 1, Graphics::kHotspotObject, "Pfad" },
	{ 20, 2, Graphics::kHotspotObject, "Baum" },
	{ 20, 3, Graphics::kHotspotObject, "Rasen" },
	{ 20, 4, Graphics::kHotspotObject, "Pfad" },
	{ 20, 6, Graphics::kHotspotObject, "Fenster" },
	{ 20, 7, Graphics::kHotspotObject, "Holzt" "\x81" "r" },
	{ 20, 8, Graphics::kHotspotObject, "Berge" },
	{ 20, 9, Graphics::kHotspotObject, "W" "\x84" "sche" },
	{ 20, 10, Graphics::kHotspotObject, "Seil" },
	{ 20, 11, Graphics::kHotspotObject, "Baum" },
	{ 20, 12, Graphics::kHotspotObject, "Pfad" },
	{ 21, 1, Graphics::kHotspotObject, "Eichenfass" },
	{ 21, 2, Graphics::kHotspotObject, "Vogelk" "\x84" "fig" },
	{ 21, 3, Graphics::kHotspotObject, "Fenster" },
	{ 21, 4, Graphics::kHotspotObject, "Luke" },
	{ 21, 5, Graphics::kHotspotObject, "Mauer" },
	{ 21, 6, Graphics::kHotspotObject, "Flasche" },
	{ 21, 7, Graphics::kHotspotObject, "Lampe" },
	{ 21, 8, Graphics::kHotspotObject, "Whiskyglas" },
	{ 21, 9, Graphics::kHotspotObject, "Tisch" },
	{ 21, 10, Graphics::kHotspotObject, "Deckel" },
	{ 21, 11, Graphics::kHotspotObject, "Kiste" },
	{ 21, 12, Graphics::kHotspotObject, "Koffer" },
	{ 21, 13, Graphics::kHotspotObject, "Bett" },
	{ 21, 14, Graphics::kHotspotObject, "Raum" },
	{ 21, 15, Graphics::kHotspotObject, "Flasche" },
	{ 22, 1, Graphics::kHotspotObject, "Schrank" },
	{ 22, 2, Graphics::kHotspotObject, "Schrank" },
	{ 22, 3, Graphics::kHotspotObject, "Schrank" },
	{ 22, 4, Graphics::kHotspotExit, "Luke" },
	{ 22, 5, Graphics::kHotspotObject, "Fass" },
	{ 22, 6, Graphics::kHotspotObject, "B" "\x84" "renfell" },
	{ 22, 7, Graphics::kHotspotObject, "Kerze" },
	{ 22, 8, Graphics::kHotspotObject, "Wasserkrug" },
	{ 22, 9, Graphics::kHotspotObject, "Zeug" },
	{ 22, 10, Graphics::kHotspotObject, "Stofftasche" },
	{ 22, 11, Graphics::kHotspotObject, "Seekoffer" },
	{ 22, 12, Graphics::kHotspotObject, "Dach" },
	{ 22, 13, Graphics::kHotspotExit, "Treppe" },
	{ 22, 14, Graphics::kHotspotObject, "Flasche" },
	{ 22, 15, Graphics::kHotspotObject, "Schrank" },
	{ 23, 1, Graphics::kHotspotObject, "Pfad" },
	{ 23, 2, Graphics::kHotspotObject, "Gef" "\x84" "hrt" },
	{ 23, 4, Graphics::kHotspotObject, "Wald" },
	{ 23, 5, Graphics::kHotspotObject, "Lagerfeuer" },
	{ 23, 6, Graphics::kHotspotObject, "Zelt" },
	{ 24, 1, Graphics::kHotspotObject, "Asche" },
	{ 24, 2, Graphics::kHotspotObject, "Steg" },
	{ 24, 3, Graphics::kHotspotObject, "Himmel" },
	{ 24, 4, Graphics::kHotspotObject, "Gebirge" },
	{ 24, 5, Graphics::kHotspotObject, "Ufer" },
	{ 24, 6, Graphics::kHotspotObject, "Fluss" },
	{ 24, 7, Graphics::kHotspotObject, "Baum" },
	{ 24, 8, Graphics::kHotspotObject, "Busch" },
	{ 24, 9, Graphics::kHotspotObject, "Ufer" },
	{ 24, 10, Graphics::kHotspotObject, "Pfad" },
	{ 24, 11, Graphics::kHotspotObject, "Busch" },
	{ 24, 12, Graphics::kHotspotObject, "Pferd" },
	{ 24, 13, Graphics::kHotspotObject, "Stamm" },
	{ 26, 1, Graphics::kHotspotObject, "Busch" },
	{ 26, 2, Graphics::kHotspotObject, "Weg" },
	{ 26, 3, Graphics::kHotspotObject, "Dickicht" },
	{ 26, 4, Graphics::kHotspotObject, "Pfad" },
	{ 26, 6, Graphics::kHotspotObject, "Baum" },
	{ 30, 1, Graphics::kHotspotObject, "Landschaft" },
	{ 30, 2, Graphics::kHotspotObject, "Baum" },
	{ 30, 3, Graphics::kHotspotObject, "Fass" },
	{ 30, 4, Graphics::kHotspotObject, "Pumpe" },
	{ 30, 5, Graphics::kHotspotObject, "Holzscheite" },
	{ 30, 6, Graphics::kHotspotObject, "Mauer" },
	{ 30, 7, Graphics::kHotspotExit, "Treppe" },
	{ 30, 8, Graphics::kHotspotExit, "Leiter" },
	{ 30, 9, Graphics::kHotspotExit, "Holzt" "\x81" "r" },
	{ 30, 10, Graphics::kHotspotObject, "Farm" },
	{ 30, 11, Graphics::kHotspotObject, "Heuwagen" },
	{ 30, 14, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 30, 16, Graphics::kHotspotObject, "Vorplatz" },
	{ 31, 1, Graphics::kHotspotObject, "Wasser" },
	{ 31, 2, Graphics::kHotspotExit, "Leiter" },
	{ 31, 3, Graphics::kHotspotObject, "Mauer" },
	{ 31, 4, Graphics::kHotspotObject, "Himmel" },
	{ 31, 5, Graphics::kHotspotObject, "Baum" },
	{ 31, 6, Graphics::kHotspotObject, "Landschaft" },
	{ 31, 7, Graphics::kHotspotObject, "Busch" },
	{ 31, 8, Graphics::kHotspotObject, "Winde" },
	{ 31, 9, Graphics::kHotspotObject, "Angreifer" },
	{ 31, 10, Graphics::kHotspotObject, "Treppe" },
	{ 31, 11, Graphics::kHotspotObject, "Mauer" },
	{ 32, 1, Graphics::kHotspotObject, "Holz" },
	{ 32, 2, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 32, 3, Graphics::kHotspotObject, "Heuwagen" },
	{ 32, 4, Graphics::kHotspotObject, "Haus" },
	{ 32, 6, Graphics::kHotspotObject, "Boden" },
	{ 32, 7, Graphics::kHotspotObject, "Mauer" },
	{ 32, 8, Graphics::kHotspotObject, "Unkraut" },
	{ 32, 10, Graphics::kHotspotObject, "Farm" },
	{ 32, 11, Graphics::kHotspotObject, "Himmel" },
	{ 32, 12, Graphics::kHotspotObject, "Baum" },
	{ 32, 13, Graphics::kHotspotObject, "Fenster" },
	{ 33, 1, Graphics::kHotspotObject, "Mauer" },
	{ 33, 2, Graphics::kHotspotObject, "Eimer" },
	{ 33, 3, Graphics::kHotspotObject, "Pfahl" },
	{ 33, 4, Graphics::kHotspotObject, "Gel" "\x84" "nder" },
	{ 33, 9, Graphics::kHotspotObject, "Mist" },
	{ 33, 10, Graphics::kHotspotObject, "Boden" },
	{ 33, 11, Graphics::kHotspotObject, "Haus" },
	{ 33, 13, Graphics::kHotspotObject, "Mauer" },
	{ 33, 14, Graphics::kHotspotObject, "Unkraut" },
	{ 33, 15, Graphics::kHotspotObject, "Pferdekoppel" },
	{ 33, 16, Graphics::kHotspotObject, "Wolken" },
	{ 34, 1, Graphics::kHotspotObject, "Winde" },
	{ 34, 2, Graphics::kHotspotExit, "Luke" },
	{ 34, 3, Graphics::kHotspotObject, "Mauer" },
	{ 34, 4, Graphics::kHotspotObject, "Ufer" },
	{ 34, 5, Graphics::kHotspotObject, "Ufer" },
	{ 34, 6, Graphics::kHotspotObject, "Holzdach" },
	{ 34, 7, Graphics::kHotspotObject, "Haus" },
	{ 34, 8, Graphics::kHotspotObject, "Fenster" },
	{ 34, 9, Graphics::kHotspotObject, "Kanone" },
	{ 34, 10, Graphics::kHotspotObject, "Stahlkugeln" },
	{ 34, 11, Graphics::kHotspotObject, "Windlicht" },
	{ 35, 1, Graphics::kHotspotObject, "Kamin" },
	{ 35, 2, Graphics::kHotspotObject, "Musketen" },
	{ 35, 3, Graphics::kHotspotExit, "Holzt" "\x81" "r" },
	{ 35, 4, Graphics::kHotspotExit, "Treppe" },
	{ 35, 5, Graphics::kHotspotObject, "Raum" },
	{ 35, 6, Graphics::kHotspotObject, "Tisch" },
	{ 35, 7, Graphics::kHotspotObject, "Holzbank" },
	{ 35, 8, Graphics::kHotspotObject, "Brett" },
	{ 35, 10, Graphics::kHotspotObject, "Lampe" },
	{ 35, 11, Graphics::kHotspotObject, "Landschaft" },
	{ 35, 12, Graphics::kHotspotObject, "Tier" },
	{ 35, 13, Graphics::kHotspotObject, "Mauer" },
	{ 35, 15, Graphics::kHotspotObject, "Spiegel" },
	{ 35, 16, Graphics::kHotspotObject, "Lampe" },
	{ 36, 1, Graphics::kHotspotObject, "Holzt" "\x81" "r" },
	{ 36, 3, Graphics::kHotspotExit, "Treppe" },
	{ 36, 4, Graphics::kHotspotObject, "Schaufel" },
	{ 36, 6, Graphics::kHotspotObject, "Holzfass" },
	{ 36, 7, Graphics::kHotspotObject, "Holzfass" },
	{ 36, 8, Graphics::kHotspotObject, "Eichenfass" },
	{ 36, 10, Graphics::kHotspotObject, "Kiste" },
	{ 36, 11, Graphics::kHotspotObject, "Schleifspuren" },
	{ 36, 13, Graphics::kHotspotObject, "W" "\x84" "nde" },
	{ 36, 14, Graphics::kHotspotObject, "Decke" },
	{ 36, 15, Graphics::kHotspotObject, "Boden" },
	{ 37, 1, Graphics::kHotspotObject, "Planken" },
	{ 37, 2, Graphics::kHotspotObject, "Schrank" },
	{ 37, 3, Graphics::kHotspotObject, "Gusspfannen" },
	{ 37, 4, Graphics::kHotspotObject, "Holztisch" },
	{ 37, 5, Graphics::kHotspotObject, "W" "\x84" "nde" },
	{ 37, 6, Graphics::kHotspotObject, "Gussofen" },
	{ 37, 7, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 37, 8, Graphics::kHotspotObject, "Teppich" },
	{ 37, 9, Graphics::kHotspotObject, "Flasche" },
	{ 37, 10, Graphics::kHotspotObject, "Tonvase" },
	{ 37, 11, Graphics::kHotspotObject, "Brett" },
	{ 37, 12, Graphics::kHotspotObject, "Sch" "\x81" "ssel" },
	{ 37, 15, Graphics::kHotspotExit, "Holzt" "\x81" "r" },
	{ 38, 1, Graphics::kHotspotObject, "Schrank" },
	{ 38, 2, Graphics::kHotspotObject, "Kiste" },
	{ 38, 3, Graphics::kHotspotObject, "Schublade" },
	{ 38, 4, Graphics::kHotspotObject, "Bildrahmen" },
	{ 38, 5, Graphics::kHotspotObject, "Teddyb" "\x84" "r" },
	{ 38, 6, Graphics::kHotspotObject, "Bild" },
	{ 38, 7, Graphics::kHotspotObject, "Wand" },
	{ 38, 8, Graphics::kHotspotObject, "Stuhl" },
	{ 38, 9, Graphics::kHotspotObject, "Bett" },
	{ 38, 10, Graphics::kHotspotObject, "Schlange" },
	{ 38, 11, Graphics::kHotspotObject, "Holzpferd" },
	{ 38, 12, Graphics::kHotspotObject, "Spielkl" "\x94" "tze" },
	{ 38, 13, Graphics::kHotspotObject, "Holzeier" },
	{ 38, 14, Graphics::kHotspotObject, "Boden" },
	{ 38, 15, Graphics::kHotspotObject, "Holzt" "\x81" "r" },
	{ 39, 1, Graphics::kHotspotObject, "Luke" },
	{ 39, 3, Graphics::kHotspotObject, "Hackenspitze" },
	{ 39, 4, Graphics::kHotspotObject, "Boden" },
	{ 39, 5, Graphics::kHotspotExit, "Hanfseil" },
	{ 39, 6, Graphics::kHotspotObject, "Fluss" },
	{ 39, 7, Graphics::kHotspotObject, "Felsen" },
	{ 39, 8, Graphics::kHotspotObject, "Fluss" },
	{ 46, 1, Graphics::kHotspotObject, "Ger" "\x94" "ll" },
	{ 46, 2, Graphics::kHotspotObject, "Dynamit" },
	{ 46, 3, Graphics::kHotspotObject, "Wand" },
	{ 46, 4, Graphics::kHotspotObject, "Leiter" },
	{ 46, 5, Graphics::kHotspotObject, "Boden" },
	{ 46, 6, Graphics::kHotspotObject, "Felsbl" "\x94" "cke" },
	{ 46, 7, Graphics::kHotspotObject, "Steine" },
	{ 46, 8, Graphics::kHotspotObject, "Schienen" },
	{ 46, 9, Graphics::kHotspotObject, "Bohlen" },
	{ 46, 10, Graphics::kHotspotObject, "Konstruktion" },
	{ 46, 11, Graphics::kHotspotExit, "Eingang" },
	{ 46, 12, Graphics::kHotspotObject, "Gras" },
	{ 46, 13, Graphics::kHotspotObject, "Landschaft" },
	{ 47, 1, Graphics::kHotspotObject, "Beutel" },
	{ 47, 2, Graphics::kHotspotObject, "Boden" },
	{ 47, 3, Graphics::kHotspotObject, "Wand" },
	{ 47, 4, Graphics::kHotspotExit, "Felswand" },
	{ 47, 6, Graphics::kHotspotObject, "Felsbl" "\x94" "cke" },
	{ 47, 7, Graphics::kHotspotObject, "Schienen" },
	{ 47, 8, Graphics::kHotspotObject, "Bohlen" },
	{ 47, 9, Graphics::kHotspotExit, "Eingang" },
	{ 47, 10, Graphics::kHotspotExit, "Eingang" },
	{ 47, 11, Graphics::kHotspotObject, "Gras" },
	{ 47, 12, Graphics::kHotspotExit, "Eingang" },
	{ 47, 13, Graphics::kHotspotObject, "Landschaft" },
	{ 48, 1, Graphics::kHotspotObject, "Felsen" },
	{ 48, 2, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 48, 3, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 48, 5, Graphics::kHotspotObject, "Lore" },
	{ 48, 6, Graphics::kHotspotObject, "Schienen" },
	{ 48, 7, Graphics::kHotspotObject, "Bohlen" },
	{ 48, 8, Graphics::kHotspotObject, "Steine" },
	{ 48, 9, Graphics::kHotspotObject, "Boden" },
	{ 48, 11, Graphics::kHotspotObject, "Felswand" },
	{ 48, 13, Graphics::kHotspotObject, "Konstruktion" },
	{ 49, 1, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 49, 2, Graphics::kHotspotObject, "Felsen" },
	{ 49, 3, Graphics::kHotspotObject, "H" "\x81" "tte" },
	{ 49, 4, Graphics::kHotspotObject, "Felsen" },
	{ 49, 6, Graphics::kHotspotObject, "Bohlen" },
	{ 49, 8, Graphics::kHotspotObject, "Boden" },
	{ 49, 9, Graphics::kHotspotObject, "Bohlen" },
	{ 49, 10, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 49, 11, Graphics::kHotspotObject, "Brett" },
	{ 49, 12, Graphics::kHotspotObject, "H" "\x81" "tte" },
	{ 49, 13, Graphics::kHotspotObject, "Brecheisen" },
	{ 50, 1, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 50, 2, Graphics::kHotspotObject, "Felsen" },
	{ 50, 3, Graphics::kHotspotObject, "H" "\x81" "tte" },
	{ 50, 4, Graphics::kHotspotObject, "Brett" },
	{ 50, 6, Graphics::kHotspotObject, "Brecheisen" },
	{ 50, 9, Graphics::kHotspotObject, "Bohlen" },
	{ 50, 10, Graphics::kHotspotObject, "Mauer" },
	{ 50, 12, Graphics::kHotspotObject, "Balken" },
	{ 50, 13, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 50, 14, Graphics::kHotspotObject, "Boden" },
	{ 50, 15, Graphics::kHotspotObject, "St" "\x81" "ck" },
	{ 51, 1, Graphics::kHotspotObject, "Raum" },
	{ 51, 2, Graphics::kHotspotObject, "Kiste" },
	{ 51, 3, Graphics::kHotspotObject, "Dynamit" },
	{ 51, 4, Graphics::kHotspotObject, "Balken" },
	{ 51, 5, Graphics::kHotspotObject, "Ger" "\x94" "ll" },
	{ 51, 6, Graphics::kHotspotObject, "Mine" },
	{ 51, 8, Graphics::kHotspotObject, "Boden" },
	{ 52, 1, Graphics::kHotspotObject, "St" "\x81" "tze" },
	{ 52, 2, Graphics::kHotspotExit, "Eingang" },
	{ 52, 3, Graphics::kHotspotObject, "Balken" },
	{ 52, 4, Graphics::kHotspotObject, "Balken" },
	{ 52, 5, Graphics::kHotspotObject, "Balken" },
	{ 52, 6, Graphics::kHotspotObject, "Balken" },
	{ 52, 7, Graphics::kHotspotExit, "Ausgang" },
	{ 52, 9, Graphics::kHotspotObject, "Boden" },
	{ 52, 10, Graphics::kHotspotObject, "Raum" },
	{ 53, 1, Graphics::kHotspotExit, "Treppe" },
	{ 53, 2, Graphics::kHotspotObject, "Totempfahl" },
	{ 53, 3, Graphics::kHotspotObject, "Kopf" },
	{ 53, 4, Graphics::kHotspotObject, "Loch" },
	{ 53, 5, Graphics::kHotspotExit, "Gang" },
	{ 53, 6, Graphics::kHotspotObject, "Fackel" },
	{ 53, 7, Graphics::kHotspotObject, "Sch" "\x84" "del" },
	{ 53, 8, Graphics::kHotspotObject, "Raum" },
	{ 53, 9, Graphics::kHotspotExit, "Gang" },
	{ 54, 1, Graphics::kHotspotObject, "Kopf" },
	{ 54, 4, Graphics::kHotspotObject, "Totempfahl" },
	{ 54, 5, Graphics::kHotspotExit, "Loch" },
	{ 54, 6, Graphics::kHotspotExit, "Treppe" },
	{ 54, 7, Graphics::kHotspotObject, "Fackel" },
	{ 54, 8, Graphics::kHotspotObject, "Raum" },
	{ 54, 9, Graphics::kHotspotExit, "Gang" },
	{ 54, 10, Graphics::kHotspotObject, "Sch" "\x84" "del" },
	{ 54, 11, Graphics::kHotspotExit, "Gang" },
	{ 55, 1, Graphics::kHotspotObject, "Steinpyramide" },
	{ 55, 2, Graphics::kHotspotObject, "Emblem" },
	{ 55, 3, Graphics::kHotspotObject, "Gegenstand" },
	{ 55, 4, Graphics::kHotspotObject, "Gegenstand" },
	{ 55, 5, Graphics::kHotspotObject, "Steins" "\x84" "ule" },
	{ 55, 6, Graphics::kHotspotObject, "Steins" "\x84" "ule" },
	{ 55, 7, Graphics::kHotspotObject, "Kachel" },
	{ 55, 8, Graphics::kHotspotExit, "Treppe" },
	{ 55, 9, Graphics::kHotspotExit, "Treppe" },
	{ 55, 10, Graphics::kHotspotExit, "Treppe" },
	{ 55, 15, Graphics::kHotspotObject, "Vertiefungen" },
	{ 55, 16, Graphics::kHotspotExit, "Steins" "\x84" "ule" },
	{ 56, 2, Graphics::kHotspotExit, "Raum" },
	{ 57, 1, Graphics::kHotspotObject, "Gangsystem" },
	{ 57, 2, Graphics::kHotspotObject, "Boden" },
	{ 57, 3, Graphics::kHotspotObject, "Abgrund" },
	{ 57, 4, Graphics::kHotspotObject, "Pf" "\x81" "tze" },
	{ 57, 5, Graphics::kHotspotObject, "Plattform" },
	{ 57, 6, Graphics::kHotspotExit, "Treppe" },
	{ 57, 10, Graphics::kHotspotObject, "S" "\x84" "ulen" },
	{ 57, 11, Graphics::kHotspotObject, "Felsen" },
	{ 57, 12, Graphics::kHotspotObject, "Br" "\x81" "cke" },
	{ 58, 1, Graphics::kHotspotObject, "Gew" "\x94" "lbe" },
	{ 58, 2, Graphics::kHotspotExit, "Gang" },
	{ 58, 3, Graphics::kHotspotObject, "Boden" },
	{ 58, 4, Graphics::kHotspotObject, "Felsen" },
	{ 59, 2, Graphics::kHotspotObject, "Kiste" },
	{ 59, 4, Graphics::kHotspotExit, "Steint" "\x81" "r" },
	{ 59, 5, Graphics::kHotspotObject, "Kammer" },
	{ 59, 6, Graphics::kHotspotObject, "Boden" },
	{ 59, 7, Graphics::kHotspotObject, "Truhe" },
	{ 59, 8, Graphics::kHotspotObject, "Kiste" },
	{ 59, 11, Graphics::kHotspotObject, "Emblem" },
	{ 59, 12, Graphics::kHotspotObject, "Speer" },
	{ 60, 1, Graphics::kHotspotObject, "Winde" },
	{ 60, 2, Graphics::kHotspotObject, "H" "\x81" "tte" },
	{ 60, 3, Graphics::kHotspotObject, "See" },
	{ 60, 4, Graphics::kHotspotObject, "Plateau" },
	{ 60, 5, Graphics::kHotspotObject, "Steine" },
	{ 60, 6, Graphics::kHotspotObject, "Fr" "\x81" "chte" },
	{ 60, 7, Graphics::kHotspotObject, "M" "\x94" "glichkeit" },
	{ 60, 8, Graphics::kHotspotObject, "See" },
	{ 60, 9, Graphics::kHotspotObject, "Damm" },
	{ 60, 10, Graphics::kHotspotObject, "Berge" },
	{ 60, 11, Graphics::kHotspotObject, "Schleier" },
	{ 60, 12, Graphics::kHotspotObject, "Insel" },
	{ 60, 13, Graphics::kHotspotObject, "See" },
};

const SceneHotspotNameEntry kSceneHotspotNamesDemo[] = {
	{ 30, 1, Graphics::kHotspotObject, "Landschaft" },
	{ 30, 2, Graphics::kHotspotObject, "Baum" },
	{ 30, 3, Graphics::kHotspotObject, "Fass" },
	{ 30, 4, Graphics::kHotspotObject, "Pumpe" },
	{ 30, 5, Graphics::kHotspotObject, "Holzscheite" },
	{ 30, 6, Graphics::kHotspotObject, "Mauer" },
	{ 30, 7, Graphics::kHotspotExit, "Treppe" },
	{ 30, 8, Graphics::kHotspotExit, "Leiter" },
	{ 30, 9, Graphics::kHotspotExit, "Holzt" "\x81" "r" },
	{ 30, 10, Graphics::kHotspotObject, "Farm" },
	{ 30, 11, Graphics::kHotspotObject, "Heuwagen" },
	{ 30, 14, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 30, 16, Graphics::kHotspotObject, "Vorplatz" },
	{ 31, 1, Graphics::kHotspotObject, "Wasser" },
	{ 31, 2, Graphics::kHotspotExit, "Leiter" },
	{ 31, 3, Graphics::kHotspotObject, "Mauer" },
	{ 31, 4, Graphics::kHotspotObject, "Himmel" },
	{ 31, 5, Graphics::kHotspotObject, "Baum" },
	{ 31, 6, Graphics::kHotspotObject, "Landschaft" },
	{ 31, 7, Graphics::kHotspotObject, "Busch" },
	{ 31, 8, Graphics::kHotspotObject, "Winde" },
	{ 31, 9, Graphics::kHotspotObject, "Angreifer" },
	{ 31, 10, Graphics::kHotspotObject, "Treppe" },
	{ 31, 11, Graphics::kHotspotObject, "Mauer" },
	{ 32, 1, Graphics::kHotspotObject, "Holz" },
	{ 32, 2, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 32, 3, Graphics::kHotspotObject, "Heuwagen" },
	{ 32, 4, Graphics::kHotspotObject, "Haus" },
	{ 32, 6, Graphics::kHotspotObject, "Boden" },
	{ 32, 7, Graphics::kHotspotObject, "Mauer" },
	{ 32, 8, Graphics::kHotspotObject, "Unkraut" },
	{ 32, 10, Graphics::kHotspotObject, "Farm" },
	{ 32, 11, Graphics::kHotspotObject, "Himmel" },
	{ 32, 12, Graphics::kHotspotObject, "Baum" },
	{ 32, 13, Graphics::kHotspotObject, "Fenster" },
	{ 33, 1, Graphics::kHotspotObject, "Mauer" },
	{ 33, 2, Graphics::kHotspotObject, "Eimer" },
	{ 33, 3, Graphics::kHotspotObject, "Pfahl" },
	{ 33, 4, Graphics::kHotspotObject, "Gel" "\x84" "nder" },
	{ 33, 9, Graphics::kHotspotObject, "Mist" },
	{ 33, 10, Graphics::kHotspotObject, "Boden" },
	{ 33, 11, Graphics::kHotspotObject, "Haus" },
	{ 33, 13, Graphics::kHotspotObject, "Mauer" },
	{ 33, 14, Graphics::kHotspotObject, "Unkraut" },
	{ 33, 15, Graphics::kHotspotObject, "Pferdekoppel" },
	{ 33, 16, Graphics::kHotspotObject, "Wolken" },
	{ 35, 1, Graphics::kHotspotObject, "Kamin" },
	{ 35, 2, Graphics::kHotspotObject, "Musketen" },
	{ 35, 3, Graphics::kHotspotExit, "Holzt" "\x81" "r" },
	{ 35, 4, Graphics::kHotspotExit, "Treppe" },
	{ 35, 5, Graphics::kHotspotObject, "Raum" },
	{ 35, 6, Graphics::kHotspotObject, "Tisch" },
	{ 35, 7, Graphics::kHotspotObject, "Holzbank" },
	{ 35, 8, Graphics::kHotspotObject, "Brett" },
	{ 35, 10, Graphics::kHotspotObject, "Lampe" },
	{ 35, 11, Graphics::kHotspotObject, "Landschaft" },
	{ 35, 12, Graphics::kHotspotObject, "Tier" },
	{ 35, 13, Graphics::kHotspotObject, "Mauer" },
	{ 35, 15, Graphics::kHotspotObject, "Spiegel" },
	{ 35, 16, Graphics::kHotspotObject, "Lampe" },
	{ 36, 1, Graphics::kHotspotObject, "Holzt" "\x81" "r" },
	{ 36, 3, Graphics::kHotspotExit, "Treppe" },
	{ 36, 4, Graphics::kHotspotObject, "Schaufel" },
	{ 36, 6, Graphics::kHotspotObject, "Holzfass" },
	{ 36, 7, Graphics::kHotspotObject, "Holzfass" },
	{ 36, 8, Graphics::kHotspotObject, "Eichenfass" },
	{ 36, 10, Graphics::kHotspotObject, "Kiste" },
	{ 36, 11, Graphics::kHotspotObject, "Schleifspuren" },
	{ 36, 13, Graphics::kHotspotObject, "W" "\x84" "nde" },
	{ 36, 14, Graphics::kHotspotObject, "Decke" },
	{ 36, 15, Graphics::kHotspotObject, "Boden" },
	{ 37, 1, Graphics::kHotspotObject, "Planken" },
	{ 37, 2, Graphics::kHotspotObject, "Schrank" },
	{ 37, 3, Graphics::kHotspotObject, "Gusspfannen" },
	{ 37, 4, Graphics::kHotspotObject, "Holztisch" },
	{ 37, 5, Graphics::kHotspotObject, "W" "\x84" "nde" },
	{ 37, 6, Graphics::kHotspotObject, "Gussofen" },
	{ 37, 7, Graphics::kHotspotExit, "T" "\x81" "r" },
	{ 37, 8, Graphics::kHotspotObject, "Teppich" },
	{ 37, 9, Graphics::kHotspotObject, "Flasche" },
	{ 37, 10, Graphics::kHotspotObject, "Tonvase" },
	{ 37, 11, Graphics::kHotspotObject, "Brett" },
	{ 37, 12, Graphics::kHotspotObject, "Sch" "\x81" "ssel" },
	{ 37, 15, Graphics::kHotspotExit, "Holzt" "\x81" "r" },
	{ 38, 1, Graphics::kHotspotObject, "Schrank" },
	{ 38, 2, Graphics::kHotspotObject, "Kiste" },
	{ 38, 3, Graphics::kHotspotObject, "Schublade" },
	{ 38, 4, Graphics::kHotspotObject, "Bildrahmen" },
	{ 38, 5, Graphics::kHotspotObject, "Teddyb" "\x84" "r" },
	{ 38, 6, Graphics::kHotspotObject, "Bild" },
	{ 38, 7, Graphics::kHotspotObject, "Wand" },
	{ 38, 8, Graphics::kHotspotObject, "Stuhl" },
	{ 38, 9, Graphics::kHotspotObject, "Bett" },
	{ 38, 10, Graphics::kHotspotObject, "Schlange" },
	{ 38, 11, Graphics::kHotspotObject, "Holzpferd" },
	{ 38, 12, Graphics::kHotspotObject, "Spielkl" "\x94" "tze" },
	{ 38, 13, Graphics::kHotspotObject, "Holzeier" },
	{ 38, 14, Graphics::kHotspotObject, "Boden" },
	{ 38, 15, Graphics::kHotspotObject, "Holzt" "\x81" "r" },
};

static void activeHotspotTable(const SceneHotspotNameEntry *&table, uint &count) {
	if (g_engine && g_engine->isDemo()) {
		table = kSceneHotspotNamesDemo;
		count = ARRAYSIZE(kSceneHotspotNamesDemo);
	} else {
		table = kSceneHotspotNames;
		count = ARRAYSIZE(kSceneHotspotNames);
	}
}

Common::String lookupSceneHotspotName(uint16 sceneIndex, uint16 hotspotIndex) {
	const SceneHotspotNameEntry *table;
	uint tableCount;
	activeHotspotTable(table, tableCount);
	for (uint i = 0; i < tableCount; ++i) {
		const SceneHotspotNameEntry &e = table[i];
		if (e.sceneIndex == sceneIndex && e.hotspotIndex == hotspotIndex) {
			if (g_engine)
				return g_engine->translateHotspotLabel(e.name);
			return e.name;
		}
	}
	return Common::String();
}

Graphics::HotspotType lookupSceneHotspotType(uint16 sceneIndex, uint16 hotspotIndex) {
	const SceneHotspotNameEntry *table;
	uint tableCount;
	activeHotspotTable(table, tableCount);
	for (uint i = 0; i < tableCount; ++i) {
		const SceneHotspotNameEntry &e = table[i];
		if (e.sceneIndex == sceneIndex && e.hotspotIndex == hotspotIndex)
			return e.type;
	}
	return Graphics::kHotspotObject;
}

} // namespace Macs2
