version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

sphinx:
  configuration: doc/docportal/conf.py

python:
  install:
    - requirements: doc/docportal/requirements.txt

formats:
  - pdf
