# $Header$

CC      = cc
CFLAGS  = -g -O -Wall -Wstrict-prototypes -Wuninitialized -Wno-long-long -Wno-multichar
DEFINES = -DUNIX -DMACOSX
LDFLAGS :=
INCLUDES:= `sdl-config --cflags` -I./ -I./sound
CPPFLAGS= $(DEFINES) $(INCLUDES)

# Add -lmad for -DCOMPRESSED_SOUND_FILE
LIBS	= `sdl-config --libs` -framework QuickTime -framework AudioUnit

OBJS	= sdl.o

include Makefile.common
