### Modify these paths if needed
SDL_CFLAGS=-I/usr/i586-mingw32msvc/include/SDL
SDL_LIBS=-L/usr/i586-mingw32msvc/lib -lSDL

CXX = i586-mingw32msvc-g++
CXXFLAGS = -W -Wall -Wno-multichar -Ilua/include $(SDL_CFLAGS) # -O2
LDFLAGS = -W -Wall # -O2
LIBS = -Llua/lib -llua -llualib -lmingw32 -lopengl32 -lglu32 -lgdi32 \
	$(SDL_LIBS) -lz
EXEEXT =.exe

include Makefile.common

.PHONY: lua-build lua-clean
