# $Header$

CC      = gcc
CFLAGS  = -g -O -Wall -Wstrict-prototypes -Wuninitialized -Wno-long-long -Wno-multichar -DCOMPRESSED_SOUND_FILE
DEFINES = -DUNIX_X11
LDFLAGS := -L/usr/X11R6/lib -L/usr/local/lib
INCLUDES:= -I/usr/X11R6/include -I./ -I./sound -I/usr/local/include
CPPFLAGS= $(DEFINES) $(INCLUDES)

# Add -lmad for -DCOMPRESSED_SOUND_FILE
LIBS	= -lXext -lX11 -lncurses -lm -lmad -lpthread

OBJS	= x11.o

include Makefile.common

dist:
	rm -f $(ZIPFILE)
	zip -q $(ZIPFILE) $(DISTFILES)
