#include "common/scummsys.h"

// In this file, the TYPO tag is used when a typo is fixed in a piece of text, or when
// text is changed to match the audio.

namespace StarTrek {

extern const char *const g_gameStrings[] = {
	NULL,
	"",
	"Dialog error",
	"Animation error",

	"Capt. Kirk",
	"Mr. Spock",
	"Dr. McCoy",
	"Lt. Uhura",
	"Mr. Scott",
	"Mr. Sulu",
	"Mr. Chekov",

	"Ensign Everts",
	"Prel. Angiven",
	"Sign",
	"Klingon",
	"Brother Kandrey",
	"Brother Stephen",
	"Brother Chub",
	"Brother Roberts",
	"Brother Grisnash",
	"Nauian",
	"Ship's Computer",

	"Lt. Christensen",
	"Crewman Simpson",
	"Elasi Guard",
	"Elasi Clansman",
	"Elasi Cereth",
	"Masada Crewman",

	"Lt. Ferris",
	"Computer",
	"Dr. Marcus",
	"Dr. Cheever",
	"Preax",

	"Lt. Buchert",
	"Harry Mudd",

	"Lt. Stragey",
	"Quetzecoatl",
	"Tlaoxac",

	"Ensign Bennie",
	"Vlict",
	"Klingon Guard",
	"Entity",
	"Bialbi",
	"A Voice Speaks",
	"Light of War",
	"Light of Knowledge",
	"Light of Travel",

	"Ensign Mosher",

	"Ensign Kije",
	"*Capt. Patterson*",
	"*Commander Andrade*",
	"Elasi Captain",
	"Elasi Weapons Master",
	"Elasi Crewman",
	"Brittany Marata",

	"#BRID\\BRIDU146#Nothing to report, Captain.",

	"#GENE\\G_014#This person's dead, Jim.",
	"#GENE\\G_024#Fascinating.",
	"#GENE\\G_043#Ouch! Watch it with that thing!",

	"#GENE\\GENER004#Game Over",

	"#COMP\\COMPA180#Orbit Stabilized. Warning Cancelled.",
	"#COMP\\COMPA185#Please select an impedence.",
	"#COMP\\COMPA186#Ammonia",
	"#COMP\\COMPA187#Di-hydrogen Oxide",
	"#COMP\\COMPA189#Nitrous Oxide",
	"#COMP\\COMPA190#Oroborus Virus",
	"#COMP\\COMPA191#Exit Database",
	"#COMP\\COMPA193#TLTDH Gas",
	"#COMP\\COMPU181#Warning. Orbital Decay is now irreversible. Abandon Ship. Abandon Ship.",
	"#COMP\\COMPU182#Warning. Orbital decay detected. Warning.",
	"#COMP\\COMPU186#Ammonia: a colorless pungent compound NH3, a common byproduct of metabolism in carbon-based lifeforms. Liquid or gaseous at 1 atm. Compounds widely used in agricultural, medical and industrial applications.",
	"#COMP\\COMPU187#Di-hydrogen Oxide: a colorless, tasteless, nonflammable compound HO- water. Liquid, solid, or gaseous at 1 atm. Temperature scales defined in most humanoid cultures by state-shift of pure water.",
	"#COMP\\COMPU188#Dr. Marcus' Log, Supplemental: Continued testing of the Oroborus Virus confirms its potential harmful effects on Romulan/Vulcan humanoids. As soon as the spill has been cleaned up, we will sterilize both labs and purge the circulation system to make sure no traces of the virus will remain viable. Then all research files must be erased -- we must leave no chance that this terrible accident will ever be repeated.",
	"#COMP\\COMPU189#Nitrous Oxide: a colorless nonflammable compound NO, gaseous at 1 atm and temperatures within the human norm. Early anesthetic among humans, in whom it produces laughter, feelings of exhiliration, euphoria; sometimes leading to unconsciousness.",
	"#COMP\\COMPU190#Oroborus virus: Atypical growth patterns for L-Type virus. Opportunistic pneumococcal mimic affecting Romulo-Vulcan genotype. Etiology: contact or airborne vector with alveoli microcollapse involvement immediately upon exposure. Tissue dehydration follows pneumal flooding. Mortality: 0.6 in 1.0 stardates, 1.0 within 2.0 stardates Treatment: none. Named for the mythic worldsnake that swallows its own tail.",
	"#COMP\\COMPU192#Please select subject file...",
	"#COMP\\COMPU193#TLTDH gas: The chemical compound tantalum bi-lithium thalo-dihydroxide. Colorless, odorless, nonflammable gaseous at 1 atm and temperatures within the human norm. Early anesthetic among Vulcans and Romulans, in whom it produces laughter, feelings of exhiliration, euphoria; sometimes leading to unconsciousness. In post-industrial/pre-spaceflight era, a social problem evolved when crude TLTDH became popular to \"cook up\" from non-conductive tantalo-lithial compounds commonly used as electrical insulation.",

	"#DEM0\\DEM0N009#Spock raises an eyebrow.",	// kept because it's used as an enhancement in mudd1
	"All mining equipment use this road.",
	"#DEM1\\DEM1_F23#Federation Scum!",
	"#DEM3\\DEM3_019#He's dead, Jim...",
	"#DEM3\\DEM3_A32#Aieeee!",
	"#DEM3\\DEM3_F21#Oh, thank you, kind souls, for saving my life. Let me rest here for a little before returning to report this miracle to Prelate Angiven.",

	"#TUG0\\TUG0_F30#I suppose I should be grateful to see anyone after that. I thought I was dead.",
	"#TUG0\\TUG0_F31#Thank you, Doctor. Be careful, Captain, the Elasi like to set boobytraps. if you need any equipment I've got my tools in this workspace.",
	"#TUG0\\TUG0_S06#Aye Captain.",
	"#TUG0\\TUG0_S11#Captain, you're alive!",
	"#TUG2\\TUG2J003#I recommend extreme caution, Captain. We must be ready to expect anything.",
	"Snip...snip...snip.",
	"#TUG3\\TUG3_F27#Foolhardy words, Kirk. You have underestimated me at every turn.",
	"#TUG3\\TUG3_S07#Aye, Captain.",
	"#TUG3\\TUG3_S08#Aye, Captain.",

	"#LOV3\\LOV3NA08#With a hiss, the Romulan Laughing Gas billows down the vent. Things are strangely quiet below.",
	"#LOV3\\LOV3NA09#With a hiss, the Romulan Laughing Gas billows down the vent. You hear the muffled sounds through the vent of hearty Romulan laughter, followed by the dull thud of bodies hitting the deck.",
	"#LOV3\\LOV3NA20#This is a service access panel, permitting used-up or worn materials to be replaced.",
	"#LOV3\\LOV3NA21#This is a vent shaft that leads to the lower level.",
	"#LOV3\\LOV3NA22#This is an engineering access panel, allowing repairs to be made to the interior wiring in the equipment.",
	"#LOV3\\LOV3NA23#This is the engineering center for the ARK7 space station.",
	"#LOV3\\LOV3NJ32#You attach the antigrav unit to the gas tank. It can be moved freely.",
	"(Raises an eyebrow)", // NOTE: no corresponding audio
	"#LOVA\\LOVA_F01#He's been cured of the Oroborus virus.",
	"#LOVA\\LOVA_F02#I'm picking up some kind of virus. I can't identify it without more information.",
	"#LOVA\\LOVA_F03#He's infected with the virus, Jim.",
	"#LOVA\\LOVA_F04#The virus affects the Romulan-Vulcan genotype, Jim.",
	"#LOVA\\LOVA_F07#All lifesigns are normal.",
	"#LOVA\\LOVA_F08#It's what I was afraid of, Jim. I think Spock is getting worse.", // TYPO
	"#LOVA\\LOVA_F10#He has weak vital signs.",
	"#LOVA\\LOVA_F54#The virus has spread to me, Captain. I suggest you concentrate your efforts on the problem.",
	"#LOVA\\LOVA_F55#Jim, we need to synthesize more to make the serum before we can use it.", // TYPO

	"#MUD0\\MUD0_018#Life support down to 25%, Captain.",
	"#MUD0\\MUD0_019#Life support down to 50%, Captain.",
	"#MUD0\\MUD0_020#Life support down to 75%, Captain.",
	"#MUD1\\MUD1N014#This is much too heavy to lift.",
	"#MUD2\\MUD2_040#You look troubled, Captain.",
	"#MUD4\\MUD4_018#Kirk to Enterprise ... Kirk to Enterprise.", // TYPO: used in MUD4 and LOVE mission; the text was different in LOVE, not matching with audio.
	"#MUD4\\MUD4_019#Later, Mr. Scott.",
	"#MUD4\\MUD4_023#No, I need to have a word with Harry Mudd before we go.",
	"#MUD4\\MUD4_A29#Very well, bring us home, Mr. Scott.",
	"#MUD4\\MUD4_S02#The Elasi pirates have been driven off, Captain. We have damage, and injuries among the crew. We just arrived back here a few minutes ago, and we've been trying to raise you on the communicators.",
	"#MUD4\\MUD4_S03#The neutron star is causing more and more problems, Captain.  I would recommend beaming over at your earliest possible convenience.",
	"#MUD4\\MUD4_S04#We can do it, Captain, no problem. At least right now, but the situation is only going to get worse. Are you ready to beam over now?",
	
	"#FEA1\\FEA1_A46#There is not enough support, Captain.",
	"#FEA1\\FEA1_F25#What on Earth are you doing with that slithering thing!",

	"#TRI0\\TRI0_F24#How amusing. Federation weaklings.",
	"#TRI1\\TRI1_J00#Why do I have the feeling that I'm about to have a bad day?",
	"#TRI1\\TRI1U080#Affirmative, sir.",
	"Zzzt! Sptttz! Zzzt! Tttt!",
	"Clunk.",
	"#SFX\\QUIET#Zzzzzzzzzzzmmmm.",
	"#TRI4\\TRI4_076#You humans have an excellent imagination, but a poor grasp of reality.",

	"#SIN2\\SIN2_F12#This says: \"Dominant People only to dominate things beyond >,<these Submissive Walls\". My guess is that only authorized personnel were allowed beyond this door.",
	"#SIN2\\SIN2_F26#Computer science sounds more like medicine every day.",
	"#SIN3\\SIN3_008#All readings are normal. The structure seems to be protecting us from the cosmic rays.",
	"#SIN3\\SIN3_012#Can't say I like the decor.",
	"Laser Setting: 001",
	"Laser Setting: 010",
	"Laser Setting: 100",
	"cancel",
	"#SIN4\\SIN4U83B#Captain, we'll help you all we can.",

	"#VEN0\\VEN0_001#Dick Patterson and I weren't exactly friends, but this...",
	"#VEN0\\VEN0_002#Any idea of which one it was?",
	"#VEN0\\VEN0_003#Can you bring him back?",
	"#VEN0\\VEN0_004#Dick Patterson was never one for making long speeches.",
	"#VEN0\\VEN0_005#Do the sensors read any other ships in the sector?",
	"#VEN0\\VEN0_006#I don't know, Bones. We're too far from the Klingon and Romulan borders for it to be one of their ships.",
	"#VEN0\\VEN0_007#It's a mess, Scotty. Life support's functioning, but that's about it.",
	"#VEN0\\VEN0_008#Kirk Here. What is it, Scotty?",
	"#VEN0\\VEN0_009#Mr. Scott, we will continue here. Assist the trade ship and return here. If we need assistance, we will contact you.",
	"#VEN0\\VEN0_010#Well, Gentlemen. Let's see if we can reestablish power.",
	"#VEN0\\VEN0_011#Yes, Scotty. Just don't take too long. Kirk out.",
	"#VEN0\\VEN0_012#Captain, I believe we have exhausted all our options concerning data retrieval here on the bridge.",
	"#VEN0\\VEN0_013#Captain, these phasers are not configured for fine cutting. We could cause extensive damage.",
	"#VEN0\\VEN0_014#What kind of a butcher would do this sort of thing?",
	"#VEN0\\VEN0_015#I'm a doctor, not a civil engineer!",
	"#VEN0\\VEN0_016#They're dead, Jim. All of them.", // TYPO (for only some rooms this text appears in)
	"#VEN0\\VEN0_017#Jim, don't forget, there's another survivor on board. We've got to find him!",
	"#VEN0\\VEN0_018#My God, Jim. What kind of butcher would do something like this?",
	"#VEN0\\VEN0_019#Punctured lung, nerve damage, brain damage, fractured arm and ribs; it's a miracle he lasted as long as he did. He's not coming back, Jim.",
	"#VEN0\\VEN0_020#Someone must have tampered with the computer records!",
	"#VEN0\\VEN0_021#Thanks for the dissertation, Spock.",
	"#VEN0\\VEN0_022#We're too late. This man must have just died a few moments ago.",
	"#VEN0\\VEN0_023#I recommend checking as many of the logs and sensor records as possible.",
	"#VEN0\\VEN0_024#The controls have been totally destroyed. Undoubtedly due to circuit overloads caused by the battle.",
	"#VEN0\\VEN0_025#There are no more computer entries accessible from this station.",
	"#VEN0\\VEN0_026#There are no more log entries.",
	"#VEN0\\VEN0_027#Tricorder readings indicate that the ship is running on minimal battery power. Only life support and essential systems are currently running.",
	"#VEN0\\VEN0_028#Captain, records indicate that this ship was attacked by a Constitution-class Starship.",
	"#VEN0\\VEN0_029#I am reading a record of the transponder signal. NCC-1701. It's the Enterprise, Captain.",
	"#VEN0\\VEN0_030#I've done a primary scan of the Republic's systems. Main and auxiliary power is out. Life support is stable. I also read that communications are operable.",
	"#VEN0\\VEN0_031#May I remind you, Doctor, that the main computer of a Constitution class starship has safeguards against such an intrusion. Furthermore, I do not see any discrepancies in any of the files that I am able to access.",
	"#VEN0\\VEN0_32#My tricorder has picked up the final entry of the Republic.",
	"#VEN0\\VEN0_033#That's all there is, Captain.",
	"#VEN0\\VEN0_034#This is a standard Tritanium/Duranium support beam. Tricorder readings indicate that although it has experienced enough tensile stress to push it from one side of its mooring, it has not elastically deformed beyond its ability to support a compressive load.",
	"#VEN0\\VEN0_035#We are under attack. Our sensors are inoperative. We're trying to get shields up. Our rear deflector's down. It appears our enemy is a Constitution class starship. We have tried to defend ourselves. We've hailed them, but no response.",
	"#VEN0\\VEN0_036#I feel sick.",
	"#VEN0\\VEN0_037#I think I remember seeing a ton of these at spacedock 4.",
	"#VEN0\\VEN0_038#There is no response, Captain. The controls are completely dead.",
	"#VEN0\\VEN0_039#Besides the trade wessel, this sector is clear, Sir.",
	"#VEN0\\VEN0_S12#Enterprise to Captain Kirk.",
	"#VEN0\\VEN0_S15#Should we beam you back, Captain?",
	"#VEN0\\VEN0_S52#We've picked up a distress signal. It appears a trading vessel is having a wee bit of trouble with their warp drive. What condition is the Republic in?",
	"#VEN0\\VEN0_S54#You sure you'll be all right, Captain?",
	"#VEN0\\VEN0N000#A common Tritanium/Duranium support beam which has snapped away from the hull.",
	"#VEN0\\VEN0N001#Captain James T. Kirk. This is not one of the best days of his life.",
	"#VEN0\\VEN0N002#Dr. Leonard McCoy. You have rarely seen him as shaken as he is now.",
	"#VEN0\\VEN0N003#Ensign Kije, who wishes that Lieutenant Stackpole had drawn this assignment.",
	"#VEN0\\VEN0N004#Here is the body of Captain Patterson of the Republic. He didn't die without a fight.",
	"#VEN0\\VEN0N005#Main computer banks. They appear to have been damaged.",
	"#VEN0\\VEN0N006#Mr. Spock, awaiting orders.",
	"#VEN0\\VEN0N007#The molecular saw easily cuts through the beam, separating it from the hull.",
	"#VEN0\\VEN0N008#The support beam has already been detached from the hull.",
	"#VEN0\\VEN0N009#The support beam is still attached to the hull.",
	"#VEN0\\VEN0N010#The viewscreen is not functioning.",
	"#VEN0\\VEN0N011#These are the helm controls for the Republic. They are currently inactive.",
	"#VEN0\\VEN0N012#These are the navigation controls for the Republic. They are currently inactive.",
	"#VEN0\\VEN0N013#This beam has been detached from the hull.",
	"#VEN0\\VEN0N015#This is is the Captain's chair, where the Captain's log is stored.",
	"#VEN0\\VEN0N016#This man is dead.",
	"#VEN0\\VEN0N017#This person is dead.",
	"#VEN0\\VEN0N018#You are in what's left of the bridge of the U.S.S. Republic.",
	"#VEN0\\VEN0N019#You pick up the beam. It's a little heavy, but you manage it.",


	"#VEN1\\VEN1_001#I wonder if anything will be working in Auxilary Control.",
	"#VEN1\\VEN1_002#You'll get your chance, Bones. I promise.",
	"#VEN1\\VEN1_004#I'd like to meet the people responsible for this and give them a piece of my mind.",
	"#VEN1\\VEN1_005#Too bad you can't say the same for the crew.",
	"#VEN1\\VEN1_006#Initial scans show that the gear mechanism is currently jammed with metallic debris.",
	"#VEN1\\VEN1_007#Readings of the door indicate a jam in the gear mechanism.",
	"#VEN1\\VEN1_008#That may not be wise, Captain. It could damage the entire door assembly in its weakened condition.",
	"#VEN1\\VEN1_009#The gear mechanism is now cleared.",
	"#VEN1\\VEN1_010#The gears are moving freely and are completely operative.",
	"#VEN1\\VEN1_011#The vent is far too small for any one of us to fit through. It is also blocked point three meters inside the duct.",
	"#VEN1\\VEN1_012#This is a molecular saw, Captain. It is used for precision cutting. My tricorder reads that the power cells are fully charged.",
	"#VEN1\\VEN1_013#The Starfleet Engineers did their work well Captain. A surprising amount of the ship is intact.",
	"#VEN1\\VEN1_014#Tricorder indicates that the panel is currently sealed by Federation standard molecular bonding cement.",
	"#VEN1\\VEN1_015#From my lessons at the Academy, sir, we were told that a standard issue Federation phaser does not have enough power to cut through a security door such as this one.",
	"#VEN1\\VEN1_016#I'm not in a talking mood right now, sir.",
	"#VEN1\\VEN1_F33#The panel is open.",
	"#VEN1\\VEN1N000#A knot of debris is jamming the gear mechanism.",
	"#VEN1\\VEN1N001#A Molecular Saw. The 23rd century equivalent of a hacksaw.",
	"#VEN1\\VEN1N002#Captain Kirk hopes that he will never see the day when the Enterprise is this badly battered.",
	"#VEN1\\VEN1N003#Irritated by the emotions of the humans that are accompanying him, Spock does his best to keep his mind on the problems at hand.",
	"#VEN1\\VEN1N004#Leonard McCoy wishes he were back on the Enterprise.",
	"#VEN1\\VEN1N005#Kije wishes that everyone would stop fidgeting. It's making him nervous.",
	"#VEN1\\VEN1N006#The debris is jammed in too tight.",
	"#VEN1\\VEN1N007#The door is jammed shut.",
	"#VEN1\\VEN1N008#The drill easily breaks through the seal of the panel.",
	"#VEN1\\VEN1N009#The drill is not powerful enough to cut through the debris.",
	"#VEN1\\VEN1N010#The gear mechanism for the door is now fully functional.",
	"#VEN1\\VEN1N011#The gears are completely cleared of debris.",
	"#VEN1\\VEN1N012#The Hypo is empty.",
	"#VEN1\\VEN1N013#The molecular saw is much too large for the panel.",
	"#VEN1\\VEN1N014#The molecular saw will not penetrate a security door.",
	"#VEN1\\VEN1N015#The oil seeps into and loosens the debris.",
	"#VEN1\\VEN1N016#The panel has been fastened shut with some kind of sealant.",
	"#VEN1\\VEN1N017#The panel opens easily.",
	"#VEN1\\VEN1N018#The saw is too bulky to reach the jammed debris.",
	"#VEN1\\VEN1N019#There appears to be debris jammed in the gear mechanism.",
	"#VEN1\\VEN1N020#This corridor leads to auxiliary control. It is a real mess.",
	"#VEN1\\VEN1N021#This door leads to auxiliary control.",
	"#VEN1\\VEN1N022#This is the maintenance panel for the auxiliary control room door.",
	"#VEN1\\VEN1N023#You retrieve the molecular saw.",


	"#VEN2\\VEN2_001#Mr. Spock, what is the condition of the fire control system?",
	"#VEN2\\VEN2_002#Mr. Spock, what is the status of the ship's computer?",
	"#VEN2\\VEN2_003#Spock, what is the situation with the impulse engines?",
	"#VEN2\\VEN2_004#We don't have much time for talk. The Elasi are known for their punctuality.",
	"#VEN2\\VEN2_005#What a mess. I wonder what we can do to fix this.",
	"#VEN2\\VEN2_006#I assume, since you haven't blasted us to bits, you want something.",
	"#VEN2\\VEN2_007#I don't know, Bones.",
	"#VEN2\\VEN2_008#I see your point.",
	"#VEN2\\VEN2_009#I'm not one to overlook strategic implications, Mr. Spock, but we can save that for another time.",
	"#VEN2\\VEN2_010#It was a setup?!",
	"#VEN2\\VEN2_011#It will take time. The controls are smashed, and the main computer's badly damaged. It will take hours to get power to the computer banks.",
	"#VEN2\\VEN2_012#Just try and get it. You can't threaten me!",
	"#VEN2\\VEN2_013#No, Ensign. It looks like the Elasi have been doing some business with them. Scotty, beam us back. We need to find that ship that attacked the Republic.",
	"#VEN2\\VEN2_014#Not too soon, I hope.",
	"#VEN2\\VEN2_015#Not yet. We're having trouble accessing all the data files.",
	"#VEN2\\VEN2_016#Put it on Screen, Spock.",
	"#VEN2\\VEN2_017#Spock, just tell me if they will help.",
	"#VEN2\\VEN2_018#Spock, what about the Fusion Power Pack? Could we use it to power the transporter?",
	"#VEN2\\VEN2_019#That ship was cloaked!",
	"#VEN2\\VEN2_020#The Masada, I presume. You want the locations of all your imprisoned comrades?",
	"#VEN2\\VEN2_021#The Republic will fall apart if you fire on us. Then you'll never get the data.",
	"#VEN2\\VEN2_022#Thirty minutes, then. Kirk out.",
	"#VEN2\\VEN2_023#Umm, well...",
	"#VEN2\\VEN2_024#We don't have several days, Mr. Spock.",
	"#VEN2\\VEN2_025#We'll comply. Kirk out.",
	"#VEN2\\VEN2_026#We're fine, lieutenant.",
	"#VEN2\\VEN2_027#What do you want?",
	"#VEN2\\VEN2_028#Yes, Uhura, Just wanted a status report. Kirk out.",
	"#VEN2\\VEN2_029#Yes, we have. You'll have to beam over and get it, though. The computer's subspace transmitter is out.",
	"#VEN2\\VEN2_030#Both Tricorders are rigged into the main computer's central processing unit. We now have enough computational power to control a single ship's system.",
	"#VEN2\\VEN2_031#Captain, I recommend we wait until we have restored power before I hook up the tricorders to the main computer. We may need them in engineering first.",
	"#VEN2\\VEN2_032#Captain, I suggest we try to raise the shields.",
	"#VEN2\\VEN2_033#Captain, I suggest we try to raise the shields.",
	"#VEN2\\VEN2_034#Captain, the elasi can surely detect the lowering of our shields. They will undoubtedly try to board us if we lower them.",
	"#VEN2\\VEN2_035#Captain, the elasi can surely detect the lowering of our shields. They will undoubtedly try to board us if we lower them.",
	"#VEN2\\VEN2_036#Captain, the torpedo loading system is malfunctioning. To clear it, we will have to physically examine the mechanism. Currently, all turbolift access to the torpedo bay is blocked by a hull breach. Fortunately, it is highly unlikely that we will need this ship's weapons systems.",
	"#VEN2\\VEN2_037#Captain, the torpedo loading system is malfunctioning. To clear it, we will have to physically examine the mechanism. Currently, all turbolift access to the torpedo bay is blocked by a hull breach. It is imperative that we get the weapons on-line.",
	"#VEN2\\VEN2_038#I'm a doctor, not a computer scientist!",
	"#VEN2\\VEN2_039#I'm glad this isn't the Enterprise.",
	"#VEN2\\VEN2_040#Jim, since we do not have what they want, I don't think it is a good idea to contact them until we are able to defend ourselves.",
	"#VEN2\\VEN2_041#Cloaked Elasi. I wonder who the old friend they mentioned is?",
	"#VEN2\\VEN2_042#Is that all you can say?",
	"#VEN2\\VEN2_043#Jim, do we really need a lesson in starship engineering?",
	"#VEN2\\VEN2_044#Shut up, Spock!",
	"#VEN2\\VEN2_045#That's just great, Spock. We don't exactly carry an M-5 computer in our inventory.",
	"#VEN2\\VEN2_046#I have memorized all pertinent data, Captain. there is no need to reexamine the journals.",
	"#VEN2\\VEN2_047#It would not be prudent to remove the tricorder at this time, Captain. Doing so will cause the shields to shut down and allow the elasi to beam a boarding party over.",
	"#VEN2\\VEN2_048#Lowering shields and allocating power to photon torpedo systems. Torpedo is loaded and ready.",
	"#VEN2\\VEN2_050#Photon torpedoes are loaded and ready to be fired.", // TYPO
	"#VEN2\\VEN2_051#Power is available, but the main computer is too badly damaged to actively control the power circuits.",
	"#VEN2\\VEN2_052#Sensors indicate that the Elasi Ship has lowered its shields. I suggest we prepare your surprise soon, Captain. They will beam over any moment.",
	"#VEN2\\VEN2_053#That would be unwise, Captain. I thought our plan was to surprise the Elasi.",
	"#VEN2\\VEN2_054#The elasi ship's shield are still raised, captain. A single photon hit will have a negligible effect on the ship.",
	"#VEN2\\VEN2_055#The impulse engines are back on-line, but we have no way of directing power to the weapons system.",
	"#VEN2\\VEN2_056#The impulse power allocation controls are functional, but there is no power available, Captain.",
	"#VEN2\\VEN2_057#The main computer is too badly damaged to actively control the power circuits.",
	"#VEN2\\VEN2_058#The torpedo warning systems are showing a malfunction in the torpedo loading bay.",
	"#VEN2\\VEN2_059#The tricorders are currently operating at 12.69 percent less than normal computing efficiency.",
	"#VEN2\\VEN2_060#The unit doesn't generate enough power to run any of the major systems. Main or Auxiliary power is required for that, Captain.",
	"#VEN2\\VEN2_061#There are no more log decks, Captain.",
	"#VEN2\\VEN2_062#There currently is no power being allocated to the weapons system. Even if there were a power source, the damage to the main computer is enough to prevent power allocation to that system.",
	"#VEN2\\VEN2_063#There is currently no power to be allocated from the engines.",
	"#VEN2\\VEN2_064#There is no power allocated to the weapons system, Captain.",
	"#VEN2\\VEN2_065#There is no power allocated to the weapons system.",
	"#VEN2\\VEN2_066#They are jamming all frequencies, Captain. We will not be able to contact the Enterprise.",
	"#VEN2\\VEN2_067#This input/output slot for the record decks is still functional, Captain.",
	"#VEN2\\VEN2_068#Weapons control is functioning properly, however, there appears to be a jam in the primary loading mechanism.",
	"#VEN2\\VEN2_069#With impulse power online and the tricorders performing computer control, I can divert power to...",
	"#VEN2\\VEN2_070#Captain, I have examined the Engineering Journals. According to chapter eighteen, we can run...",
	"#VEN2\\VEN2_071#Captain, I suggest we try to raise the shields.",
	"#VEN2\\VEN2_072#Captain, the main computer is far beyond...",
	"#VEN2\\VEN2_073#Captain, we are being hailed by the Elasi Captain.",
	"#VEN2\\VEN2_074#Correct, Doctor. However, there may be another alternative. Linked tricorders, along with the circuits in the data reader, should have the processing power necessary to control a single starship system.",
	"#VEN2\\VEN2_075#Fascinating. A cloaked Elasi.",
	"#VEN2\\VEN2_076#Fascinating.",
	"#VEN2\\VEN2_077#I believe so, Captain. It would require a connection to the transporter circuits in the main control console.",
	"#VEN2\\VEN2_078#That is beyond the Elasi's capabilities, Ensign.",
	"#VEN2\\VEN2_079#There is extensive damage to the main processing unit of the ship's computer. It will take several days at a starbase to repair.",
	"#VEN2\\VEN2_080#Unless we can find a suitable computational alternative, there will be no way to control the ship's systems.",
	"#VEN2\\VEN2_081#Why, yes, Captain.",
	"#VEN2\\VEN2_082#Captain's log, stardate 6087.6. The Republic is currently approaching the Vardaine system. Sensors have detected unusual energy fluctuations near one of the Vardainian moons. Starfleet has ordered us to investigate.",
	"#VEN2\\VEN2_083#Captain's log, stardate 6087.8. We are under attack by two unidentified ships. I don't know how they could have approached undetected. They must have some kind of cloaking device, although there are no reports of Romulans in this sector.",
	"#VEN2\\VEN2_084#Captain's log, stardate 6088.1. We have successfully driven off our assailants. Major damage has been sustained by our warp engines. Communications has reported that U.S.S. Enterprise is in sector. I requested Mr. Scott's assistance in repairing damage to the Republic. With luck, we will be fully operational in a couple of days.",
	"#VEN2\\VEN2_085#Captain, the Elasi will surely fire upon us if we raise our shields.",
	"#VEN2\\VEN2_086#If there's anything I can do, sir, just ask.",
	"#VEN2\\VEN2_087#Power allocated to transporter systems, sir.",
	"#VEN2\\VEN2_088#Power allocated to weapons systems, Captain.",
	"#VEN2\\VEN2_089#Power has already been allocated to the shields, sir.",
	"#VEN2\\VEN2_090#Power has already been allocated to the transporter systems, Captain.",
	"#VEN2\\VEN2_091#Power has already been allocated to the weapons, Sir.",
	"#VEN2\\VEN2_092#Shields are up, sir.",
	"#VEN2\\VEN2_093#Captain, Look! An Elasi ship!",
	"#VEN2\\VEN2_094#Captain, do you suppose the Elasi might have used cloaking technology to project a false image, of a ship the Republic would trust?",
	"#VEN2\\VEN2_096#Thank goodness for parallel processing. I don't know what computers could do without it.",
	"#VEN2\\VEN2_097#Captain's log, stardate 6088.5. First Officer Andrade commanding. The Enterprise has unexplicably opened fire upon us. Captain Patterson has been mortally wounded. We have sustained major damage to all systems. Impulse power is out. We cannot understand why...",
	"#VEN2\\VEN2_098#What are you stalling for? Lower your shields.",
	"#VEN2\\VEN2_099#Can't threaten you?! As you said, I can blow you to bits!",
	"#VEN2\\VEN2_100#You better step on it, Kirk! You only have a few minutes left!",
	"#VEN2\\VEN2_101#Activate cloaking device! Kirk, until we meet again.",
	"#VEN2\\VEN2_102#All right, Kirk. We'll do it your way. I would rather not kill you. Besides, there's an old friend that wants to meet you. I give you thirty minutes. And remember, no tricks.",
	"#VEN2\\VEN2_103#I can see why they made you Captain!",
	"#VEN2\\VEN2_104#Kirk! I should have known you'd try something underhanded like this. Weaponsmaster, fire all weapons on the Republic!",
	"#VEN2\\VEN2_105#Maybe I should just pump a few torpedoes into your shields and check it out for myself.",
	"#VEN2\\VEN2_106#Watch yourself, Captain. It may be sooner than you realize.",
	"#VEN2\\VEN2_107#We finally meet in person, Captain Kirk. So where is the data I requested?",
	"#VEN2\\VEN2_108#Well, Captain Kirk, I trust you and your valiant crew have retrieved the data I requested?",
	"#VEN2\\VEN2_109#Well, if it isn't Captain Kirk. Fancy meeting you out here all alone in such a shabby starship.",
	"#VEN2\\VEN2_110#What? You mean you were deliberately wasting my time? Guards, take them back to the ship! I'll think of a suitable punishment for them later.",
	"#VEN2\\VEN2_111#Why, yes I do. It seems you failed to give one of my associates some rather important information.",
	"#VEN2\\VEN2_112#Yes, Kirk. The Republic's computers will have the data just as your Enterprise would. I give you one minute to comply.",
	"#VEN2\\VEN2_113#You should be more civil considering your Enterprise is far away on a mercy mission helping that poor trader.",
	"#VEN2\\VEN2_114#How convenient, Kirk. We'll beam over, but no tricks. My sensors read that only your shields have power. Lower them now!",
	"#VEN2\\VEN2_115#Sir, we picked up another ship nearby and we came as fast as we could. It appeared to cloak. Were you attacked by Romulans?",
	"#VEN2\\VEN2_ELA#Contact Elasi Ship.",
	"#VEN2\\VEN2_ENT#Contact Enterprise.",
	"#VEN2\\VEN2_F28#Captain, the Enterprise is coming on high speed approach!",
	"#VEN2\\VEN2_F29#We can't, Captain. All weapons systems off-line!",
	"#VEN2\\VEN2_F35#This is the photon torpedo launching control.",
	"#VEN2\\VEN2_S09#Aye, Captain.",
	"#VEN2\\VEN2_SHI#Shields",
	"#VEN2\\VEN2_TRA#Transporter Circuits",
	"#VEN2\\VEN2_WEA#Weapons",
	"#VEN2\\VEN2N000#A red flashing light is currently indicating a jam in the torpedo loading mechanism.",
	"#VEN2\\VEN2N001#All indicators are dead.",
	"#VEN2\\VEN2N002#An Elasi frigate is visible on the viewscreen. Though silent now, you know it is ready to attack at a moment's notice.",
	"#VEN2\\VEN2N003#Damage from the battle has disabled the ship's main computer.",
	"#VEN2\\VEN2N004#Ensign Kije doesn't see the need for a security escort.",
	"#VEN2\\VEN2N005#Indicators currently show all power diverted to the shields.",
	"#VEN2\\VEN2N006#Indicators currently show all power diverted to transporter systems.",
	"#VEN2\\VEN2N007#Indicators currently show all power diverted to weapons control.",
	"#VEN2\\VEN2N008#Indicators currently show no power output from the impulse engines.",
	"#VEN2\\VEN2N009#Indicators show impulse power online, but no power allocated to any systems.",
	"#VEN2\\VEN2N010#Kirk is dismayed by the damage that was done to Auxiliary Control.",
	"#VEN2\\VEN2N011#McCoy is fidgeting around.",
	"#VEN2\\VEN2N012#McCoy wishes that Mr. Scott were here.",
	"#VEN2\\VEN2N013#Medical Tricorder taken.",
	"#VEN2\\VEN2N015#Science Tricorder taken.",
	"#VEN2\\VEN2N016#Spock crudely attaches the medical tricorder to the computer console.",
	"#VEN2\\VEN2N017#Spock crudely attaches the science tricorder to the computer console.",
	"#VEN2\\VEN2N018#Spock is analyzing the surroundings.",
	"#VEN2\\VEN2N019#Spock wishes that Mr. Scott were here.",
	"#VEN2\\VEN2N020#Status indicator show that the torpedo tubes are currently empty.",
	"#VEN2\\VEN2N021#Status indicators show that photon torpedo number one and is loaded and ready to be fired.",
	"#VEN2\\VEN2N022#The auxiliary control room viewscreen is still operating. It is displaying a view of empty space.",
	"#VEN2\\VEN2N023#The medical tricorder is crudely wired into the computer console.",
	"#VEN2\\VEN2N024#The medical tricorder is currently wired into the computer console.",
	"#VEN2\\VEN2N025#The science and medical tricorders are jury-rigged to the remains of the Republic computer system.",
	"#VEN2\\VEN2N027#The science tricorder is currently wired into the computer console.",
	"#VEN2\\VEN2N028#There is no response.",
	"#VEN2\\VEN2N029#These are Federation standard record decks.",
	"#VEN2\\VEN2N030#These are the auxiliary helm and navigation controls for the Republic. Though they are intact, the ship is in no condition to move under her own power.",
	"#VEN2\\VEN2N031#This is a standard input/output slot for record decks.",
	"#VEN2\\VEN2N032#This is the auxiliary ship damage display. Red flashing damage indicators dominate its surface.",
	"#VEN2\\VEN2N033#This is the fire control for the photon torpedoes. ",
	"#VEN2\\VEN2N034#This is the impulse power allocation control.",
	"#VEN2\\VEN2N035#This is the Republic's Auxiliary Control Room. It appears to be in better shape than the main bridge.",
	"#VEN2\\VEN2N038#You are in a typical starship corridor.",
	"#VEN2\\VEN2N039#You take the record decks.",
	"#VEN2\\VEN2U093#Enterprise here. We're still tracking the distress call. Are you all right, Sir?",
	"#VEN2\\VEN2U094#Enterprise to Captain Kirk. Are you safe, sir?",
	"Hail Elasi",
	"Hail Enterprise",
	"cancel",


	"#VEN3\\VEN3_001#I wish I were a poet. I wish I had the words to match how this makes me feel. These people were Starfleet officers, giving their lives to explore the cosmos. I wish I knew some eulogy that did them justice.",
	"#VEN3\\VEN3_002#Captain, using the stun setting is most illogical.",
	"#VEN3\\VEN3_003#Damn this tricorder. Why couldn't one of them be alive?",
	"#VEN3\\VEN3_004#I'm a doctor, not a coal miner.",
	"#VEN3\\VEN3_005#A poor choice of words, Ensign.",
	"#VEN3\\VEN3_006#I thought you were a science officer, not a tour guide.",
	"#VEN3\\VEN3_007#The beam is supporting the ceiling, Captain.",
	"#VEN3\\VEN3_008#The debris appears quite unstable. Any disturbances may trigger an avalanche of debris to fall.",
	"#VEN3\\VEN3_009#The debris is highly unstable, Captain. I recommend we try to find a support of some kind to secure the ceiling.",
	"#VEN3\\VEN3_010#The molecular saw is too fine of a cutting tool to be of any use in clearing the debris.",
	"#VEN3\\VEN3_011#There is too much debris to remove by hand.",
	"#VEN3\\VEN3_012#Turbolift ahead, Captain.",
	"#VEN3\\VEN3_013#Captain, it is critical that we gain access to this turbolift. It is our only means of exploring the rest of this ship.",
	"#VEN3\\VEN3_014#Captain, the support beam for the ceiling is damaged here. There will be no way to safely clear out the debris without a replacement.",
	"#VEN3\\VEN3_015#The ceiling appears stable. We should now be able to use Turbolift 2, Captain.",
	"#VEN3\\VEN3_016#It will take us forever to dig through all that, sir.",
	"#VEN3\\VEN3_017#Sir, I really don't think we should try and mess with that debris. We may bring the whole thing down on us.",
	"#VEN3\\VEN3_018#Be careful, Captain. This ship is a death trap.",
	"#VEN3\\VEN3N000#Kije struggles with emotions he never knew he had.",
	"#VEN3\\VEN3N001#Kirk is increasingly distressed by what he has seen.",
	"#VEN3\\VEN3N002#McCoy examines his tricorder, knowing that his hopes are not going to be fulfilled.",
	"#VEN3\\VEN3N003#One of the many battered corridors of the U.S.S. Republic. It has seen better days. Much better days.",
	"#VEN3\\VEN3N004#Spock says nothing, but this tragedy stirs something in his Vulcan soul.",
	"#VEN3\\VEN3N005#The crewman's death was pointless. Just like too many deaths in human history.",
	"#VEN3\\VEN3N006#The debris is blocking the Turbolift doors.",
	"#VEN3\\VEN3N007#The support beam appears to have stabilized the ceiling.",
	"#VEN3\\VEN3N009#There is a twisted mess of wire and metal falling from the gaping hole in the ceiling. It is blocking access to turbolift 2.",
	"#VEN3\\VEN3N010#There is far too much debris to be cleared by hand.",
	"#VEN3\\VEN3N011#This door leads to Sickbay.",
	"#VEN3\\VEN3N012#This door leads to TurboLift 2.",
	"#VEN3\\VEN3N013#This is a length of heavy duty insulated power cable.",
	"#VEN3\\VEN3N014#You have taken the cable.",


	"#VEN4\\VEN4_001#Do what you can, Bones. I need to find out what happened here.",
	"#VEN4\\VEN4_002#You always hope the instruments are wrong...that you'll find someone alive.",
	"#VEN4\\VEN4_003#It wasn't the Enterprise, Marata!",
	"#VEN4\\VEN4_004#Marata, what happened?",
	"#VEN4\\VEN4_005#I can't believe it. That's Brittany Marata. I knew her from my Academy days. We studied alien history together.",
	"#VEN4\\VEN4_006#What about the Enterprise?",
	"#VEN4\\VEN4_007#He's dead, Jim. I can't bring him back.",
	"#VEN4\\VEN4_008#That will accomplish nothing, Jim.",
	"#VEN4\\VEN4_009#She's in bad shape, Jim. I've tried to stabilize her, but it doesn't look good.",
	"#VEN4\\VEN4_010#She's in no condition to talk right now.",
	"#VEN4\\VEN4_011#She's suffering from severe trauma and internal bleeding. I'll see what I can do.",
	"#VEN4\\VEN4_012#That won't bring her back. She's gone.",
	"#VEN4\\VEN4_013#There's nothing more I can do for her, Jim.",
	"#VEN4\\VEN4_014#At least she's still alive, although just barely.",
	"#VEN4\\VEN4_015#Life support must have gone down during the fight. Most of the people died from shock before the back-up systems came on line.",
	"#VEN4\\VEN4_016#There's nothing more I can do.", // TYPO (in some rooms, this has "Jim..." at the start of the text, though not in VENG4 itself)
	"#VEN4\\VEN4_017#I believe nothing needs to be said, Captain.",
	"#VEN4\\VEN4_018#An interesting hypothesis, doctor. Had Mr. Scott been present, he might have been able to verify it.",
	"#VEN4\\VEN4_019#No... you won't get us...",
	"#VEN4\\VEN4_020#They said it was the Enterprise...They had visual confirmation...",
	"#VEN4\\VEN4_021#You killed us, Jim. We were friends for... I trusted ...",
	"#VEN4\\VEN4_022#Captain, did I ever mention how much I hate hospitals?",
	"#VEN4\\VEN4N000#A very concerned Doctor Leonard McCoy.",
	"#VEN4\\VEN4N001#A very unhappy looking Ensign Kije.",
	"#VEN4\\VEN4N002#James T. Kirk, in total confusion at the moment.",
	"#VEN4\\VEN4N003#Mr. Spock, looking pensive as usual.",
	"#VEN4\\VEN4N004#Seeing Brittany in this condition stirs you on to find the culprits responsible for this injustice.",
	"#VEN4\\VEN4N005#The medical scanner has registered the death of Brittany Marata.",
	"#VEN4\\VEN4N006#The medical scanner is monitoring the woman's condition.",
	"#VEN4\\VEN4N007#The woman in this sickbed is alive, barely.",
	"#VEN4\\VEN4N008#This door leads back to the corridor and turbolifts.",
	"#VEN4\\VEN4N009#This door leads back to the corridor, and turbolifts 1 and 2.",
	"#VEN4\\VEN4N010#This is an empty hypodermic injector.",
	"#VEN4\\VEN4N011#This is the Republic's sickbay. Fortunately, power is still functioning here.",
	"#VEN4\\VEN4N012#This medical drill fires a microscopic phaser beam.",
	"#VEN4\\VEN4N013#This monitor has recorded the death of a patient.",
	"#VEN4\\VEN4N014#Yet another crewman of the Republic whose life was unfairly abbreviated.",
	"#VEN4\\VEN4N015#You pick up the empty hypodermic injector.",
	"#VEN4\\VEN4N016#You retrieve the medical drill.",
	"#VEN4\\VEN4N017#You see the dead body of Brittany. Her life was cut short and you won't stop until you find the persons responsible.",


	"#VEN5\\VEN5_001#We must complete our mission, gentlemen.",
	"#VEN5\\VEN5_002#Is the fire in danger of spreading, spock?",
	"#VEN5\\VEN5_003#Thank you, Spock, I think we get the point.",
	"#VEN5\\VEN5_004#A standard portable fusion power pack. It is fully functional, Captain.",
	"#VEN5\\VEN5_005#Captain, I'm picking up a functioning energy source in the immediate vicinity.",
	"#VEN5\\VEN5_006#I can't say that I'm very talkative right now.",
	"#VEN5\\VEN5_007#Jim, are you mad? Put that phaser away. You almost killed us once already.",
	"#VEN5\\VEN5_008#No lifeforms present, Jim. I'm picking up some kind of energy reading, though.",
	"#VEN5\\VEN5_009#One of those fusion power packs, Jim. What do you want me to do with it?",
	"#VEN5\\VEN5_010#A few centimeters lower with that phaser and half this section would be history, not to mention us...",
	"#VEN5\\VEN5_011#Oh, my God, Jim! Is that what I think it is?",
	"#VEN5\\VEN5_012#I am picking up a high energy power source somewhere under the debris. I recommend caution, Captain.",
	"#VEN5\\VEN5_013#The stun setting would be ineffective, Captain.",
	"#VEN5\\VEN5_015#Captain, it is unadvisable to approach too closely. There is an open fire nearby.",
	"#VEN5\\VEN5_016#No, Captain. There is an inadequate supply of flammable material. It will eventually burn itself out.",
	"#VEN5\\VEN5_017#This corridor seems to have been particularly damaged. There have been hull breaches on the deck below.",
	"#VEN5\\VEN5_018#Yes, Doctor. It is a portable fusion power pack.",
	"#VEN5\\VEN5_019#Actually, Doctor, three point two centimeters. And based on our proximity to the explosion, and the angle of the beam...",
	"#VEN5\\VEN5_R19#Is there a question, Captain?",
	"#VEN5\\VEN5_R20#I will monitor the situation, Mr. Spock. I can use the distraction.",
	"#VEN5\\VEN5N000#A look of terror is still etched on the face of this crewman.",
	"#VEN5\\VEN5N001#A rather large pile of debris.",
	"#VEN5\\VEN5N002#A resolute Mr. Spock.",
	"#VEN5\\VEN5N003#A sad but determined James T. Kirk.",
	"#VEN5\\VEN5N004#Dr. McCoy avoids the glances of his crewmates.",
	"#VEN5\\VEN5N005#Ensign Kije, learning that Starfleet isn't always very pleasant.",
	"#VEN5\\VEN5N006#This corridor leads to the Republic's Engineering section.",
	"#VEN5\\VEN5N007#This door leads to main engineering.",
	"#VEN5\\VEN5N008#These ladders are used when turbolifts are unavailable. Unfortunately, it is blocked by debris and a small, smoldering fire.",
	"#VEN5\\VEN5N009#This is the most powerful portable energy storage device ever developed by man. It is used to provide temporary power to small systems when Main or Auxiliary power is unavailable.",
	"#VEN5\\VEN5N010#You pick up the portable Fusion power pack.",


	"#VEN6\\VEN6_001#Can we re-route the power lines?",
	"#VEN6\\VEN6_002#Go ahead and adjust the settings, Spock.",
	"#VEN6\\VEN6_003#Spock?",
	"#VEN6\\VEN6_005#This reminds me of a poem I read when I was a child. \"I am Ozymandius, King of Kings, look upon my works, ye mighty, and despair.\"", // TYPO
	"#VEN6\\VEN6_006#Captain, the energy output of the Fusion Power pack is insufficient to power any of the major ship's systems.",
	"#VEN6\\VEN6_007#Captain, this is the fusion mixture regulator for the impulse engines. There is currently no power running to it.",
	"#VEN6\\VEN6_008#Remind me to compliment Mr. Scott on the efficiency of his engineering section.",
	"#VEN6\\VEN6_009#You have good reason to despair, here, Jim.",
	"#VEN6\\VEN6_010#Impulse power is functioning, Captain.",
	"#VEN6\\VEN6_011#It is illogical to use this machine before we have something connected to it.",
	"#VEN6\\VEN6_012#The impedance is correctly set, Captain. Changing the setting could be dangerous.",
	"#VEN6\\VEN6_013#The regulator is fully operating from the power tap run from the impulse engines. We can allocate power to ship's systems in Auxiliary Control.",
	"#VEN6\\VEN6_014#There has been a .0003 degradation in hull integrity in the last hour. There should be no danger, Captain.",
	"#VEN6\\VEN6_015#This is an engineering circuit junction box. It is used for temporary re-routing of power. Without using one of these devices set to the proper impedance, an overload can occur.",
	"#VEN6\\VEN6_016#Captain, the information obtained from the engineering journals indicates the correct impedance setting to be nineteen thousand ohms.",
	"#VEN6\\VEN6_017#Captain, the wrong setting on this particular device may cause the fusion reactors to melt down. We will have to do some research to determine the correct setting.",
	"#VEN6\\VEN6_018#Given that Mr. Scott has received a Starfleet Citation on five occasions for efficiency, I do not see the logic in your suggestion, Doctor.",
	"#VEN6\\VEN6_019#Power has now been restored, Captain.",
	"#VEN6\\VEN6_020#The impulse engines are intact, Captain. We could use the fusion reactors from the impulse engines to restore power, but the lines have been severed to the power regulator.",
	"#VEN6\\VEN6_021#These journals may prove useful in our attempt to reestablish power. A functioning computer terminal will allow us to examine them.",
	"#VEN6\\VEN6_022#We should be able to, Captain, if we can find a suitable supply of power cable. We will need to route the power through a junction box so we can set an impedance level. A direct connection to the regulator would cause an overload.",
	"#VEN6\\VEN6_023#Tragic, Captain. This is one of the greatest disasters in Starfleet history.",
	"#VEN6\\VEN6N000#Kije fidgets nervously.",
	"#VEN6\\VEN6N001#Kirk wonders if the landing party has overlooked anything.",
	"#VEN6\\VEN6N002#McCoy wonders when it will be his turn to die in the line of duty.",
	"#VEN6\\VEN6N003#Spock glances at his tricorder, making certain the superstructure of the Republic is stable.",
	"#VEN6\\VEN6N005#The closet opens revealing a library of engineering technical journals.",
	"#VEN6\\VEN6N006#The hypo is already filled with oil.",
	"#VEN6\\VEN6N007#The hypo is now filled with multipurpose oil.",
	"#VEN6\\VEN6N008#The oil canister is bolted to the hull and can't be taken.",
	"#VEN6\\VEN6N009#These are the controls to the Republic's impulse engines.",
	"#VEN6\\VEN6N010#These are the impulse engines for the Republic.",
	"#VEN6\\VEN6N011#This is a canister of high grade multipurpose oil. Very useful for lubricating machinery.",
	"#VEN6\\VEN6N012#This is a junction box used for temporary re-routing of engineering circuits.",
	"#VEN6\\VEN6N013#This is a length of heavy duty insulated power cable.",
	"#VEN6\\VEN6N015#This is a standard storage closet.",
	"#VEN6\\VEN6N016#This is the emergency power input port for the fusion mixture regulator.",
	"#VEN6\\VEN6N017#This is the fusion mixture regulator for the Republic's impulse engines.",
	"#VEN6\\VEN6N018#This port is used to connect emergency power from the impulse engines to other systems if dedicated lines are damaged.",
	"#VEN6\\VEN6N019#This was the engineering section of the U.S.S. Republic.",
	"#VEN6\\VEN6N020#You connect a length of cable between the impulse engine and the junction box.",
	"#VEN6\\VEN6N022#You connect a length of cable between the regulator circuits and the junction box.",
	"#VEN6\\VEN6N024#You take the engineering technical journals.",
	"#VEN6\\VEN6N025#This is a library of engineering technical journals.",


	"#VEN7\\VEN7_001#I haven't seen anything this bad since I was aboard the Farragut, and this vampire cloud...",
	"#VEN7\\VEN7_003#Captain, please be careful. The floor in that area is very unstable and might collapse from our added weight.",
	"#VEN7\\VEN7_005#I do not see the need for conversation, Captain. Humans have an irrational enjoyment of endless discourse.",
	"#VEN7\\VEN7_006#It appears to be a section from a coolant exhaust port. I would not recommend too close of an inspection, Captain. The floor could collapse from our added weight.",
	"#VEN7\\VEN7_007#It does get better than this, doesn't it Captain?",
	"#VEN7\\VEN7N000#A corpse is half-buried under the debris.",
	"#VEN7\\VEN7N001#A large piece of equipment has fallen through the ceiling. The area looks extremely unstable. fortunately, the entry to the transporter room is near.",
	"#VEN7\\VEN7N002#Ensign Kije.",
	"#VEN7\\VEN7N003#James T. Kirk.",
	"#VEN7\\VEN7N004#Leonard McCoy.",
	"#VEN7\\VEN7N005#Mister Spock.",
	"#VEN7\\VEN7N006#This corridor leads to the transporter room.",
	"#VEN7\\VEN7N007#This door leads to the transporter room.",
	"#VEN7\\VEN7N008#This is a length of heavy duty insulated power cable.",
	"#VEN7\\VEN7N009#You pick up a length of cable.",


	"#VEN8\\VEN8_001#Let's get back to auxiliary control and give them our... information.",
	"#VEN8\\VEN8_002#Now, let's give the Elasi something to remember us by.",
	"#VEN8\\VEN8_003#Spock, please check out the transporter.",
	"#VEN8\\VEN8_004#Spock, please check out the transporter.",
	"#VEN8\\VEN8_005#This is it. We know what we have to do.",
	"#VEN8\\VEN8_006#This room's in pretty good condition compared to the rest of the ship.",
	"#VEN8\\VEN8_007#Beam him back, Spock.",
	"#VEN8\\VEN8_008#Do it, Ensign.  We'll just have to gamble that the system doesn't jam again.",
	"#VEN8\\VEN8_009#Do it, Spock.",
	"#VEN8\\VEN8_010#Ensign Kije, I want you to beam into the torpedo bay and unjam the loading mechanism. If you don't succeed, we'll all be on permanent shoreleave in an Elasi jail.",
	"#VEN8\\VEN8_011#Spock, would it be possible to connect the fusion power pack directly into the transporter power circuits?",
	"#VEN8\\VEN8_012#What's causing the malfunction in the loading mechanism?",
	"#VEN8\\VEN8_013#Captain, there are no coordinates set for the transporter.",
	"#VEN8\\VEN8_014#Captain, there is no power allocated to the transporter.",
	"#VEN8\\VEN8_015#Captain, there is no power allocated to the transporter.",
	"#VEN8\\VEN8_016#Don't look at me, Jim. You know how much I hate that thing.",
	"#VEN8\\VEN8_018#Oh, great, my favorite place in the ship. Wouldn't you know it would be in the best shape.",
	"#VEN8\\VEN8_020#Shall we give the Elasi our transmission, Jim?",
	"#VEN8\\VEN8_021#We don't have much time!",
	"#VEN8\\VEN8_023#No, you did \"well\", ensign.",
	"#VEN8\\VEN8_024#I recommend I stay behind, Captain. If there is a problem with the transporter, I am the most qualified to repair it.",
	"#VEN8\\VEN8_025#Surprisingly, the transporter controls have escaped damage.",
	"#VEN8\\VEN8_026#The impulse engines are not generating any power for this system.",
	"#VEN8\\VEN8_027#The impulse engines are not generating any power for this system.",
	"#VEN8\\VEN8_028#The transporter pads seem intact, Captain.",
	"#VEN8\\VEN8_029#This is the only access to the torpedo bay, Captain.",
	"#VEN8\\VEN8_030#This unit is fully functional. But I do not see the logic in using it at this time, Captain. The Enterprise is out of range for transport.",
	"#VEN8\\VEN8_031#Transporter systems are operational, Captain. Coordinates have been set to the Photon Torpedo Loading bay.",
	"#VEN8\\VEN8_032#A very efficient job, Captain.",
	"#VEN8\\VEN8_033#Fascinating. It can be done. However, the transporter will only be able to transport a single person.",
	"#VEN8\\VEN8_034#I did good, didn't I sir?",
	"#VEN8\\VEN8_035#I'll do my best, Sir.",
	"#VEN8\\VEN8_036#I'm a security officer, not a grammarian.",
	"#VEN8\\VEN8_037#I've reached the torpedo loading bay, Captain. It's not too badly damaged, fortunately.", // TYPO
	"#VEN8\\VEN8_038#The door's open, Captain. I'm ready to transport back.",
	"#VEN8\\VEN8_039#The inner loading door is stuck in the closed position. I can force it open, but when the loading cycle is begun, the room will lose pressure.  We won't be able to beam back here again.",
	"#VEN8\\VEN8_040#I have a bad feeling about this place.",
	"#VEN8\\VEN8_041#Ready for your orders, sir.",
	"#VEN8\\VEN8_042#There is no need to go back to the torpedo bay, Captain. I can assure you that it is unjammed.",
	"#VEN8\\VEN8N000#Kije is eager to perform his duties.",
	"#VEN8\\VEN8N001#Kirk is extremely worried.",
	"#VEN8\\VEN8N003#The former transporter chief of the U.S.S. Republic.",
	"#VEN8\\VEN8N004#The Fusion power pack is rigged into the transporter power circuits.",
	"#VEN8\\VEN8N005#The transporter room appears to have escaped serious damage.",
	"#VEN8\\VEN8N006#These are the power conduits for the transporter system.",
	"#VEN8\\VEN8N007#These controls set the coordinates for the transporter.",
	"#VEN8\\VEN8N008#These sliders activate the transporter systems.",
	"#VEN8\\VEN8N009#This door leads back to the corridor and turbolift 2.",
	"#VEN8\\VEN8N010#This is the transporter chamber. The pads do not seem to be damaged.",


	"#VENA\\VENA_F32#The landing party has been taken captive by the Elasi, and you know Starfleet does not negotiate with terrorists. As you look forward to a long captivity you wonder who will take command of the Enterprise. Better luck next time.",
	"#VENA\\VENA_F34#Captain, it would be unwise to use your phaser considering the already extensive damage sustained by the Republic.",
	"#VENA\\VENA_F40#The Elasi fire photon torpedoes. The Republic has been destroyed.",
	"#VENA\\VENA_F41#Kirk out.",


	"#sfx\\spokcoff#cough... cough...",
	"#SFX\\STATICU1#Ent... neu ... trans...",
};

} // End of namespace StarTrek
