/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

#ifndef STARTREK_TEXT_H
#define STARTREK_TEXT_H

namespace StarTrek {

// Text that's loaded from "GROUND.TXT". First 0x40 pieces of text are for items.
enum GroundTextIDs {
	// Generic "perform undefined action" text (ie. look at nothing, talk to wall)
	GROUNDTX_LOOK_KIRK = 0x49,
	GROUNDTX_LOOK_SPOCK = 0x4a,
	GROUNDTX_LOOK_MCCOY = 0x4b,
	GROUNDTX_LOOK_REDSHIRT = 0x4c,
	GROUNDTX_LOOK_ANYWHERE = 0x4d,
	GROUNDTX_TALK_TO_CREWMAN = 0x4e,
	GROUNDTX_NO_RESPONSE = 0x4f,

	GROUNDTX_KIRK_USE = 0x50,
	GROUNDTX_SPOCK_USE = 0x51,
	GROUNDTX_MCCOY_USE = 0x52,
	GROUNDTX_REDSHIRT_USE = 0x53,
	GROUNDTX_SPOCK_SCAN = 0x54,
	GROUNDTX_MCCOY_SCAN = 0x55,
	GROUNDTX_USE_MEDKIT = 0x56,

	GROUNDTX_PHASER_ON_MCCOY = 0x57, // 8 variations
	GROUNDTX_PHASER_ON_SPOCK = 0x5f, // 8 variations
	GROUNDTX_PHASER_ON_REDSHIRT = 0x67, // 8 variations
	GROUNDTX_PHASER_ANYWHERE = 0x6f, // 7 variations

	GROUNDTX_USE_COMMUNICATOR = 0x76,
	GROUNDTX_NOTHING_HAPPENS = 0x77,
	GROUNDTX_FAIL_TO_OBTAIN_ANYTHING = 0x78
};

// Text that's hardcoded into "RDF" files, and copied into here for a sane referencing
// scheme.
enum GameStringIDs {
	TX_NULL,
	TX_BLANK,
	TX_DIALOG_ERROR,

	TX_SPEAKER_KIRK,
	TX_SPEAKER_SPOCK,
	TX_SPEAKER_MCCOY,
	TX_SPEAKER_UHURA,
	TX_SPEAKER_SCOTT,

	TX_SPEAKER_EVERTS,
	TX_SPEAKER_ANGIVEN,
	TX_SPEAKER_SIGN,
	TX_SPEAKER_KLINGON,
	TX_SPEAKER_KANDREY,
	TX_SPEAKER_STEPHEN,
	TX_SPEAKER_CHUB,
	TX_SPEAKER_ROBERTS,
	TX_SPEAKER_GRISNASH,
	TX_SPEAKER_NAUIAN,

	TX_SPEAKER_CHRISTENSEN,
	TX_SPEAKER_SIMPSON,

	TX_DEM0_001,
	TX_DEM0_002,
	TX_DEM0_003,
	TX_DEM0_004,
	TX_DEM0_005,
	TX_DEM0_006,
	TX_DEM0_007,
	TX_DEM0_008,
	TX_DEM0_009,
	TX_DEM0_010,
	TX_DEM0_011,
	TX_DEM0_012,
	TX_DEM0_013,
	TX_DEM0_014,
	TX_DEM0_015,
	TX_DEM0_016,
	TX_DEM0_017,
	TX_DEM0_018,
	TX_DEM0_019,
	TX_DEM0_020,
	TX_DEM0_021,
	TX_DEM0_022,
	TX_DEM0_023,
	TX_DEM0_024,
	TX_DEM0_025,
	TX_DEM0_026,
	TX_DEM0_027,
	TX_DEM0_028,
	TX_DEM0_029,
	TX_DEM0_030,
	TX_DEM0_031,
	TX_DEM0_032,
	TX_DEM0_033,
	TX_DEM0_034,
	TX_DEM0_035,
	TX_DEM0_036,
	TX_DEM0_037,
	TX_DEM0_038,
	TX_DEM0_039,
	TX_DEM0_040,
	TX_DEM0_041,
	TX_DEM0_042,
	TX_DEM0_043,
	TX_DEM0_044,
	TX_DEM0N000,
	TX_DEM0N001,
	TX_DEM0N002,
	TX_DEM0N003,
	TX_DEM0N004,
	TX_DEM0N005,
	TX_DEM0N006,
	TX_DEM0N007,
	TX_DEM0N008,
	TX_DEM0N009,
	TX_DEM0N010,
	TX_DEM0C001, // "C" = "Custom" (no ID originally assigned)


	TX_DEM1_001,
	TX_DEM1_002,
	TX_DEM1_003,
	TX_DEM1_004,
	TX_DEM1_005,
	TX_DEM1_006,
	TX_DEM1_007,
	TX_DEM1_008,
	TX_DEM1_009,
	TX_DEM1_011,
	TX_DEM1_012,
	TX_DEM1_013,
	TX_DEM1_014,
	TX_DEM1_015,
	TX_DEM1_016,
	TX_DEM1_017,
	TX_DEM1_018,
	TX_DEM1_019,
	TX_DEM1_020,
	TX_DEM1_021,
	TX_DEM1_022,
	TX_DEM1_023,
	TX_DEM1_024,
	TX_DEM1_025,
	TX_DEM1_026,
	TX_DEM1_F23,
	TX_DEM1N000,
	TX_DEM1N001,
	TX_DEM1N002,
	TX_DEM1N003,
	TX_DEM1N004,
	TX_DEM1N005,
	TX_DEM1N006,
	TX_DEM1N007,
	TX_DEM1N008,
	TX_DEM1N009,
	TX_DEM1N010,
	TX_DEM1N011,
	TX_DEM1N012,
	TX_DEM1N013,
	TX_DEM1N014,
	TX_DEM1N015,
	TX_DEM1N016,
	TX_DEM1N017,
	TX_DEM1N018,
	TX_DEM1N019,
	TX_DEM1N020,
	TX_DEM1N021,
	TX_DEM1N023,
	TX_DEM1U077,
	TX_DEM1U078,


	TX_DEM2_001,
	TX_DEM2_002,
	TX_DEM2_003,
	TX_DEM2_004,
	TX_DEM2_005,
	TX_DEM2_006,
	TX_DEM2_007,
	TX_DEM2_008,
	TX_DEM2_009,
	TX_DEM2_010,
	TX_DEM2_011,
	TX_DEM2_012,
	TX_DEM2_013,
	TX_DEM2_014,
	TX_DEM2_015,
	TX_DEM2_016,
	TX_DEM2_017,
	TX_DEM2_018,
	TX_DEM2_019,
	TX_DEM2_020,
	TX_DEM2N000,
	TX_DEM2N002,
	TX_DEM2N003,
	TX_DEM2N004,
	TX_DEM2N005,
	TX_DEM2N006,
	TX_DEM2N007,
	TX_DEM2N008,
	TX_DEM2N009,
	TX_DEM2N010,
	TX_DEM2N011,
	TX_DEM2N012,
	TX_DEM2N013,


	TX_DEM3_001,
	TX_DEM3_002,
	TX_DEM3_003,
	TX_DEM3_004,
	TX_DEM3_005,
	TX_DEM3_006,
	TX_DEM3_007,
	TX_DEM3_008,
	TX_DEM3_009,
	TX_DEM3_010,
	TX_DEM3_011,
	TX_DEM3_012,
	TX_DEM3_013,
	TX_DEM3_014,
	TX_DEM3_015,
	TX_DEM3_016,
	TX_DEM3_017,
	TX_DEM3_018,
	TX_DEM3_019,
	TX_DEM3_020,
	TX_DEM3_021,
	TX_DEM3_022,
	TX_DEM3_023,
	TX_DEM3_024,
	TX_DEM3_025,
	TX_DEM3_026,
	TX_DEM3_027,
	TX_DEM3_028,
	TX_DEM3_029,
	TX_DEM3_030,
	TX_DEM3_031,
	TX_DEM3_033,
	TX_DEM3_034,
	TX_DEM3_035,
	TX_DEM3_036,
	TX_DEM3_A32,
	TX_DEM3_B32,
	TX_DEM3_F21,
	TX_DEM3N000,
	TX_DEM3N001,
	TX_DEM3N002,
	TX_DEM3N003,
	TX_DEM3N004,
	TX_DEM3N005,
	TX_DEM3N006,
	TX_DEM3N007,
	TX_DEM3N008,
	TX_DEM3N009,
	TX_DEM3N010,
	TX_DEM3N011,
	TX_DEM3N012,
	TX_DEM3N013,
	TX_DEM3N014,
	TX_DEM3N015,
	TX_DEM3N016,
	TX_DEM3N017,
	TX_DEM3N018,
	TX_DEM3N019,
	TX_DEM3N020,


	TX_DEM4_001,
	TX_DEM4_002,
	TX_DEM4_003,
	TX_DEM4_004,
	TX_DEM4_005,
	TX_DEM4_006,
	TX_DEM4_007,
	TX_DEM4_008,
	TX_DEM4_009,
	TX_DEM4_010,
	TX_DEM4_011,
	TX_DEM4_012,
	TX_DEM4_013,
	TX_DEM4_014,
	TX_DEM4_015,
	TX_DEM4_017,
	TX_DEM4_018,
	TX_DEM4_019,
	TX_DEM4_020,
	TX_DEM4_021,
	TX_DEM4_022,
	TX_DEM4_023,
	TX_DEM4_024,
	TX_DEM4_025,
	TX_DEM4_026,
	TX_DEM4_027,
	TX_DEM4_029,
	TX_DEM4_030,
	TX_DEM4_031,
	TX_DEM4_032,
	TX_DEM4_033,
	TX_DEM4_034,
	TX_DEM4_035,
	TX_DEM4_036,
	TX_DEM4_037,
	TX_DEM4_038,
	TX_DEM4_039,
	TX_DEM4_040,
	TX_DEM4_041,
	TX_DEM4_042,
	TX_DEM4_043,
	TX_DEM4_044,
	TX_DEM4_045,
	TX_DEM4_046,
	TX_DEM4_047,
	TX_DEM4N000,
	TX_DEM4N001,
	TX_DEM4N002,
	TX_DEM4N003,
	TX_DEM4N004,
	TX_DEM4N005,
	TX_DEM4N006,
	TX_DEM4N007,
	TX_DEM4N008,
	TX_DEM4N009,
	TX_DEM4N010,
	TX_DEM4N011,
	TX_DEM4N012,
	TX_DEM4N013,
	TX_DEM4N014,


	TX_DEM5_001,
	TX_DEM5_002,
	TX_DEM5_003,
	TX_DEM5_004,
	TX_DEM5_005,
	TX_DEM5_006,
	TX_DEM5_007,
	TX_DEM5_008,
	TX_DEM5_009,
	TX_DEM5_010,
	TX_DEM5_011,
	TX_DEM5_012,
	TX_DEM5_013,
	TX_DEM5_014,
	TX_DEM5_015,
	TX_DEM5_016,
	TX_DEM5_017,
	TX_DEM5_018,
	TX_DEM5_019,
	TX_DEM5_020,
	TX_DEM5_021,
	TX_DEM5_022,
	TX_DEM5_023,
	TX_DEM5_024,
	TX_DEM5_025,
	TX_DEM5_026,
	TX_DEM5_027,
	TX_DEM5_028,
	TX_DEM5_029,
	TX_DEM5_030,
	TX_DEM5_031,
	TX_DEM5_032,
	TX_DEM5_033,
	TX_DEM5_034,
	TX_DEM5_035,
	TX_DEM5_036,
	TX_DEM5_037,
	TX_DEM5_038,
	TX_DEM5_039,
	TX_DEM5_040,
	TX_DEM5_041,
	TX_DEM5_042,
	TX_DEM5_043,
	TX_DEM5_044,
	TX_DEM5_045,
	TX_DEM5L027,
	TX_DEM5L028,
	TX_DEM5L029,
	TX_DEM5L030,
	TX_DEM5L031,
	TX_DEM5N000,
	TX_DEM5N001,
	TX_DEM5N002,
	TX_DEM5N003,
	TX_DEM5N004,
	TX_DEM5N005,
	TX_DEM5N006,
	TX_DEM5N007,
	TX_DEM5N008,
	TX_DEM5N009,
	TX_DEM5N010,
	TX_DEM5N011,
	TX_DEM5N012,
	TX_DEM5N013,


	TX_DEM6_001,
	TX_DEM6_002,
	TX_DEM6_003,
	TX_DEM6_004,
	TX_DEM6_005,
	TX_DEM6_006,
	TX_DEM6_007,
	TX_DEM6_008,
	TX_DEM6_009,
	TX_DEM6_010,
	TX_DEM6_011,
	TX_DEM6_012,
	TX_DEM6_013,
	TX_DEM6_014,
	TX_DEM6_015,
	TX_DEM6_016,
	TX_DEM6_017,
	TX_DEM6_018,
	TX_DEM6_019,
	TX_DEM6_020,
	TX_DEM6_021,
	TX_DEM6_022,
	TX_DEM6_023,
	TX_DEM6_024,
	TX_DEM6_025,
	TX_DEM6_026,
	TX_DEM6_027,
	TX_DEM6_028,
	TX_DEM6_029,
	TX_DEM6_030,
	TX_DEM6_031,
	TX_DEM6_032,
	TX_DEM6_033,
	TX_DEM6_034,
	TX_DEM6_035,
	TX_DEM6_036,
	TX_DEM6_037,
	TX_DEM6_038,
	TX_DEM6_039,
	TX_DEM6_040,
	TX_DEM6_041,
	TX_DEM6_042,
	TX_DEM6_043,
	TX_DEM6_044,
	TX_DEM6_045,
	TX_DEM6_046,
	TX_DEM6_047,
	TX_DEM6_048,
	TX_DEM6_049,
	TX_DEM6_050,
	TX_DEM6_051,
	TX_DEM6_052,
	TX_DEM6_053,
	TX_DEM6N000,
	TX_DEM6N001,
	TX_DEM6N002,
	TX_DEM6N003,
	TX_DEM6N004,
	TX_DEM6N005,
	TX_DEM6N006,
	TX_DEM6N007,
	TX_DEM6N008,
	TX_DEM6N009,
	TX_DEM6N010,
	TX_DEM6N011,
	TX_DEM6N012,
	TX_DEM6N013,
	TX_DEM6N014,
	TX_DEM6N015,
	TX_DEM6N016,
	TX_DEM6N017,
	TX_DEM6N018,
	TX_DEM6N019,
	TX_DEM6N020,
	TX_DEM6N021,
	TX_DEM6N022,
	TX_DEM6N023,
	TX_DEM6N024,


	TX_TUG0_001,
	TX_TUG0_002,
	TX_TUG0_003,
	TX_TUG0_004,
	TX_TUG0_005,
	TX_TUG0_006,
	TX_TUG0_007,
	TX_TUG0_008,
	TX_TUG0_009,
	TX_TUG0_010,
	TX_TUG0_011,
	TX_TUG0_012,
	TX_TUG0_013,
	TX_TUG0_014,
	TX_TUG0_015,
	TX_TUG0_016,
	TX_TUG0_017,
	TX_TUG0_018,
	TX_TUG0_019,
	TX_TUG0_020,
	TX_TUG0_021,
	TX_TUG0_022,
	TX_TUG0_023,
	TX_TUG0_024,
	TX_TUG0_025,
	TX_TUG0_026,
	TX_TUG0_027,
	TX_TUG0_028,
	TX_TUG0_029,
	TX_TUG0_030,
	TX_TUG0_031,
	TX_TUG0_032,
	TX_TUG0_033,
	TX_TUG0_034,
	TX_TUG0_035,
	TX_TUG0_036,
	TX_TUG0_037,
	TX_TUG0_038,
	TX_TUG0_039,
	TX_TUG0_040,
	TX_TUG0_041,
	TX_TUG0_042,
	TX_TUG0_043,
	TX_TUG0_F30,
	TX_TUG0_F31,
	TX_TUG0_S06,
	TX_TUG0_S11,
	TX_TUG0L006,
	TX_TUG0L008,
	TX_TUG0L009,
	TX_TUG0L010,
	TX_TUG0N000,
	TX_TUG0N001,
	TX_TUG0N002,
	TX_TUG0N003,
	TX_TUG0N004,
	TX_TUG0N005,
	TX_TUG0N006,
	TX_TUG0N007,
	TX_TUG0N008,
	TX_TUG0N009,
	TX_TUG0N010,
	TX_TUG0N011,
	TX_TUG0N012,
	TX_TUG0N013,
	TX_TUG0N014,


	TX_SIN3_012,
	TX_TUG1_001,
	TX_TUG1_002,
	TX_TUG1_003,
	TX_TUG1_004,
	TX_TUG1_005,
	TX_TUG1_006,
	TX_TUG1_007,
	TX_TUG1_008,
	TX_TUG1_009,
	TX_TUG1_010,
	TX_TUG1_011,
	TX_TUG1_012,
	TX_TUG1_013,
	TX_TUG1_014,
	TX_TUG1_015,
	TX_TUG1_016,
	TX_TUG1_017,
	TX_TUG1_018,
	TX_TUG1L000,
	TX_TUG1L005,
	TX_TUG1N000,
	TX_TUG1N001,
	TX_TUG1N002,
	TX_TUG1N003,
	TX_TUG1N004,
	TX_TUG1N005,
	TX_TUG1N006,
	TX_TUG1N007,
	TX_TUG1N008,
	TX_TUG1N009,
	TX_TUG1N010,
	TX_TUG1N011,
	TX_TUG1N013,


	TX_END
};

const char * const g_gameStrings[] = {
	nullptr,
	"",
	"There is a dialog error here.",

	"Capt. Kirk",
	"Mr. Spock",
	"Dr. McCoy",
	"Lt. Uhura",
	"Mr. Scott",

	"Ensign Everts",
	"Prel. Angiven",
	"Sign",
	"Klingon",
	"Brother Kandrey",
	"Brother Stephen",
	"Brother Chub",
	"Brother Roberts",
	"Brother Grisnash",
	"Nauian",

	"Lt. Christensen",
	"Crewman Simpson",

	"#DEM0\\DEM0_001#Doctor, you need to investigate the possibility of disease, mental or physical, among these people, before we go chasing up the mountains. Prelate Angiven, may we see those who have encountered the demons?",
	"#DEM0\\DEM0_002#Aside from seeing demons, has any hard data been collected? Any evidence I could see?",
	"#DEM0\\DEM0_003#Been seeing ghosts and bogeymen eh? I find that a little hard to believe.",
	"#DEM0\\DEM0_004#C'mon Bones, the cold will improve your circulation.",
	"#DEM0\\DEM0_005#Demons? Gates of Hell? This is the 23rd Century!",
	"#DEM0\\DEM0_006#I'm Captain James T. Kirk of the U.S.S. Enterprise. We have received word that alien lifeforms are creating problems at your mining facilities at Idyll Mountain. Tell me more.",
	"#DEM0\\DEM0_007#Later Ensign. We have work to do.",
	"#DEM0\\DEM0_008#Most High Prelate Angiven, I am honored to meet you. I consider it my divine duty to assist you in any possible way with the spawn of the devil.",
	"#DEM0\\DEM0_009#This planet's as beautiful as everyone says it is.",
	"#DEM0\\DEM0_010#What can you tell me about the mine itself?",
	"#DEM0\\DEM0_011#You look rather cold, Bones.",
	"#DEM0\\DEM0_012#You're wasting the time of a starship capable of destroying this planet with campfire stories? No wonder you were dumped out here in the middle of nowhere.",
	"#DEM0\\DEM0_013#Captain, Doctor McCoy is correct.",
	"#DEM0\\DEM0_014#Captain, demons and supernatural creatures are, almost by definition, illogical. Yet it is evident these people believe what they have seen. Barring illness or mass hysteria, I agree that a real problem seems to exist.",
	"#DEM0\\DEM0_015#Burning down their house is not the best way to gain their confidence Jim!",
	"#DEM0\\DEM0_016#Captain, the flora on this planet is very interesting. I wonder how useful it may be for medicinal purposes.",
	"#DEM0\\DEM0_017#Quite the vandal aren't we, Jim?",
	"#DEM0\\DEM0_018#His blood pressure's up a bit, but he believes he's telling the truth.",
	"#DEM0\\DEM0_019#I don't know if the problem is real, the result of a new illness, or mass hysteria. But at the very least, there's an injured miner who needs my help.",
	"#DEM0\\DEM0_020#Jim! Are you out of your mind?",
	"#DEM0\\DEM0_021#Jim, I am not picking up any unusual life here, just native lifeforms and the settlers. The colonists are all human, except for the one Tellarite. If there are demons here, they don't register on my tricorder.",
	"#DEM0\\DEM0_022#The man's in perfect health.",
	"#DEM0\\DEM0_023#I'm not cold, I'm freezing! And that damn transporter just had to set me down in the middle of a snow drift!",
	"#DEM0\\DEM0_024#Some people get too much circulation!",
	"#DEM0\\DEM0_025#Well...",
	"#DEM0\\DEM0_026#You mean you've never built a snowman, ensign?",
	"#DEM0\\DEM0_027#The trees. The fresh air. The freezing cold...",
	"#DEM0\\DEM0_028#Captain, reading the rocks in this area, I find that this locality may have been disturbed in the distant past. Recent disturbances created by the colonists' construction and mining prevent me from discovering anything further.",
	"#DEM0\\DEM0_029#A centimeter of snow does not technically constitute a drift, Doctor.",
	"#DEM0\\DEM0_030#They are already gathered in the chapel, and will cooperate in any way with you. First door on my right.",
	"#DEM0\\DEM0_031#A skeptic would consider everything merely anecdotal or unproven. My people will gladly tell you their own stories, so you need not hear it secondhand through me.",
	"#DEM0\\DEM0_032#Captain Kirk. I had no idea we were blessed with one of our order in the ranks of Starfleet. We believe we have located the very Gates of Hell below Idyll Mountain.",
	"#DEM0\\DEM0_033#Starfleet recognizes our freedom to worship and believe as we see fit, Captain. I am surprised that you do not share that feeling. Rest assured that Starfleet Command will be informed of your rudeness.",
	"#DEM0\\DEM0_034#Thank you for your courtesy, Kirk. May you receive the guidance and protection of our God as you complete this divine mission.",
	"#DEM0\\DEM0_035#The area is exceptionally stable tectonically, and easy for our machinery to work in, praise God. We've mined for hafnium and a variety of useful trace elements. The deeper we dig, however, the more anomalous the variety of minerals seems to be. Our Ignaciate, Brother Stephen, has his own theories about why this might be. Either way, the anomalies inspired Brother Kandrey to conduct studies inside the mine. Yesterday, he reported discovering a strange door -- a gate to Hell, surely, for the demons caused a cave-in immediately. Kandrey was trapped, unconscious, and the demons prevent us from rescuing him. We can only hope he is still alive.",
	"#DEM0\\DEM0_036#This is so much better, gentlefolk. We are honored at your presence and hope you will find peace here in our haven.",
	"#DEM0\\DEM0_037#We need your help, Kirk. You may have no respect for our beliefs, but I hope you will look beyond that. Godspeed.",
	"#DEM0\\DEM0_038#Certainly, Captain Kirk. Not aliens, per se -- we have encountered what we believe are demons at Idyll Mountain, creatures surely emerging from the very gates of Hell. Our God would not test us thus without reason, so we believe your might and insight are our God's method to help us discover what is going on.",
	"#DEM0\\DEM0_039#Aw, Captain, please don't melt the snow. I've never seen it before.",
	"#DEM0\\DEM0_040#Is he always this trigger happy on ground missions?",
	"#DEM0\\DEM0_041#And doctors say that patients complain too much!",
	"#DEM0\\DEM0_042#I've never even thrown a snowball. Do you think anyone would mind?",
	"#DEM0\\DEM0_043#I've never seen snow like this before. This is great!",
	"#DEM0\\DEM0_044#Of course, sir.",
	"#DEM0\\DEM0N000#A beautiful, snow covered scene with a path leading off to Mount Idyll.",
	"#DEM0\\DEM0N001#A quickly constructed spartan shelter, primarily used by fledgling colonies.",
	"#DEM0\\DEM0N002#Dr. Leonard McCoy, the finest doctor in Starfleet, wishes that he were on a warmer planet.",
	"#DEM0\\DEM0N003#Ensign Everts, who has never been this close to snow before in his life, gazes with child-like fascination at the ground.",
	"#DEM0\\DEM0N004#High Prelate Angiven waits patiently for you to decide what you will do next.",
	"#DEM0\\DEM0N005#James Tiberius Kirk, Captain of the Enterprise. He's always happy to run an errand of mercy.",
	"#DEM0\\DEM0N006#On the other side of the trees is Idyll Mountain. A tall, forbidding place. You have a vague feeling of danger.",
	"#DEM0\\DEM0N007#Remnants of a recent snowfall cover the ground.",
	"#DEM0\\DEM0N008#Some colonists.",
	"#DEM0\\DEM0N009#Spock raises an eyebrow.",
	"#DEM0\\DEM0N010#Various bushes and shrubs grow along the edge of the forest.",
	"All mining equipment use this road.",


	"#DEM1\\DEM1_001#We were caught flat footed there. I don't want any more surprises to catch us off guard.",
	"#DEM1\\DEM1_002#No just an idea, Kirk out.",
	"#DEM1\\DEM1_003#We're fine. Did you register any Disruptor fire?",
	"#DEM1\\DEM1_004#What is it, Spock?",
	"#DEM1\\DEM1_005#Doctis Cattails are similar to their terran name sake except that they are known to cause hives if in contact with flesh for any amount of time.",
	"#DEM1\\DEM1_006#Gindorian ferns are regarded as an intergalactic weed, Captain.",
	"#DEM1\\DEM1_007#Khytellian tulips are a perennial flower that survive in almost any climate.",
	"#DEM1\\DEM1_008#The Brandzite pod is similar to terran milkweed except that the silk pods are in bright iridecent colors.",
	"#DEM1\\DEM1_009#He's only stunned. He'll be back up in a few seconds.",
	"#DEM1\\DEM1_011#The fire fight is over, Jim. I think you can put that away now.",
	"#DEM1\\DEM1_012#This is definitely not a real klingon Jim.",
	"#DEM1\\DEM1_013#Demons, Klingons, avalanches... What's next, the Wicked Witch of the West?",
	"#DEM1\\DEM1_014#It wasn't supposed to be logical, you green blooded Vulcan! Why does everything have to be so damned logical?",
	"#DEM1\\DEM1_015#Well, we've seen Klingons. Now all we need is a few Romulans...",
	"#DEM1\\DEM1_016#The circuit was damaged. It appears reparable, but some specialized equipment will be required.",
	"#DEM1\\DEM1_017#This is a detached hand with some kind of circuitry in the palm, Captain.",
	"#DEM1\\DEM1_018#This is not a Klingon, Captain, not a real one. It is an organic construct -- an android-like robot. It looks like a Klingon, but the appearance is entirely superficial. There is something different about this particular construct. Come here, Captain, look at the hand.It seems to have been separated from the body. There is a wiring circuit in the middle of the palm.",
	"#DEM1\\DEM1_019#This is not a Klingon, Captain, not a real one. It is an organic construct -- an android-like robot. It looks like a Klingon, but the appearance is entirely superficial.",
	"#DEM1\\DEM1_020#Fascinating. I begin to suspect that we have stumbled upon something that the colonists would never have uncovered.",
	"#DEM1\\DEM1_021#I wish to gather further data before making a definite conclusion, Captain.",
	"#DEM1\\DEM1_022#Captain, I detect a recent avalanche, approximately 6.2 kilometers away, that occurred within the last three days. The mountain may be quite dangerous.",
	"#DEM1\\DEM1_023#Control your thoughts, Doctor. There is a high probability that something here is using our own memories against us.",
	"#DEM1\\DEM1_024#That is not logical, doctor.",
	"#DEM1\\DEM1_025#I guess they don't make Klingons like they used to, Sir.",
	"#DEM1\\DEM1_026#I guess this isn't such a great planet after all.",
	"#DEM1\\DEM1_F23#Federation Scum!",
	"#DEM1\\DEM1N000#Captain Kirk is fatally shot by a Klingon, game over.",
	"#DEM1\\DEM1N001#Dr. McCoy, still hoping the cold winds that whip around Mount Idyll will soon die down.",
	"#DEM1\\DEM1N002#Ensign Everts seems to be rattled by the attack of the Klingons.",
	"#DEM1\\DEM1N003#James Kirk, filled with a premonition of more dangers yet to come.",
	"#DEM1\\DEM1N004#They look like Klingons.",
	"#DEM1\\DEM1N005#You already took the hand from the Klingon.",
	"#DEM1\\DEM1N006#You find nothing new.",
	"#DEM1\\DEM1N007#You take the Klingon's detached hand.",
	"#DEM1\\DEM1N008#Your Vulcan science officer seems to be lost in thought, but remains alert.",
	"#DEM1\\DEM1N009#A Gindorian Fern.",
	"#DEM1\\DEM1N010#A large patch of Khytellian Tulips.",
	"#DEM1\\DEM1N011#A small stream flows down towards the forest.",
	"#DEM1\\DEM1N012#Captain Kirk is unconscious.",
	"#DEM1\\DEM1N013#Dr. McCoy is unconscious.",
	"#DEM1\\DEM1N014#Ensign Everts is unconscious.",
	"#DEM1\\DEM1N015#Mr. Spock is unconscious.",
	"#DEM1\\DEM1N016#Mt. Idyll rises above you.",
	"#DEM1\\DEM1N017#The path is surrounded by some beautiful shrubbery.",
	"#DEM1\\DEM1N018#These are very beautiful Doctis Cattails.",
	"#DEM1\\DEM1N019#These Brandzite Pods add a nice touch to the local flora.",
	"#DEM1\\DEM1N020#You see a small explosion, and the Klingon's hand falls to the ground with a dull thud.",
	"#DEM1\\DEM1N021#You see the mine entrance ahead.",
	"#DEM1\\DEM1N023#It's the Klingon's detached hand!",
	"#DEM1\\DEM1U077#Captain we registered Phaser fire and an unknown energy beam. Is everyone OK?",
	"#DEM1\\DEM1U078#No, Captain. Why, are Klingons down there?",


	"#DEM2\\DEM2_001#The answer to this mystery lies ahead of us, gentlemen.",
	"#DEM2\\DEM2_002#Just don't make that mistake again, Ensign.",
	"#DEM2\\DEM2_003#The thought had occurred to me, Mr. Spock, but thank you for mentioning it.",
	"#DEM2\\DEM2_004#We've all had our share of conflict with Klingons, Ensign. The Organians told me that one day Humans and Klingons will become good friends. I wonder if I'll ever live to see that day.",
	"#DEM2\\DEM2_005#Captain, I'm having trouble getting reliable readings from inside the mountain. Unusual crystalline structures within the ore may be at fault, though I cannot say for certain.",
	"#DEM2\\DEM2_006#Gindorian ferns are regarded as an intergalactic weed, Captain.",
	"#DEM2\\DEM2_007#The Phequedine moss extracts nourishment from hafnium, Captain.",
	"#DEM2\\DEM2_008#These seem to be Laraxian berries, Captain. They have several medicinal uses, but Dr. McCoy would know more.",
	"#DEM2\\DEM2_009#Jim, these are Laraxian Berries that we used to make the Hypo-Dytoxin.",
	"#DEM2\\DEM2_010#Jim, these are the berries we need to synthesize the Hypo-Dytoxin. We must get these to Brother Stephen quickly.",
	"#DEM2\\DEM2_011#Jim, you usually pick food and then cook it.",
	"#DEM2\\DEM2_012#These are Laraxian Berries. From what I remember, certain chemical compounds in the berry can be used to treat Nugaireyn infections.",
	"#DEM2\\DEM2_013#These are the Laraxian Berries we used to cure Brother Chub.",
	"#DEM2\\DEM2_014#We don't need any more berries, Jim.",
	"#DEM2\\DEM2_015#Does your tricorder say the cave is warmer, Spock...",
	"#DEM2\\DEM2_016#Spock, everybody talks about the weather!",
	"#DEM2\\DEM2_017#It is not logical for me to use my tricorder to determine the cave's temperature, doctor. I do not see what purpose it would serve.",
	"#DEM2\\DEM2_018#Whoever was trying to stop us may not stop with those Klingons, Captain. I recommend extreme caution.",
	"#DEM2\\DEM2_019#I'm sorry I let you down with those Klingons back there. I should have been paying more attention.",
	"#DEM2\\DEM2_020#Those Klingons give me the willies. They always have. My sister was wounded by them in the Chozon ambush.",
	"#DEM2\\DEM2N000#Ensign Everts. Keeping a sharp eye out for anything dangerous.",
	"#DEM2\\DEM2N002#James T. Kirk. Always wondering what the next surprise will be.",
	"#DEM2\\DEM2N003#Leonard McCoy. Hoping that the cave will be warmer than outside.",
	"#DEM2\\DEM2N004#Spock. Perhaps the most brilliant mind in Starfleet, pondering a most peculiar mystery.",
	"#DEM2\\DEM2N005#A Gindorian fern.",
	"#DEM2\\DEM2N006#Feeble lights illuminate the mine tunnel.",
	"#DEM2\\DEM2N007#Idyll Mountain.",
	"#DEM2\\DEM2N008#Idyll Mountain.",
	"#DEM2\\DEM2N009#Mine entrance.",
	"#DEM2\\DEM2N010#Phequedian moss grows on the cave wall.",
	"#DEM2\\DEM2N011#The mine entrance goes deep into Mount Idyll.",
	"#DEM2\\DEM2N012#Various types of berries grow amongst the bushes.",
	"#DEM2\\DEM2N013#You have retrieved a sample of berries.",


	"#DEM3\\DEM3_001#Assume firing positions.",
	"#DEM3\\DEM3_002#A gateway to an alien race. The wonders of the galaxy are endless, aren't they, Mr. Spock?",
	"#DEM3\\DEM3_003#Bones..",
	"#DEM3\\DEM3_004#Don't be too anxious, Ensign. We may want to talk with them.",
	"#DEM3\\DEM3_005#Captain, I would strongly recommend clearing all the debris first.",
	"#DEM3\\DEM3_006#Captain, the structure is extremely unstable. I would not recommend disturbing the lower section before the upper sections have been cleared.",
	"#DEM3\\DEM3_007#Captain, the stun setting would be very ineffective on these boulders.",
	"#DEM3\\DEM3_008#I think Doctor McCoy would be better suited to deal with this.",
	"#DEM3\\DEM3_009#It appears to be a security lock designed to open the door when the correct hand print is registered.",
	"#DEM3\\DEM3_010#Captain, there are several weak points in the cave-in's structure. Careful use of our phasers, from the top down, should be able to clear it.",
	"#DEM3\\DEM3_011#Captain, this course of action is ineffectual.",
	"#DEM3\\DEM3_012#Fascinating, Captain. This door is made of an unknown material. It is clearly built by an alien race we have no knowledge of.",
	"#DEM3\\DEM3_013#He's already dead, Jim. Isn't that good enough for you?",
	"#DEM3\\DEM3_014#I'm sorry, Jim. Ensign Everts is beyond my help.",
	"#DEM3\\DEM3_015#I've done all I can. He just needs rest now.",
	"#DEM3\\DEM3_016#This is incredible, Jim. I'm picking up faint lifesign readings behind this door!",
	"#DEM3\\DEM3_017#Dammit, Jim, I'm a doctor, not a bellhop. This man's too hurt to be moved.",
	"#DEM3\\DEM3_018#He's dead Jim.",
	"#DEM3\\DEM3_019#He's dead, Jim...",
	"#DEM3\\DEM3_020#I'm picking up weak vital signs. If we don't dig him out soon, we're going to lose him!",
	"#DEM3\\DEM3_021#It was a near thing, but he'll live.",
	"#DEM3\\DEM3_022#The miner is dead.",
	"#DEM3\\DEM3_023#This man is badly hurt, and suffering from shock and exposure as well.",
	"#DEM3\\DEM3_024#I'll probably end up coming along.",
	"#DEM3\\DEM3_025#Jim, the next time you need medical help on a snowball...",
	"#DEM3\\DEM3_026#They can also be damned cold.",
	"#DEM3\\DEM3_027#Fascinating...  I'm registering low-intensity shielding unlike anything we've encountered before.  That kept this door -- and whatever is behind it -- hidden from the ship's sensors and earlier tricorder readings.",
	"#DEM3\\DEM3_028#I recommend as thorough an analysis of this area as possible.",
	"#DEM3\\DEM3_029#Indeed, Captain.",
	"#DEM3\\DEM3_030#Sir, I think we should clear the rest of the rocks before we check out the device.",
	"#DEM3\\DEM3_031#Sir, it may be dangerous. Let me try it.",
	"#DEM3\\DEM3_033#I think I was shocked, sir.",
	"#DEM3\\DEM3_034#Ouch, that hurt.",
	"#DEM3\\DEM3_035#That was definitely a mild shock.",
	"#DEM3\\DEM3_036#No sign of demons, Klingons, or other hostiles, Captain. I promise I'll let you know the instant something appears.",
	"#DEM3\\DEM3_A32#Aieeee!",
	"#DEM3\\DEM3_B32#Aieeeee.",
	"#DEM3\\DEM3_F21#Oh, thank you, kind souls, for saving my life. Let me rest here for a little before returning to report this miracle to Prelate Angiven.",
	"#DEM3\\DEM3N000#Brother Kandrey is barely conscious, and is lying still, trying to regain his strength.",
	"#DEM3\\DEM3N001#Commander Spock; curious about what lies ahead.",
	"#DEM3\\DEM3N002#Doctor Leonard McCoy, glad that the cave provides some shelter from the breeze.",
	"#DEM3\\DEM3N003#Ensign Everts, wary of more ambushes.",
	"#DEM3\\DEM3N004#James T. Kirk. Captain of the Enterprise.",
	"#DEM3\\DEM3N005#Nothing happens.",
	"#DEM3\\DEM3N006#One of the Acolytes, who was trapped by the the rockfall.",
	"#DEM3\\DEM3N007#The fit is perfect, but something seems to be shorting out.",
	"#DEM3\\DEM3N008#The hand's circuitry triggers a connection, and the door opens.",
	"#DEM3\\DEM3N009#There is no apparent effect.",
	"#DEM3\\DEM3N010#A cavern, deep in Mount Idyll.",
	"#DEM3\\DEM3N011#A huge boulder sits upon a large pile of rubble.",
	"#DEM3\\DEM3N012#A large metallic door is set in the structure.",
	"#DEM3\\DEM3N013#A large pile of rubble blocks what appears to be a large metallic structure.",
	"#DEM3\\DEM3N014#A long tunnel descends into the mountain.",
	"#DEM3\\DEM3N015#A pulsing red light is set in the structure above the door.",
	"#DEM3\\DEM3N016#A structure built into the surrounding rock. It must have been buried here for millennia.",
	"#DEM3\\DEM3N017#Ensign Everts lies dead, crushed by the boulder.",
	"#DEM3\\DEM3N018#The crushed body of Ensign Everts reminds you of your poor command judgement.",
	"#DEM3\\DEM3N019#This looks like some of the hand security panels on the Enterprise.",
	"#DEM3\\DEM3N020#You notice what appears to be a man's arm sticking out from beneath the rubble.",


	"#DEM4\\DEM4_001#I think we've found the answer to our mystery.",
	"#DEM4\\DEM4_002#Stop! You're trespassing on Federation territory.",
	"#DEM4\\DEM4_003#I think I should return it to where I got it from.",
	"#DEM4\\DEM4_004#I welcome you on behalf of the United Federation of Planets. Who are you? Where do you come from?",
	"#DEM4\\DEM4_005#No, I want to keep it as a memento for myself.",
	"#DEM4\\DEM4_006#Of course. I think you will get along well with the Pollux inhabitants, and I'm sure you will have interesting theological discussions.",
	"#DEM4\\DEM4_007#Perhaps you can tell us about the demons.",
	"#DEM4\\DEM4_008#Some advanced civilization!",
	"#DEM4\\DEM4_009#We did fix your machine. Can we write the repair bill off against rent on this land?",
	"#DEM4\\DEM4_010#I would be glad to accept your application to the Federation. We shall have a diplomatic envoy sent to make the final arrangements.",
	"#DEM4\\DEM4_011#Kirk to Enterprise... Beam us up, Mr. Scott.",
	"#DEM4\\DEM4_012#This seems to be a Cryogenic Suspension chamber, Captain.",
	"#DEM4\\DEM4_013#Captain, Starfleet would not be pleased.",
	"#DEM4\\DEM4_014#Fascinating, Captain. It is a diagram of a lunar eclipse of this planet. See how the red ball, the moon, is casting a shadow on the blue ball, Pollux V. This must be a very old piece of work, because this planet's moon was destroyed thousands of years ago.",
	"#DEM4\\DEM4_015#I wonder who, or what, constructed all this.",
	"#DEM4\\DEM4_017#Jim, think about that skull we picked up from Brother Stephen. Now look at this alien.  See the resemblance?",
	"#DEM4\\DEM4_018#Ouch!",
	"#DEM4\\DEM4_019#Perhaps we should try to communicate with the alien.",
	"#DEM4\\DEM4_020#This is a very old and very complex life-support system. It appears to still be operational.",
	"#DEM4\\DEM4_021#You should ask Spock, Jim.",
	"#DEM4\\DEM4_022#Fascinating. this lifeform may represent what would have happened had the dinosaurs of your earth not become extinct.",
	"#DEM4\\DEM4_023#It is an alien life-support system, Captain, utilizing geothermal energy. It is still functioning, waiting for some sort of signal.",
	"#DEM4\\DEM4_024#Logically, the machinery is sustaining some type of life in suspended animation. If we can reactivate the machines, then we may be able to meet its creators.",
	"#DEM4\\DEM4_025#The machinery is waiting for the gravitational pull of another eclipse to activate it, an eclipse that will never come. And one other thing, Captain. This may also be a diagram showing the proper settings on that control panel.",
	"#DEM4\\DEM4_026#This alien construction takes readings of mental activity. It also activates manufacturing equipment related to security, and includes a short-distance transportation device.",
	"#DEM4\\DEM4_027#This control panel is a manual override for the alien life-support equipment.",
	"#DEM4\\DEM4_029#This lifeform appears to be intelligent, a new sentient race. There appear to be resemblances between it and the silotis, although the present forms are quite small and definitely nonsentient.",
	"#DEM4\\DEM4_030#Live long and prosper.",
	"#DEM4\\DEM4_031#Have you found the key?",
	"#DEM4\\DEM4_032#Our patience is exhausted! Now feel our wrath!",
	"#DEM4\\DEM4_033#There is no need for violence, Captain. We are a peaceful people.",
	"#DEM4\\DEM4_034#You found the key! I can now turn off the machinery creating our guardians, and no more sentients shall be at risk. Surely the Holy One smiles upon us all. I have no way to thank you, Captain, but please carry this request from my people to yours. We have much ancient knowledge we can share, and we would like to join your Federation. Go in peace.",
	"#DEM4\\DEM4_035#We look forward to meeting them. We also look forward to having discourse with the colonists. Farewell.  May the Holy One bless you.",
	"#DEM4\\DEM4_036#A child?  No, I see many differences. This must be what our people who did not slumber have become. Still, I would like to see these remains properly interred, according to the precepts of our religion. May I keep this?",
	"#DEM4\\DEM4_037#I see you have already shut off the machinery that creates the guardians. I have no way to thank you, Captain, but please carry this request from my people to yours. We have much ancient knowledge we can share, and we would like to join your Federation. Go in peace.",
	"#DEM4\\DEM4_038#Oh woe! Alas!  The key is missing, I can do nothing!  Even we will suffer the attacks of our own guardians unless the key can be found!  I implore you, if you can help, please do so.",
	"#DEM4\\DEM4_039#So the Ferengi are not the only traders in the universe! Yes, Captain Kirk, excusing the settlers' debts is an excellent way of ensuring that our people will be friends.",
	"#DEM4\\DEM4_040#The demons, as you call them, are created by a machine designed to keep intruders away from our sleep chambers. It pulls from the minds of any approaching creature their most feared enemy and produces replicas to scare them away. For you and your crew it was Klingons, for the Tellarite a wolf-demon, and for the other Humans a demon from their religion. On behalf of my people, thank you for waking us.  I will turn off the machinery which creates our guardians, so that they no longer bedevil those with whom we now share our home.",
	"#DEM4\\DEM4_041#There is no need for disrespect, intruder. Our race is old and powerful, wise in many things. Like our guardians, for example.",
	"#DEM4\\DEM4_042#Violence is hardly necessary, Captain Kirk. We owe you a debt for your service to us, and are more than willing to peacefully co-exist with your kind.",
	"#DEM4\\DEM4_043#We call ourselves Nauians. Thousands of years ago, we saw that meteor impacts were going to cause an Ice Age. We created this huge underground shelter to preserve our race, keeping us in suspended animation until the planet had recovered. We programmed the machinery to revive us at the next eclipse, but we did not count on the destruction of our moon.",
	"#DEM4\\DEM4_044#Welcome to our home. Thank you for repairing our Sonambutron.",
	"#DEM4\\DEM4_045#I do not think that would be a prudent action, sir.",
	"#DEM4\\DEM4_046#I'm just a security officer, sir.",
	"#DEM4\\DEM4_047#What is that?",
	"#DEM4\\DEM4N000#Dr. McCoy looks back.",
	"#DEM4\\DEM4N001#Ensign Everts is looking around.",
	"#DEM4\\DEM4N002#It appears to be an abstract piece of alien art.",
	"#DEM4\\DEM4N003#James T. Kirk, Captain of the Enterprise.",
	"#DEM4\\DEM4N004#Many alien machines fill the room.",
	"#DEM4\\DEM4N005#Spock is analyzing the alien machines.",
	"#DEM4\\DEM4N006#The alien emerged from this metal chamber.",
	"#DEM4\\DEM4N007#The alien is humanoid, with green reptilian skin. It appears unarmed.",
	"#DEM4\\DEM4N008#This appears to control some unusual security equipment.",
	"#DEM4\\DEM4N009#This floor contains conduits for conducting geothermal energy.",
	"#DEM4\\DEM4N010#This is where the panel should pop up.",
	"#DEM4\\DEM4N011#You meet your death at the hands of a race that could have been your ally. What a waste. Better luck next time.",
	"#DEM4\\DEM4N012#It looks like a control panel with slide switches.",
	"#DEM4\\DEM4N013#Nothing Happens.",
	"#DEM4\\DEM4N014#You fit the key into the slot, but you cannot find a way to turn it.",


	"#DEM5\\DEM5_001#Just thinking to myself. Don't mind me.",
	"#DEM5\\DEM5_002#Can you tell us what they looked like?",
	"#DEM5\\DEM5_003#It will be good to help them for a change.",
	"#DEM5\\DEM5_004#Not the good ones, that's for sure.",
	"#DEM5\\DEM5_005#The demons didn't follow you?",
	"#DEM5\\DEM5_006#I detect various pieces of mining equipment but nothing of note.",
	"#DEM5\\DEM5_007#May I suggest using a more diplomatic approach to questioning the colonists. Force will gain us little, if anything.",
	"#DEM5\\DEM5_008#Jim, that wouldn't be wise.",
	"#DEM5\\DEM5_009#Jim, these need to be processed first!",
	"#DEM5\\DEM5_010#This man is getting worse. We've got to find those berries before he dies.",
	"#DEM5\\DEM5_011#Jim, I've completed my study. I find no evidence for physical or mental disturbances among the colonists, causing them to see hallucinations. There must be other reasons for what these people are seeing.",
	"#DEM5\\DEM5_012#Jim, this man has suffered severe physical injuries to his head and arm. The wounds have been adequately cared for; however, he has developed the Nugaireyn infection. If not treated swiftly, the effects can be fatal. The infection can normally be treated with Hypo-Dytoxin, but there's none on the Enterprise.",
	"#DEM5\\DEM5_013#The alien's lifesigns seem stress-elevated. Otherwise he appears fundamentally healthy.",
	"#DEM5\\DEM5_014#The man is suffering moderately from the effects of his age, but seems healthy, alert, and in fine spirits.",
	"#DEM5\\DEM5_015#The man seems worried and stressed, but all body functions appear within normal limits.",
	"#DEM5\\DEM5_016#This man has recently suffered a nasty but non-life-threatening wound. The damage has been adequately cared for. The man's vital effects are attributable to shock and stress.",
	"#DEM5\\DEM5_017#This man needs help, Jim, and I wouldn't want to put it off for too long.",
	"#DEM5\\DEM5_018#By our standards yes. Here the Acolytes prefer a simpler life style; unfortunately, this is one of the consequences.",
	"#DEM5\\DEM5_019#Neither were some of my professors.",
	"#DEM5\\DEM5_020#So did I, but I became one anyway.",
	"#DEM5\\DEM5_021#The Acolytes did a lot of good work for the needy in this quadrant.",
	"#DEM5\\DEM5_022#Why, Spock, you two should get along fine, he sounds just like you.",
	"#DEM5\\DEM5_023#You know Jim, they can take a captain out of a starship, and a science officer out of his lab, but you can never retire a doctor.",
	"#DEM5\\DEM5_024#Captain, a Krognik-demon has a decidedly wolfish appearance. Brother Grisnash, is this not the traditional shape of the Evil One and his minions among Tellarites?",
	"#DEM5\\DEM5_025#I believe this may be significant, Captain.",
	"#DEM5\\DEM5_026#That is not logical, doctor.",
	"#DEM5\\DEM5_027#The medical methods of these people seem primitive to me, doctor.",
	"#DEM5\\DEM5_028#I am Brother Grisnash. I went up the mountainside in solitary prayer, seeking to face my fears. Indeed I found them.  A bellowing Krognik-demon with sharp teeth and a long snout descended upon me in a rush of wind.",
	"#DEM5\\DEM5_029#It is.",
	"#DEM5\\DEM5_030#Brother Kandrey was -- is -- my partner. I was on the communications link when the demons caused the rockfall and silenced him.  He said he'd found a strange door with devilish writing.  Truly he came upon the Gate of Hell itself.",
	"#DEM5\\DEM5_031#You tread close to unholy knowledge, Brother Stephen!",
	"#DEM5\\DEM5_032#Ahh, I see you found the berries. Meet me in my lab.",
	"#DEM5\\DEM5_033#Good, you have found the berries. Bring them to my lab quickly.",
	"#DEM5\\DEM5_034#I am worried about Brother Chub. Can you examine him, Doctor?",
	"#DEM5\\DEM5_035#Please hurry Doctor. Brother Chub is looking worse.",
	"#DEM5\\DEM5_036#That's very nice, but I'm busy now.",
	"#DEM5\\DEM5_037#Those are Laraxian berries. They grow wild by the mine entrance.",
	"#DEM5\\DEM5_038#Time is of the essence, you must hurry and retrieve the berry.",
	"#DEM5\\DEM5_039#What an interesting artifact. Hmmm... It appears to have been damaged. When you have a chance, take it to my lab and we'll see if it can be repaired.",
	"#DEM5\\DEM5_040#I may be of some assistance. The Laraxian Berry grows near the mouth of the cave. If I could acquire it, I would be able to synthesize the Hypo-Dytoxin from the berry. Unfortunately, the demons prevent us from approaching the cave entrance. perhaps you could retrieve it for me.",
	"#DEM5\\DEM5_041#I am Brother Stephen, an Ignaciate, following the holy teachings with mind and soul alike. I believe the anomalous mineral readings, in combination with evidence of ancient disturbances in this otherwise highly stable geologic location indicates previous habitation of the region, eons ago.",
	"#DEM5\\DEM5_042#I appreciate your prayers, Brother Roberts. Captain, if you and your people go up the mountain, I hope afterward you will visit me in my study, which is next door. I am too old to make the trek myself, but I am eager for knowledge. In return, I will offer you what insights our God grants these old eyes.",
	"#DEM5\\DEM5_043#I would be equally honored to discuss medicine with you, Doctor, as science with your Vulcan associate.  Let me continue. I believe our God made humans, aliens -- and demons all.  If I could get a real demon into my study, I would bless our God for the opportunity, as I thank Him for everything in this life.",
	"#DEM5\\DEM5_044#My mom wanted me to become a doctor. Honest. But I hated my biology classes.",
	"#DEM5\\DEM5_045#My uncle John lived with the Acolytes a long time ago. He died in their service, helping plague victims on New Ontario VI twenty years ago.",
	"#DEM5\\DEM5L027#Thank you. You are most kind.",
	"#DEM5\\DEM5L028#You'll understand if I don't stand up, I hope. I am not well.",
	"#DEM5\\DEM5L029#I headed up the party that sought to rescue Brother Kandrey. Without warning, the demons appeared and attacked us as we approached the mine!",
	"#DEM5\\DEM5L030#Like the demons that have plagued devout folk since before our people left the Earth. Huge muscular demons, with ruddy skin. Truly the manifestation of Evil, with batwings, horns and talons, and a pointed tail. God preserve us all. One tore open my arm and I surely would have perished -- but for my companions who bore me back down the mountain.",
	"#DEM5\\DEM5L031#No.",
	"#DEM5\\DEM5N000#A chapel typical of the Acolytes of the Stars.",
	"#DEM5\\DEM5N001#A grim-faced miner-colonist nods curtly at you.",
	"#DEM5\\DEM5N002#A majestic view of Mt. Idyll can be seen through the skylight.",
	"#DEM5\\DEM5N003#A sturdy man of advanced years, whose blue eyes meet yours with clarity, curiosity, and directness.",
	"#DEM5\\DEM5N004#Boxes of supplies and mining equipment litter the floor.",
	"#DEM5\\DEM5N005#Ensign Everts cannot take his eyes off the sight of Mount Idyll.",
	"#DEM5\\DEM5N006#James Kirk takes time to rest and ponder the remainder of the mission.",
	"#DEM5\\DEM5N007#McCoy looks anxiously about the room.",
	"#DEM5\\DEM5N008#Spock waits for your command, patient as ever.",
	"#DEM5\\DEM5N009#The Tellarite appears completely at home surrounded by humans, but the wrinkling on his brow indicates a great deal of worry.",
	"#DEM5\\DEM5N010#He is too busy consoling the wounded man.",
	"#DEM5\\DEM5N011#He is too busy consoling the wounded man.",
	"#DEM5\\DEM5N012#They are too heavy to move.",
	"#DEM5\\DEM5N013#This man is in no condition to talk.",


	"#DEM6\\DEM6_001#Looks like a pile of junk if you ask me.",
	"#DEM6\\DEM6_002#Well, what happens next?",
	"#DEM6\\DEM6_003#Where did you find all this?",
	"#DEM6\\DEM6_004#Mr. Spock, See what you can dig up from that old fashioned computer terminal.",
	"#DEM6\\DEM6_005#Mr. Spock, see what you can do about that hand.",
	"#DEM6\\DEM6_006#Yes, tell us about these things.",
	"#DEM6\\DEM6_007#A vintage 801286 of the mid-21st century. It is a fine museum piece.",
	"#DEM6\\DEM6_008#Fascinating, Captain. It is an Ardak-4 molecular synthesizer. A museum piece in perfect working order.",
	"#DEM6\\DEM6_009#Residue of several different compounds are in the tubes. None of the compounds would explain the sightings.",
	"#DEM6\\DEM6_010#A completely ordinary nickel-iron meteorite.",
	"#DEM6\\DEM6_011#A manufactured vanadium-tungsten alloy of considerable age and indeterminate use.",
	"#DEM6\\DEM6_012#A sample of a local lifeform called a siloti, the largest animal reported on this planet.  About the size of an Earth housecat, the silotis have an insectoid-reptilian genotype with praying mantis like forelimbs.",
	"#DEM6\\DEM6_013#A variety of rock specimens, including native silver, azurite, crystalline forms of various minerals.",
	"#DEM6\\DEM6_014#Captain, this appears to be a model of the Earth. Notice how it models the proper situation for a total eclipse?",
	"#DEM6\\DEM6_015#Do I look like a pointy eared, green blooded, know-it-all alien?",
	"#DEM6\\DEM6_016#He's in fine physical and mental condition, Jim.",
	"#DEM6\\DEM6_017#Jim, that would destroy the glass case!",
	"#DEM6\\DEM6_018#We've got to get this to brother Chub as quickly as possible, Jim!",
	"#DEM6\\DEM6_019#I think we should wait and talk to the owner when he comes back, Jim.",
	"#DEM6\\DEM6_020#This place looks real comfortable, a place to combine work and contemplation.  The man's got an eye for the beauty of useful things, and the use of beautiful things.  I think we could get along fine.",
	"#DEM6\\DEM6_021#Fossil shells in limestone substrate, compatible with local geologic features.",
	"#DEM6\\DEM6_022#I feel like this is delicate as surgery, Captain, but I've got it back in working order now.",
	"#DEM6\\DEM6_023#I read a collection of small items of no evident value.  I would characterize this as a small museum display, Captain.",
	"#DEM6\\DEM6_024#This machinery is delicate but I have managed to repair the circuitry.",
	"#DEM6\\DEM6_025#This study represents a man with a keen mind, Captain.  To judge by what I see, there is little which does not interest him.  The equipment is antiquated, but practical.",
	"#DEM6\\DEM6_026#Fascinating, these berries can be used to synthesize Hypo-Dytoxin.",
	"#DEM6\\DEM6_027#The settings on the Ardak-4 have already been adjusted. Simply place the berry in the machine and the Hypo-Dytoxin will be synthesized.",
	"#DEM6\\DEM6_028#There is no need to threaten me if you need to use my study.",
	"#DEM6\\DEM6_029#Bless you for returning my things.",
	"#DEM6\\DEM6_030#Everything of this world is secondary to the perfection of the next, Captain.",
	"#DEM6\\DEM6_031#Here and there.  Much of it was brought to me by others exploring widely.",
	"#DEM6\\DEM6_032#How interesting!  Praise God for this opportunity. He brings me through you.",
	"#DEM6\\DEM6_033#I believe this is evidence of the cataclysm which destroyed the moon of Pollux V eons past. I've constructed a theoretical model based on analysis of the planet's ring of what things might have been like. I think that the moon, like Earth's moon, would have made a total eclipse of the sun possible. I would have liked to have seen that, for conditions making a perfect total eclipse are rare in the Universe. Our God creates great wonders.",
	"#DEM6\\DEM6_034#I enjoy talking about these treasures.",
	"#DEM6\\DEM6_035#I never dreamed that Starfleet would be interested in my discoveries, Captain, but our God often surprises us.",
	"#DEM6\\DEM6_036#One of the oldest forms I've seen on this planet. Our God makes beautiful things, indeed.",
	"#DEM6\\DEM6_037#See how the fingertips have microsized sensors? I wonder what use they may have.",
	"#DEM6\\DEM6_038#The skull of a modern siloti, the largest creature native to this planet, about the size of a housecat from Earth.  The silotis combine a rather insectoid pattern with four-legged reptilian form including praying mantis-like forelimbs.",
	"#DEM6\\DEM6_039#This chunk of rock is a greatly weathered example of a vanadium-tungsten alloy -- which doesn't occur naturally.  It is my best evidence that the area was previously inhabited.",
	"#DEM6\\DEM6_040#True curiosities, nothing more.  I think they're very pretty, don't you?",
	"#DEM6\\DEM6_041#Very well.  I can't imagine why, but if you have a further interest in any of this, take what you like.  But please remember to return my treasures when you are done with them.",
	"#DEM6\\DEM6_042#Welcome to my study! Feel free to look around. My medical and scientific equipment is surely not so sophisticated as you are accustomed to, but if there is anything you wish to use, please feel free. Also, I would be interested in anything you might have to show me.",
	"#DEM6\\DEM6_043#What a fascinating piece of equipment!  Highly advanced technology.  You see here, it seems to have been damaged, however.  Take it to my workbench and let's see if it can be repaired.  I fear my hands are too shaky to perform such fine work, but perhaps one of you can do it.",
	"#DEM6\\DEM6_044#You are interested in my little museum of curiosities?",
	"#DEM6\\DEM6_045#Mineral Specimens,",
	"#DEM6\\DEM6_046#Meteorite,",
	"#DEM6\\DEM6_047#Fossil Shells,",
	"#DEM6\\DEM6_048#Skull of a small alien animal,",
	"#DEM6\\DEM6_049#Twist of Metal,",
	"#DEM6\\DEM6_050#or would you rather move on to something else?",
	"#DEM6\\DEM6_051#Shall I go into...",
	"#DEM6\\DEM6_052#I believe Mr. Spock would be more helpful with this, sir.",
	"#DEM6\\DEM6_053#I wonder if any of this stuff might be useful.",
	"#DEM6\\DEM6N000#A common-looking meteorite, about the size of a fist.",
	"#DEM6\\DEM6N001#A glass-fronted display of mineral specimens including a meteorite, a few fossil shells, the skull of a cat-sized alien animal, and a very encrusted twist of metal.",
	"#DEM6\\DEM6N002#A majestic view of Mt. Idyll can be seen through the skylight.",
	"#DEM6\\DEM6N003#A multi-purpose work space, with fine, well-worn tools and equipment close at hand.",
	"#DEM6\\DEM6N004#An antiquated molecular synthesizer sits in the corner.",
	"#DEM6\\DEM6N005#An old corroded twist of metal.",
	"#DEM6\\DEM6N006#An old-fashioned computer. It appears to have some type of simulation running.",
	"#DEM6\\DEM6N007#Assorted pieces of glass rest on this table, from ancient beakers, to double burners.",
	"#DEM6\\DEM6N008#Captain Kirk wonders what is going to happen on this mission.",
	"#DEM6\\DEM6N009#Dr. McCoy is glad that he is in a warm, heated room.",
	"#DEM6\\DEM6N010#Ensign Everts finds himself fascinated by the Acolytes and their planet.",
	"#DEM6\\DEM6N011#Fossil shells of esthetic interest.",
	"#DEM6\\DEM6N012#It is locked.",
	"#DEM6\\DEM6N013#It opens.",
	"#DEM6\\DEM6N014#It opens.",
	"#DEM6\\DEM6N015#Mr. Spock finds the scientific equipment in this room to be rather primitive.",
	"#DEM6\\DEM6N016#Pretty rock specimens.",
	"#DEM6\\DEM6N017#The braincase of a small creature, looking slightly insectoid, somewhat reptilian.",
	"#DEM6\\DEM6N018#The mechanism in the hand has already been repaired.",
	"#DEM6\\DEM6N019#The old man carefully returns the items to his cabinet.",
	"#DEM6\\DEM6N020#You tinker with it but do nothing significant.",
	"#DEM6\\DEM6N021#Brother Stephen watches patiently as you examine his study.",
	"#DEM6\\DEM6N022#The glass case is locked.",
	"#DEM6\\DEM6N023#The machine synthesizes a quantity of Hypo-Dytoxin.",
	"#DEM6\\DEM6N024#This appears to be a study and lab. The equipment looks very ancient.",


	"#TUG0\\TUG0_001#I'm going to have a word for you, Spock, if we appear inside the door!",
	"#TUG0\\TUG0_002#Analysis, Lt. Christensen",
	"#TUG0\\TUG0_003#Beam us out of here.",
	"#TUG0\\TUG0_004#Bones, later. Kirk to Enterprise.",
	"#TUG0\\TUG0_005#Can they be repaired, Spock?",
	"#TUG0\\TUG0_006#Get what you can from this area -- let's get moving.",
	"#TUG0\\TUG0_007#I can't see them winning any popularity contests, Bones.",
	"#TUG0\\TUG0_008#I've always been a gambler, Spock. Figure out what you'll need.",
	"#TUG0\\TUG0_009#Let's not look too far ahead, Mr. Spock.",
	"#TUG0\\TUG0_010#Mr. Spock, you're a genius!",
	"#TUG0\\TUG0_011#Okay, but let's not stay too long in one place.",
	"#TUG0\\TUG0_012#Provided the Elasi don't have anything to say about it.",
	"#TUG0\\TUG0_013#Spock, we don't have two days. If we can repair the transporter, we might be able to transport onto the bridge and capture the Elasi.",
	"#TUG0\\TUG0_014#Captain, I need to find a bit that will fit into the transmogrifier before I can go further with this.",
	"#TUG0\\TUG0_015#Even our most efficient Chief Engineer Scott would have trouble repairing this damage in less than two days.",
	"#TUG0\\TUG0_016#Damn it, Jim. I'm a doctor, not a rocket scientist.",
	"#TUG0\\TUG0_017#He will be all right, but we shouldn't move him.",
	"#TUG0\\TUG0_018#He's not hurt badly. I can revive him.",
	"#TUG0\\TUG0_019#I don't think he should be moved, Jim.",
	"#TUG0\\TUG0_020#Well, at least I'm not picking up residue of any biologicalweapons.  The Elasi used some restraint if you can call it that.",
	"#TUG0\\TUG0_021#And any hostages on the bridge will be killed when the bomb goes off! No, Jim, that's inhuman!",
	"#TUG0\\TUG0_022#I wouldn't go that far, Jim. But I do have to congratulate you, Mr. Spock. Now we can really risk shooting our atoms around the universe. Is this really necessary, Jim?",
	"#TUG0\\TUG0_023#My God Jim, what have you done! You killed them all. You probably blew up the whole damn bridge.",
	"#TUG0\\TUG0_024#They can forget about my vote.",
	"#TUG0\\TUG0_025#Well Jim, there's one thing I can tell you -- I don't like Elasi.",
	"#TUG0\\TUG0_026#Well, with any luck, you won't have to worry about that for quite some time.",
	"#TUG0\\TUG0_027#You cold blooded emotionless...",
	"#TUG0\\TUG0_028#I am registering energy residue from phaser fire and phaser grenade detonations. There are readings of another energy weapon, but the type is unknown.",
	"#TUG0\\TUG0_029#I attach these here... Now all I need is a spare length of wiring.",
	"#TUG0\\TUG0_030#I believe this would be in Dr. McCoy's field of expertise.",
	"#TUG0\\TUG0_031#I strongly recommend that we keep our silence, Captain. The Elasi are quite capable of tracing any communication from within this vessel.",
	"#TUG0\\TUG0_032#I think that does it -- a Comb Bit for the transmogrifier. Now I can continue repairs on the transporter controls. ",
	"#TUG0\\TUG0_033#I'll be able to use this later, so I want to keep it -- but I need to get some equipment in here first.",
	"#TUG0\\TUG0_034#The bits are not long enough, I need a longer piece of wire.",
	"#TUG0\\TUG0_035#The parts fit together satisfactorily.",
	"#TUG0\\TUG0_036#Captain, a thorough analysis is required.",
	"#TUG0\\TUG0_037#Captain, the ship will crash into the planet in 18.32 seconds, I would recommend, leaving the ship immediately.",
	"#TUG0\\TUG0_038#I can attempt to jury-rig repairs if I can find parts. However, there is only a 67.357 percent probability of success.",
	"#TUG0\\TUG0_039#The controls are set for just inside the bridge door Captain.",
	"#TUG0\\TUG0_040#The controls have been virtually destroyed, Captain.",
	"#TUG0\\TUG0_041#To say nothing of the possible damage to the bridge controls.",
	"#TUG0\\TUG0_042#When this operation is complete, Captain, we should have Mr. Scott or Transporter Chief Kyle come here to assist with the repairs.",
	"#TUG0\\TUG0_043#With chief Engineer Scott's assistance, I believe we could get them in perfect working order in two days.",
	"#TUG0\\TUG0_F30#I suppose I should be grateful to see anyone after that. I thought I was dead.",
	"#TUG0\\TUG0_F31#Thank you, Doctor. Be careful, Captain, the Elasi like to set boobytraps. if you need any equipment I've got my tools in this workspace.",
	"#TUG0\\TUG0_S06#Aye Captain.",
	"#TUG0\\TUG0_S11#Captain, you're alive!",
	"#TUG0\\TUG0L006#This is just like their raid on Damocles Station, hard, fast, and dirty.",
	"#TUG0\\TUG0L008#If we could get past the forcefield on the door of the bridge, we should be able to surprise them for sure.",
	"#TUG0\\TUG0L009#Security analysis, sir: if we transport onto the bridge, we'll have the drop on them -- assuming Mr. Spock has the transporter working porperly.",
	"#TUG0\\TUG0L010#Since we have a bomb, Captain, we could rearm it, transport it onto the bridge, and perhaps the Elasi will flee into the hallway. Then we could capture them.",
	"#TUG0\\TUG0N000#A Runcinate Transmogrifier: An engineering tool used in the maintainance of transporters, which can be fitted with bits having a variety of irregularly serrated surfaces.",
	"#TUG0\\TUG0N001#A small bomb appears to have damaged the transporter controls.",
	"#TUG0\\TUG0N002#Crewman Simpson.",
	"#TUG0\\TUG0N003#James T. Kirk cautiously watches the area.",
	"#TUG0\\TUG0N004#Lieutenant Christensen stands ready.",
	"#TUG0\\TUG0N005#McCoy wonders how many patients he'll have on this mission.",
	"#TUG0\\TUG0N006#Phaser Welder is now charged.",
	"#TUG0\\TUG0N007#Spock quietly analyzes the damaged areas of this transporter room.",
	"#TUG0\\TUG0N008#The cabinet is empty.",
	"#TUG0\\TUG0N009#The transporter bay has been damaged in a recent fire fight.",
	"#TUG0\\TUG0N010#The wire scraps are too small, they melt instead of fusing together, and you're left with nothing. ",
	"#TUG0\\TUG0N011#These doors have been scarred by phaser fire. There was a battle here.",
	"#TUG0\\TUG0N012#These transporter controls are now operational. They are set for just inside the bridge door.",
	"#TUG0\\TUG0N013#This is the main transporter pad of the Masada.",
	"#TUG0\\TUG0N014#This man was obviously the transporter engineer. He is unconscious, but alive.",


	"#SIN3\\SIN3_012#Can't say I like the decor.", // FIXME
	"#TUG1\\TUG1_001#This is a mess now, isn't it?",
	"#TUG1\\TUG1_002#A forcefield of unusual configurations has been erected in front of the doorway which leads into the bridge. I don't think it would be healthy to approach too closely, Captain.",
	"#TUG1\\TUG1_003#I'm getting life readings both on the bridge and in the brig, Jim.",
	"#TUG1\\TUG1_004#Jim, I can only perform medical miracles not engineering ones.",
	"#TUG1\\TUG1_005#Jim, I'm picking up 11 life forms in the brig. That accounts for over half the crew. I don't like what that indicates.",
	"#TUG1\\TUG1_006#Nothing unusual is detected.",
	"#TUG1\\TUG1_007#The force field is interfering too much to get an accurate reading, Jim",
	"#TUG1\\TUG1_008#My daddy would have sent me to bed without supper if I'd done something like this.",
	"#TUG1\\TUG1_009#Five phasers without power packs, a drained phaser welder, insulation and bits of wire, and droplets of cooled molten metal.",
	"#TUG1\\TUG1_010#I don't think we can bring down that forcefield, Captain. If we could, though, it might be less risky than trying to transport onto the bridge.",
	"#TUG1\\TUG1_011#I strongly recommend that we keep our silence, Captain. The Elasi are quite capable of tracing any communication from within this vessel.",
	"#TUG1\\TUG1_012#I think that does it -- a Comb Bit for the transmogrifier. Now I can continue repairs on the transporter controls. ",
	"#TUG1\\TUG1_013#If we could find a point to interrupt the flow of power to the field we could gain access to the bridge, Captain.",
	"#TUG1\\TUG1_014#Strong electromagnetic readings come from the doorway at the far end of the hallway.",
	"#TUG1\\TUG1_015#That did it. The field is deactivated, Captain.",
	"#TUG1\\TUG1_016#The field is absorbing the energy.",
	"#TUG1\\TUG1_017#he parts fit together satisfactorily.",
	"#TUG1\\TUG1_018#Tricorder readings indicate an indeterminate number of people in the brig. At least 2 are armed with phasers. I recommend caution when entering.",
	"#TUG1\\TUG1L000#I doubt that our phasers could get through that, Captain.",
	"#TUG1\\TUG1L005#This corridor provides access to the transporter room, Captain. It is secure.",
	"#TUG1\\TUG1N000#A tangle of mangled equipment, reduced to junk. There are the remains of five phasers without power packs, a drained phaser welder, and scraps of wire and uncertain bits of metal junk.",
	"#TUG1\\TUG1N001#According to the deckplans of this class of Starship, this is the entrance to the ship's brig.",
	"#TUG1\\TUG1N002#Lt. Christensen is carefully watching the hallway",
	"#TUG1\\TUG1N003#McCoy is fidgeting around.",
	"#TUG1\\TUG1N004#Phaser Welder is now charged.",
	"#TUG1\\TUG1N005#Some kind of forcefield appears to cover the door. ",
	"#TUG1\\TUG1N006#Spock is analyzing the surroundings.",
	"#TUG1\\TUG1N007#The field has already been deactivated.",
	"#TUG1\\TUG1N008#The field has already been deactivated",
	"#TUG1\\TUG1N009#The wire scraps are too small, they melt instead of fusing together, and you're left with nothing. ",
	"#TUG1\\TUG1N010#This viewscreen/ communication terminal has been damaged beyond repair.",
	"#TUG1\\TUG1N011#Twisted debris has been scattered along the side of the corridor.",
	"#TUG1\\TUG1N013#You are in a typical starship corridor.",
};

}

#endif
