#!/usr/bin/python

from tasm.parser import parser
from tasm.cpp import cpp

p = parser()
p.strip_path = 3
context = p.parse('dreamweb/dreamweb.asm')
p.link()
generator = cpp(context, "DreamGen", blacklist = [
	'randomnumber',
	'quickquit',
	'quickquit2',
	'seecommandtail',
	'multiget',
	'multiput',
	'multidump',
	'frameoutnm',
	'frameoutbh',
	'frameoutfx',
	'cls', 
	'printundermon',
	'worktoscreen',
	'width160',
	'convertkey',
	'readabyte',
	'readoneblock',
	'printsprites',
	'printasprite',
	'eraseoldobs',
	'clearsprites',
	'makesprite',
	'showframe',
	'spriteupdate',
	'frameoutv',
	'modifychar',
	'lockmon'
	])
generator.generate('dreamweb') #start routine
