ifdef ENABLE_SCUMM
DEFINES += -DENABLE_SCUMM=$(ENABLE_SCUMM)
MODULES += engines/scumm
ifdef ENGINE_WIP_SCUMM
DEFINES += -DENGINE_WIP_SCUMM=$(ENGINE_WIP_SCUMM)
endif

ifdef ENABLE_SCUMM_7_8
DEFINES += -DENABLE_SCUMM_7_8
ifdef ENGINE_WIP_SCUMM_7_8
DEFINES += -DENGINE_WIP_SCUMM_7_8=$(ENGINE_WIP_SCUMM_7_8)
endif
endif

ifdef ENABLE_HE
DEFINES += -DENABLE_HE
ifdef ENGINE_WIP_HE
DEFINES += -DENGINE_WIP_HE=$(ENGINE_WIP_HE)
endif
endif

endif

ifdef ENABLE_AGI
DEFINES += -DENABLE_AGI=$(ENABLE_AGI)
MODULES += engines/agi
ifdef ENGINE_WIP_AGI
DEFINES += -DENGINE_WIP_AGI=$(ENGINE_WIP_AGI)
endif
endif

ifdef ENABLE_AGOS
DEFINES += -DENABLE_AGOS=$(ENABLE_AGOS)
MODULES += engines/agos
ifdef ENGINE_WIP_AGOS
DEFINES += -DENGINE_WIP_AGOS=$(ENGINE_WIP_AGOS)
endif

ifdef ENABLE_AGOS2
DEFINES += -DENABLE_AGOS2
ifdef ENGINE_WIP_AGOS2
DEFINES += -DENGINE_WIP_AGOS2=$(ENGINE_WIP_AGOS2)
endif
endif
endif

ifdef ENABLE_CINE
DEFINES += -DENABLE_CINE=$(ENABLE_CINE)
MODULES += engines/cine
ifdef ENGINE_WIP_CINE
DEFINES += -DENGINE_WIP_CINE=$(ENGINE_WIP_CINE)
endif
endif

ifdef ENABLE_CRUISE
DEFINES += -DENABLE_CRUISE=$(ENABLE_CRUISE)
MODULES += engines/cruise
ifdef ENGINE_WIP_CRUISE
DEFINES += -DENGINE_WIP_CRUISE=$(ENGINE_WIP_CRUISE)
endif
endif

ifdef ENABLE_DRACI
DEFINES += -DENABLE_DRACI=$(ENABLE_DRACI)
MODULES += engines/draci
ifdef ENGINE_WIP_DRACI
DEFINES += -DENGINE_WIP_DRACI=$(ENGINE_WIP_DRACI)
endif
endif

ifdef ENABLE_DRASCULA
DEFINES += -DENABLE_DRASCULA=$(ENABLE_DRASCULA)
MODULES += engines/drascula
ifdef ENGINE_WIP_DRASCULA
DEFINES += -DENGINE_WIP_DRASCULA=$(ENGINE_WIP_DRASCULA)
endif
endif

ifdef ENABLE_GOB
DEFINES += -DENABLE_GOB=$(ENABLE_GOB)
MODULES += engines/gob
ifdef ENGINE_WIP_GOB
DEFINES += -DENGINE_WIP_GOB=$(ENGINE_WIP_GOB)
endif
endif

ifdef ENABLE_GROOVIE
DEFINES += -DENABLE_GROOVIE=$(ENABLE_GROOVIE)
MODULES += engines/groovie
ifdef ENGINE_WIP_GROOVIE
DEFINES += -DENGINE_WIP_GROOVIE=$(ENGINE_WIP_GROOVIE)
endif

ifdef ENABLE_GROOVIE2
DEFINES += -DENABLE_GROOVIE2
ifdef ENGINE_WIP_GROOVIE2
DEFINES += -DENGINE_WIP_GROOVIE2=$(ENGINE_WIP_GROOVIE2)
endif
endif
endif

ifdef ENABLE_HUGO
DEFINES += -DENABLE_HUGO=$(ENABLE_HUGO)
MODULES += engines/hugo
ifdef ENGINE_WIP_HUGO
DEFINES += -DENGINE_WIP_HUGO=$(ENGINE_WIP_HUGO)
endif
endif

ifdef ENABLE_KYRA
DEFINES += -DENABLE_KYRA=$(ENABLE_KYRA)
MODULES += engines/kyra
ifdef ENGINE_WIP_KYRA
DEFINES += -DENGINE_WIP_KYRA=$(ENGINE_WIP_KYRA)
endif

ifdef ENABLE_LOL
DEFINES += -DENABLE_LOL
ifdef ENGINE_WIP_LOL
DEFINES += -DENGINE_WIP_LOL=$(ENGINE_WIP_LOL)
endif
endif
endif

ifdef ENABLE_LASTEXPRESS
DEFINES += -DENABLE_LASTEXPRESS=$(ENABLE_LASTEXPRESS)
MODULES += engines/lastexpress
ifdef ENGINE_WIP_LASTEXPRESS
DEFINES += -DENGINE_WIP_LASTEXPRESS=$(ENGINE_WIP_LASTEXPRESS)
endif
endif

ifdef ENABLE_LURE
DEFINES += -DENABLE_LURE=$(ENABLE_LURE)
MODULES += engines/lure
ifdef ENGINE_WIP_LURE
DEFINES += -DENGINE_WIP_LURE=$(ENGINE_WIP_LURE)
endif
endif

ifdef ENABLE_M4
DEFINES += -DENABLE_M4=$(ENABLE_M4)
MODULES += engines/m4
ifdef ENGINE_WIP_M4
DEFINES += -DENGINE_WIP_M4=$(ENGINE_WIP_M4)
endif
endif

ifdef ENABLE_MADE
DEFINES += -DENABLE_MADE=$(ENABLE_MADE)
MODULES += engines/made
ifdef ENGINE_WIP_MADE
DEFINES += -DENGINE_WIP_MADE=$(ENGINE_WIP_MADE)
endif
endif

ifdef ENABLE_MOHAWK
DEFINES += -DENABLE_MOHAWK=$(ENABLE_MOHAWK)
MODULES += engines/mohawk
ifdef ENGINE_WIP_MOHAWK
DEFINES += -DENGINE_WIP_MOHAWK=$(ENGINE_WIP_MOHAWK)
endif

ifdef ENABLE_CSTIME
DEFINES += -DENABLE_CSTIME
ifdef ENGINE_WIP_CSTIME
DEFINES += -DENGINE_WIP_CSTIME=$(ENGINE_WIP_CSTIME)
endif
endif

ifdef ENABLE_MYST
DEFINES += -DENABLE_MYST
ifdef ENGINE_WIP_MYST
DEFINES += -DENGINE_WIP_MYST=$(ENGINE_WIP_MYST)
endif
endif

ifdef ENABLE_RIVEN
DEFINES += -DENABLE_RIVEN
ifdef ENGINE_WIP_RIVEN
DEFINES += -DENGINE_WIP_RIVEN=$(ENGINE_WIP_RIVEN)
endif
endif
endif

ifdef ENABLE_PARALLACTION
DEFINES += -DENABLE_PARALLACTION=$(ENABLE_PARALLACTION)
MODULES += engines/parallaction
ifdef ENGINE_WIP_PARALLACTION
DEFINES += -DENGINE_WIP_PARALLACTION=$(ENGINE_WIP_PARALLACTION)
endif
endif

ifdef ENABLE_QUEEN
DEFINES += -DENABLE_QUEEN=$(ENABLE_QUEEN)
MODULES += engines/queen
ifdef ENGINE_WIP_QUEEN
DEFINES += -DENGINE_WIP_QUEEN=$(ENGINE_WIP_QUEEN)
endif
endif

ifdef ENABLE_SAGA
DEFINES += -DENABLE_SAGA=$(ENABLE_SAGA)
MODULES += engines/saga
ifdef ENGINE_WIP_SAGA
DEFINES += -DENGINE_WIP_SAGA=$(ENGINE_WIP_SAGA)
endif

ifdef ENABLE_IHNM
DEFINES += -DENABLE_IHNM
ifdef ENGINE_WIP_IHNM
DEFINES += -DENGINE_WIP_IHNM=$(ENGINE_WIP_IHNM)
endif
endif

ifdef ENABLE_SAGA2
DEFINES += -DENABLE_SAGA2
ifdef ENGINE_WIP_SAGA2
DEFINES += -DENGINE_WIP_SAGA2=$(ENGINE_WIP_SAGA2)
endif
endif
endif

ifdef ENABLE_SCI
DEFINES += -DENABLE_SCI=$(ENABLE_SCI)
MODULES += engines/sci
ifdef ENGINE_WIP_SCI
DEFINES += -DENGINE_WIP_SCI=$(ENGINE_WIP_SCI)
endif

ifdef ENABLE_SCI32
DEFINES += -DENABLE_SCI32
ifdef ENGINE_WIP_SCI32
DEFINES += -DENGINE_WIP_SCI32=$(ENGINE_WIP_SCI32)
endif
endif
endif

ifdef ENABLE_SKY
DEFINES += -DENABLE_SKY=$(ENABLE_SKY)
MODULES += engines/sky
ifdef ENGINE_WIP_SKY
DEFINES += -DENGINE_WIP_SKY=$(ENGINE_WIP_SKY)
endif
endif

ifdef ENABLE_SWORD1
DEFINES += -DENABLE_SWORD1=$(ENABLE_SWORD1)
MODULES += engines/sword1
ifdef ENGINE_WIP_SWORD1
DEFINES += -DENGINE_WIP_SWORD1=$(ENGINE_WIP_SWORD1)
endif
endif

ifdef ENABLE_SWORD2
DEFINES += -DENABLE_SWORD2=$(ENABLE_SWORD2)
MODULES += engines/sword2
ifdef ENGINE_WIP_SWORD2
DEFINES += -DENGINE_WIP_SWORD2=$(ENGINE_WIP_SWORD2)
endif
endif

ifdef ENABLE_SWORD25
DEFINES += -DENABLE_SWORD25=$(ENABLE_SWORD25)
MODULES += engines/sword25
ifdef ENGINE_WIP_SWORD25
DEFINES += -DENGINE_WIP_SWORD25=$(ENGINE_WIP_SWORD25)
endif
endif

ifdef ENABLE_TESTBED
DEFINES += -DENABLE_TESTBED=$(ENABLE_TESTBED)
MODULES += engines/testbed
ifdef ENGINE_WIP_TESTBED
DEFINES += -DENGINE_WIP_TESTBED=$(ENGINE_WIP_TESTBED)
endif
endif

ifdef ENABLE_TEENAGENT
DEFINES += -DENABLE_TEENAGENT=$(ENABLE_TEENAGENT)
MODULES += engines/teenagent
ifdef ENGINE_WIP_TEENAGENT
DEFINES += -DENGINE_WIP_TEENAGENT=$(ENGINE_WIP_TEENAGENT)
endif
endif

ifdef ENABLE_TINSEL
DEFINES += -DENABLE_TINSEL=$(ENABLE_TINSEL)
MODULES += engines/tinsel
ifdef ENGINE_WIP_TINSEL
DEFINES += -DENGINE_WIP_TINSEL=$(ENGINE_WIP_TINSEL)
endif
endif

ifdef ENABLE_TOON
DEFINES += -DENABLE_TOON=$(ENABLE_TOON)
MODULES += engines/toon
ifdef ENGINE_WIP_TOON
DEFINES += -DENGINE_WIP_TOON=$(ENGINE_WIP_TOON)
endif
endif

ifdef ENABLE_TOUCHE
DEFINES += -DENABLE_TOUCHE=$(ENABLE_TOUCHE)
MODULES += engines/touche
ifdef ENGINE_WIP_TOUCHE
DEFINES += -DENGINE_WIP_TOUCHE=$(ENGINE_WIP_TOUCHE)
endif
endif

ifdef ENABLE_TSAGE
DEFINES += -DENABLE_TSAGE=$(ENABLE_TSAGE)
MODULES += engines/tsage
ifdef ENGINE_WIP_TSAGE
DEFINES += -DENGINE_WIP_TSAGE=$(ENGINE_WIP_TSAGE)
endif
endif

ifdef ENABLE_TUCKER
DEFINES += -DENABLE_TUCKER=$(ENABLE_TUCKER)
MODULES += engines/tucker
ifdef ENGINE_WIP_TUCKER
DEFINES += -DENGINE_WIP_TUCKER=$(ENGINE_WIP_TUCKER)
endif
endif

