#! /bin/sh

# This simple script is called from the upstream makefile whenever someone
# calls "make deb".  It adds a changelog entry to the top of debian/changelog
# so that the version number is correct.

VERSION=`sed -n -e 's/svn//g' -e 's/^#define SCUMMVM_VERSION "\(.*\)"/\1/p' base/internal_version.h`-0svn`date +%Y%m%d`
USERNAME=`whoami`
GECOS=`getent passwd $USERNAME | awk '-F[,:]' '{print $5}'`
DOMAIN=`hostname --fqdn`
DATE=`date -R`

head -1 debian/changelog | grep -qF $VERSION && exit 0

TMP=`tempfile`

cat debian/changelog > $TMP

cat << __eof > debian/changelog
scummvm ($VERSION) experimental; urgency=low

  * SVN snapshot.

    Builder:    $GECOS <$USERNAME@$DOMAIN>
    Build-date: $DATE

    Please don't file bugs you find in this package in the Debian Bug Tracking
    system, use the ScummVM team's own bug tracker instead.  You can find this
    tracker at <http://sourceforge.net/tracker/?group_id=37116>.

 -- Tore Anderson <tore@debian.org>  $DATE

__eof

cat $TMP >> debian/changelog
rm -f $TMP
