MODULE := engines/mads

MODULE_OBJS := \
	console.o \
	engine.o \
	metaengine.o \
	mads.o \
	animview/anim_timer.o \
	animview/animview.o \
	animview/functions.o \
	textview/textview.o \
	core/anim.o \
	core/attr.o \
	core/buffer.o \
	core/camera.o \
	core/color.o \
	core/config.o \
	core/conv.o \
	core/cursor.o \
	core/cycle.o \
	core/dialog.o \
	core/ems.o \
	core/env.o \
	core/error.o \
	core/fileio.o \
	core/font.o \
	core/game.o \
	core/global.o \
	core/heap.o \
	core/himem.o \
	core/hspot.o \
	core/image.o \
	core/imath.o \
	core/implode.o \
	core/inter.o \
	core/kernel.o \
	core/keys.o \
	core/lib.o \
	core/loader.o \
	core/magic.o \
	core/matte.o \
	core/mcga.o \
	core/mem.o \
	core/mouse.o \
	core/mps_archive.o \
	core/mps_installer.o \
	core/object.o \
	core/pack.o \
	core/pal.o \
	core/pfab.o \
	core/player.o \
	core/popup.o \
	core/quote.o \
	core/rail.o \
	core/room.o \
	core/screen.o \
	core/sort.o \
	core/sound.o \
	core/sound_manager.o \
	core/speech.o \
	core/sprite.o \
	core/text.o \
	core/tile.o \
	core/timer.o \
	core/video.o \
	core/vocab.o \
	core/window.o \
	core/xms.o \
	nebular/nebular.o \
	nebular/asound.o \
	nebular/console.o \
	nebular/copy.o \
	nebular/extra.o \
	nebular/global.o \
	nebular/main.o \
	nebular/main_menu.o \
	nebular/menus.o \
	nebular/popup.o \
	nebular/sound_nebular.o \
	nebular/mads/mads.o \
	nebular/rooms/thunks.o \
	nebular/rooms/room101.o \
	nebular/rooms/room102.o \
	nebular/rooms/room103.o \
	nebular/rooms/room104.o \
	nebular/rooms/room105.o \
	nebular/rooms/room106.o \
	nebular/rooms/room107.o \
	nebular/rooms/room108.o \
	nebular/rooms/room109.o \
	nebular/rooms/room110.o \
	nebular/rooms/room111.o \
	nebular/rooms/room112.o \
	nebular/rooms/room201.o \
	nebular/rooms/room202.o \
	nebular/rooms/room203.o \
	nebular/rooms/room205.o \
	nebular/rooms/room207.o \
	nebular/rooms/room208.o \
	nebular/rooms/room209.o \
	nebular/rooms/room210.o \
	nebular/rooms/room211.o \
	nebular/rooms/room212.o \
	nebular/rooms/room213.o \
	nebular/rooms/room214.o \
	nebular/rooms/room215.o \
	nebular/rooms/room216.o \
	nebular/rooms/room301.o \
	nebular/rooms/room302.o \
	nebular/rooms/room303.o \
	nebular/rooms/room304.o \
	nebular/rooms/room307.o \
	nebular/rooms/room308.o \
	nebular/rooms/room309.o \
	nebular/rooms/room310.o \
	nebular/rooms/room311.o \
	nebular/rooms/room313.o \
	nebular/rooms/room316.o \
	nebular/rooms/room318.o \
	nebular/rooms/room319.o \
	nebular/rooms/room320.o \
	nebular/rooms/room321.o \
	nebular/rooms/room322.o \
	nebular/rooms/room351.o \
	nebular/rooms/room352.o \
	nebular/rooms/room353.o \
	nebular/rooms/room354.o \
	nebular/rooms/room357.o \
	nebular/rooms/room358.o \
	nebular/rooms/room359.o \
	nebular/rooms/room360.o \
	nebular/rooms/room361.o \
	nebular/rooms/room366.o \
	nebular/rooms/room387.o \
	nebular/rooms/room388.o \
	nebular/rooms/room389.o \
	nebular/rooms/room390.o \
	nebular/rooms/room391.o \
	nebular/rooms/room399.o \
	nebular/rooms/room401.o \
	nebular/rooms/room402.o \
	nebular/rooms/room405.o \
	nebular/rooms/room406.o \
	nebular/rooms/room407.o \
	nebular/rooms/room408.o \
	nebular/rooms/room409.o \
	nebular/rooms/room410.o \
	nebular/rooms/room411.o \
	nebular/rooms/room413.o \
	nebular/rooms/room501.o \
	nebular/rooms/room502.o \
	nebular/rooms/room503.o \
	nebular/rooms/room504.o \
	nebular/rooms/room505.o \
	nebular/rooms/room506.o \
	nebular/rooms/room507.o \
	nebular/rooms/room508.o \
	nebular/rooms/room511.o \
	nebular/rooms/room512.o \
	nebular/rooms/room513.o \
	nebular/rooms/room515.o \
	nebular/rooms/room551.o \
	nebular/rooms/room601.o \
	nebular/rooms/room602.o \
	nebular/rooms/room603.o \
	nebular/rooms/room604.o \
	nebular/rooms/room605.o \
	nebular/rooms/room607.o \
	nebular/rooms/room608.o \
	nebular/rooms/room609.o \
	nebular/rooms/room610.o \
	nebular/rooms/room611.o \
	nebular/rooms/room612.o \
	nebular/rooms/room620.o \
	nebular/rooms/room701.o \
	nebular/rooms/room702.o \
	nebular/rooms/room703.o \
	nebular/rooms/room704.o \
	nebular/rooms/room705.o \
	nebular/rooms/room706.o \
	nebular/rooms/room707.o \
	nebular/rooms/room710.o \
	nebular/rooms/room711.o \
	nebular/rooms/room751.o \
	nebular/rooms/room752.o \
	nebular/rooms/room801.o \
	nebular/rooms/room802.o \
	nebular/rooms/room803.o \
	nebular/rooms/room804.o \
	nebular/rooms/room805.o \
	nebular/rooms/room807.o \
	nebular/rooms/room808.o \
	nebular/rooms/room810.o \
	nebular/rooms/section1.o \
	nebular/rooms/section2.o \
	nebular/rooms/section3.o \
	nebular/rooms/section4.o \
	nebular/rooms/section5.o \
	nebular/rooms/section6.o \
	nebular/rooms/section7.o \
	nebular/rooms/section8.o \
	nebular/rooms/dialog.o \
	nebular/rooms/forcefield.o \
	nebular/rooms/teleporter.o \
	phantom/mads/mads.o \
	phantom/rooms/section1.o \
	phantom/rooms/room101.o \
	phantom/rooms/room102.o \
	phantom/rooms/room103.o \
	phantom/rooms/room104.o \
	phantom/rooms/room105.o \
	phantom/rooms/room106.o \
	phantom/rooms/room107.o \
	phantom/rooms/room108.o \
	phantom/rooms/room109.o \
	phantom/rooms/room110.o \
	phantom/rooms/room111.o \
	phantom/rooms/room112.o \
	phantom/rooms/room113.o \
	phantom/rooms/room114.o \
	phantom/rooms/room150.o \
	phantom/rooms/section2.o \
	phantom/rooms/room201.o \
	phantom/rooms/room202.o \
	phantom/rooms/room203.o \
	phantom/rooms/room204.o \
	phantom/rooms/room205.o \
	phantom/rooms/room206.o \
	phantom/rooms/room207.o \
	phantom/rooms/room208.o \
	phantom/rooms/room250.o \
	phantom/rooms/section3.o \
	phantom/rooms/room301.o \
	phantom/rooms/room302.o \
	phantom/rooms/room303.o \
	phantom/rooms/room304.o \
	phantom/rooms/room305.o \
	phantom/rooms/room306.o \
	phantom/rooms/room307.o \
	phantom/rooms/room308.o \
	phantom/rooms/room309.o \
	phantom/rooms/room310.o \
	phantom/rooms/section4.o \
	phantom/rooms/room401.o \
	phantom/rooms/room403.o \
	phantom/rooms/room404.o \
	phantom/rooms/room406.o \
	phantom/rooms/room407.o \
	phantom/rooms/room408.o \
	phantom/rooms/room409.o \
	phantom/rooms/room410.o \
	phantom/rooms/room453.o \
	phantom/rooms/room456.o \
	phantom/rooms/section5.o \
	phantom/rooms/room501.o \
	phantom/rooms/room502.o \
	phantom/rooms/room504.o \
	phantom/rooms/room505.o \
	phantom/rooms/room506.o \
	phantom/phantom.o \
	phantom/asound.o \
	phantom/catacombs.o \
	phantom/global.o \
	phantom/main_menu.o \
	phantom/menus.o \
	phantom/main.o \
	phantom/sound_phantom.o \
	dragonsphere/mads/mads.o \
	dragonsphere/rooms/section1.o \
	dragonsphere/rooms/room101.o \
	dragonsphere/rooms/section2.o \
	dragonsphere/rooms/section3.o \
	dragonsphere/rooms/section4.o \
	dragonsphere/rooms/section5.o \
	dragonsphere/rooms/section6.o \
	dragonsphere/rooms/section9.o \
	dragonsphere/rooms/room102.o \
	dragonsphere/rooms/room103.o \
	dragonsphere/rooms/room104.o \
	dragonsphere/rooms/room105.o \
	dragonsphere/rooms/room106.o \
	dragonsphere/rooms/room107.o \
	dragonsphere/rooms/room108.o \
	dragonsphere/rooms/room109.o \
	dragonsphere/rooms/room110.o \
	dragonsphere/rooms/room111.o \
	dragonsphere/rooms/room112.o \
	dragonsphere/rooms/room113.o \
	dragonsphere/rooms/room114.o \
	dragonsphere/rooms/room115.o \
	dragonsphere/rooms/room116.o \
	dragonsphere/rooms/room117.o \
	dragonsphere/rooms/room118.o \
	dragonsphere/rooms/room119.o \
	dragonsphere/rooms/room120.o \
	dragonsphere/rooms/room201.o \
	dragonsphere/rooms/room203.o \
	dragonsphere/rooms/room204.o \
	dragonsphere/rooms/room205.o \
	dragonsphere/rooms/room206.o \
	dragonsphere/rooms/room301.o \
	dragonsphere/rooms/room302.o \
	dragonsphere/rooms/room303.o \
	dragonsphere/rooms/room401.o \
	dragonsphere/rooms/room402.o \
	dragonsphere/rooms/room403.o \
	dragonsphere/rooms/room404.o \
	dragonsphere/rooms/room405.o \
	dragonsphere/rooms/room406.o \
	dragonsphere/rooms/room407.o \
	dragonsphere/rooms/room408.o \
	dragonsphere/rooms/room409.o \
	dragonsphere/rooms/room410.o \
	dragonsphere/rooms/room411.o \
	dragonsphere/rooms/room412.o \
	dragonsphere/rooms/room454.o \
	dragonsphere/rooms/room501.o \
	dragonsphere/rooms/room502.o \
	dragonsphere/rooms/room503.o \
	dragonsphere/rooms/room504.o \
	dragonsphere/rooms/room505.o \
	dragonsphere/rooms/room506.o \
	dragonsphere/rooms/room507.o \
	dragonsphere/rooms/room508.o \
	dragonsphere/rooms/room509.o \
	dragonsphere/rooms/room510.o \
	dragonsphere/rooms/room511.o \
	dragonsphere/rooms/room512.o \
	dragonsphere/rooms/room557.o \
	dragonsphere/rooms/room601.o \
	dragonsphere/rooms/room603.o \
	dragonsphere/rooms/room604.o \
	dragonsphere/rooms/room605.o \
	dragonsphere/rooms/room606.o \
	dragonsphere/rooms/room607.o \
	dragonsphere/rooms/room609.o \
	dragonsphere/rooms/room612.o \
	dragonsphere/rooms/room613.o \
	dragonsphere/rooms/room614.o \
	dragonsphere/rooms/room909.o \
	dragonsphere/dragonsphere.o \
	dragonsphere/asound.o \
	dragonsphere/global.o \
	dragonsphere/main.o \
	dragonsphere/main_menu.o \
	dragonsphere/menus.o \
	dragonsphere/sound_dragonsphere.o \
	forest/forest.o \
	forest/digi.o \
	forest/extra.o \
	forest/global.o \
	forest/inventory.o \
	forest/journal.o \
	forest/main.o \
	forest/menus.o \
	forest/midi.o \
	forest/mads/mads.o \
	forest/rooms/room101.o \
	forest/rooms/room103.o \
	forest/rooms/room104.o \
	forest/rooms/room106.o \
	forest/rooms/room107.o \
	forest/rooms/room199.o \
	forest/rooms/room201.o \
	forest/rooms/room203.o \
	forest/rooms/room204.o \
	forest/rooms/room205.o \
	forest/rooms/room210.o \
	forest/rooms/room211.o \
	forest/rooms/room220.o \
	forest/rooms/room221.o \
	forest/rooms/room301.o \
	forest/rooms/room302.o \
	forest/rooms/room303.o \
	forest/rooms/room304.o \
	forest/rooms/room305.o \
	forest/rooms/room306.o \
	forest/rooms/room307.o \
	forest/rooms/room308.o \
	forest/rooms/room321.o \
	forest/rooms/room322.o \
	forest/rooms/room401.o \
	forest/rooms/room402.o \
	forest/rooms/room403.o \
	forest/rooms/room404.o \
	forest/rooms/room405.o \
	forest/rooms/room420.o \
	forest/rooms/room501.o \
	forest/rooms/room503.o \
	forest/rooms/room509.o \
	forest/rooms/room510.o \
	forest/rooms/room520.o \
	forest/rooms/room901.o \
	forest/rooms/room903.o \
	forest/rooms/room904.o \
	forest/rooms/section1.o \
	forest/rooms/section2.o \
	forest/rooms/section3.o \
	forest/rooms/section4.o \
	forest/rooms/section5.o \
	forest/rooms/section9.o

# This module can be built as a plugin
ifeq ($(ENABLE_MADS), DYNAMIC_PLUGIN)
PLUGIN := 1
endif

# Include common rules
include $(srcdir)/rules.mk

# Detection objects
DETECT_OBJS += $(MODULE)/detection.o
