MODULE := engines/mads

MODULE_OBJS := \
	core/sound_manager.o \
	nebular/nebular.o \
	nebular/debugger.o \
	nebular/dialogs_nebular.o \
	nebular/game_nebular.o \
	nebular/globals_nebular.o \
	nebular/menu_nebular.o \
	nebular/sound_nebular.o \
	nebular/nebular_scenes.o \
	nebular/nebular_scenes1.o \
	nebular/nebular_scenes2.o \
	nebular/nebular_scenes3.o \
	nebular/nebular_scenes4.o \
	nebular/nebular_scenes5.o \
	nebular/nebular_scenes6.o \
	nebular/nebular_scenes7.o \
	nebular/nebular_scenes8.o \
	nebular/core/action.o \
	nebular/core/animation.o \
	nebular/core/assets.o \
	nebular/core/asound.o \
	nebular/core/audio.o \
	nebular/core/camera.o \
	nebular/core/compression.o \
	nebular/core/conversations.o \
	nebular/core/dialogs.o \
	nebular/core/events.o \
	nebular/core/font.o \
	nebular/core/game.o \
	nebular/core/game_data.o \
	nebular/core/globals.o \
	nebular/core/hag.o \
	nebular/core/hotspots.o \
	nebular/core/inventory.o \
	nebular/core/menu_views.o \
	nebular/core/messages.o \
	nebular/core/msurface.o \
	nebular/core/mps_installer.o \
	nebular/core/palette.o \
	nebular/core/player.o \
	nebular/core/rails.o \
	nebular/core/resources.o \
	nebular/core/scene.o \
	nebular/core/scene_data.o \
	nebular/core/screen.o \
	nebular/core/sequence.o \
	nebular/core/sprites.o \
	nebular/core/staticres.o \
	nebular/core/user_interface.o \
	metaengine.o \
	mads.o

ifdef ENABLE_MADSV2
MODULE_OBJS += \
	madsv2/console.o \
	madsv2/engine.o \
	madsv2/animview/anim_timer.o \
	madsv2/animview/animview.o \
	madsv2/animview/functions.o \
	madsv2/textview/textview.o \
	madsv2/core/anim.o \
	madsv2/core/attr.o \
	madsv2/core/buffer.o \
	madsv2/core/camera.o \
	madsv2/core/color.o \
	madsv2/core/config.o \
	madsv2/core/conv.o \
	madsv2/core/copy.o \
	madsv2/core/cursor.o \
	madsv2/core/cycle.o \
	madsv2/core/dialog.o \
	madsv2/core/ems.o \
	madsv2/core/env.o \
	madsv2/core/error.o \
	madsv2/core/extra.o \
	madsv2/core/fileio.o \
	madsv2/core/font.o \
	madsv2/core/game.o \
	madsv2/core/global.o \
	madsv2/core/heap.o \
	madsv2/core/himem.o \
	madsv2/core/hspot.o \
	madsv2/core/image.o \
	madsv2/core/imath.o \
	madsv2/core/implode.o \
	madsv2/core/inter.o \
	madsv2/core/kernel.o \
	madsv2/core/keys.o \
	madsv2/core/lbm.o \
	madsv2/core/lib.o \
	madsv2/core/loader.o \
	madsv2/core/magic.o \
	madsv2/core/matte.o \
	madsv2/core/mcga.o \
	madsv2/core/mem.o \
	madsv2/core/mouse.o \
	madsv2/core/object.o \
	madsv2/core/pack.o \
	madsv2/core/pal.o \
	madsv2/core/pfab.o \
	madsv2/core/player.o \
	madsv2/core/popup.o \
	madsv2/core/quote.o \
	madsv2/core/rail.o \
	madsv2/core/room.o \
	madsv2/core/screen.o \
	madsv2/core/sort.o \
	madsv2/core/sound.o \
	madsv2/core/speech.o \
	madsv2/core/sprite.o \
	madsv2/core/text.o \
	madsv2/core/tile.o \
	madsv2/core/timer.o \
	madsv2/core/video.o \
	madsv2/core/vocab.o \
	madsv2/core/window.o \
	madsv2/core/xms.o \
	madsv2/phantom/mads/mads.o \
	madsv2/phantom/rooms/section1.o \
	madsv2/phantom/rooms/room101.o \
	madsv2/phantom/rooms/room102.o \
	madsv2/phantom/rooms/room103.o \
	madsv2/phantom/rooms/room104.o \
	madsv2/phantom/rooms/room105.o \
	madsv2/phantom/rooms/room106.o \
	madsv2/phantom/rooms/room107.o \
	madsv2/phantom/rooms/room108.o \
	madsv2/phantom/rooms/room109.o \
	madsv2/phantom/rooms/room110.o \
	madsv2/phantom/rooms/room111.o \
	madsv2/phantom/rooms/room112.o \
	madsv2/phantom/rooms/room113.o \
	madsv2/phantom/rooms/room114.o \
	madsv2/phantom/rooms/room150.o \
	madsv2/phantom/rooms/section2.o \
	madsv2/phantom/rooms/room201.o \
	madsv2/phantom/rooms/room202.o \
	madsv2/phantom/rooms/room203.o \
	madsv2/phantom/rooms/room204.o \
	madsv2/phantom/rooms/room205.o \
	madsv2/phantom/rooms/room206.o \
	madsv2/phantom/rooms/room207.o \
	madsv2/phantom/rooms/room208.o \
	madsv2/phantom/rooms/room250.o \
	madsv2/phantom/rooms/section3.o \
	madsv2/phantom/rooms/room301.o \
	madsv2/phantom/rooms/room302.o \
	madsv2/phantom/rooms/room303.o \
	madsv2/phantom/rooms/room304.o \
	madsv2/phantom/rooms/room305.o \
	madsv2/phantom/rooms/room306.o \
	madsv2/phantom/rooms/room307.o \
	madsv2/phantom/rooms/room308.o \
	madsv2/phantom/rooms/room309.o \
	madsv2/phantom/rooms/room310.o \
	madsv2/phantom/rooms/section4.o \
	madsv2/phantom/rooms/room401.o \
	madsv2/phantom/rooms/room403.o \
	madsv2/phantom/rooms/room404.o \
	madsv2/phantom/rooms/room406.o \
	madsv2/phantom/rooms/room407.o \
	madsv2/phantom/rooms/room408.o \
	madsv2/phantom/rooms/room409.o \
	madsv2/phantom/rooms/room410.o \
	madsv2/phantom/rooms/room453.o \
	madsv2/phantom/rooms/room456.o \
	madsv2/phantom/rooms/section5.o \
	madsv2/phantom/rooms/room501.o \
	madsv2/phantom/rooms/room502.o \
	madsv2/phantom/rooms/room504.o \
	madsv2/phantom/rooms/room505.o \
	madsv2/phantom/rooms/room506.o \
	madsv2/phantom/phantom.o \
	madsv2/phantom/asound.o \
	madsv2/phantom/catacombs.o \
	madsv2/phantom/global.o \
	madsv2/phantom/main_menu.o \
	madsv2/phantom/menus.o \
	madsv2/phantom/main.o \
	madsv2/phantom/sound_phantom.o \
	madsv2/dragonsphere/mads/mads.o \
	madsv2/dragonsphere/rooms/section1.o \
	madsv2/dragonsphere/rooms/room101.o \
	madsv2/dragonsphere/rooms/section2.o \
	madsv2/dragonsphere/rooms/section3.o \
	madsv2/dragonsphere/rooms/section4.o \
	madsv2/dragonsphere/rooms/section5.o \
	madsv2/dragonsphere/rooms/section6.o \
	madsv2/dragonsphere/rooms/section9.o \
	madsv2/dragonsphere/rooms/room102.o \
	madsv2/dragonsphere/rooms/room103.o \
	madsv2/dragonsphere/rooms/room104.o \
	madsv2/dragonsphere/rooms/room105.o \
	madsv2/dragonsphere/rooms/room106.o \
	madsv2/dragonsphere/rooms/room107.o \
	madsv2/dragonsphere/rooms/room108.o \
	madsv2/dragonsphere/rooms/room109.o \
	madsv2/dragonsphere/rooms/room110.o \
	madsv2/dragonsphere/rooms/room111.o \
	madsv2/dragonsphere/rooms/room112.o \
	madsv2/dragonsphere/rooms/room113.o \
	madsv2/dragonsphere/rooms/room114.o \
	madsv2/dragonsphere/rooms/room115.o \
	madsv2/dragonsphere/rooms/room116.o \
	madsv2/dragonsphere/rooms/room117.o \
	madsv2/dragonsphere/rooms/room118.o \
	madsv2/dragonsphere/rooms/room119.o \
	madsv2/dragonsphere/rooms/room201.o \
	madsv2/dragonsphere/rooms/room203.o \
	madsv2/dragonsphere/rooms/room204.o \
	madsv2/dragonsphere/rooms/room205.o \
	madsv2/dragonsphere/rooms/room206.o \
	madsv2/dragonsphere/rooms/room301.o \
	madsv2/dragonsphere/rooms/room302.o \
	madsv2/dragonsphere/rooms/room303.o \
	madsv2/dragonsphere/rooms/room401.o \
	madsv2/dragonsphere/rooms/room402.o \
	madsv2/dragonsphere/rooms/room403.o \
	madsv2/dragonsphere/rooms/room404.o \
	madsv2/dragonsphere/rooms/room405.o \
	madsv2/dragonsphere/rooms/room406.o \
	madsv2/dragonsphere/rooms/room407.o \
	madsv2/dragonsphere/rooms/room408.o \
	madsv2/dragonsphere/rooms/room409.o \
	madsv2/dragonsphere/rooms/room410.o \
	madsv2/dragonsphere/rooms/room411.o \
	madsv2/dragonsphere/rooms/room412.o \
	madsv2/dragonsphere/rooms/room454.o \
	madsv2/dragonsphere/rooms/room501.o \
	madsv2/dragonsphere/rooms/room502.o \
	madsv2/dragonsphere/rooms/room503.o \
	madsv2/dragonsphere/rooms/room504.o \
	madsv2/dragonsphere/rooms/room505.o \
	madsv2/dragonsphere/rooms/room506.o \
	madsv2/dragonsphere/rooms/room507.o \
	madsv2/dragonsphere/rooms/room508.o \
	madsv2/dragonsphere/rooms/room509.o \
	madsv2/dragonsphere/rooms/room510.o \
	madsv2/dragonsphere/rooms/room511.o \
	madsv2/dragonsphere/rooms/room512.o \
	madsv2/dragonsphere/rooms/room557.o \
	madsv2/dragonsphere/rooms/room601.o \
	madsv2/dragonsphere/rooms/room603.o \
	madsv2/dragonsphere/rooms/room604.o \
	madsv2/dragonsphere/rooms/room605.o \
	madsv2/dragonsphere/rooms/room606.o \
	madsv2/dragonsphere/rooms/room607.o \
	madsv2/dragonsphere/rooms/room609.o \
	madsv2/dragonsphere/rooms/room612.o \
	madsv2/dragonsphere/rooms/room613.o \
	madsv2/dragonsphere/rooms/room614.o \
	madsv2/dragonsphere/rooms/room909.o \
	madsv2/dragonsphere/dragonsphere.o \
	madsv2/dragonsphere/asound.o \
	madsv2/dragonsphere/global.o \
	madsv2/dragonsphere/main.o \
	madsv2/dragonsphere/main_menu.o \
	madsv2/dragonsphere/menus.o \
	madsv2/dragonsphere/sound_dragonsphere.o \
	madsv2/forest/forest.o
endif

# This module can be built as a plugin
ifeq ($(ENABLE_MADS), DYNAMIC_PLUGIN)
PLUGIN := 1
endif

# Include common rules
include $(srcdir)/rules.mk

# Detection objects
DETECT_OBJS += $(MODULE)/detection.o
