{ STR_COPYRIGHT_1995, STR_LANG_ANY, "(C) 1995 Optik Software. All rights reserved." },
{ STR_COPYRIGHT_1994, STR_LANG_ANY, "(C) 1994 PENDULO STUDIOS. All rights reserved." },
{ STR_BOTTLE_OF_WHISKY, STR_LANG_ENG, " bottle of whisky" },
{ STR_EMPTY_BOTTLE, STR_LANG_ENG, " empty bottle" },
{ STR_BOTTLE_OF_WATER, STR_LANG_ENG, " bottle of water" },
{ STR_LIZARD, STR_LANG_ENG, " lizard" },
{ STR_FAT_LIZARD, STR_LANG_ENG, " fat lizard" },
{ STR_CAROLINE_FOLDER, STR_LANG_ENG, " Caroline%s folder" },
{ STR_PHILIP_FOLDER, STR_LANG_ENG, " Philip%s folder" },
{ STR_STATUETTE, STR_LANG_ENG, " statuette" },
{ STR_REWARD, STR_LANG_ENG, " reward" },

{ STR_IGOR_OBJECTIVE_UIKOKAHONIA, STR_LANG_ENG, "\"Igor. Objective Uikokahonia\"" },
{ STR_SHAREWARE_VERSION, STR_LANG_ENG, "Shareware version" },
{ STR_SHAREWARE_PLACE_ORDER, STR_LANG_ENG, "To place an order: 1-800-OPTIK-99" },

{ STR_SHAREWARE_TEXT1, STR_LANG_ENG, "This is SHAREWARE!" },
{ STR_SHAREWARE_TEXT2, STR_LANG_ENG, "You can copy this version!" },
{ STR_SHAREWARE_TEXT3, STR_LANG_ENG, "Pass it around, give it to your friends, family," },
{ STR_SHAREWARE_TEXT4, STR_LANG_ENG, "colleagues and upload it to your favorite BBS." },
{ STR_SHAREWARE_TEXT5, STR_LANG_ENG, "Let everyone enjoy IGOR!" },

{ STR_SHAREWARE_ORDER_1, STR_LANG_ENG, "Order the full IGOR game for only $34.99 US." },
{ STR_SHAREWARE_ORDER_2, STR_LANG_ENG, "$5.00 for shipping and handling (US & CANADA)." },
{ STR_SHAREWARE_ORDER_3, STR_LANG_ENG, "Please add $3.00 for international shipping." },
{ STR_SHAREWARE_ORDER_4, STR_LANG_ENG, "To place an order: 1-800-OPTIK-99" },

{ STR_SHAREWARE_SHIPPING_1, STR_LANG_ENG, "90 day limited warranty." },
{ STR_SHAREWARE_SHIPPING_2, STR_LANG_ENG, "Please allow 2-4 days for delivery (US only)." },
{ STR_SHAREWARE_SHIPPING_3, STR_LANG_ENG, "Elsewhere, up to a week or two..." },
{ STR_SHAREWARE_SHIPPING_4, STR_LANG_ENG, "Overnight/second day shipping available an" },
{ STR_SHAREWARE_SHIPPING_5, STR_LANG_ENG, "aditional change. Please call for exact pricing." },
{ STR_SHAREWARE_SHIPPING_6, STR_LANG_ENG, "Three easy ways to order:" },
{ STR_SHAREWARE_SHIPPING_7, STR_LANG_ENG, "- Call 1-800-678-4599 (orders only) and use" },
{ STR_SHAREWARE_SHIPPING_8, STR_LANG_ENG, "Your Visa, Mastercard or Discover card." },
{ STR_SHAREWARE_SHIPPING_9, STR_LANG_ENG, "- Fax your order (please include credit card" },
{ STR_SHAREWARE_SHIPPING_10, STR_LANG_ENG, "information) to (412) 381-1031" },

{ STR_SHAREWARE_OPTIK_ADDRESS_1, STR_LANG_ENG, "- Mail a check or money order to:" },
{ STR_SHAREWARE_OPTIK_ADDRESS_2, STR_LANG_ENG, "Optik Software Inc." },
{ STR_SHAREWARE_OPTIK_ADDRESS_3, STR_LANG_ENG, "1000 Napor Boulevard" },
{ STR_SHAREWARE_OPTIK_ADDRESS_4, STR_LANG_ENG, "Pittsburgh, PA. 15205" },
{ STR_SHAREWARE_OPTIK_ADDRESS_5, STR_LANG_ENG, "USA" },
{ STR_SHAREWARE_OPTIK_ADDRESS_6, STR_LANG_ENG, "Optik Software Inc." },
{ STR_SHAREWARE_OPTIK_ADDRESS_7, STR_LANG_ENG, "Orders only: 1-800-OPTIK-99 (67845-99)" },
{ STR_SHAREWARE_OPTIK_ADDRESS_8, STR_LANG_ENG, "Fax: (412) 381-1031" },
{ STR_SHAREWARE_OPTIK_ADDRESS_9, STR_LANG_ENG, "E-mail: optiksoft\xFA""aol.com" },

{ STR_SHAREWARE_PENDULO_ADDRESS_1, STR_LANG_ENG, "A game by" },
{ STR_SHAREWARE_PENDULO_ADDRESS_2, STR_LANG_ENG, "PENDULO STUDIOS" },
{ STR_SHAREWARE_PENDULO_ADDRESS_3, STR_LANG_ENG, "P.O. Box 21091" },
{ STR_SHAREWARE_PENDULO_ADDRESS_4, STR_LANG_ENG, "28009 Madrid" },
{ STR_SHAREWARE_PENDULO_ADDRESS_5, STR_LANG_ENG, "Spain" },
{ STR_SHAREWARE_PENDULO_ADDRESS_6, STR_LANG_ENG, "E-mail: 100641.1737\xFA""compuserve.com" },
