/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef MADS_FOREST_MADS_WORDS_H
#define MADS_FOREST_MADS_WORDS_H

#include "common/scummsys.h"

namespace MADS {
namespace MADSV2 {
namespace Forest {

enum {
	words_game                 =   1,
	words_qsave                =   2,
	words_look                 =   3,
	words_take                 =   4,
	words_push                 =   5,
	words_open                 =   6,
	words_put                  =   7,
	words_talk_to              =   8,
	words_give                 =   9,
	words_pull                 =  10,
	words_close                =  11,
	words_throw                =  12,
	words_walk_to              =  13,
	words_room_101             =  15,
	words_room_104             =  16,
	words_room_106             =  17,
	words_room_107             =  18,
	words_room_110             =  19,
	words_room_150             =  20,
	words_room_201             =  21,
	words_room_202             =  22,
	words_room_203             =  23,
	words_room_204             =  24,
	words_room_205             =  25,
	words_room_209             =  26,
	words_room_210             =  27,
	words_room_210h            =  28,
	words_room_211             =  29,
	words_room_220             =  30,
	words_room_221             =  31,
	words_room_250             =  32,
	words_room_251             =  33,
	words_room_301             =  34,
	words_room_302             =  35,
	words_room_303             =  36,
	words_room_304             =  37,
	words_room_305             =  38,
	words_room_306             =  39,
	words_room_307             =  40,
	words_room_308             =  41,
	words_room_320             =  42,
	words_room_321             =  43,
	words_room_322             =  44,
	words_room_350             =  45,
	words_room_401             =  46,
	words_room_402             =  47,
	words_room_403             =  48,
	words_room_404             =  49,
	words_room_405             =  50,
	words_room_406             =  51,
	words_room_410             =  52,
	words_room_420             =  53,
	words_room_450             =  54,
	words_room_501             =  55,
	words_room_502             =  56,
	words_room_503             =  57,
	words_room_509             =  58,
	words_room_510             =  59,
	words_room_511             =  60,
	words_room_520             =  61,
	words_room_521             =  62,
	words_room_550             =  63,
	words_owl_tree             =  64,
	words_abi_bubble           =  65,
	words_all_bubble           =  66,
	words_attack               =  67,
	words_bedroom              =  68,
	words_bird_figurine        =  69,
	words_birdcall             =  70,
	words_book                 =  71,
	words_bookcase             =  72,
	words_books                =  73,
	words_bookshelf            =  74,
	words_bush                 =  75,
	words_carve_up             =  76,
	words_chicory              =  77,
	words_click_on             =  78,
	words_cliff                =  79,
	words_climb_down           =  80,
	words_climb_up             =  81,
	words_comfrey              =  82,
	words_dandelion            =  83,
	words_door                 =  84,
	words_door_1               =  85,
	words_door_2               =  86,
	words_door_3               =  87,
	words_door_4               =  88,
	words_door_5               =  89,
	words_down_page            =  90,
	words_eat                  =  91,
	words_edge_of_cliff        =  92,
	words_elm_leaves           =  93,
	words_exit_journal         =  94,
	words_eyebright            =  95,
	words_feather              =  96,
	words_five                 =  97,
	words_floor                =  98,
	words_flowers              =  99,
	words_forest               = 100,
	words_forked_stick         = 101,
	words_four                 = 102,
	words_foxglove             = 103,
	words_frog                 = 104,
	words_gears                = 105,
	words_ground               = 106,
	words_hole                 = 107,
	words_invoke               = 108,
	words_ivy_leaf             = 109,
	words_journal              = 110,
	words_laboratory           = 111,
	words_leaves               = 112,
	words_lily_pad             = 113,
	words_look_at              = 114,
	words_make_noise           = 115,
	words_map                  = 116,
	words_marsh                = 117,
	words_mint                 = 118,
	words_moss                 = 119,
	words_mushroom             = 120,
	words_needle               = 121,
	words_nothing              = 122,
	words_one                  = 123,
	words_overhanging_grass    = 124,
	words_pebbles              = 125,
	words_pick_up              = 126,
	words_plant                = 127,
	words_polish               = 128,
	words_pond                 = 129,
	words_poster               = 130,
	words_primrose             = 131,
	words_reeds                = 132,
	words_river                = 133,
	words_rocks                = 134,
	words_rope                 = 135,
	words_rub                  = 136,
	words_rubber_band          = 137,
	words_sanctuary_woods      = 138,
	words_shieldstone          = 139,
	words_signet_ring          = 140,
	words_six                  = 141,
	words_snapdragon           = 142,
	words_spider_silk          = 143,
	words_stairs               = 144,
	words_sticks               = 145,
	words_sunflower            = 146,
	words_sword                = 147,
	words_table                = 148,
	words_telescope            = 149,
	words_thistle              = 150,
	words_three                = 151,
	words_thrust               = 152,
	words_tie                  = 153,
	words_twine                = 154,
	words_two                  = 155,
	words_up_page              = 156,
	words_use                  = 157,
	words_vine_weed            = 158,
	words_walk                 = 159,
	words_walk_down            = 160,
	words_wear                 = 161,
	words_weasel               = 162,
	words_web                  = 163,
	words_wood                 = 164,
	words_woods                = 165,
	words_wrench               = 166,
	words_y_stick              = 167,
	words_abigail              = 168,
	words_edgar                = 169,
	words_russel               = 170,
	words_snapdragon2          = 171,
	words_lungwort             = 172,
	words_grass                = 173,
	words_fwt                  = 174,
	words_dragon1              = 175,
	words_dragon2              = 176,
	words_nest                 = 177,
	words_paint_can            = 178,
	words_dam                  = 179,
	words_brown                = 180,
	words_turtle               = 181,
	words_dragonfly            = 182,
	words_fenwick              = 183,
	words_blue_bird            = 184,
	words_black_bird           = 185,
	words_lever                = 186,
	words_rock                 = 187,
	words_used_it              = 188,
	words_tail                 = 189
};

} // namespace Forest
} // namespace MADSV2
} // namespace MADS

#endif
