begin_section("AGI");
	add_person("Stuart George", "darkfiber", "");
	add_person("Matthew Hoops", "clone2727", "(retired)");
	add_person("Filippos Karapetis", "bluegr", "");
	add_person("Martin Kiewitz", "m_kiewitz", "");
	add_person("Pawe&#322; Ko&#322;odziejski", "aquadran", "");
	add_person("Walter van Niftrik", "waltervn", "");
	add_person("Kari Salminen", "Buddha^", "");
	add_person("Eugene Sandulenko", "sev", "");
	add_person("David Symonds", "dsymonds", "(retired)");
end_section();
