#line 2 "engines/director/lingo/lingo-lex.cpp"

#line 4 "engines/director/lingo/lingo-lex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[365] =
    {   0,
        0,    0,   77,   75,    4,   73,   73,   75,   75,   75,
       72,   72,   72,   71,   72,   68,   72,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   75,    3,    3,   69,    4,   73,
        0,    0,    0,   74,    5,   67,    2,   70,   71,   66,
       64,   65,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   22,   13,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   35,   36,   69,   38,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   57,   69,
       69,   69,    1,    3,    3,    0,   69,    5,    2,   70,

       69,    7,   69,   69,   69,   69,   69,   69,   16,   69,
       69,    0,   69,   69,   69,   69,   69,   69,   69,   31,
       69,   69,   34,   69,   69,   69,   69,   44,   69,   46,
       69,   69,   69,   69,   69,   69,   69,   69,   69,    0,
       69,   69,   69,    9,   69,   11,   12,   15,    0,   18,
       69,    0,   69,   69,   25,   26,   27,   28,   69,   69,
       69,   33,   37,   40,   69,   69,   69,   69,   69,   69,
       49,    0,   56,   61,   69,   59,   63,    0,   69,    6,
       69,   69,    0,   16,   69,   21,   69,   69,   29,   69,
       32,    0,   69,   69,   69,   69,   69,   69,   69,   55,

       55,   55,   55,   62,   69,    0,   69,    8,   69,    0,
       16,   19,    0,   69,   69,   69,    0,   69,   69,   69,
       45,    0,   69,   58,   48,    0,    0,   55,   55,   55,
       60,    0,   69,   69,   14,    0,   69,   69,    0,   30,
        0,   69,   69,   69,    0,    0,    0,    0,   69,   69,
       69,   69,    0,    0,    0,    0,   55,   55,   55,    0,
       17,   10,    0,   23,   69,   30,   30,    0,   69,   42,
       43,    0,    0,    0,    0,   69,   69,   69,   69,    0,
        0,    0,   55,   55,   55,   17,    0,   69,   30,    0,
       41,    0,    0,    0,    0,   69,   69,   69,   69,    0,

        0,    0,   55,    0,   55,    0,   24,   39,    0,    0,
        0,   47,   69,   69,   69,   47,   54,   53,   54,   55,
        0,    0,    0,   20,   47,    0,    0,    0,   47,   69,
       69,   69,   53,    0,    0,    0,    0,   47,    0,    0,
       47,   69,   69,    0,    0,   50,   51,   47,    0,   47,
       69,    0,   51,   47,   47,    0,   53,    0,   53,    0,
        0,   52,   52,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    9,    1,    8,
        8,    8,   10,    8,   11,   12,    8,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    8,    1,   14,
       15,   16,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   26,
        8,    1,    8,    8,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   26,   26,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   26,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   65,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    2,    3,    3,    2,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1
    } ;

static yyconst flex_int16_t yy_base[381] =
    {   0,
        0,   64,  642,  908,   68,  908,  908,   72,  625,    0,
      908,  617,  581,   55,   63,  908,  535,   59,   59,   59,
       55,   63,    0,   64,   75,   70,  100,   77,  110,  102,
       98,  139,  126,  152,   83,  184,  205,  458,  209,  908,
      213,  145,  482,  908,    0,  908,    0,  430,  139,  908,
      908,  908,    0,   66,  116,  136,  149,   74,  166,  106,
      151,  153,  125,   91,    0,  165,  176,  139,  151,  201,
      191,  201,  188,  194,    0,    0,  209,    0,  215,  212,
      200,  205,  202,  203,  207,  226,  214,  223,    0,  246,
      213,  223,  908,  279,  283,  333,  324,    0,    0,  234,

      233,    0,  243,  242,  241,  256,  260,  269,  289,  258,
      277,  296,  268,  286,  276,  287,  274,  277,  287,    0,
      287,  279,    0,  289,  279,  284,  291,    0,  303,    0,
      294,  300,  302,  312,  349,  312,  325,  332,  337,  190,
      166,  320,  327,    0,  341,    0,    0,  304,  359,    0,
      345,  336,  350,  336,    0,    0,    0,    0,  340,  341,
      351,    0,    0,  383,  348,  353,  362,  360,  351,  354,
        0,  401,    0,    0,  370,  371,    0,  131,  130,    0,
      380,  382,  406,    0,  382,  410,  388,  384,    0,  394,
        0,  418,  400,  392,  391,  392,  423,  415,  395,  445,

      447,  458,  462,    0,  416,  119,   88,    0,  441,  444,
        0,    0,  471,  452,  453,  473,  444,  461,  448,  450,
        0,  514,  569,    0,    0,  493,  467,  487,  520,  519,
        0,   42,   20,  469,  908,  477,  460,  497,  432,    0,
      500,  510,  477,  480,  513,  515,  516,  516,  527,  520,
      528,  524,  563,  543,  549,  551,  579,  585,  597,   18,
        0,    0,  563,    0,  547,    0,    0,  558,  567,    0,
        0,  578,  578,  592,  581,  582,  594,  598,  589,  586,
      561,  597,  645,  636,  646,  908,  601,  596,    0,  616,
        0,  618,  637,  620,  630,  629,  643,  629,  639,  644,

      666,  651,  672,  676,  693,  654,    0,  908,  658,  677,
      666,  908,  678,  684,  679,    0,  908,    0,  908,  710,
      714,  686,  720,  908,  908,  657,  681,  693,    0,  694,
      692,  707,    0,  740,  734,  746,  715,  908,  714,  726,
        0,  719,  729,  756,  724,  761,  762,  908,  738,    0,
      751,  785,  786,  908,    0,  787,  791,  773,  800,  753,
      761,  908,  908,  908,  841,  843,  846,  849,  855,  860,
      865,  867,  872,  877,  880,  883,  888,  891,  896,  901
    } ;

static yyconst flex_int16_t yy_def[381] =
    {   0,
      364,    1,  364,  364,  364,  364,  364,  364,  365,  366,
      364,  364,  364,  364,  364,  364,  364,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  364,  364,  364,  367,  364,  364,
      364,  364,  365,  364,  368,  364,  369,  364,  364,  364,
      364,  364,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  364,  364,  364,  364,  367,  368,  369,  364,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  364,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  364,
      367,  367,  367,  367,  367,  367,  367,  367,  370,  367,
      367,  364,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  371,  367,  367,  367,  367,  367,  364,  367,  367,
      367,  367,  364,  372,  367,  364,  367,  367,  367,  367,
      367,  364,  367,  367,  367,  367,  367,  367,  367,  371,

      371,  371,  371,  367,  367,  364,  367,  367,  367,  364,
      372,  367,  364,  367,  367,  373,  364,  367,  367,  367,
      367,  364,  367,  367,  367,  364,  364,  371,  371,  371,
      367,  364,  367,  367,  364,  364,  367,  367,  374,  375,
      364,  367,  367,  367,  364,  364,  364,  364,  367,  367,
      367,  367,  364,  364,  364,  364,  371,  371,  371,  364,
      367,  367,  364,  367,  367,  376,  375,  364,  367,  367,
      367,  364,  364,  364,  364,  367,  367,  367,  367,  364,
      364,  364,  371,  371,  371,  364,  364,  367,  376,  364,
      367,  364,  364,  364,  364,  367,  367,  367,  367,  364,

      377,  364,  371,  364,  371,  364,  367,  364,  364,  364,
      364,  364,  367,  367,  367,  367,  364,  378,  364,  371,
      364,  364,  364,  364,  364,  364,  364,  364,  367,  367,
      367,  367,  378,  364,  364,  364,  364,  364,  364,  364,
      367,  367,  367,  364,  364,  377,  364,  364,  364,  367,
      367,  364,  377,  364,  367,  379,  380,  364,  380,  364,
      364,  364,  364,    0,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364
    } ;

static yyconst flex_int16_t yy_nxt[974] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   11,
       13,    4,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   23,   25,   23,   26,   27,   28,   29,
       30,   23,   31,   32,   33,   23,   23,   34,   23,   23,
       23,   18,   19,   20,   21,   22,   23,   24,   23,   25,
       26,   27,   28,   29,   30,   23,   31,   32,   33,   23,
       23,   34,   23,   23,   35,   36,   48,   49,   37,   39,
       40,   40,   41,   41,   40,   40,   41,   50,   51,   56,
       54,  286,   57,  261,   59,   93,   93,   55,   58,   60,
       63,   61,  112,   64,   68,  112,   65,   73,  260,   69,

      101,   62,  105,   66,   56,   54,   74,   57,   59,   67,
       38,   55,   58,   60,   63,   61,   70,   64,   82,   68,
       71,   65,   73,   69,  101,   62,  105,   66,   79,   72,
       74,   75,   42,   67,   80,  102,   42,   81,   76,  108,
       77,   70,   78,   82,  233,   71,   87,   93,   93,   88,
       48,   49,   79,   72,  111,   89,   75,  103,   80,   83,
      102,   81,   76,  108,   77,  104,   78,  116,   84,   85,
      109,   87,  232,   86,   88,   90,   91,  110,  111,   89,
      117,   92,  103,  207,   83,   94,   40,   40,   95,  206,
      104,  116,   84,   85,  106,  109,  115,   86,  113,  114,

       90,   91,  110,  107,  117,   92,   95,   40,   40,   95,
       39,   40,   40,   41,   41,   40,   40,   41,  106,  118,
      120,  115,  113,  114,  179,  119,  122,  107,  123,  124,
       96,  125,  126,  178,  128,  129,  130,  121,  131,  132,
      134,  127,  133,  135,  118,  120,  100,  138,   42,  119,
      122,   96,  123,  142,  124,  139,  125,  126,  128,  129,
      130,  121,  131,  132,  134,  127,  136,  133,  135,   42,
      137,  138,  143,   42,  144,  145,  146,   42,  142,  139,
       94,   40,   40,   95,   95,   40,   40,   95,  147,  148,
      149,  136,  150,  149,  151,  137,  143,  112,  144,  145,

      112,  146,  153,  156,  158,  183,  154,  157,  183,  159,
      160,  161,  147,  162,  148,  155,  150,  163,  164,  151,
      165,  166,  168,  167,  169,   96,  153,  156,  158,   96,
      152,  154,  157,  159,  170,  160,  161,  162,  171,  155,
      174,  163,  164,   42,  165,  166,  168,   42,  167,  169,
      172,  175,  180,  172,  152,  176,  177,  182,  170,  181,
      149,  185,  171,  149,  174,  186,  187,  141,  188,  189,
      190,  191,  194,  195,  140,  175,  180,  173,  196,  197,
      176,  177,  182,  181,  192,  198,  185,  192,  199,  186,
      204,  187,  188,  189,  190,  205,  191,  194,  195,  193,

      208,  173,  172,  196,  197,  172,  209,  183,  212,  198,
      183,  213,  199,  216,  213,  204,  214,  215,  218,  192,
      205,  219,  192,  220,  193,  208,  221,  222,  225,  201,
      210,  209,  212,  239,  202,  224,  239,  203,  216,  217,
      214,  215,  100,  218,  231,  219,  226,  220,  226,  226,
      221,  226,  225,  201,  227,  210,  227,  223,  202,  226,
      224,  203,  226,  226,  217,  235,  226,  227,  231,  234,
      237,  227,  213,  238,  239,  213,  241,  239,  230,  242,
      264,  223,  228,  243,  244,   53,  254,   44,  226,  229,
      235,  226,  236,  234,  253,  237,  227,  253,  238,   97,

      241,  256,  262,  230,  242,  264,  228,  243,  244,  263,
      270,  254,  254,  229,  257,  265,  268,  236,  222,  271,
      226,  226,  255,  226,  226,  256,  262,  256,  227,  227,
      269,  273,  245,  263,  270,  246,  277,  254,  257,  272,
      265,  268,  274,  271,  247,  259,  255,  248,  222,   52,
      275,  256,  258,  276,  278,  269,  273,  245,  279,  280,
      246,  277,  301,  272,  253,  301,  274,  253,  247,  259,
      281,  248,  222,  222,  275,  282,  258,  276,  278,  287,
      226,  288,  279,  226,  280,  290,  226,  249,  227,  226,
      250,   47,  255,  291,  227,  281,  283,  293,  226,  251,

      282,  226,  252,  223,  287,  288,  227,  292,  294,  290,
      295,  296,  249,  297,  298,  250,  255,  291,  299,  284,
      300,  283,  293,  251,  302,   46,  252,  223,  306,  307,
       44,  292,  285,  294,  295,  296,  308,  304,  297,  298,
      304,  364,  299,  284,  300,  227,  226,  226,  302,  226,
      226,  309,  306,  307,  227,  227,  285,  310,  364,  311,
      312,  308,  313,  314,  317,  303,  305,  301,  315,  316,
      301,  319,  364,  226,  324,  309,  226,  321,  325,  364,
      321,  227,  310,  311,  312,  338,  313,  328,  314,  317,
      303,  305,  315,  316,  323,  254,  319,  323,  329,  324,

      332,  326,  227,  325,  320,  322,  327,  335,  330,  338,
      256,  334,  328,  331,  334,  321,  339,  340,  321,  227,
      254,  336,  341,  329,  336,  332,  326,  342,  320,  322,
      327,  343,  335,  330,  256,  346,  347,  331,  346,  254,
      339,  344,  340,  322,  344,  352,  341,  336,  348,  337,
      336,  342,  349,  350,  256,  351,  343,  344,  354,  254,
      344,  347,  346,  353,  254,  346,  353,  322,  364,  345,
      352,  355,  348,  337,  256,  337,  349,  350,  256,  351,
      364,  362,  363,  354,  254,  345,  356,  353,  356,  356,
      353,  356,  358,  345,  364,  358,  355,  360,  256,  337,

      364,  358,  361,  333,  358,  362,  364,  363,  364,  345,
      364,  364,  333,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  360,  364,  364,  364,  361,  318,  364,  364,
      364,  333,  364,  364,  364,  364,  364,  364,  364,  364,
      333,   43,   43,  364,   43,   43,   43,   45,   45,   53,
       53,   53,   98,   98,   98,   99,   99,  364,   99,   99,
       99,  184,  364,  364,  184,  184,  200,  364,  364,  200,
      211,  211,  211,  240,  364,  240,  240,  240,  266,  364,
      364,  266,  266,  267,  267,  267,  289,  289,  289,  318,
      364,  364,  318,  318,  333,  333,  333,  357,  364,  364,

      357,  357,  359,  364,  359,  359,  359,    3,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364
    } ;

static yyconst flex_int16_t yy_chk[974] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,   14,   14,    2,    5,
        5,    5,    5,    8,    8,    8,    8,   15,   15,   19,
       18,  260,   20,  233,   21,   35,   35,   18,   20,   22,
       24,   22,   64,   24,   26,   64,   25,   28,  232,   26,

       54,   22,   58,   25,   19,   18,   28,   20,   21,   25,
        2,   18,   20,   22,   24,   22,   27,   24,   31,   26,
       27,   25,   28,   26,   54,   22,   58,   25,   30,   27,
       28,   29,    5,   25,   30,   55,    8,   30,   29,   60,
       29,   27,   29,   31,  207,   27,   33,   42,   42,   33,
       49,   49,   30,   27,   63,   33,   29,   56,   30,   32,
       55,   30,   29,   60,   29,   57,   29,   68,   32,   32,
       61,   33,  206,   32,   33,   34,   34,   62,   63,   33,
       69,   34,   56,  179,   32,   36,   36,   36,   36,  178,
       57,   68,   32,   32,   59,   61,   67,   32,   66,   66,

       34,   34,   62,   59,   69,   34,   37,   37,   37,   37,
       39,   39,   39,   39,   41,   41,   41,   41,   59,   70,
       72,   67,   66,   66,  141,   71,   73,   59,   74,   77,
       36,   79,   80,  140,   81,   82,   83,   72,   84,   85,
       87,   80,   86,   88,   70,   72,  100,   91,   36,   71,
       73,   37,   74,  101,   77,   92,   79,   80,   81,   82,
       83,   72,   84,   85,   87,   80,   90,   86,   88,   37,
       90,   91,  103,   39,  104,  105,  106,   41,  101,   92,
       94,   94,   94,   94,   95,   95,   95,   95,  107,  108,
      109,   90,  110,  109,  111,   90,  103,  112,  104,  105,

      112,  106,  113,  115,  117,  148,  114,  116,  148,  118,
      119,  121,  107,  122,  108,  114,  110,  124,  125,  111,
      126,  127,  131,  129,  132,   94,  113,  115,  117,   95,
      112,  114,  116,  118,  133,  119,  121,  122,  134,  114,
      136,  124,  125,   94,  126,  127,  131,   95,  129,  132,
      135,  137,  142,  135,  112,  138,  139,  145,  133,  143,
      149,  151,  134,  149,  136,  152,  153,   97,  154,  159,
      160,  161,  165,  166,   96,  137,  142,  135,  167,  168,
      138,  139,  145,  143,  164,  169,  151,  164,  170,  152,
      175,  153,  154,  159,  160,  176,  161,  165,  166,  164,

      181,  135,  172,  167,  168,  172,  182,  183,  185,  169,
      183,  186,  170,  190,  186,  175,  187,  188,  193,  192,
      176,  194,  192,  195,  164,  181,  196,  197,  199,  172,
      183,  182,  185,  239,  172,  198,  239,  172,  190,  192,
      187,  188,   48,  193,  205,  194,  200,  195,  201,  200,
      196,  201,  199,  172,  200,  183,  201,  197,  172,  202,
      198,  172,  202,  203,  192,  210,  203,  202,  205,  209,
      214,  203,  213,  215,  216,  213,  217,  216,  203,  218,
      237,  197,  201,  219,  220,  216,  227,   43,  228,  202,
      210,  228,  213,  209,  226,  214,  228,  226,  215,   38,

      217,  227,  234,  203,  218,  237,  201,  219,  220,  236,
      243,  227,  226,  202,  228,  238,  241,  213,  222,  244,
      230,  229,  226,  230,  229,  227,  234,  226,  230,  229,
      242,  246,  222,  236,  243,  222,  250,  226,  228,  245,
      238,  241,  247,  244,  222,  230,  226,  222,  222,   17,
      248,  226,  229,  249,  251,  242,  246,  222,  252,  254,
      222,  250,  281,  245,  253,  281,  247,  253,  222,  230,
      255,  222,  222,  223,  248,  256,  229,  249,  251,  263,
      257,  265,  252,  257,  254,  268,  258,  223,  257,  258,
      223,   13,  253,  269,  258,  255,  257,  273,  259,  223,

      256,  259,  223,  223,  263,  265,  259,  272,  274,  268,
      275,  276,  223,  277,  278,  223,  253,  269,  279,  258,
      280,  257,  273,  223,  282,   12,  223,  223,  287,  288,
        9,  272,  259,  274,  275,  276,  290,  284,  277,  278,
      284,    3,  279,  258,  280,  284,  283,  285,  282,  283,
      285,  292,  287,  288,  283,  285,  259,  293,    0,  294,
      295,  290,  296,  297,  300,  283,  285,  301,  298,  299,
      301,  302,    0,  303,  306,  292,  303,  304,  309,    0,
      304,  303,  293,  294,  295,  326,  296,  311,  297,  300,
      283,  285,  298,  299,  305,  304,  302,  305,  313,  306,

      315,  310,  305,  309,  303,  304,  310,  322,  314,  326,
      304,  320,  311,  314,  320,  321,  327,  328,  321,  320,
      304,  323,  330,  313,  323,  315,  310,  331,  303,  304,
      310,  332,  322,  314,  304,  335,  337,  314,  335,  323,
      327,  334,  328,  321,  334,  345,  330,  336,  339,  323,
      336,  331,  340,  342,  323,  343,  332,  344,  349,  334,
      344,  337,  346,  347,  323,  346,  347,  321,    0,  334,
      345,  351,  339,  323,  334,  336,  340,  342,  323,  343,
        0,  360,  361,  349,  334,  344,  352,  353,  356,  352,
      353,  356,  357,  334,    0,  357,  351,  358,  334,  336,

        0,  359,  358,  357,  359,  360,    0,  361,    0,  344,
        0,    0,  359,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  358,    0,    0,    0,  358,  356,    0,    0,
        0,  357,    0,    0,    0,    0,    0,    0,    0,    0,
      359,  365,  365,    0,  365,  365,  365,  366,  366,  367,
      367,  367,  368,  368,  368,  369,  369,    0,  369,  369,
      369,  370,    0,    0,  370,  370,  371,    0,    0,  371,
      372,  372,  372,  373,    0,  373,  373,  373,  374,    0,
        0,  374,  374,  375,  375,  375,  376,  376,  376,  377,
        0,    0,  377,  377,  378,  378,  378,  379,    0,    0,

      379,  379,  380,    0,  380,  380,  380,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "engines/director/lingo/lingo-lex.l"
/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */
#define YY_NO_INPUT 1
#line 29 "engines/director/lingo/lingo-lex.l"

#define YY_NO_UNISTD_H
#define FORBIDDEN_SYMBOL_ALLOW_ALL

#include "common/str.h"

#include "director/director.h"
#include "director/lingo/lingo.h"
#include "director/lingo/lingo-gr.h"
#include "director/lingo/lingo-the.h"

using namespace Director;

int yyparse();

static void count() {
	if (debugChannelSet(-1, kDebugLingoParse))
		debug("LEXER: Read '%s' at %d:%d", yytext, g_lingo->_linenumber, g_lingo->_colnumber);

	char *p = yytext;

	while (*p && *p != '\n' && *p != '\r') {
		p++;
		g_lingo->_colnumber++;
	}

	while (*p == '\n' || *p == '\r') {
		if (*p == '\n') {
			g_lingo->_linenumber++;
			g_lingo->_colnumber = 0;
		}

		p++;
	}

	g_lingo->_colnumber = strlen(p);
}

static int checkImmediate(int token) {
	if (g_lingo->_immediateMode) {
		yylval.s = new Common::String(yytext);

		return ID;
	}

	return token;
}

#line 862 "engines/director/lingo/lingo-lex.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 87 "engines/director/lingo/lingo-lex.l"


#line 1048 "engines/director/lingo/lingo-lex.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 365 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 364 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 89 "engines/director/lingo/lingo-lex.l"
{ count(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 90 "engines/director/lingo/lingo-lex.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 91 "engines/director/lingo/lingo-lex.l"
{ count(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "engines/director/lingo/lingo-lex.l"
{ count(); return ' '; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 94 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.s = new Common::String(yytext); return SYMBOL; }	// D3
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 96 "engines/director/lingo/lingo-lex.l"
{ count(); return tAFTER; }		// D3
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "engines/director/lingo/lingo-lex.l"
{ count(); return tAND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 98 "engines/director/lingo/lingo-lex.l"
{ count(); return tBEFORE; }	// D3
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "engines/director/lingo/lingo-lex.l"
{ count(); return tCHAR; }		// D3
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "engines/director/lingo/lingo-lex.l"
{ count(); return tCONTAINS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "engines/director/lingo/lingo-lex.l"
{ count(); return tDONE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "engines/director/lingo/lingo-lex.l"
{ count(); return tDOWN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "engines/director/lingo/lingo-lex.l"
{ count(); return tIF; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "engines/director/lingo/lingo-lex.l"
{ count(); return tELSIF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 105 "engines/director/lingo/lingo-lex.l"
{ count(); return tELSE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 106 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[4]; // Skip 'end '
		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		if (!scumm_stricmp(ptr, "if"))
			return tENDIF;
		else if (!scumm_stricmp(ptr, "repeat"))
			return tENDREPEAT;
		else if (!scumm_stricmp(ptr, "tell"))
			return tENDTELL;

		yylval.s = new Common::String(ptr);

		return ENDCLAUSE;
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "engines/director/lingo/lingo-lex.l"
{ count(); return tFACTORY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 125 "engines/director/lingo/lingo-lex.l"
{ count(); return tEXIT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "engines/director/lingo/lingo-lex.l"
{ count(); return tGLOBAL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 127 "engines/director/lingo/lingo-lex.l"
{ count(); return tGO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "engines/director/lingo/lingo-lex.l"
{ count(); return tGO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 129 "engines/director/lingo/lingo-lex.l"
{ count(); return tGO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 130 "engines/director/lingo/lingo-lex.l"
{ count(); return tINSTANCE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 131 "engines/director/lingo/lingo-lex.l"
{ count(); return tINTERSECTS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 132 "engines/director/lingo/lingo-lex.l"
{ count(); return tINTO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 133 "engines/director/lingo/lingo-lex.l"
{ count(); return tITEM; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 134 "engines/director/lingo/lingo-lex.l"
{ count(); return tLINE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 135 "engines/director/lingo/lingo-lex.l"
{ count(); return checkImmediate(tLOOP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 136 "engines/director/lingo/lingo-lex.l"
{ count(); return tMACRO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[6]; // Skip 'method '
		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		yylval.s = new Common::String(ptr);

		return tMETHOD;
	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "engines/director/lingo/lingo-lex.l"
{ count(); return tMOD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 149 "engines/director/lingo/lingo-lex.l"
{ count(); return tMOVIE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 150 "engines/director/lingo/lingo-lex.l"
{ count(); return tNEXT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 151 "engines/director/lingo/lingo-lex.l"
{ count(); return tNOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 152 "engines/director/lingo/lingo-lex.l"
{ count(); return tOF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 153 "engines/director/lingo/lingo-lex.l"
{ count(); return tON; }		// D3
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "engines/director/lingo/lingo-lex.l"
{ count(); return tOPEN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 155 "engines/director/lingo/lingo-lex.l"
{ count(); return tOR; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 156 "engines/director/lingo/lingo-lex.l"
{ count(); return tPLAY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 157 "engines/director/lingo/lingo-lex.l"
{ count(); return tPLAY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.s = new Common::String(yytext); return tPLAYACCEL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 159 "engines/director/lingo/lingo-lex.l"
{ count(); return tPREVIOUS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 160 "engines/director/lingo/lingo-lex.l"
{ count(); return tPROPERTY; }	// D4
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 161 "engines/director/lingo/lingo-lex.l"
{ count(); return tPUT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 162 "engines/director/lingo/lingo-lex.l"
{ count(); return checkImmediate(tREPEAT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 163 "engines/director/lingo/lingo-lex.l"
{ count(); return tSET; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 164 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[6]; // Skip 'sound '
		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		Common::String command;
		while (*ptr != ' ' && *ptr != '\t')
			command += *ptr++;

		Common::String bltin = Common::String::format("sound-%s", command.c_str());

		if (g_lingo->_builtins.contains(bltin)) {
			yylval.s = new Common::String(bltin);
			return BLTIN;
		} else {
			error("LEXER: Unhandled 'sound %s'", command.c_str());
		}
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 184 "engines/director/lingo/lingo-lex.l"
{ count(); return tSTARTS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 185 "engines/director/lingo/lingo-lex.l"
{ count(); return tTELL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 186 "engines/director/lingo/lingo-lex.l"
{
		count();

		yylval.e[0] = g_lingo->_theEntities["sqrt"]->entity;
		yylval.e[1] = 0;	// No field

		return THEENTITYWITHID;
	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 194 "engines/director/lingo/lingo-lex.l"
{
		count();

		yylval.s = new Common::String("value");

		return FBLTIN;
	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 201 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[4]; // Skip 'the '
		while (*ptr == ' ' || *ptr == '\t') ptr++;

		ptr += 6; // skip 'number '
		while (*ptr == ' ' || *ptr == '\t') ptr++;

		ptr += 3; // Skip 'of '
		while (*ptr == ' ' || *ptr == '\t') ptr++;

		Common::String field;
		while (*ptr != ' ' && *ptr != '\t')
			field += *ptr++;

		yylval.s = new Common::String(Common::String::format("numberOf%s", field.c_str()));

		if (g_lingo->_builtins.contains(*yylval.s))
			return FBLTIN;
		else
			error("LEXER: Unhandled chunk expression '%s'", yylval.s->c_str());
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 224 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[4]; // Skip 'the '
		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		Common::String field;
		while (*ptr != ' ' && *ptr != '\t')
			field += *ptr++;

		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		ptr += 3; // Skip 'of '

		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		if (g_lingo->_theEntities.contains(ptr)) {
			field = Common::String::format("%d%s", g_lingo->_theEntities[ptr]->entity, field.c_str());

			if (!g_lingo->_theEntityFields.contains(field)) {
				error("LEXER: Unhandled the field %s", ptr);
			}

			if (g_lingo->_theEntityFields[field]->entity != g_lingo->_theEntities[ptr]->entity)
				error("LEXER: Unsupported field '%s' for entity '%s'", field.c_str(), ptr);

			yylval.e[0] = g_lingo->_theEntities[ptr]->entity;
			yylval.e[1] = g_lingo->_theEntityFields[field]->field;

			if (g_lingo->_theEntities[ptr]->hasId)
				return THEENTITYWITHID;
			else
				return THEENTITY;
		} else {
			if (g_director->getVersion() >= 4) {
				field = Common::String::format("%d%s", g_lingo->_objectEntityId, field.c_str());

				if (!g_lingo->_theEntityFields.contains(field)) {
					error("LEXER: Unhandled the field '%s' for object", field.c_str());
				}

				yylval.objectfield.os = new Common::String(ptr);
				yylval.objectfield.oe = g_lingo->_theEntityFields[field]->field;

				return THEOBJECTFIELD;
			}
		}

		warning("LEXER: Unhandled the entity '%s', field '%s'", ptr, field.c_str());
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 277 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[4]; // Skip 'the '
		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		Common::String field;
		while (*ptr != ' ' && *ptr != '\t')
			field += *ptr++;

		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		field = Common::String::format("%d%s", g_lingo->_theEntities[ptr]->entity, field.c_str());

		if (!g_lingo->_theEntityFields.contains(field)) {
			error("LEXER: Unhandled the field %s", ptr);
		}

		if (g_lingo->_theEntityFields[field]->entity != g_lingo->_theEntities[ptr]->entity)
			error("LEXER: Unsupported field '%s' for entity '%s'", field.c_str(), ptr);

		yylval.e[0] = g_lingo->_theEntities[ptr]->entity;
		yylval.e[1] = g_lingo->_theEntityFields[field]->field;

		if (g_lingo->_theEntities[ptr]->hasId)
			return THEENTITYWITHID;
		else
			return THEENTITY;
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 308 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[4]; // Skip 'the '
		while (*ptr == ' ' || *ptr == '\t')
			ptr++;

		if (g_lingo->_theEntities.contains(ptr)) {
			yylval.e[0] = g_lingo->_theEntities[ptr]->entity;
			yylval.e[1] = 0;	// No field

			if (g_lingo->_theEntities[ptr]->hasId)
				return THEENTITYWITHID;
			else
				return THEENTITY;
		}

		warning("LEXER: Unhandled the entity '%s'", ptr);
	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 327 "engines/director/lingo/lingo-lex.l"
{ count(); return tTHEN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 328 "engines/director/lingo/lingo-lex.l"
{ count(); return tTO; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 329 "engines/director/lingo/lingo-lex.l"
{ count(); return tSPRITE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 330 "engines/director/lingo/lingo-lex.l"
{ count(); return tWITH; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 331 "engines/director/lingo/lingo-lex.l"
{ count(); return tWITHIN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 332 "engines/director/lingo/lingo-lex.l"
{ count(); return tWHEN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 333 "engines/director/lingo/lingo-lex.l"
{ count(); return tWHILE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 334 "engines/director/lingo/lingo-lex.l"
{ count(); return tWORD; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 336 "engines/director/lingo/lingo-lex.l"
{ count(); return tNEQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 337 "engines/director/lingo/lingo-lex.l"
{ count(); return tGE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 338 "engines/director/lingo/lingo-lex.l"
{ count(); return tLE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 339 "engines/director/lingo/lingo-lex.l"
{ count(); return tCONCAT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 340 "engines/director/lingo/lingo-lex.l"
{ count(); return tEQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 342 "engines/director/lingo/lingo-lex.l"
{
		count();
		yylval.s = new Common::String(yytext);

		if (g_lingo->_ignoreMe && yylval.s->equalsIgnoreCase("me"))
			return ID;

		// When we are defining arguments, allow any string
		if (g_lingo->_indef == kStateInArgs)
			return ID;

		// First of all, match against argument list
		if (g_lingo->_indef == kStateInDef)
			if (g_lingo->isInArgStack(yylval.s))
				return ID;

		if (g_lingo->_builtins.contains(yytext)) {
			int type = g_lingo->_builtins[yytext]->type;
			if ((type == BLTIN || type == FBLTIN || type == RBLTIN) && g_lingo->_builtins[yytext]->parens == false) {
				if (type == RBLTIN) {
					if (g_lingo->_builtins[yytext]->nargs != 1 || g_lingo->_builtins[yytext]->maxArgs != 1)
						error("Incorrectly set RBLTIN %s", yytext);

					return RBLTIN;
				}

				return type;
			}
		}

		return ID;
	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 374 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.f = atof(yytext); return FLOAT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 375 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.i = strtol(yytext, NULL, 10); return INT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 376 "engines/director/lingo/lingo-lex.l"
{ count(); return *yytext; }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 377 "engines/director/lingo/lingo-lex.l"
{ count(); return '\n'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 378 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.s = new Common::String(&yytext[1]); yylval.s->deleteLastChar(); return STRING; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 379 "engines/director/lingo/lingo-lex.l"
{ count(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 381 "engines/director/lingo/lingo-lex.l"
ECHO;
	YY_BREAK
#line 1722 "engines/director/lingo/lingo-lex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 365 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 365 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 364);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 381 "engines/director/lingo/lingo-lex.l"



extern int yydebug;

namespace Director {

int Lingo::parse(const char *code) {
	YY_BUFFER_STATE bp;

	if (debugChannelSet(-1, kDebugLingoParse))
		yydebug = 1;
	else
		yydebug = 0;

	yy_delete_buffer(YY_CURRENT_BUFFER);

	bp = yy_scan_string(code);
	yy_switch_to_buffer(bp);
	yyparse();
	yy_delete_buffer(bp);

	return 0;
}

} // End of namespace Director

