#!/bin/sh

if [ ! -e debian/rules ] ; then
	echo "Run from the top-level source directory as debian/prepare"
	exit 1
fi

if [ -d CVS/ ] && [ $1 != "--nocvs" ]; then
	TODATE=`date +%Y%m%d`
	NEXT_VERSION=`grep SCUMMVM_VERSION scumm.h | sed 's,\#define\ SCUMMVM_VERSION\ \",,gi' | sed 's,\ devel\",,gi'`
	cat debian/changelog.cvs | sed s/@VERSION@/$NEXT_VERSION.cvs$TODATE/g \
	> debian/changelog.tmp && mv debian/changelog.tmp debian/changelog
	exit 0
else
	if [ x$USER = xhadess ]; then
		cp debian/changelog.debian_official debian/changelog
	else
		cp debian/changelog.debian debian/changelog
	fi
fi
