#!/bin/sh
set -e
here=$(dirname "$0")

# Build both ABIs first
for CROSS_HOST in aarch64-linux-android armv7a-linux-androideabi; do (
	echo ">>> Building libresidualvm.so for $CROSS_HOST"
	. "$here"/android-set-environment
	DEPENDENCIES=$(pwd)/dependencies/$CROSS_HOST
	mkdir -p build-${ANDROID_ABI}
	cd build-${ANDROID_ABI}
	../configure --enable-all-engines --enable-static --enable-opengl-shaders --with-jpeg-prefix=$DEPENDENCIES --with-freetype2-prefix=$DEPENDENCIES --host=${ANDROID_TARGET}
	make libresidualvm.so
) || exit 1 ; done

echo ">>> Creating final APK"
# Now copy the ARMv7 one into the ARM64 tree and build the final package from there
ln -s build-arm64-v8a build
install -C -D -m 644 build-armeabi-v7a/libresidualvm.so build/android/jni/armeabi-v7a/libresidualvm.so
TERM=dumb make -C build androidrelease ABI=arm64-v8a
