#!/bin/sh
set -e
here=$(dirname "$0")

if [ -n "$ANDROID_KEYSTORE_KEY" ]; then
	echo ">>> Decrypting Android keystore"
	openssl aes-256-cbc -k "$ANDROID_KEYSTORE_KEY" -in .travis/android.keystore.enc -out /tmp/android.keystore -d -md sha1
	export KEYSTORE=/tmp/android.keystore
	unset ANDROID_KEYSTORE_KEY
fi

# Build both ABIs first
for CROSS_HOST in aarch64-linux-android armv7a-linux-androideabi; do (
	echo ">>> Building libresidualvm.so for $CROSS_HOST"
	. "$here"/android-set-environment
	DEPENDENCIES=$(pwd)/dependencies/$CROSS_HOST
	mkdir -p build-${ANDROID_ABI}
	cd build-${ANDROID_ABI}
	../configure --enable-all-engines --enable-static --enable-opengl-shaders --with-jpeg-prefix=$DEPENDENCIES --with-freetype2-prefix=$DEPENDENCIES --host=${ANDROID_TARGET}
	make libresidualvm.so
) || exit 1 ; done

echo ">>> Creating final APK"
# Now copy the ARMv7 one into the ARM64 tree and build the final package from there
[ ! -d build ] && ln -s build-arm64-v8a build
export ANDROID_VERSIONCODE=$((40000 + ${TRAVIS_BUILD_NUMBER:-0}))
mkdir -p build/android/jni/armeabi-v7a
install -C -m 644 build-armeabi-v7a/libresidualvm.so build/android/jni/armeabi-v7a/libresidualvm.so
TERM=dumb make -C build androidrelease ABI=arm64-v8a
