/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#include "sky/ibasstext.h"
#include "common/array.h"

namespace Sky {

const char *const ukAscii[] = {
	"The Firedoor is locked – how do I open it?",
	"I do wish that Joey was with me – what should I do?",
	"How do I get that elevator working?",
	"How do I get down the elevator shaft?",
	"How do I get out of the furnace room?",
	"I need to de-activate the welder robot. Help!",
	"How do I get the welder shell for Joey?",
	"How can I get into the storeroom?",
	"How can I stop things I get from the storeroom being confiscated?",
	"How can I get rid of the man in the power room?",
	"How can I restore power?",
	"How can I use that elevator?",
	"How do I get a ticket from the travel agent?",
	"What should I do with this ticket?",
	"Lamb has my ticket – what now?",
	"How do I get into the surgery?",
	"How do I get a Schriebmann port?",
	"How can I get that anchor?",
	"I’ve got the anchor – what now?",
	"What do I do with this grappling hook?",
	"I’m in the security HQ. What next?",
	"I’m stuck in the LINC world – what should I do?",
	"I’m in a cyber maze – how do I get through it?",
	"I’m through the cyber maze – what now?",
	"How do I get out of LINC space?",
	"I’ve got to ground level. What should I do now?",
	"How do I get those dog biscuits?",
	"How do I get past the security man?",
	"I’m in the cathedral – what now?",
	"Anita’s been murdered. What should I do?",
	"I’ve got Anita’s card – maybe she left some clues?",
	"I’ve read Anita’s message – how do I make contact with Eduardo?",
	"I’ve made contact with Eduardo. What now?",
	"I’ve got Colston’s glass, but why?",
	"How do get through to the subway?",
	"I’ve made a hole in the grill – how do I enlarge the hole?",
	"I’ve made a hole in the grill – what now?",
	"There’s a creature that grabs me – how can I avoid it?",
	"How do I get through the big metal door?",
	"There’s a strange pit – what do I do with it?",
	"What do I do in this strange underworld?",
	"How can we get past the android in the lab?",
	"I killed the android. What next?",
	"Anita mentioned a virus – how do I get it?",
	"I'm back in LINC – how do I get the virus?",
	"Poor old Joey – how do I get resurrect him? Again!",
	"I’ve turned Joey into an android. What I do with him?",
	"I’ve got the virus from LINC – how do I get it into the real world?",
	"I’ve got some infected tissue – what now?",
	"I’ve met my own father – how do I save humanity?",
	"I've out-foxed the guard - what now?",
	"I'm in an industrial area. What should I do?",
	"I've found some putty-like substance - but what now?",
	"I've given myself special security status on LINC - now what?",
	"User interface and game controls – help!",
	"Inventory Instructions",
	"First screen walkthrough",
	// Hint answers
	"Get the rung from the top of the stairs on the left of the gantry.",
	"Open your inventory and use the rung on the fire door to lever it open. See the 'First Screen Walkthrough' for detailed explanation.",
	"Examine the junk in the foreground to reveal the robot shell.",
	"Use the circuit board on the robot shell.",
	"Examine the transport droid.",
	"Talk to Hobbins until you get option to ask him about the transport droid – and he tells you what’s wrong with it.",
	"Ask Joey to start the transport droid (you may need to talk nicely to him about a range of subjects beforehand).",
	"When the elevator descends, quickly climb down the shaft.",
	"Examine the lock on the door.",
	"When joey arrives, ask him to open the door.",
	"You need to ‘throw a wrench in the works’.",
	"Did you find the wrench in Hobbins’s workshop? If not, then return to Hobbins’s workshop, open the cupboard and take the wrench.",
	"Return to the production line – in the room beyond the welder robot you will see some gears.",
	"If you haven’t done so, talk to Anita and then Lamb until he leaves. Then throw the wrench into the gears.",
	"Retrieve the wrench from the cogs.",
	"Use the wrench on the welder robot.",
	"Talk to Joey, and offer him a new shell.",
	"Attempt to enter the storeroom.",
	"Tell Joey to check out the storeroom. When he reports that he has found the fusebox, tell him to disable the fuse box.",
	"Lift the gangway on the floor.",
	"Pick up the putty (plastic explosive) which was under the gangway. This is the only object that you can keep after leaving.",
	"Use the wrench on each of the two buttons beneath the pipes on the right.",
	"Tell Joey to press the right hand button, then press the other as he does so.",
	"Turn off the switch on the control panel on the left.",
	"Remove the light bulb.",
	"Put the putty in the light fitting.",
	"Turn the switch back on.",
	"Pull the right hand power switch down to restore power to the lift.",
	"Examine Reich’s corpse in the furnace room to get his ID.",
	"Use Reich’s ID card on the lift slot.",
	"Go to Reich’s apartment and lift the pillow to reveal a motorbiking magazine.",
	"Go to the travel agent and ask him about the tours.",
	"Ask for the economy tour.",
	"Give him the motorbiking magazine in return for a tour ticket.",
	"Give the ticket to Lamb to be invited on a tour of the pipe factory.",
	"Ask Lamb about the tour – he will leave when he sees that the conveyor has stopped.",
	"Talk to Anita.",
	"She will eventually offer you a “jammer” – give her Reich’s ID.",
	"Talk further to learn about the Schriebmann port.",
	"Talk to the surgery receptionist by clicking on the projector.",
	"Ask for a Schriebmann port.",
	"Ask Joey to talk to the receptionist to gain admittance to the surgery.",
	"Talk to Burke until you get an offer to fit a Schriebmann port.",
	"After the operation, keep talking to Burke to learn about Anchor’s “special policy”.",
	"Visit Anchor in the insurance office and mention Burke’s name to get him out of the room.",
	"Ask Joey to get the anchor from the statue.",
	"Pick up the anchor after Joey has melted the statue’s arm.",
	"If you don’t have it, now would be a good time to get the cable hanging from the Industrial level.",
	"Ask Joey to cut the loose cable - get out of his way.",
	"Retrieve the cable which has fallen onto the Belle Vue level.",
	"Use the anchor on the cable to create a grappling hook.",
	"Go to the fire door in Hobbins's recycling plant and walk out on the ledge.",
	"Use the grappling hook on the security sign on the opposite wall.",
	"In the Security HQ, use the ID card on the slot and sit down.",
	"Pick up the ball (compressed data) in area 1.",
	"Go right to area 2 and use open (in inventory) on the carpet bag.",
	"Get the birthday surprise (decompress). Use decompress on compressed data (in inventory).",
	"Get magnifying glass (decrypt) and use it on report.doc and briefing.doc (in inventory).",
	"Use green password on lower row / left tile. Use red password on lower row / centre tile.",
	"Pick up the green password and use on middle row / left tile.",
	"Pick up the red password and use on central tile.",
	"Pick up the green password and use on lower row / right tile.",
	"Get book (phoenix.doc).",
	"Use decrypt on phoenix.doc.",
	"Get bust (phoenix program).",
	"Disconnect from LINC.",
	"Use ID card on LINC terminal.",
	"Select “Security services”. Select “view documents”",
	"Read each document. Note that they need to have been decrypted in LINC space.",
	"Select “special operations”. Select “special status request”.",
	"Select “file adjustment” to D-LINC Lamb.",
	"Talk to Henri, the bouncer, to find out about sponsorship for the club.",
	"Talk to Danielle to be invited back to her apartment.",
	"Go back to Danielle’s Apartment.",
	"You will need the cat video from Lamb’s apartment.",
	"D-LINC Lamb from “file adjustment” on the LINC terminal, and then talk to him.",
	"While Danielle is on the phone, play the video.",
	"While the dog is distracted, get the dog biscuits.",
	"Go to the see-saw by the lake and use the dog biscuits on the plank.",
	"When the dog is nearby, pull the rope.",
	"When the dog gets onto the plank, release the rope.",
	"Explore the lockers in the lower level - until you discover the terrible truth.",
	"Return to the reactor in the factory and put on the radiation suit.",
	"Go to the terminal and open the reactor. Inside, pick up Anita’s ID card.",
	"Go back through the Security building.",
	"Enter LINC using Anita’s card.",
	"Use “blind” on the eyeball in area 2.",
	"Use “playback” on the holographic projector (“well”) to view Anita’s message.",
	"Disconnect from LINC.",
	"Return to Hyde Park.",
	"Talk to Vincent to find out about the gardener.",
	"Talk to the gardener until he tells you about the virus.",
	"Walk into the courtroom to witness Hobbins’s trial.",
	"Go to the club.",
	"Select “You search, but find nothing” on jukebox.",
	"Get Colston’s glass while he is away from the table.",
	"Give the glass to Burke to get fingerprints.",
	"Touch the plate to open the door to the wine cellar.",
	"Use the crowbar on the large box on the left.",
	"Get the lid and use it on the smaller box.",
	"Climb on top of the box.",
	"Use the crowbar on the grill.",
	"If you haven’t found the secateurs then go to the shed in the park.",
	"Look at the door.",
	"Use the ID card on the lock.",
	"Enter the shed and get the secateurs.",
	"Use the secateurs on the grill.",
	"Climb through the grill.",
	"Use the light bulb on the light socket to the left of the creature’s hole.",
	"Use the crowbar on the crumbling plaster, then again on the brickwork to obtain a brick.",
	"-",
	"Use the crowbar on the clot in the vein.",
	"Use the brick on the crowbar to puncture the clot.",
	"Wait until the medical robot comes to repair the puncture, then exit through the door to the right.",
	"Close the cover over the pit using the terminal beside the pit.",
	"Climb on top of the pit cover.",
	"Pull the retaining bar on the grill above your head to loosen the grill.",
	"Return to the room above.",
	"Look through the grills to warn of any impending danger.",
	"Look through the first grill that you encounter.",
	"Walk right to the room where the medical robot is recharging.",
	"Use the circuit board on the medical robot.",
	"Talk to Joey and send him into the tank room.",
	"Ask Joey what he saw in the tank room.",
	"Ask Joey about the tank.",
	"Tell Joey to open the tap.",
	"Enter the tank room and watch the android plunge to his death.",
	"Walk to the right of the tanks, into the computer room.",
	"Use Reich’s ID card on the terminal (to the left of the bank of computers).",
	"Open the access door.",
	"Leave the computer room and watch Joey get destroyed again.",
	"Take Gallagher’s card from his remains.",
	"Return to the computer room.",
	"Enter LINC using Gallagher’s card.",
	"You need to enter LINC using Gallagher’s card. Drop out, then return again.",
	"Use blind on the eyeball in area 1. Quickly go to area 2 and blind the eyeball.",
	"Get the oscillator (tuning fork).",
	"Go to the Crusader room. Use “divine wrath” to remove the Crusader.",
	"Enter the crystal room. Use the oscillator on the crystal.",
	"Get the virus. Disconnect from LINC.",
	"Go to the special android room. Open the cabinet on the middle console.",
	"Insert the circuit board in the cabinet.",
	"Use the monitor to download the data from the board.",
	"Run the android start-up program.",
	"Go right to the room with the large tanks.",
	"Ask Joey/Ken to put his hand on the door panel.",
	"Put your own hand on the other panel.",
	"Go to the tank of tissue samples and get the tongs from the wall (just to right of tank).",
	"Use Gallagher’s card (or whichever card contains the virus) on the console to infect the tissue with the virus.",
	"Remove a sample of infected tissue with the tongs.",
	"Put the sample of tissue into the nitrogen tank to freeze it.",
	"Go to the end of the pipes. Attach the cable to the pipe support.",
	"Use the rungs to descend to the feeding orifice.",
	"Drop the infected tissue into the orifice.",
	"Use the hanging rope to swing into the final room.",
	"When Joey/Ken enters tell him to sit in the chair.",
	"Explore the factory. Perhaps you'll be able to get Joey working again.",
	"Take a look around - there must be someone around who can help.",
	"Explore some more - there's sure to be more to find.",
	"Take the elevator down to the level below, and then take the next elevator down to ground level.",
	"Moving around the environment",
	"Tap a point on the floor area and Foster will walk there - if he can. To leave an area, you will need to interact with the exit arrow icon.",
	"Interacting with the environment",
	"Slide your finger around the game screen to find areas of interest (hotspots). Animating blue circles will appear over hotspots as your finger gets close to them. Slide your finger over the blue circle and action icons will be displayed to indicate what actions Foster can perform. To perform that action, lift your finger and tap the specific icon.",
	"DUMMY LINE",
	"The inventory – what is it?",
	"Items that Foster picks up go into the ‘inventory’. Tap the box icon to display the items in the inventory. Tap an item to get a description of it.",
	"How to use an inventory item on background objects and people",
	"Open the inventory and press on an item for a few moments until it appears above your finger. While continuing to press the screen, drag the item over a hotspot and release when it highlights with a blue outline.",
	"Combining inventory items",
	"Sometimes you will need to combine two inventory items to create a third item. To do this, select the first item by pressing on it for a few moments until it appears above your finger. Now drag the item straight onto the second item – release when both are highlighted with a blue outline.",
	"Walkthrough for getting Foster to open the fire-door",
	"Slide your finger over the rung that is to the far left of the screen. A blue circle will animate over the rung as you get close. When your finger is over the rung, two icons will appear – turning cogs (interact) and a blinking eye (examine), and the word 'Rung' will appear at the top of the screen. Lift your finger and tap the cogs. The cogs will flash, and Foster will walk to the rung and pull it off. He will automatically put the rung into his inventory - where it will appear as 'Metal Bar.'",
	"LINE DELETED",
	"Open the inventory by tapping on the box icon. Press on the metal bar icon until it is displayed above your finger with a blue outline, then drag it across to the fire door until your finger is over the blue circle and 'Door' is displayed at the top of the screen, then lift your finger. Foster will now use the metal bar to lever open the fire door. Foster will then automatically walk out. Good luck!",
	"?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?",
	"Hint %d of %d"
};

const uint kUkAsciiCount = ARRAYSIZE(ukAscii);

}
