#!/bin/sh

echo -------------------------[Depreciation warning]--------------------------------
echo Using \'sciv\' to start FreeSCI is deprecated and will not be supported in future
echo versions of FreeSCI. Instead, use the \'freesci\' binary.
echo -------------------------------------------------------------------------------
sleep 3

freesci $@

echo -------------------------[Depreciation warning]--------------------------------
echo Using \'sciv\' to start FreeSCI is deprecated and will not be supported in future
echo versions of FreeSCI. Instead, use the \'freesci\' binary.
echo -------------------------------------------------------------------------------

