begin_section("Grim");
	add_person("James Brown", "ender", "Grim (retired)");
	add_person("Giulio Camuffo", "giucam", "Grim (retired)");
	add_person("Daniel Schepler", "", "Initial engine contributor");
	add_person("Dries Harnie", "Botje", "EMI");
	add_person("Pawe&#322; Ko&#322;odziejski", "aquadran", "Grim");
	add_person("Christian Krause", "chkr", "EMI (retired)");
	add_person("Einar Johan T. S&oslash;m&aring;en", "somaen", "Grim, EMI");
	add_person("Joel Teichroeb", "klusark", "EMI");
	add_person("Joni V&auml;h&auml;m&auml;ki", "Akz", "EMI (retired)");
end_section();
