/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _alpha_blend_v_h_
#define _alpha_blend_v_h_
//---------------------------------------------------------------------------------
extern const unsigned char alpha_blend_v[];
extern const int alpha_blend_v_size;
//---------------------------------------------------------------------------------
#endif //_alpha_blend_v_h_
//---------------------------------------------------------------------------------
