/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _sharp_bilinear_v_h_
#define _sharp_bilinear_v_h_
//---------------------------------------------------------------------------------
extern const unsigned char sharp_bilinear_v[];
extern const int sharp_bilinear_v_size;
//---------------------------------------------------------------------------------
#endif //_sharp_bilinear_v_h_
//---------------------------------------------------------------------------------
