/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _texture_tint_f_h_
#define _texture_tint_f_h_
//---------------------------------------------------------------------------------
extern const unsigned char texture_tint_f[];
extern const int texture_tint_f_size;
//---------------------------------------------------------------------------------
#endif //_texture_tint_f_h_
//---------------------------------------------------------------------------------
