MODULE := engines/ultima8

MODULE_OBJS := \
	metaengine.o \
	ultima8.o \
	audio/audio_channel.o \
	audio/audio_mixer.o \
	audio/audio_process.o \
	audio/audio_sample.o \
	audio/midi_player.o \
	audio/music_flex.o \
	audio/music_process.o \
	audio/cru_music_process.o \
	audio/raw_audio_sample.o \
	audio/sonarc_audio_sample.o \
	audio/sound_flex.o \
	audio/speech_flex.o \
	audio/u8_music_process.o \
	conf/config_file_manager.o \
	convert/convert_shape.o \
	convert/u8/convert_shape_u8.o \
	convert/crusader/convert_shape_crusader.o \
	filesys/archive.o \
	filesys/archive_file.o \
	filesys/file_system.o \
	filesys/flex_file.o \
	filesys/raw_archive.o \
	filesys/savegame.o \
	filesys/u8_save_file.o \
	games/cru_game.o \
	games/game.o \
	games/game_data.o \
	games/game_info.o \
	games/start_crusader_process.o \
	games/start_u8_process.o \
	games/treasure_loader.o \
	games/u8_game.o \
	graphics/anim_dat.o \
	graphics/avi_player.o \
	graphics/cycle_process.o \
	graphics/frame_id.o \
	graphics/fade_to_modal_process.o \
	graphics/gump_shape_archive.o \
	graphics/inverter_process.o \
	graphics/main_shape_archive.o \
	graphics/palette.o \
	graphics/palette_fader_process.o \
	graphics/palette_manager.o \
	graphics/raw_shape_frame.o \
	graphics/render_surface.o \
	graphics/shape.o \
	graphics/shape_archive.o \
	graphics/shape_frame.o \
	graphics/shape_info.o \
	graphics/skf_player.o \
	graphics/type_flags.o \
	graphics/wpn_ovlay_dat.o \
	graphics/xform_blend.o \
	graphics/fonts/font.o \
	graphics/fonts/font_manager.o \
	graphics/fonts/font_shape_archive.o \
	graphics/fonts/jp_font.o \
	graphics/fonts/jp_rendered_text.o \
	graphics/fonts/rendered_text.o \
	graphics/fonts/shape_font.o \
	graphics/fonts/shape_rendered_text.o \
	graphics/fonts/ttf_rendered_text.o \
	graphics/fonts/tt_font.o \
	gumps/ask_gump.o \
	gumps/bark_gump.o \
	gumps/book_gump.o \
	gumps/computer_gump.o \
	gumps/container_gump.o \
	gumps/credits_gump.o \
	gumps/cru_ammo_gump.o \
	gumps/cru_credits_gump.o \
	gumps/cru_demo_gump.o \
	gumps/cru_energy_gump.o \
	gumps/cru_health_gump.o \
	gumps/cru_inventory_gump.o \
	gumps/cru_menu_gump.o \
	gumps/cru_pickup_area_gump.o \
	gumps/cru_pickup_gump.o \
	gumps/cru_stat_gump.o \
	gumps/cru_status_gump.o \
	gumps/cru_weapon_gump.o \
	gumps/desktop_gump.o \
	gumps/difficulty_gump.o \
	gumps/fast_area_vis_gump.o \
	gumps/game_map_gump.o \
	gumps/gump.o \
	gumps/gump_notify_process.o \
	gumps/inverter_gump.o \
	gumps/item_relative_gump.o \
	gumps/keypad_gump.o \
	gumps/main_menu_process.o \
	gumps/menu_gump.o \
	gumps/message_box_gump.o \
	gumps/minimap_gump.o \
	gumps/mini_stats_gump.o \
	gumps/modal_gump.o \
	gumps/movie_gump.o \
	gumps/paged_gump.o \
	gumps/paperdoll_gump.o \
	gumps/quit_gump.o \
	gumps/readable_gump.o \
	gumps/resizable_gump.o \
	gumps/scroll_gump.o \
	gumps/shape_viewer_gump.o \
	gumps/slider_gump.o \
	gumps/target_gump.o \
	gumps/translucent_gump.o \
	gumps/u8_save_gump.o \
	gumps/weasel_dat.o \
	gumps/weasel_gump.o \
	gumps/widgets/button_widget.o \
	gumps/widgets/edit_widget.o \
	gumps/widgets/sliding_widget.o \
	gumps/widgets/text_widget.o \
	kernel/delay_process.o \
	kernel/kernel.o \
	kernel/mouse.o \
	kernel/object.o \
	kernel/object_manager.o \
	kernel/process.o \
	misc/debugger.o \
	misc/encoding.o \
	misc/id_man.o \
	misc/util.o \
	std/string.o \
	usecode/bit_set.o \
	usecode/byte_set.o \
	usecode/uc_list.o \
	usecode/uc_machine.o \
	usecode/uc_process.o \
	usecode/uc_stack.o \
	usecode/usecode.o \
	usecode/usecode_flex.o \
	world/bobo_boomer_process.o \
	world/camera_process.o \
	world/container.o \
	world/create_item_process.o \
	world/crosshair_process.o \
	world/current_map.o \
	world/damage_info.o \
	world/destroy_item_process.o \
	world/egg.o \
	world/egg_hatcher_process.o \
	world/fireball_process.o \
	world/fire_type.o \
	world/fire_type_table.o \
	world/get_object.o \
	world/glob_egg.o \
	world/gravity_process.o \
	world/item.o \
	world/item_factory.o \
	world/item_selection_process.o \
	world/item_sorter.o \
	world/map.o \
	world/map_glob.o \
	world/minimap.o \
	world/missile_tracker.o \
	world/monster_egg.o \
	world/snap_process.o \
	world/sort_item.o \
	world/split_item_process.o \
	world/sprite_process.o \
	world/super_sprite_process.o \
	world/target_reticle_process.o \
	world/teleport_egg.o \
	world/world.o \
	world/actors/actor.o \
	world/actors/actor_anim_process.o \
	world/actors/actor_bark_notify_process.o \
	world/actors/ambush_process.o \
	world/actors/animation.o \
	world/actors/animation_tracker.o \
	world/actors/anim_action.o \
	world/actors/attack_process.o \
	world/actors/auto_firer_process.o \
	world/actors/avatar_death_process.o \
	world/actors/avatar_gravity_process.o \
	world/actors/avatar_mover_process.o \
	world/actors/battery_charger_process.o \
	world/actors/clear_feign_death_process.o \
	world/actors/cru_avatar_mover_process.o \
	world/actors/cru_healer_process.o \
	world/actors/cru_pathfinder_process.o \
	world/actors/combat_dat.o \
	world/actors/combat_process.o \
	world/actors/grant_peace_process.o \
	world/actors/guard_process.o \
	world/actors/heal_process.o \
	world/actors/loiter_process.o \
	world/actors/main_actor.o \
	world/actors/npc_dat.o \
	world/actors/pace_process.o \
	world/actors/pathfinder.o \
	world/actors/pathfinder_process.o \
	world/actors/quick_avatar_mover_process.o \
	world/actors/resurrection_process.o \
	world/actors/rolling_thunder_process.o \
	world/actors/scheduler_process.o \
	world/actors/surrender_process.o \
	world/actors/targeted_anim_process.o \
	world/actors/teleport_to_egg_process.o \
	world/actors/u8_avatar_mover_process.o

# This module can be built as a plugin
ifeq ($(ENABLE_ULTIMA8), DYNAMIC_PLUGIN)
PLUGIN := 1
endif

# Include common rules
include $(srcdir)/rules.mk

# Detection objects
DETECT_OBJS += $(MODULE)/detection.o
