MODULE := engines/ultima8

MODULE_OBJS := \
	detection.o \
	ultima8.o \
	conf/config_file_manager.o \
	conf/ini_file.o \
	conf/setting_manager.o \
	convert/convert_shape.o \
	convert/u8/convert_shape_u8.o \
	convert/crusader/convert_shape_crusader.o \
	filesys/archive.o \
	filesys/archive_file.o \
	filesys/data.o \
	filesys/dir_file.o \
	filesys/file_system.o \
	filesys/flex_file.o \
	filesys/list_files.o \
	filesys/output_logger.o \
	filesys/raw_archive.o \
	filesys/savegame.o \
	filesys/savegame_writer.o \
	filesys/u8_save_file.o \
	filesys/zip_file.o \
	graphics/texture.o \
	graphics/texture_bitmap.o \
	graphics/texture_png.o \
	graphics/texture_targa.o \
	gumps/ask_gump.o \
	gumps/bark_gump.o \
	gumps/bind_gump.o \
	gumps/book_gump.o \
	gumps/console_gump.o \
	gumps/container_gump.o \
	gumps/controls_gump.o \
	gumps/credits_gump.o \
	gumps/desktop_gump.o \
	gumps/fast_area_vis_gump.o \
	gumps/game_map_gump.o \
	gumps/gump.o \
	gumps/gump_notify_process.o \
	gumps/inverter_gump.o \
	gumps/item_relative_gump.o \
	gumps/main_menu_process.o \
	gumps/menu_gump.o \
	gumps/message_box_gump.o \
	gumps/minimap_gump.o \
	gumps/mini_stats_gump.o \
	gumps/modal_gump.o \
	gumps/movie_gump.o \
	gumps/options_gump.o \
	gumps/paged_gump.o \
	gumps/paperdoll_gump.o \
	gumps/pentagram_menu_gump.o \
	gumps/quit_gump.o \
	gumps/readable_gump.o \
	gumps/resizable_gump.o \
	gumps/scaler_gump.o \
	gumps/scroll_gump.o \
	gumps/shape_viewer_gump.o \
	gumps/slider_gump.o \
	gumps/target_gump.o \
	gumps/u8_save_gump.o \
	gumps/widgets/button_widget.o \
	gumps/widgets/edit_widget.o \
	gumps/widgets/game_widget.o \
	gumps/widgets/sliding_widget.o \
	gumps/widgets/text_widget.o \
	kernel/allocator.o \
	kernel/core_app.o \
	kernel/delay_process.o \
	kernel/gui_app.o \
	kernel/hid_keys.o \
	kernel/hid_manager.o \
	kernel/joystick.o \
	kernel/kernel.o \
	kernel/memory_manager.o \
	kernel/mouse.o \
	kernel/object.o \
	kernel/object_manager.o \
	kernel/pool.o \
	kernel/process.o \
	kernel/segmented_allocator.o \
	kernel/segmented_pool.o \
	misc/args.o \
	misc/console.o \
	misc/encoding.o \
	misc/id_man.o \
	misc/istring.o \
	misc/md5.o \
	misc/pent_include.o \
	misc/util.o \
	misc/version.o \
	std/misc.o \
	std/string.o \
	usecode/bit_set.o \
	usecode/uc_list.o \
	usecode/uc_machine.o \
	usecode/uc_process.o \
	usecode/uc_stack.o \
	usecode/usecode.o \
	usecode/usecode_flex.o \
	world/camera_process.o \
	world/container.o \
	world/create_item_process.o \
	world/current_map.o \
	world/destroy_item_process.o \
	world/egg.o \
	world/egg_hatcher_process.o \
	world/fireball_process.o \
	world/get_object.o \
	world/glob_egg.o \
	world/gravity_process.o \
	world/item.o \
	world/item_factory.o \
	world/item_sorter.o \
	world/map.o \
	world/map_glob.o \
	world/missile_process.o \
	world/missile_tracker.o \
	world/monster_egg.o \
	world/split_item_process.o \
	world/sprite_process.o \
	world/teleport_egg.o \
	world/world.o \
	world/actors/actor.o \
	world/actors/actor_anim_process.o \
	world/actors/actor_bark_notify_process.o \
	world/actors/ambush_process.o \
	world/actors/animation.o \
	world/actors/animation_tracker.o \
	world/actors/anim_action.o \
	world/actors/avatar_death_process.o \
	world/actors/avatar_gravity_process.o \
	world/actors/avatar_mover_process.o \
	world/actors/clear_feign_death_process.o \
	world/actors/combat_process.o \
	world/actors/grant_peace_process.o \
	world/actors/heal_process.o \
	world/actors/loiter_process.o \
	world/actors/main_actor.o \
	world/actors/pathfinder.o \
	world/actors/pathfinder_process.o \
	world/actors/quick_avatar_mover_process.o \
	world/actors/resurrection_process.o \
	world/actors/scheduler_process.o \
	world/actors/targeted_anim_process.o \
	world/actors/teleport_to_egg_process.o \


# This module can be built as a plugin
ifeq ($(ENABLE_ULTIMA8), DYNAMIC_PLUGIN)
PLUGIN := 1
endif

# Include common rules
include $(srcdir)/rules.mk
