.Dd July 20, 2022
.Dt SCUMMVM 6
.Os
.Sh NAME
.Nm scummvm
.Nd graphic adventure game interpreter
.Sh SYNOPSIS
.Nm scummvm
.Op Ar OPTIONS
.Op Ar GAME
.Sh DESCRIPTION
.Nm
is an interpreter that will play graphic adventure games
based on a variety of game engines.
.Pp
.Ar GAME
is a short name of game to load.
For example,
.Em scumm:monkey
for Monkey Island.
This can be either a built-in gameid, or a user configured target.
.Sh OPTIONS
More details for the following options can be
found at
.Lk https://docs.scummvm.org .
.Pp
The meaning of most long options (that is, those options starting with a
double-dash) can be inverted by prefixing them with
.Sy no- .
For example,
.Fl -no-aspect-ratio
will turn aspect ratio correction off.
This is useful if you want to override a setting in the configuration file.
.Bl -tag -width Ds
.It Fl a | -add
Add all games from current or specified directory.
If
.Fl -game= Ns Ar ID
is passed only the game with id
.Ar ID
is added.
See also
.Fl -detect .
Use
.Fl -path= Ns Ar PATH
to specify a directory.
.It Fl b | -boot-param= Ns Ar NUM
Pass number to the boot script (boot param).
.It Fl c | -config= Ns Ar CONFIG
Use alternate configuration file.
.It Fl d | -debuglevel= Ns Ar NUM
Set debug verbosity level.
.It Fl e | -music-driver= Ns Ar MODE
Select music driver:
.Bl -tag -width 10m
.It Ar adlib
Internal AdLib emulation.
.It Ar alsa
Output using ALSA sequencer device.
.It Ar core
CoreAudio sound, for macOS users.
.It Ar coremidi
CoreMIDI sound, for macOS users.
.It Ar fluidsynth
FluidSynth MIDI emulation.
.It Ar mt32
Internal MT-32 emulation.
.It Ar null
Null output.
Don't play any music.
.It Ar pcjr
Internal PCjr emulation.
.It Ar pcspk
Internal PC Speaker emulation.
.It Ar seq
Use /dev/sequencer for MIDI, *nix users.
.It Ar sndio
Use sndio MIDI.
.It Ar timidity
Connect to TiMidity++ MIDI server.
.It Ar towns
Internal FM-TOWNS YM2612 emulation (only usable in SCUMM FM-TOWNS games)
Use only if you have a hardware MIDI synthesizer.
.It Ar windows
Windows built in MIDI sequencer for Windows users.
.El
.It Fl F | -no-fullscreen
Force windowed mode.
.It Fl f | -fullscreen
Force full-screen mode.
.It Fl g | -gfx-mode= Ns Ar MODE
Select graphics mode:
.Po
.Ar opengl ,
.Ar surfacesdl
.Pc
.It Fl h | -help
Display a brief help text and exit.
.It Fl l | -logfile= Ns Ar PATH
Use alternate path for log file.
.It Fl m | -music-volume= Ns Ar NUM
Set the music volume, 0-255 (default: 192).
.It Fl n | -subtitles
Enable subtitles (use with games that have voice).
.It Fl p | -path= Ns Ar PATH
Path to where the game is installed.
.It Fl q | -language= Ns Ar LANG
Select game's language:
.Bl -tag -width auto -compact
.\" Sorted by English name of language
.It Ar ar
Arabic (Modern Standard)
.It Ar ca
Catalan
.It Ar zh
Chinese (Generic)
.It Ar cn
Chinese (Simplified)
.It Ar tw
Chinese (Traditional)
.It Ar hr
Croatian
.It Ar cs
Czech
.It Ar da
Danish
.It Ar nl
Dutch
.It Ar en
English (Generic, default)
.It Ar gb
English (Great Britain)
.It Ar us
English (US)
.It Ar et
Estonian
.It Ar fi
Finnish
.It Ar be
Flemish
.It Ar fr
French
.It Ar de
German
.It Ar el
Greek
.It Ar he
Hebrew
.It Ar hu
Hungarian
.It Ar it
Italian
.It Ar ja
Japanese
.It Ar ko
Korean
.It Ar lv
Latvian
.It Ar nb
Norwegian (Bokm\(oal)
.It Ar fa
Persian
.It Ar pl
Polish
.It Ar br
Portuguese (Brazil)
.It Ar pt
Portuguese (Portugal)
.It Ar ru
Russian
.It Ar sr
Serbian
.It Ar sk
Slovak
.It Ar es
Spanish
.It Ar se
Swedish
.It Ar tr
Turkish
.It Ar uk
Ukrainian
.El
.It Fl r | -speech-volume Ns Ar NUM
Set the voice volume to, 0-255 (default: 192).
.It Fl s | -sfx-volume= Ns Ar NUM
Set the sfx volume to, 0-255 (default: 192).
.It Fl t | -list-targets
Display list of configured targets and exit.
.It Fl u | -dump-scripts
Enable script dumping if a directory called
.Pa dumps
exists in the current directory.
.It Fl v | -version
Display ScummVM version information and exit.
.It Fl x | -save-slot= Ns Ar [SLOT]
Saved game slot to load (default: autosave).
.It Fl z | -list-games
Display list of supported games and exit.
.It Fl -alt-intro
Use alternative intro for CD versions of Beneath a Steel Sky and Flight of the
Amazon Queen.
.It Fl -aspect-ratio
Enable aspect ratio correction.
.It Fl -auto-detect
Display a list of games from current or specified directory and start the first
one.
Use
.Fl -path= Ns Ar PATH
to specify a directory.
.It Fl -cdrom= Ns Ar NUM
CD drive to play CD audio from (default: 0 = first drive).
.It Fl -copy-protection
Enable copy protection in games, when ScummVM disables it by default.
.It Fl -dirtyrects
Enable dirty rectangles optimisation in software renderer (default: enabled).
.It Fl -debug-channels-only
Show only the specified debug channels.
.It Fl -debugflags= Ns Ar FLAGS
Enable engine specific debug flags (separated by commas).
.It Fl -demo-mode
Start demo mode of Maniac Mansion or The 7th Guest.
.It Fl -detect
Display a list of games with their ID from current or specified directory
without adding it to the config.
Use
.Fl -path= Ns Ar PATH
to specify a directory.
.It Fl -dump-midi
Dump MIDI events to
.Pa dump.mid ,
until quitting from game.
.It Fl -enable-gs
Enable Roland GS mode for MIDI playback.
.It Fl -engine= Ns Ar ID
In combination with
.Fl -list-games
or
.Fl -list-all-games
only lists games for this engine.
.It Fl -engine-speed= Ns Ar NUM
Set frame per second limit (0 - 100), 0 = no limit (default: 60).
.It Fl -extrapath= Ns Ar PATH
Extra path to additional game data.
.It Fl -filtering
Force filtered graphics mode.
.It Fl -game= Ns Ar ID
In combination with
.Fl -add
or
.Fl -detect
only adds or attempts to detect the game with id
.Ar ID .
.It Fl -gui-theme= Ns Ar THEME
Select GUI theme
.Po
.Ar default ,
.Ar modern ,
.Ar classic
.Pc .
.It Fl -joystick= Ns Ar NUM
Enable joystick input (default: 0 = first joystick).
.It Fl -iconspath= Ns Ar PATH
Path to additional icons for the launcher grid view.
.It Fl -list-all-debugflags
Display list of all engine specified debugflags.
.It Fl -list-all-engines
Display list of all detection engines and exit.
.It Fl -list-all-games
Display list of all detected games and exit.
.It Fl -list-audio-devices
List all available audio devices.
.It Fl -list-debugflags= Ns Ar engine
Display list of engine specified debugflags.
if
.Ar engine= Ns global
or
.Ar engine
is not specified, then it will list global debugflags.
.It Fl -list-engines
Display list of supported engines and exit.
.It Fl -list-saves
Display a list of saved games for the target specified with
.Fl -game= Ns Ar TARGET
or all targets if none is specified.
.Fl -game= Ns Ar ID
In combination with
.Fl -add
or
.Fl -detect
only adds or attempts to detect the game with id
.Ar ID .
.It Fl -list-themes
Display list of all usable GUI themes and exit.
.It Fl -md5
Shows MD5 hash of the file given by
.Fl -md5-path= Ns Ar PATH .
If
.Fl -md5-length= Ns Ar NUM
is passed then it shows the MD5 hash of the first or last
.Ar NUM
bytes of the file given by
.Ar PATH .
If
.Fl -md5-engine= Ns Ar ENGINE_ID
is passed, it fetches the MD5 length automatically, overriding
.Fl -md5-length .
.It Fl -md5mac
Shows MD5 hash for both the resource fork and data fork of the
mac file given by
.Fl -md5-path= Ns Ar PATH .
If
.Fl -md5-length= Ns Ar NUM
is passed then it shows the MD5 hash of the first or last
.Ar NUM
bytes of each fork.
.It Fl -midi-gain= Ns Ar NUM
Set the gain for MIDI playback, 0-1000 (default: 100).
.br
(only supported by some MIDI drivers)
.It Fl -multi-midi
Enable combination of AdLib and native MIDI.
.It Fl -native-mt32
True Roland MT-32 MIDI (disable GM emulation).
.It Fl -no-filtering
Force unfiltered graphics mode.
.It Fl -opl-driver= Ns Ar DRIVER
Select AdLib (OPL) emulator
.Po
.Ar alsa ,
.Ar db ,
.Ar mame ,
.Ar nuked ,
.Ar opl2lpt
.Pc .
.It Fl -output-rate= Ns Ar RATE
Set output sample rate in Hz (e.g. 22050).
.It Fl -platform= Ns Ar WORD
Specify platform of game
.Po
.Ar 2gs ,
.Ar 3do ,
.Ar acorn ,
.Ar amiga ,
.Ar android ,
.Ar apple2 ,
.Ar atari ,
.Ar atari8 ,
.Ar beos ,
.Ar c64 ,
.Ar cdi ,
.Ar coco ,
.Ar coco3 ,
.Ar fmtowns ,
.Ar ios ,
.Ar linux ,
.Ar macintosh ,
.Ar macintosh2 ,
.Ar megadrive ,
.Ar nes ,
.Ar os2 ,
.Ar pc ,
.Ar pc98 ,
.Ar pce ,
.Ar pippin ,
.Ar playstation ,
.Ar playstation2 ,
.Ar ppc ,
.Ar saturn ,
.Ar segacd ,
.Ar shockwave ,
.Ar ti994 ,
.Ar wii ,
.Ar windows ,
.Ar xbox ,
.Ar zx
.Pc .
.It Fl -recursive
In combination with
.Fl -add
or
.Fl -detect
recurse down all subdirectories.
.It Fl -render-mode= Ns Ar MODE
Enable additional render modes
.Po
.Ar 2gs ,
.Ar amiga ,
.Ar atari ,
.Ar cga ,
.Ar cgaBW ,
.Ar cgaComp ,
.Ar ega ,
.Ar fmtowns ,
.Ar hercAmber ,
.Ar hercGreen ,
.Ar macintosh ,
.Ar macintoshbw ,
.Ar pc9801 ,
.Ar pc9821 ,
.Ar vga
.Pc .
.It Fl -renderer= Ns Ar RENDERER
Select 3D renderer
.Po
.Ar software ,
.Ar opengl ,
.Ar opengl_shaders
.Pc .
.It Fl -savepath= Ns Ar PATH
Path to where saved games are stored.
.It Fl -scale-factor= Ns Ar FACTOR
Factor to scale the graphics by.
.It Fl -scaler= Ns Ar MODE
Select graphics scaler
.Po
.Ar normal ,
.Ar hq ,
.Ar edge ,
.Ar advmame ,
.Ar sai ,
.Ar supersai ,
.Ar supereagle ,
.Ar pm ,
.Ar dotmatrix ,
.Ar tv2x
.Pc .
.It Fl -screenshotpath= Ns Ar PATH
Specify path where screenshot files are created.
.It Fl -show-fps
Display FPS in 3D games.
.It Fl -soundfont= Ns Ar FILE
Select the SoundFont for MIDI playback (only supported by some MIDI drivers).
.It Fl -start-movie= Ns Ar NAME Ns Ar @NUM
Start movie at frame for Director.
Either can be specified without the other.
.It Fl -stretch-mode= Ns Ar MODE
Select stretch mode
.Po
.Ar center ,
.Ar integral ,
.Ar fit ,
.Ar stretch
.Pc .
.It Fl -talkspeed= Ns Ar NUM
Set talk delay for SCUMM games, or talk speed for other games (default: 60).
.It Fl -tempo= Ns Ar NUM
Set music tempo (in percent, 50-200) for SCUMM games (default: 100).
.It Fl -themepath= Ns Ar PATH
Path to where GUI themes are stored.
.It Fl -window-size= Ns Ar W,H
Set the ScummVM window size to the specified dimensions (OpenGL only).
.El
.Sh INGAME HOTKEYS
.Bl -tag -width 13m
.It Ctrl-F5
Display the Global Menu
.It Cmd-q
Quit (macOS)
.It Ctrl-q
Quit (Most platforms)
.It Ctrl-u
Mute all sounds
.It Ctrl-m
Toggle mouse capture
.It Ctrl-Alt 1-8
Switch between graphics filters
.It Ctrl-Alt +
Increase scale factor
.It Ctrl-Alt -
Decrease scale factor
.It Ctrl-Alt a
Toggle aspect-ratio correction
.It Ctrl-Alt f
Toggle graphics filtering
.It Ctrl-Alt s
Cycle through scaling modes
.It Alt-Enter
Toggle full screen/windowed
.It Alt-s
Make a screenshot (SDL backend only)
.It Ctrl-F7
Open virtual keyboard (if enabled). This can also be triggered by a long press
of the middle mouse button or wheel.
.El
.Pp
There are many more game-specific hotkeys.
See
.Lk https://wiki.scummvm.org/index.php?title=Category:Supported_Games .
.Sh ENVIRONMENT
.Bl -tag -width SCUMMVM
.It Ev SCUMMVM_MIDI
The sequencer device to use with the
.Ql seq
MIDI driver.
.It Ev SCUMMVM_MIDIPORT
The number of the sequencer to use when using the
.Ql seq
MIDI driver.
.It Ev SCUMMVM_PORT
The ALSA port to open for output when using the
.Ql alsa
MIDI driver.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.scummvmrc
Configuration file on UNIX.
.It Pa "$HOME/Library/Preferences/ScummVM Preferences"
Configuration file on macOS.
.El
.Sh EXAMPLES
Running the builtin game launcher:
.Pp
.Dl $ scummvm
.Pp
Running Day of the Tentacle specifying the path:
.Pp
.Dl $ scummvm -p /usr/local/share/games/tentacle scumm:tentacle
.Pp
Running The Dig with advmame2x filter with subtitles:
.Pp
.Dl $ scummvm -g advmame2x -n scumm:dig
.Pp
Running the Italian version of Maniac Mansion fullscreen:
.Pp
.Dl $ scummvm -q it -f scumm:maniac
.Sh SEE ALSO
.Lk https://docs.scummvm.org ,
.Lk https://www.scummvm.org .
.Sh AUTHORS
ScummVM was written by the ScummVM team.
See
.Pa AUTHORS
file for more information.
