/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 */

#ifndef STARTREK_FUNCTIONMAP_H
#define STARTREK_FUNCTIONMAP_H

#include "startrek/action.h"
#include "startrek/room.h"

namespace StarTrek {

RoomAction demon0ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon0Tick1 },
	{ Action(ACTION_TICK, 2, 0, 0), &Room::demon0Tick2 },
	{ Action(ACTION_TICK, 60, 0, 0), &Room::demon0Tick60 },
	{ Action(ACTION_TICK, 100, 0, 0), &Room::demon0Tick100 },
	{ Action(ACTION_TICK, 140, 0, 0), &Room::demon0Tick140 },

	{ Action(ACTION_TOUCHED_WARP, 0, 0, 0), &Room::demon0TouchedWarp0 },

	{ Action(ACTION_WALK, 0x27, 0, 0), &Room::demon0WalkToBottomDoor },
	{ Action(ACTION_WALK, 9, 0, 0), &Room::demon0WalkToBottomDoor },
	{ Action(ACTION_TOUCHED_HOTSPOT, 1, 0, 0), &Room::demon0TouchedHotspot1 },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon0ReachedBottomDoor },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon0ReachedBottomDoor },

	{ Action(ACTION_WALK, 0x26, 0, 0), &Room::demon0WalkToTopDoor },
	{ Action(ACTION_WALK, 10, 0, 0), &Room::demon0WalkToTopDoor },
	{ Action(ACTION_TOUCHED_HOTSPOT, 0, 0, 0), &Room::demon0TouchedHotspot0 },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon0ReachedTopDoor },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::demon0ReachedTopDoor },

	{ Action(ACTION_TALK, 8, 0, 0), &Room::demon0TalkToPrelate },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::demon0LookAtPrelate },

	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x23, 0), &Room::demon0UsePhaserOnSnow },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x23, 0), &Room::demon0UsePhaserOnSnow },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x25, 0), &Room::demon0UsePhaserOnSign },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x25, 0), &Room::demon0UsePhaserOnSign },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x20, 0), &Room::demon0UsePhaserOnShelter },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 8, 0), &Room::demon0UsePhaserOnPrelate },

	{ Action(ACTION_LOOK, 0x25, 0, 0), &Room::demon0LookAtSign },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon0LookAtTrees },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::demon0LookAtTrees },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::demon0LookAtSnow },
	{ Action(ACTION_LOOK, 0xff, 0, 0), &Room::demon0LookAnywhere },
	{ Action(ACTION_LOOK, 0x24, 0, 0), &Room::demon0LookAtBushes },

	{ Action(ACTION_LOOK, OBJECT_KIRK,     0, 0), &Room::demon0LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_MCCOY,    0, 0), &Room::demon0LookAtMcCoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon0LookAtRedShirt },
	{ Action(ACTION_LOOK, OBJECT_SPOCK,    0, 0), &Room::demon0LookAtSpock },

	{ Action(ACTION_LOOK, 9, 0, 0), &Room::demon0LookAtShelter },    // Door 1
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::demon0LookAtShelter },   // Door 2
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon0LookAtShelter }, // Shelter itself

	{ Action(ACTION_TALK, OBJECT_KIRK,     0, 0), &Room::demon0TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon0TalkToRedshirt },
	{ Action(ACTION_TALK, OBJECT_MCCOY,    0, 0), &Room::demon0TalkToMcCoy },
	{ Action(ACTION_TALK, OBJECT_SPOCK,    0, 0), &Room::demon0TalkToSpock },

	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::demon0UseSTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::demon0UseMTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::demon0UseMTricorderOnPrelate },
};

RoomAction demon1ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon1Tick1 },

	{ Action(ACTION_WALK, 0x25, 0, 0), &Room::demon1WalkToCave },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon1TouchedTopWarp },
	{ Action(ACTION_TOUCHED_WARP, 0, 0, 0), &Room::demon1TouchedTopWarp },
	{ Action(ACTION_TOUCHED_WARP, 1, 0, 0), &Room::demon1TouchedBottomWarp },

	{ Action(ACTION_TIMER_EXPIRED, 2, 0, 0), &Room::demon1Timer2Expired },
	{ Action(ACTION_TIMER_EXPIRED, 0, 0, 0), &Room::demon1Timer0Expired },
	{ Action(ACTION_TIMER_EXPIRED, 3, 0, 0), &Room::demon1Timer3Expired },
	{ Action(ACTION_TIMER_EXPIRED, 1, 0, 0), &Room::demon1Timer1Expired },

	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::demon1KlingonFinishedAimingWeapon },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon1KirkShot },

	{ Action(ACTION_USE, OBJECT_IPHASERK, -1, 0), &Room::demon1UsePhaserOnAnything },
	{ Action(ACTION_USE, OBJECT_IPHASERS, -1, 0), &Room::demon1UsePhaserOnAnything },

	{ Action(ACTION_USE, OBJECT_IPHASERK, 8, 0), &Room::demon1UsePhaserOnKlingon1 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 8, 0), &Room::demon1UsePhaserOnKlingon1 },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::demon1ShootKlingon1 },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::demon1KlingonDropsHand },

	{ Action(ACTION_USE, OBJECT_IPHASERK, 9, 0), &Room::demon1UsePhaserOnKlingon2 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 9, 0), &Room::demon1UsePhaserOnKlingon2 },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::demon1ShootKlingon2 },

	{ Action(ACTION_USE, OBJECT_IPHASERK, 10, 0), &Room::demon1UsePhaserOnKlingon3 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 10, 0), &Room::demon1UsePhaserOnKlingon3 },
	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::demon1ShootKlingon3 },

	{ Action(ACTION_TIMER_EXPIRED, 6, 0, 0), &Room::demon1AllKlingonsDead },
	{ Action(ACTION_TIMER_EXPIRED, 5, 0, 0), &Room::demon1Timer5Expired },

	{ Action(ACTION_USE, OBJECT_IMTRICOR, 13, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::demon1UseSTricorderOnTulips },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x22, 0), &Room::demon1UseSTricorderOnPods },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::demon1UseSTricorderOnCattails },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x23, 0), &Room::demon1UseSTricorderOnFerns },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 13, 0), &Room::demon1UseSTricorderOnHand },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 8, 0), &Room::demon1UseSTricorderOnKlingon1 },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 10, 0), &Room::demon1UseSTricorderOnKlingon2Or3 },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 9, 0), &Room::demon1UseSTricorderOnKlingon2Or3 },
	{ Action(ACTION_USE, OBJECT_IMEDKIT,  8, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 10, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_IMEDKIT,  9, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 10, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_IMTRICOR,  9, 0), &Room::demon1UseMTricorderOnKlingon },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 8, 0), &Room::demon1UseSTricorderOnKlingon2Or3 }, // This is redundant

	{ Action(ACTION_USE, OBJECT_IMTRICOR, OBJECT_KIRK, 0), &Room::demon1UseMTricorderOnKirk },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, OBJECT_SPOCK, 0), &Room::demon1UseMTricorderOnSpock },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, OBJECT_REDSHIRT, 0), &Room::demon1UseMTricorderOnRedshirt },

	{ Action(ACTION_GET, 13, 0, 0), &Room::demon1GetHand },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon1ReachedHand },
	{ Action(ACTION_FINISHED_ANIMATION, 6, 0, 0), &Room::demon1PickedUpHand },
	{ Action(ACTION_TIMER_EXPIRED, 4, 0, 0), &Room::demon1FinishedGettingHand },

	{ Action(ACTION_LOOK, 8, 0, 0), &Room::demon1LookAtKlingon },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::demon1LookAtKlingon },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::demon1LookAtKlingon },

	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon1LookAtCattails },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon1LookAtTulips },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::demon1LookAtPods },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::demon1LookAtFerns },
	{ Action(ACTION_LOOK, 0x24, 0, 0), &Room::demon1LookAtStream },
	{ Action(ACTION_LOOK, 0x25, 0, 0), &Room::demon1LookAtMine },
	{ Action(ACTION_LOOK, 0x26, 0, 0), &Room::demon1LookAtMountain },
	{ Action(ACTION_LOOK, 13, 0, 0), &Room::demon1LookAtHand },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::demon1LookAnywhere },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::demon1LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::demon1LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::demon1LookAtMcCoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon1LookAtRedshirt },

	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::demon1TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::demon1TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::demon1TalkToMcCoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon1TalkToRedshirt },
};

RoomAction demon2ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon2Tick1 },
	{ Action(ACTION_WALK, 0x27, 0, 0), &Room::demon2WalkToCave },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon2ReachedCave },
	{ Action(ACTION_TOUCHED_WARP, 1, 0, 0), &Room::demon2TouchedWarp1 },

	{ Action(ACTION_LOOK, 0x27, 0, 0), &Room::demon2LookAtCave },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon2LookAtCave },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon2LookAtMountain },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::demon2LookAtMountain },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::demon2LookAtBerries },
	{ Action(ACTION_LOOK, 0x24, 0, 0), &Room::demon2LookAtFern },
	{ Action(ACTION_LOOK, 0x25, 0, 0), &Room::demon2LookAtMoss },
	{ Action(ACTION_LOOK, 0x26, 0, 0), &Room::demon2LookAtLights },
	{ Action(ACTION_LOOK, -1, 0, 0),   &Room::demon2LookAtAnything },

	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::demon2LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::demon2LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::demon2LookAtMcCoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon2LookAtRedshirt },

	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::demon2TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::demon2TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::demon2TalkToMcCoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon2TalkToRedshirt },

	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x23, 0), &Room::demon2UsePhaserOnBerries },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x23, 0), &Room::demon2UsePhaserOnBerries },

	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x23, 0), &Room::demon2UseSTricorderOnBerries },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x25, 0), &Room::demon2UseSTricorderOnMoss },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x24, 0), &Room::demon2UseSTricorderOnFern },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::demon2UseSTricorderOnCave },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::demon2UseSTricorderOnCave },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x22, 0), &Room::demon2UseSTricorderOnCave },

	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x23, 0), &Room::demon2UseMTricorderOnBerries },
	{ Action(ACTION_GET, 0x23, 0, 0), &Room::demon2GetBerries },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon2ReachedBerries },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon2PickedUpBerries },
};

RoomAction demon3ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon3Tick1 },
	{ Action(ACTION_TIMER_EXPIRED, 0, 0, 0), &Room::demon3Timer0Expired },
	{ Action(ACTION_TIMER_EXPIRED, 1, 0, 0), &Room::demon3Timer1Expired },
	{ Action(ACTION_TIMER_EXPIRED, 3, 0, 0), &Room::demon3Timer3Expired },

	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon3FinishedAnimation1 },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::demon3FinishedAnimation2 },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::demon3FinishedWalking5 },

	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::demon3McCoyInFiringPosition },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon3SpockInFiringPosition },
	{ Action(ACTION_FINISHED_WALKING, 4, 0, 0), &Room::demon3RedShirtInFiringPosition },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon3KirkInFiringPosition },

	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::demon3FireAtBoulder },

	{ Action(ACTION_USE, OBJECT_IPHASERS, OBJECT_REDSHIRT, 0), &Room::demon3UsePhaserOnRedshirt },
	{ Action(ACTION_USE, OBJECT_IPHASERK, OBJECT_REDSHIRT, 0), &Room::demon3UsePhaserOnRedshirt },

	{ Action(ACTION_USE, OBJECT_IPHASERS,  9, 0), &Room::demon3UseStunPhaserOnBoulder },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 10, 0), &Room::demon3UseStunPhaserOnBoulder },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 11, 0), &Room::demon3UseStunPhaserOnBoulder },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 12, 0), &Room::demon3UseStunPhaserOnBoulder },

	{ Action(ACTION_USE, OBJECT_IPHASERK,  9, 0), &Room::demon3UsePhaserOnBoulder1 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 10, 0), &Room::demon3UsePhaserOnBoulder2 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 11, 0), &Room::demon3UsePhaserOnBoulder3 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 12, 0), &Room::demon3UsePhaserOnBoulder4 },

	{ Action(ACTION_USE, OBJECT_ISTRICOR, 13, 0), &Room::demon3UseSTricorderOnMiner },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::demon3UseSTricorderOnPanel },
	{ Action(ACTION_USE, OBJECT_ISTRICOR,  9, 0), &Room::demon3UseSTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 10, 0), &Room::demon3UseSTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 11, 0), &Room::demon3UseSTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 12, 0), &Room::demon3UseSTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_IMTRICOR,  9, 0), &Room::demon3UseMTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 10, 0), &Room::demon3UseMTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 11, 0), &Room::demon3UseMTricorderOnBoulder },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 12, 0), &Room::demon3UseMTricorderOnBoulder },

	{ Action(ACTION_USE, OBJECT_KIRK, 0x20, 0), &Room::demon3UseCrewmanOnPanel },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::demon3UseCrewmanOnPanel },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x20, 0), &Room::demon3UseCrewmanOnPanel },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::demon3UseRedshirtOnPanel },
	{ Action(ACTION_FINISHED_WALKING, 8, 0, 0), &Room::demon3RedshirtReachedPanel },
	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::demon3RedshirtUsedPanel },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::demon3RedshirtElectrocuted },

	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::demon3UseSTricorderOnDoor },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::demon3UseSTricorderOnAnything },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 14, 0), &Room::demon3UseMTricorderOnDoor },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x21, 0), &Room::demon3UseMTricorderOnDoor },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x22, 0), &Room::demon3UseMTricorderOnDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 14, 0), &Room::demon3UsePhaserOnDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 14, 0), &Room::demon3UsePhaserOnDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x21, 0), &Room::demon3UsePhaserOnDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x21, 0), &Room::demon3UsePhaserOnDoor },

	{ Action(ACTION_USE, OBJECT_IHAND, 0x20, 0), &Room::demon3UseHandOnPanel },
	{ Action(ACTION_FINISHED_WALKING, 7, 0, 0), &Room::demon3KirkReachedHandPanel },
	{ Action(ACTION_FINISHED_ANIMATION, 6, 0, 0), &Room::demon3KirkUsedHandPanel },

	{ Action(ACTION_USE, OBJECT_IMTRICOR, 13, 0), &Room::demon3UseMTricorderOnMiner },
	{ Action(ACTION_USE, OBJECT_MCCOY, 13, 0), &Room::demon3UseMedkitOnMiner },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 13, 0), &Room::demon3UseMedkitOnMiner },
	{ Action(ACTION_FINISHED_WALKING, 6, 0, 0), &Room::demon3McCoyReachedMiner },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::demon3McCoyFinishedHealingMiner },

	{ Action(ACTION_GET, 13, 0, 0), &Room::demon3GetMiner },
	{ Action(ACTION_TALK, 13, 0, 0), &Room::demon3TalkToMiner },

	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::demon3TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::demon3TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::demon3TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon3TalkToRedshirt },

	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::demon3LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::demon3LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::demon3LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon3LookAtRedshirt },

	{ Action(ACTION_LOOK, -1, 0, 0), &Room::demon3LookAnywhere },
	{ Action(ACTION_LOOK, 13, 0, 0), &Room::demon3LookAtMiner },
	{ Action(ACTION_LOOK,  9, 0, 0), &Room::demon3LookAtBoulder1 },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::demon3LookAtBoulder2 },
	{ Action(ACTION_LOOK, 11, 0, 0), &Room::demon3LookAtBoulder3 },
	{ Action(ACTION_LOOK, 12, 0, 0), &Room::demon3LookAtBoulder4 },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::demon3LookAtStructure },
	{ Action(ACTION_LOOK, 14, 0, 0), &Room::demon3LookAtDoor },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon3LookAtDoor },
	{ Action(ACTION_LOOK, 15, 0, 0), &Room::demon3LookAtPanel },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon3LookAtPanel },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::demon3LookAtLight },

};

RoomAction demon4ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon4Tick1 },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon4FinishedAnimation1 },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::demon4FinishedAnimation2 },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::demon4FinishedAnimation3 },
	{ Action(ACTION_TIMER_EXPIRED, 0, 0, 0), &Room::demon4Timer0Expired },
	{ Action(ACTION_TIMER_EXPIRED, 1, 0, 0), &Room::demon4Timer1Expired },
	{ Action(ACTION_FINISHED_WALKING, 4, 0, 0), &Room::demon4CrewmanReachedBeamoutPosition },
	{ Action(ACTION_TIMER_EXPIRED, 2, 0, 0), &Room::demon4Timer2Expired },
	{ Action(ACTION_TIMER_EXPIRED, 3, 0, 0), &Room::demon4Timer3Expired },
	{ Action(ACTION_TIMER_EXPIRED, 4, 0, 0), &Room::demon4Timer4Expired },
	{ Action(ACTION_TIMER_EXPIRED, 5, 0, 0), &Room::demon4Timer5Expired },
	{ Action(ACTION_TIMER_EXPIRED, 6, 0, 0), &Room::demon4Timer6Expired },

	{ Action(ACTION_USE, OBJECT_IPHASERK, 8, 0), &Room::demon4UsePhaserOnNauian },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 8, 0), &Room::demon4UsePhaserOnNauian },
	{ Action(ACTION_USE, OBJECT_IMETAL, 0x22, 0), &Room::demon4UseMetalOnSecurityEquipment },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::demon4KirkReachedSecurityEquipment },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::demon4KirkFinishedUsingSecurityEquipment },
	{ Action(ACTION_USE, OBJECT_IMETAL, 8, 0), &Room::demon4UseMetalOnNauian },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon4KirkReachedNauian },
	{ Action(ACTION_USE, OBJECT_ISKULL, 8, 0), &Room::demon4UseSkullOnNauian },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon4KirkReachedNauianWithSkull },

	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x21, 0), &Room::demon4UsePhaserOnPanel },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x20, 0), &Room::demon4UsePhaserOnPattern },
	{ Action(ACTION_USE, OBJECT_IPHASERS, OBJECT_MCCOY, 0), &Room::demon4UsePhaserOnMccoy },

	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::demon4TalkToNauian },
	{ Action(ACTION_TALK, 8, 0, 0), &Room::demon4TalkToNauian },

	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon4LookAtPattern },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::demon4LookAtAlien },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::demon4LookAnywhere },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::demon4LookAtSecurityEquipment },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::demon4LookAtFloor },

	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::demon4LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::demon4LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::demon4LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon4LookAtRedshirt },

	{ Action(ACTION_LOOK, 10, 0, 0), &Room::demon4LookAtChamber },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon4LookAtPanel },

	{ Action(ACTION_USE, OBJECT_KIRK, 0x21, 0), &Room::demon4UseKirkOnPanel },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x21, 0), &Room::demon4UseSpockOnPanel },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x21, 0), &Room::demon4UseMccoyOnPanel },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x21, 0), &Room::demon4UseRedshirtOnPanel },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::demon4CrewmanReachedPanel },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::demon4TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::demon4TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::demon4TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon4TalkToRedshirt },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 10, 0), &Room::demon4UseSTricorderOnChamber },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::demon4UseSTricorderOnPattern },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x20, 0), &Room::demon4UseMTricorderOnPattern },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::demon4UseSTricorderOnPanel },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x21, 0), &Room::demon4UseMTricorderOnPanel },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x23, 0), &Room::demon4UseSTricorderOnAnything },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::demon4UseSTricorderOnAnything },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x23, 0), &Room::demon4UseMTricorderOnAnything },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::demon4UseMTricorderOnAnything },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 8, 0), &Room::demon4UseSTricorderOnNauian },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::demon4UseMTricorderOnNauian },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x22, 0), &Room::demon4UseSTricorderOnSecurityEquipment },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x22, 0), &Room::demon4UseMTricorderOnSecurityEquipment },
};

RoomAction demon5ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon5Tick1 },
	{ Action(ACTION_WALK, 0x22, 0, 0), &Room::demon5WalkToDoor },
	{ Action(ACTION_WALK, 12, 0, 0), &Room::demon5WalkToDoor },
	{ Action(ACTION_TOUCHED_HOTSPOT, 0, 0, 0), &Room::demon5TouchedDoorOpenTrigger },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon5DoorOpenedOrReachedDoor },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon5DoorOpenedOrReachedDoor },

	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::demon5UseSTricorderOnCrate },
	{ Action(ACTION_USE, OBJECT_IPHASERK, -1, 0), &Room::demon5UsePhaserOnAnything },
	{ Action(ACTION_USE, OBJECT_IPHASERS, -1, 0), &Room::demon5UsePhaserOnAnything },

	{ Action(ACTION_USE, OBJECT_IHAND, 11, 0), &Room::demon5UseHandOnStephen },
	{ Action(ACTION_USE, OBJECT_IBERRY, 11, 0), &Room::demon5UseBerryOnStephen },
	{ Action(ACTION_USE, OBJECT_IDETOXIN, 9, 0), &Room::demon5UseHypoDytoxinOnChub },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon5MccoyReachedChub },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::demon5MccoyHealedChub },

	{ Action(ACTION_USE, OBJECT_IDETOXIN, -1, 0), &Room::demon5UseHypoDytoxinOnAnything },
	{ Action(ACTION_USE, OBJECT_IBERRY, 9, 0), &Room::demon5UseBerryOnChub },

	{ Action(ACTION_LOOK, 8, 0, 0), &Room::demon5LookAtRoberts },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::demon5LookAtGrisnash },
	{ Action(ACTION_LOOK, 11, 0, 0), &Room::demon5LookAtStephen },

	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::demon5LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::demon5LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::demon5LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon5LookAtRedshirt },

	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon5LookAtMountain },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon5LookAtCrate },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::demon5LookAnywhere },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::demon5LookAtChub },

	{ Action(ACTION_TALK, 8, 0, 0), &Room::demon5TalkToRoberts },
	{ Action(ACTION_TALK, 9, 0, 0), &Room::demon5TalkToChub },
	{ Action(ACTION_TALK, 10, 0, 0), &Room::demon5TalkToGrisnash },
	{ Action(ACTION_TALK, 11, 0, 0), &Room::demon5TalkToStephen },

	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::demon5TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::demon5TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon5TalkToRedshirt },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::demon5TalkToMccoy },

	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::demon5UseMTricorderOnRoberts },
	{ Action(ACTION_USE, OBJECT_IMEDKIT,  9, 0), &Room::demon5UseMTricorderOnChub },
	{ Action(ACTION_USE, OBJECT_MCCOY,    9, 0), &Room::demon5UseMTricorderOnChub },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 9, 0), &Room::demon5UseMTricorderOnChub },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 10, 0), &Room::demon5UseMTricorderOnGrisnash },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 11, 0), &Room::demon5UseMTricorderOnStephen },

	{ Action(ACTION_GET, 0x21, 0, 0), &Room::demon5GetCrate },
};

RoomAction demon6ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::demon6Tick1 },
	{ Action(ACTION_TICK, 30, 0, 0), &Room::demon6Tick30 },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::demon6SpockReachedComputer },

	{ Action(ACTION_WALK, 0x26, 0, 0), &Room::demon6WalkToDoor },
	{ Action(ACTION_WALK, 10, 0, 0), &Room::demon6WalkToDoor },
	{ Action(ACTION_TOUCHED_HOTSPOT, 0, 0, 0), &Room::demon6TouchedDoorOpenTrigger },
	{ Action(ACTION_FINISHED_WALKING, 4, 0, 0), &Room::demon6DoorOpenedOrReachedDoor },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::demon6DoorOpenedOrReachedDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 8, 0), &Room::demon6UsePhaserOnStephen },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 8, 0), &Room::demon6UsePhaserOnStephen },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x20, 0), &Room::demon6UsePhaserOnCase },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x20, 0), &Room::demon6UsePhaserOnCase },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::demon6LookAtWorkspace },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::demon6LookAtCase },
	{ Action(ACTION_LOOK, 0x25, 0, 0), &Room::demon6LookAtTable },
	{ Action(ACTION_LOOK, OBJECT_IMINERAL, 0, 0), &Room::demon6LookAtMineral },
	{ Action(ACTION_LOOK, OBJECT_ISHELLS, 0, 0), &Room::demon6LookAtShells },
	{ Action(ACTION_LOOK, OBJECT_ISKULL, 0, 0), &Room::demon6LookAtSkull },
	{ Action(ACTION_LOOK, OBJECT_IMETAL, 0, 0), &Room::demon6LookAtMetal },
	{ Action(ACTION_LOOK, OBJECT_IMETEOR, 0, 0), &Room::demon6LookAtMeteor },
	{ Action(ACTION_LOOK, 0x24, 0, 0), &Room::demon6LookAtMountain },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::demon6LookAtSynthesizer },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::demon6LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::demon6LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::demon6LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::demon6LookAtRedshirt },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::demon6LookAtComputer },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::demon6LookAtComputer },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::demon6LookAnywhere },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::demon6LookAtStephen },

	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::demon6TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::demon6TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::demon6TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::demon6TalkToRedshirt },
	{ Action(ACTION_TALK, 8, 0, 0), &Room::demon6TalkToStephen },
	{ Action(ACTION_USE, OBJECT_IBERRY, 8, 0), &Room::demon6UseBerryOnStephen },
	{ Action(ACTION_USE, OBJECT_IBERRY, 0x23, 0), &Room::demon6UseBerryOnSynthesizer },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::demon6MccoyReachedSynthesizer },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::demon6FinishedMakingHypoDytoxin },
	{ Action(ACTION_USE, OBJECT_IHAND, 0x22, 0), &Room::demon6UseHandOnWorkspace },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::demon6SpockReachedWorkspace },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::demon6SpockFinishedRepairingHand },
	{ Action(ACTION_USE, -1, 0x22, 0), &Room::demon6UseAnythingOnWorkspace },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x20, 0), &Room::demon6UseCrewmanOnCase },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x20, 0), &Room::demon6UseCrewmanOnCase },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::demon6UseCrewmanOnCase },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::demon6UseCrewmanOnCase },

	{ Action(ACTION_USE, OBJECT_KIRK, 0x21, 0), &Room::demon6UseKirkOnComputer },
	{ Action(ACTION_USE, OBJECT_KIRK, 9, 0), &Room::demon6UseKirkOnComputer },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x21, 0), &Room::demon6UseMccoyOnComputer },
	{ Action(ACTION_USE, OBJECT_MCCOY, 9, 0), &Room::demon6UseMccoyOnComputer },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x21, 0), &Room::demon6UseRedshirtOnComputer },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 9, 0), &Room::demon6UseRedshirtOnComputer },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x21, 0), &Room::demon6UseSpockOnComputer },
	{ Action(ACTION_USE, OBJECT_SPOCK, 9, 0), &Room::demon6UseSpockOnComputer },
	{ Action(ACTION_USE, OBJECT_IMINERAL, 8, 0), &Room::demon6UseMineralOnStephen },
	{ Action(ACTION_USE, OBJECT_ISHELLS, 8, 0), &Room::demon6UseShellsOnStephen },
	{ Action(ACTION_USE, OBJECT_IMETEOR, 8, 0), &Room::demon6UseMeteorOnStephen },
	{ Action(ACTION_USE, OBJECT_ISKULL, 8, 0), &Room::demon6UseSkullOnStephen },
	{ Action(ACTION_USE, OBJECT_IMETAL, 8, 0), &Room::demon6UseMetalOnStephen },
	{ Action(ACTION_USE, OBJECT_IHAND, 8, 0), &Room::demon6UseHandOnStephen },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::demon6UseMTricoderOnStephen },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x25, 0), &Room::demon6UseSTricoderOnTable },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 9, 0), &Room::demon6UseSTricoderOnComputer },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::demon6UseSTricoderOnComputer },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, OBJECT_IMINERAL, 0), &Room::demon6UseSTricoderOnMineral },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, OBJECT_ISHELLS, 0), &Room::demon6UseSTricoderOnShells },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, OBJECT_ISKULL, 0), &Room::demon6UseSTricoderOnSkull },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, OBJECT_IMETAL, 0), &Room::demon6UseSTricoderOnMetal },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, OBJECT_IMETEOR, 0), &Room::demon6UseSTricoderOnMeteor },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::demon6UseSTricoderOnCase },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x23, 0), &Room::demon6UseSTricoderOnSynthesizer },
	{ Action(ACTION_GET, 0x20, 0, 0), &Room::demon6GetCase },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::demon6KirkReachedCase },
};


RoomAction tug0ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::tug0Tick1 },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::tug0LookAtEngineer },
	{ Action(ACTION_GET, 8, 0, 0), &Room::tug0GetEngineer },

	{ Action(ACTION_LOOK, 11, 0, 0), &Room::tug0LookAtControls },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::tug0LookAtControls },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x21, 0), &Room::tug0UseSpockOnControls },
	{ Action(ACTION_FINISHED_WALKING, 16, 0, 0), &Room::tug0SpockReachedControlsToExamine },
	{ Action(ACTION_FINISHED_ANIMATION, 17, 0, 0), &Room::tug0SpockExaminedControls },
	{ Action(ACTION_USE, OBJECT_IRT, 0x21, 0), &Room::tug0UseTransmogrifierWithoutBitOnControls },
	{ Action(ACTION_USE, OBJECT_IRTWB, 0x21, 0), &Room::tug0UseTransmogrifierWithBitOnControls },
	{ Action(ACTION_FINISHED_WALKING, 6, 0, 0), &Room::tug0SpockReachedControlsWithTransmogrifier },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::tug0SpockFinishedUsingTransmogrifier },
	{ Action(ACTION_FINISHED_ANIMATION, 22, 0, 0), &Room::tug0TransporterScreenFullyLit },
	{ Action(ACTION_USE, OBJECT_IWIRSCRP, 0x21, 0), &Room::tug0UseWireScrapsOnControls },
	{ Action(ACTION_USE, OBJECT_IWIRING, 0x21, 0), &Room::tug0UseWireOnControls },
	{ Action(ACTION_FINISHED_WALKING, 8, 0, 0), &Room::tug0SpockReachedControlsWithWire },
	{ Action(ACTION_FINISHED_ANIMATION, 9, 0, 0), &Room::tug0SpockFinishedUsingWire },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 8, 0), &Room::tug0UseMedkitOnEngineer },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::tug0MccoyReachedEngineer },
	{ Action(ACTION_FINISHED_ANIMATION, 13, 0, 0), &Room::tug0MccoyHealedEngineer },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::tug0EngineerGotUp },
	{ Action(ACTION_GET, 9, 0, 0), &Room::tug0GetTransmogrifier },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::tug0KirkReachedToolbox },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::tug0KirkGotTransmogrifier },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::tug0LookAtToolbox },

	{ Action(ACTION_USE, OBJECT_IPHASERS, OBJECT_IPWE, 0), &Room::tug0UsePhaserOnWelder },
	{ Action(ACTION_USE, OBJECT_IPHASERK, OBJECT_IPWE, 0), &Room::tug0UsePhaserOnWelder },
	{ Action(ACTION_USE, OBJECT_IPWF, OBJECT_IWIRSCRP, 0), &Room::tug0UseWelderOnWireScraps },
	{ Action(ACTION_USE, OBJECT_IPWF, OBJECT_IJNKMETL, 0), &Room::tug0UseWelderOnMetalScraps },
	{ Action(ACTION_USE, OBJECT_ICOMBBIT, OBJECT_IRT, 0), &Room::tug0UseCombBitOnTransmogrifier },

	{ Action(ACTION_USE, OBJECT_SPOCK, 11, 0), &Room::tug0UseTransporter },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x22, 0), &Room::tug0UseTransporter },
	{ Action(ACTION_FINISHED_WALKING, 14, 0, 0), &Room::tug0SpockReachedControlsToTransport },
	{ Action(ACTION_FINISHED_ANIMATION, 18, 0, 0), &Room::tug0SpockPreparedTransporter },
	{ Action(ACTION_FINISHED_WALKING, 20, 0, 0), &Room::tug0SpockReachedTransporter },
	{ Action(ACTION_FINISHED_ANIMATION, 21, 0, 0), &Room::tug0FinishedTransporting },

	{ Action(ACTION_USE, OBJECT_IBOMB, 0x22, 0), &Room::tug0UseBombOnTransporter },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::tug0KirkReachedTransporter },
	{ Action(ACTION_FINISHED_ANIMATION, 10, 0, 0), &Room::tug0KirkPlacedBomb },
	{ Action(ACTION_FINISHED_WALKING, 15, 0, 0), &Room::tug0SpockReachedControlsForBomb },
	{ Action(ACTION_FINISHED_ANIMATION, 19, 0, 0), &Room::tug0SpockBeginsBeamingBomb },
	{ Action(ACTION_FINISHED_ANIMATION, 12, 0, 0), &Room::tug0SpockFinishesBeamingBomb },
	{ Action(ACTION_TIMER_EXPIRED, 0, 0, 0), &Room::tug0BombExploded },

	{ Action(ACTION_USE, OBJECT_MCCOY, 0x21, 0), &Room::tug0UseMTricorderOnControls },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x21, 0), &Room::tug0UseMTricorderOnControls },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::tug0UseSTricorderOnControls },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::tug0UseMTricorderOnEngineer },
	{ Action(ACTION_FINISHED_WALKING, 24, 0, 0), &Room::tug0MccoyReachedEngineerToScan },
	{ Action(ACTION_FINISHED_ANIMATION, 25, 0, 0), &Room::tug0MccoyFinishedScanningEngineer },
	{ Action(ACTION_USE, OBJECT_SPOCK, 8, 0), &Room::tug0UseSTricorderOnEngineer },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 8, 0), &Room::tug0UseSTricorderOnEngineer },
	{ Action(ACTION_WALK, 0x23, 0, 0), &Room::tug0WalkToDoor },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::tug0LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::tug0LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::tug0LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::tug0LookAtRedshirt },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::tug0LookAtTransporter },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::tug0LookAtDoor },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::tug0TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::tug0TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::tug0TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::tug0TalkToRedshirt },
	{ Action(ACTION_TALK, 8, 0, 0), &Room::tug0TalkToEngineer },
	{ Action(ACTION_USE, OBJECT_ICOMM, 0, 0), &Room::tug0UseCommunicator },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::tug0LookAnywhere },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::tug0UseSTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::tug0UseMTricorderAnywhere },
};


RoomAction tug1ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::tug1Tick1 },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::tug1UseSTricorderOnAnything },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::tug1LookAtBridgeDoor },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::tug1UseSTricorderOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 0x21, 0), &Room::tug1UsePhaserOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 0x21, 0), &Room::tug1UsePhaserOnBridgeDoor },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::tug1KirkReachedFiringPosition },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::tug1KirkPulledOutPhaser },
	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::tug1KirkFinishedFiringPhaser },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::tug1TalkToSpock },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 8, 0), &Room::tug1UseSTricorderOnJunkPile },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::tug1LookAtJunkPile },
	{ Action(ACTION_GET, 8, 0, 0), &Room::tug1GetJunkPile },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::tug1KirkReachedJunkPile },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::tug1KirkFinishedTakingJunkPile },

	{ Action(ACTION_USE, OBJECT_IPHASERS, OBJECT_IPWE, 0), &Room::tug1UsePhaserOnWelder },
	{ Action(ACTION_USE, OBJECT_IPHASERK, OBJECT_IPWE, 0), &Room::tug1UsePhaserOnWelder },
	{ Action(ACTION_USE, OBJECT_IPWF, OBJECT_IWIRSCRP, 0), &Room::tug1UseWelderOnWireScraps },
	{ Action(ACTION_USE, OBJECT_IPWF, OBJECT_IJNKMETL, 0), &Room::tug1UseWelderOnMetalScraps },
	{ Action(ACTION_USE, OBJECT_ICOMBBIT, OBJECT_IRT, 0), &Room::tug1UseCombBitOnTransmogrifier },

	{ Action(ACTION_USE, OBJECT_IPWF, 0x22, 0), &Room::tug1UsePhaserWelderOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IPWF, 0x21, 0), &Room::tug1UsePhaserWelderOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IPWF, 0x20, 0), &Room::tug1UsePhaserWelderOnBridgeDoorInLeftSpot },
	{ Action(ACTION_FINISHED_WALKING, 6, 0, 0), &Room::tug1KirkReachedBridgeDoorWithWelder },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::tug1KirkFinishedUsingWelder },
	{ Action(ACTION_FINISHED_WALKING, 8, 0, 0), &Room::tug1KirkReachedBridgeDoorWithWelderInLeftSpot },
	{ Action(ACTION_FINISHED_ANIMATION, 9, 0, 0), &Room::tug1KirkFinishedUsingWelderInLeftSpot },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::tug1LookAnywhere },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::tug1LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::tug1LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::tug1LookAtRedshirt },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::tug1TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::tug1TalkToRedshirt },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::tug1LookAtTerminal },
	{ Action(ACTION_LOOK, 0x24, 0, 0), &Room::tug1LookAtDebris },
	{ Action(ACTION_LOOK, 0x25, 0, 0), &Room::tug1LookAtBrigDoor },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x25, 0), &Room::tug1UseSTricorderOnBrigDoor },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::tug1TalkToKirk },
	{ Action(ACTION_USE, OBJECT_ICOMM, -1, 0), &Room::tug1UseCommunicator },
	{ Action(ACTION_WALK, 0x21, 0, 0), &Room::tug1WalkToBridgeDoor },
	{ Action(ACTION_FINISHED_WALKING, 10, 0, 0), &Room::tug1KirkReachedBridgeDoor },
	{ Action(ACTION_FINISHED_ANIMATION, 11, 0, 0), &Room::tug1BridgeDoorOpened },
	{ Action(ACTION_WALK, 0x25, 0, 0), &Room::tug1WalkToBrigDoor },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::tug1UseMTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x21, 0), &Room::tug1UseMTricorderOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x20, 0), &Room::tug1UseMTricorderOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x22, 0), &Room::tug1UseMTricorderOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x25, 0), &Room::tug1UseMTricorderOnBrigDoor },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::tug1UseSpockOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x21, 0), &Room::tug1UseSpockOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x22, 0), &Room::tug1UseSpockOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::tug1UseRedshirtOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x21, 0), &Room::tug1UseRedshirtOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x22, 0), &Room::tug1UseRedshirtOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 0x20, 0), &Room::tug1UseMedkitOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 0x21, 0), &Room::tug1UseMedkitOnBridgeDoor },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 0x22, 0), &Room::tug1UseMedkitOnBridgeDoor },
};


RoomAction tug2ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::tug2Tick1 },
	{ Action(ACTION_TICK, 60, 0, 0), &Room::tug2Tick60 },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::tug2LookAtButton },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::tug2LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::tug2LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::tug2LookAtRedshirt },
	{ Action(ACTION_GET, 11, 0, 0), &Room::tug2GetBomb },
	{ Action(ACTION_FINISHED_WALKING, 12, 0, 0), &Room::tug2KirkReachedBomb },
	{ Action(ACTION_FINISHED_ANIMATION, 13, 0, 0), &Room::tug2KirkGotBomb },
	{ Action(ACTION_LOOK, 11, 0, 0), &Room::tug2LookAtBomb },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::tug2LookAtGuard1 },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::tug2LookAtGuard2 },
	{ Action(ACTION_LOOK, 12, 0, 0), &Room::tug2LookAtWires },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 12, 0), &Room::tug2UseSTricorderOnButton },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::tug2UseSTricorderOnButton },
	{ Action(ACTION_USE, OBJECT_MCCOY, 12, 0), &Room::tug2UseMccoyOnWires },
	{ Action(ACTION_USE, OBJECT_MCCOY, 11, 0), &Room::tug2UseMccoyOnBomb },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 12, 0), &Room::tug2UseRedshirtOnWires },
	{ Action(ACTION_FINISHED_WALKING, 6, 0, 0), &Room::tug2RedshirtReachedWires },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::tug2RedshirtDefusedBomb },
	{ Action(ACTION_FINISHED_WALKING, 8, 0, 0), &Room::tug2RedshirtReturnedToPosition },
	{ Action(ACTION_USE, OBJECT_KIRK, 12, 0), &Room::tug2UseKirkOnWires },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::tug2KirkReachedWires },
	{ Action(ACTION_USE, OBJECT_SPOCK, 12, 0), &Room::tug2UseSpockOnWires },
	{ Action(ACTION_FINISHED_WALKING, 9, 0, 0), &Room::tug2SpockReachedWires },
	{ Action(ACTION_FINISHED_WALKING, 11, 0, 0), &Room::tug2SpockReturnedToPosition },
	{ Action(ACTION_GET, 12, 0, 0), &Room::tug2GetWires },
	{ Action(ACTION_FINISHED_WALKING, 28, 0, 0), &Room::tug2KirkReachedWiresToGet },
	{ Action(ACTION_FINISHED_ANIMATION, 29, 0, 0), &Room::tug2KirkGotWires },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x20, 0), &Room::tug2UseKirkOnButton },
	{ Action(ACTION_FINISHED_WALKING, 14, 0, 0), &Room::tug2KirkReachedButton },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::tug2UseSpockOnButton },
	{ Action(ACTION_FINISHED_WALKING, 16, 0, 0), &Room::tug2SpockReachedButton },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x20, 0), &Room::tug2UseMccoyOnButton },
	{ Action(ACTION_FINISHED_WALKING, 18, 0, 0), &Room::tug2MccoyReachedButton },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::tug2UseRedshirtOnButton },
	{ Action(ACTION_FINISHED_WALKING, 20, 0, 0), &Room::tug2RedshirtReachedButton },
	{ Action(ACTION_FINISHED_ANIMATION, 15, 0, 0), &Room::tug2TurnedOffForceField },
	{ Action(ACTION_FINISHED_ANIMATION, 17, 0, 0), &Room::tug2TurnedOffForceField },
	{ Action(ACTION_FINISHED_ANIMATION, 19, 0, 0), &Room::tug2TurnedOffForceField },
	{ Action(ACTION_FINISHED_ANIMATION, 21, 0, 0), &Room::tug2TurnedOffForceField },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::tug2PrisonersDead },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::tug2PrisonersReleased },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 10, 0), &Room::tug2UsePhaserOnBrig },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 10, 0), &Room::tug2UsePhaserOnBrig },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 8, 0), &Room::tug2UseStunPhaserOnGuard1 },
	{ Action(ACTION_FINISHED_ANIMATION, 22, 0, 0), &Room::tug2KirkShootGuard1 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 9, 0), &Room::tug2UseStunPhaserOnGuard2 },
	{ Action(ACTION_FINISHED_ANIMATION, 23, 0, 0), &Room::tug2KirkShootGuard2 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 8, 0), &Room::tug2UseKillPhaserOnGuard1 },
	{ Action(ACTION_FINISHED_ANIMATION, 24, 0, 0), &Room::tug2KirkKillGuard1 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 9, 0), &Room::tug2UseKillPhaserOnGuard2 },
	{ Action(ACTION_FINISHED_ANIMATION, 25, 0, 0), &Room::tug2KirkKillGuard2 },

	{ Action(ACTION_USE, OBJECT_IPHASERS, OBJECT_IPWE, 0), &Room::tug2UsePhaserOnWelder },
	{ Action(ACTION_USE, OBJECT_IPHASERK, OBJECT_IPWE, 0), &Room::tug2UsePhaserOnWelder },
	{ Action(ACTION_USE, OBJECT_IPWF, OBJECT_IWIRSCRP, 0), &Room::tug2UseWelderOnWireScraps },
	{ Action(ACTION_USE, OBJECT_IPWF, OBJECT_IJNKMETL, 0), &Room::tug2UseWelderOnMetalScraps },
	{ Action(ACTION_USE, OBJECT_ICOMBBIT, OBJECT_IRT, 0), &Room::tug2UseCombBitOnTransmogrifier },

	{ Action(ACTION_FINISHED_ANIMATION, 26, 0, 0), &Room::tug2ShotByElasi },
	{ Action(ACTION_FINISHED_ANIMATION, 27, 0, 0), &Room::tug2ShotByElasi },
	{ Action(ACTION_WALK, 0x21, 0, 0), &Room::tug2WalkToDoor },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::tug2LookAtDoor },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::tug2LookAtKirk },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::tug2TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::tug2TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::tug2TalkToRedshirt },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::tug2TalkToSpock },
	{ Action(ACTION_USE, OBJECT_ICOMM, 0, 0), &Room::tug2UseCommunicator },
	{ Action(ACTION_TIMER_EXPIRED, 0, 0, 0), &Room::tug2Timer0Expired },
	{ Action(ACTION_TIMER_EXPIRED, 2, 0, 0), &Room::tug2Timer2Expired },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 11, 0), &Room::tug2UseSTricorderOnBomb },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 8, 0), &Room::tug2UseMTricorderOnGuard1 },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 9, 0), &Room::tug2UseMTricorderOnGuard2 },
	{ Action(ACTION_TALK, 8, 0, 0), &Room::tug2TalkToGuard1 },
	{ Action(ACTION_TALK, 9, 0, 0), &Room::tug2TalkToGuard2 },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 11, 0), &Room::tug2UseMedkitOnBomb },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 8, 0), &Room::tug2UseMedkitOnGuard1 },
	{ Action(ACTION_USE, OBJECT_IMEDKIT, 9, 0), &Room::tug2UseMedkitOnGuard2 },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::tug2LookAnywhere },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::tug2LookAnywhere },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::tug2LookAnywhere },
	{ Action(ACTION_TALK, 10, 0, 0), &Room::tug2TalkToBrig },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 10, 0), &Room::tug2UseMTricorderOnBrig },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, 0x22, 0), &Room::tug2UseMTricorderOnOpenBrig },
	{ Action(ACTION_USE, OBJECT_IPHASERS, -1, 0), &Room::tug2UsePhaserAnywhere },
	{ Action(ACTION_USE, OBJECT_IPHASERK, -1, 0), &Room::tug2UsePhaserAnywhere },
};

RoomAction tug3ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::tug3Tick1 },
	{ Action(ACTION_TICK, 40, 0, 0), &Room::tug3Tick40 },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::tug3LookAnywhere },
	{ Action(ACTION_USE, OBJECT_IPHASERS, -1, 0), &Room::tug3UsePhaserAnywhere },
	{ Action(ACTION_USE, OBJECT_IPHASERK, -1, 0), &Room::tug3UsePhaserAnywhere },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 8, 0), &Room::tug3UseStunPhaserOnElasi1 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 9, 0), &Room::tug3UseStunPhaserOnElasi2 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 10, 0), &Room::tug3UseStunPhaserOnElasi3 },
	{ Action(ACTION_USE, OBJECT_IPHASERS, 11, 0), &Room::tug3UseStunPhaserOnElasi4 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 8, 0), &Room::tug3UseKillPhaserOnElasi1 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 9, 0), &Room::tug3UseKillPhaserOnElasi2 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 10, 0), &Room::tug3UseKillPhaserOnElasi3 },
	{ Action(ACTION_USE, OBJECT_IPHASERK, 11, 0), &Room::tug3UseKillPhaserOnElasi4 },
	{ Action(ACTION_FINISHED_ANIMATION, 12, 0, 0), &Room::tug3ElasiStunnedOrKilled },
	{ Action(ACTION_TALK, 8, 0, 0), &Room::tug3TalkToElasi1 },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::tug3Elasi1DrewPhaser },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::tug3Elasi1ShotConsole },
	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::tug3Elasi1DrewPhaser2 },
	{ Action(ACTION_FINISHED_ANIMATION, 6, 0, 0), &Room::tug3Elasi1ShotConsoleAndSurrenders },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::tug3LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::tug3LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::tug3LookAtRedshirt },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::tug3LookAtElasi1 },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::tug3LookAtElasi2 },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::tug3LookAtElasi3 },
	{ Action(ACTION_LOOK, 11, 0, 0), &Room::tug3LookAtElasi4 },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::tug3TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::tug3TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::tug3TalkToRedshirt },
	{ Action(ACTION_USE, OBJECT_ICOMM, -1, 0), &Room::tug3UseCommunicator },
	{ Action(ACTION_TIMER_EXPIRED, 0, 0, 0), &Room::tug3Timer0Expired },
	{ Action(ACTION_FINISHED_ANIMATION, 13, 0, 0), &Room::tug3AllCrewmenDead },
	{ Action(ACTION_TIMER_EXPIRED, 1, 0, 0), &Room::tug3Timer1Expired },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::tug3SecurityTeamBeamedIn },
};


RoomAction love0ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::love0Tick1 },
	{ Action(ACTION_TICK, 10, 0, 0), &Room::love0Tick10 },
	{ Action(ACTION_WALK, 0x21, 0, 0), &Room::love0WalkToDoor2 },
	{ Action(ACTION_WALK, 9, 0, 0), &Room::love0WalkToDoor2 },
	{ Action(ACTION_TOUCHED_HOTSPOT, 0, 0, 0), &Room::love0OpenDoor2 },
	{ Action(ACTION_FINISHED_WALKING, 4, 0, 0), &Room::love0ReachedDoor2 },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::love0ReachedDoor2 },
	{ Action(ACTION_WALK, 0x22, 0, 0), &Room::love0WalkToDoor1 },
	{ Action(ACTION_WALK, 8, 0, 0), &Room::love0WalkToDoor1 },
	{ Action(ACTION_TOUCHED_HOTSPOT, 1, 0, 0), &Room::love0OpenDoor1 },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::love0ReachedDoor1 },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::love0ReachedDoor1 },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::love0LookAtConsole },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::love0LookAtViewscreen },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::love0LookAnywhere },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::love0LookAtDoor1 },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::love0LookAtDoor2 },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::love0LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::love0LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::love0LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::love0LookAtRedshirt },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::love0TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::love0TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::love0TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::love0TalkToRedshirt },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::love0UseMTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x20, 0), &Room::love0UseSTricorderOnConsole },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::love0UseSTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x20, 0), &Room::love0UseKirkOnConsole },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::love0UseRedshirtOnConsole },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::love0UseSpockOnConsole },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::love0SpockReachedConsole },
	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::love0SpockAccessedConsole },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x20, 0), &Room::love0UseMccoyOnConsole },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::love0MccoyReachedConsole },
	{ Action(ACTION_FINISHED_ANIMATION, 6, 0, 0), &Room::love0MccoyAccessedConsole },
	// TODO: there's a lot of "extra" stuff at the end of the file. I don't think it's
	// unused, but I'm not sure how it's run.
};

RoomAction love1ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::love1Tick1 },

	{ Action(ACTION_WALK, 10, 0, 0), &Room::love1WalkToDoor3 },
	{ Action(ACTION_WALK, 0x26, 0, 0), &Room::love1WalkToDoor3 },
	{ Action(ACTION_TOUCHED_HOTSPOT, 1, 0, 0), &Room::love1OpenDoor3 },
	{ Action(ACTION_FINISHED_WALKING, 15, 0, 0), &Room::love1ReachedDoor3 },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::love1ReachedDoor3 },

	{ Action(ACTION_WALK, 8, 0, 0), &Room::love1WalkToDoor1 },
	{ Action(ACTION_WALK, 0x27, 0, 0), &Room::love1WalkToDoor1 },
	{ Action(ACTION_TOUCHED_HOTSPOT, 2, 0, 0), &Room::love1OpenDoor1 },
	{ Action(ACTION_FINISHED_WALKING, 16, 0, 0), &Room::love1ReachedDoor1 },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::love1ReachedDoor1 },

	{ Action(ACTION_WALK, 9, 0, 0), &Room::love1WalkToDoor2 },
	{ Action(ACTION_WALK, 0x28, 0, 0), &Room::love1WalkToDoor2 },
	{ Action(ACTION_TOUCHED_HOTSPOT, 3, 0, 0), &Room::love1OpenDoor2 },
	{ Action(ACTION_FINISHED_WALKING, 17, 0, 0), &Room::love1ReachedDoor2 },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::love1ReachedDoor2 },

	{ Action(ACTION_LOOK, 0x25, 0, 0), &Room::love1LookAtLaser },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::love1LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::love1LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::love1LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::love1LookAtRedshirt },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::love1LookAnywhere },
	{ Action(ACTION_LOOK, 15, 0, 0), &Room::love1LookAtNozzle },
	{ Action(ACTION_LOOK, 0x24, 0, 0), &Room::love1LookAtNozzle },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::love1LookAtLadder },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::love1LookAtDoor1Or2 },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::love1LookAtDoor1Or2 },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::love1LookAtDoor3 },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::love1LookAtDistillator },
	{ Action(ACTION_LOOK, 14, 0, 0), &Room::love1LookAtChamber },
	{ Action(ACTION_LOOK, 12, 0, 0), &Room::love1LookAtChamber },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::love1LookAtReplicator },
	{ Action(ACTION_LOOK, 11, 0, 0), &Room::love1LookAtFreezer },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::love1LookAtFreezer },
	{ Action(ACTION_LOOK, OBJECT_IDISHES, 0, 0), &Room::love1LookAtDishes },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::love1TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::love1TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::love1TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::love1TalkToRedshirt },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, OBJECT_IDISHES, 0), &Room::love1UseMTricorderOnDishes },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::love1UseMTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x23, 0), &Room::love1UseSTricorderOnReplicator },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 12, 0), &Room::love1UseSTricorderOnReplicator },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x25, 0), &Room::love1UseSTricorderOnLaser },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x25, 0), &Room::love1UseSTricorderOnLaser },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x22, 0), &Room::love1UseSTricorderOnFreezer },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::love1UseSTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, OBJECT_IDISHES, 0), &Room::love1UseSTricorderOnDishes },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x21, 0), &Room::love1UseSTricorderOnDistillator },
	{ Action(ACTION_GET, 11, 0, 0), &Room::love1GetFreezer },
	{ Action(ACTION_GET, 0x22, 0, 0), &Room::love1GetFreezer },
	{ Action(ACTION_FINISHED_WALKING, 14, 0, 0), &Room::love1KirkReachedFreezer },
	{ Action(ACTION_FINISHED_ANIMATION, 9, 0, 0), &Room::love1KirkGotVirusCulture },
	{ Action(ACTION_GET, 14, 0, 0), &Room::love1GetFromChamber },
	{ Action(ACTION_GET, 12, 0, 0), &Room::love1GetFromChamber },
	{ Action(ACTION_GET, 0x23, 0, 0), &Room::love1GetFromChamber },
	{ Action(ACTION_FINISHED_WALKING, 8, 0, 0), &Room::love1KirkReachedChamber },
	{ Action(ACTION_FINISHED_ANIMATION, 10, 0, 0), &Room::love1KirkGotCureSample },
	{ Action(ACTION_GET, 15, 0, 0), &Room::love1GetFromNozzle },
	{ Action(ACTION_GET, 0x24, 0, 0), &Room::love1GetFromNozzle },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::love1KirkReachedNozzleToGet },
	{ Action(ACTION_FINISHED_ANIMATION, 11, 0, 0), &Room::love1KirkGotBottleFromNozzle },
	{ Action(ACTION_USE, OBJECT_IN2O, 0x24, 0), &Room::love1UseN2OOnNozzle },
	{ Action(ACTION_USE, OBJECT_IH2O, 0x24, 0), &Room::love1UseH2OOnNozzle },
	{ Action(ACTION_USE, OBJECT_INH3, 0x24, 0), &Room::love1UseNH3OnNozzle },
	{ Action(ACTION_USE, OBJECT_IRLG, 0x24, 0), &Room::love1UseRLGOnNozzle },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::love1KirkReachedNozzleToPut },
	{ Action(ACTION_FINISHED_ANIMATION, 12, 0, 0), &Room::love1KirkPutBottleInNozzle },
	{ Action(ACTION_USE, -1, 0x24, 0), &Room::love1UseAnthingOnNozzle },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x23, 0), &Room::love1UseSpockOnReplicator },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x23, 0), &Room::love1UseRedshirtOnReplicator },
	{ Action(ACTION_USE, OBJECT_MCCOY, 14, 0), &Room::love1UseMccoyOnReplicator },
	{ Action(ACTION_USE, OBJECT_MCCOY, 15, 0), &Room::love1UseMccoyOnReplicator },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x23, 0), &Room::love1UseMccoyOnReplicator },
	{ Action(ACTION_FINISHED_WALKING, 4, 0, 0), &Room::love1MccoyReachedReplicator },
	{ Action(ACTION_FINISHED_ANIMATION, 13, 0, 0), &Room::love1MccoyUsedReplicator },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::love1ChamberClosed },
	{ Action(ACTION_FINISHED_ANIMATION, 8, 0, 0), &Room::love1ChamberOpened },
	{ Action(ACTION_USE, -1, 12, 0), &Room::love1UseAnythingOnChamber },
	{ Action(ACTION_USE, OBJECT_IDISHES, 12, 0), &Room::love1UseDishesOnChamber },
	{ Action(ACTION_USE, OBJECT_IDISHES, 0x23, 0), &Room::love1UseDishesOnChamber },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::love1KirkReachedChamberToPut },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::love1ChamberOpenedForDish },
	{ Action(ACTION_FINISHED_ANIMATION, 14, 0, 0), &Room::love1KirkPutDishInChamber },
	{ Action(ACTION_USE, OBJECT_IINSULAT, 0x21, 0), &Room::love1UseInsulationOnDistillator },
	{ Action(ACTION_FINISHED_WALKING, 6, 0, 0), &Room::love1KirkReachedDistillator },
	{ Action(ACTION_FINISHED_ANIMATION, 15, 0, 0), &Room::love1KirkGotPolyberylcarbonate },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x22, 0), &Room::love1UseKirkOnFreezer },
	{ Action(ACTION_USE, OBJECT_KIRK, 11, 0), &Room::love1UseKirkOnFreezer },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x22, 0), &Room::love1UseRedshirtOnFreezer },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 11, 0), &Room::love1UseRedshirtOnFreezer },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x22, 0), &Room::love1UseSpockOnFreezer },
	{ Action(ACTION_USE, OBJECT_SPOCK, 11, 0), &Room::love1UseSpockOnFreezer },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x22, 0), &Room::love1UseMccoyOnFreezer },
	{ Action(ACTION_USE, OBJECT_MCCOY, 11, 0), &Room::love1UseMccoyOnFreezer },
	{ Action(ACTION_FINISHED_WALKING, 7, 0, 0), &Room::love1CrewmanReachedFreezer },
	{ Action(ACTION_FINISHED_ANIMATION, 16, 0, 0), &Room::love1CrewmanOpenedOrClosedFreezer },
	{ Action(ACTION_USE, -1, 0x22, 0), &Room::love1UseAnythingOnFreezer },
	{ Action(ACTION_FINISHED_WALKING, 11, 0, 0), &Room::love1ReachedFreezerWithArbitraryItem },
	{ Action(ACTION_FINISHED_ANIMATION, 17, 0, 0), &Room::love1FinishedUsingArbitraryItemOnFreezer },
	{ Action(ACTION_USE, -1, 0x23, 0), &Room::love1UseAnythingOnReplicator },
	{ Action(ACTION_FINISHED_WALKING, 12, 0, 0), &Room::love1ReachedReplicatorWithArbitraryItem },
	{ Action(ACTION_FINISHED_ANIMATION, 18, 0, 0), &Room::love1FinishedUsingArbitraryItemOnReplicator },
	{ Action(ACTION_USE, -1, 0x21, 0), &Room::love1UseAnythingOnDistillator },
	{ Action(ACTION_FINISHED_WALKING, 13, 0, 0), &Room::love1ReachedDistillatorWithArbitraryItem },
	{ Action(ACTION_FINISHED_ANIMATION, 19, 0, 0), &Room::love1FinishedUsingArbitraryItemOnDistillator },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x20, 0), &Room::love1UseKirkOnLadder },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::love1UseSpockOnLadder },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x20, 0), &Room::love1UseMccoyOnLadder },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::love1UseRedshirtOnLadder },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::love1CrewmanReachedLadder },
	{ Action(ACTION_FINISHED_ANIMATION, 6, 0, 0), &Room::love1CrewmanDiedFromPhaser },
	{ Action(ACTION_TOUCHED_HOTSPOT, 0, 0, 0), &Room::love1TouchedHotspot0 },
	// TODO: common code
};

RoomAction love2ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::love2Tick1 },
	{ Action(ACTION_TOUCHED_WARP, 1, 0, 0), &Room::love2TouchedWarp1 },
	{ Action(ACTION_TIMER_EXPIRED, 3, 0, 0), &Room::love2Timer3Expired },
	{ Action(ACTION_WALK, 10, 0, 0), &Room::love2WalkToDoor },
	{ Action(ACTION_WALK, 0x22, 0, 0), &Room::love2WalkToDoor },
	{ Action(ACTION_TOUCHED_HOTSPOT, 0, 0, 0), &Room::love2TouchedHotspot0 },
	{ Action(ACTION_FINISHED_WALKING, 14, 0, 0), &Room::love2DoorReachedOrOpened },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::love2DoorReachedOrOpened },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::love2LookAtCabinet },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::love2LookAtDoor },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::love2LookAtSynthesizer },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::love2LookAtAnywhere },
	{ Action(ACTION_LOOK, 14, 0, 0), &Room::love2LookAtAntigrav },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::love2LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::love2LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::love2LookAtRedshirt },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::love2LookAtKirk },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::love2LookAtArdak },
	{ Action(ACTION_LOOK, 15, 0, 0), &Room::love2LookAtChamber },
	{ Action(ACTION_LOOK, 16, 0, 0), &Room::love2LookAtChamber },
	{ Action(ACTION_LOOK, 18, 0, 0), &Room::love2LookAtChamber },
	{ Action(ACTION_LOOK, 19, 0, 0), &Room::love2LookAtChamber },
	{ Action(ACTION_LOOK, 17, 0, 0), &Room::love2LookAtChamber },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::love2LookAtChamber },
	{ Action(ACTION_LOOK, 12, 0, 0), &Room::love2LookAtCan1 },
	{ Action(ACTION_LOOK, 13, 0, 0), &Room::love2LookAtCan2 },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::love2TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::love2TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::love2TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::love2TalkToRedshirt },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::love2UseMTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::love2UseSTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_KIRK, 8, 0), &Room::love2UseKirkOnCabinet },
	{ Action(ACTION_USE, OBJECT_SPOCK, 8, 0), &Room::love2UseSpockOnCabinet },
	{ Action(ACTION_USE, OBJECT_MCCOY, 8, 0), &Room::love2UseMccoyOnCabinet },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 8, 0), &Room::love2UseRedshirtOnCabinet },
	{ Action(ACTION_FINISHED_WALKING, 12, 0, 0), &Room::love2CrewmanReachedCabinet },
	{ Action(ACTION_FINISHED_ANIMATION, 11, 0, 0), &Room::love2CrewmanAccessedCabinet },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::love2CrewmanOpenedOrClosedCabinet },
	{ Action(ACTION_USE, OBJECT_IWRENCH, 11, 0), &Room::love2UseWrenchOnGasFeed },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::love2ReachedGasFeed },
	{ Action(ACTION_FINISHED_ANIMATION, 12, 0, 0), &Room::love2ChangedGasFeed },
	{ Action(ACTION_USE, OBJECT_IO2GAS, 0x23, 0), &Room::love2UseO2GasOnCanisterSlot },
	{ Action(ACTION_USE, OBJECT_IH2GAS, 0x23, 0), &Room::love2UseH2GasOnCanisterSlot },
	{ Action(ACTION_USE, OBJECT_IN2GAS, 0x23, 0), &Room::love2UseN2GasOnCanisterSlot },
	{ Action(ACTION_FINISHED_WALKING, 3, 0, 0), &Room::love2ReachedCanisterSlot },
	{ Action(ACTION_FINISHED_ANIMATION, 13, 0, 0), &Room::love2PutCanisterInSlot1 },
	{ Action(ACTION_FINISHED_ANIMATION, 14, 0, 0), &Room::love2PutCanisterInSlot2 },
	{ Action(ACTION_USE, OBJECT_IANTIGRA, 12, 0), &Room::love2UseAntigravOnCanister1 },
	{ Action(ACTION_FINISHED_WALKING, 4, 0, 0), &Room::love2ReachedCanisterSlot1ToGet },
	{ Action(ACTION_FINISHED_ANIMATION, 15, 0, 0), &Room::love2TookCanister1 },
	{ Action(ACTION_USE, OBJECT_IANTIGRA, 13, 0), &Room::love2UseAntigravOnCanister2 },
	{ Action(ACTION_FINISHED_WALKING, 5, 0, 0), &Room::love2ReachedCanisterSlot2ToGet },
	{ Action(ACTION_FINISHED_ANIMATION, 16, 0, 0), &Room::love2TookCanister2 },
	{ Action(ACTION_USE, OBJECT_KIRK, 0x20, 0), &Room::love2UseKirkOnSynthesizer },
	{ Action(ACTION_USE, OBJECT_SPOCK, 0x20, 0), &Room::love2UseSpockOnSynthesizer },
	{ Action(ACTION_USE, OBJECT_MCCOY, 0x20, 0), &Room::love2UseMccoyOnSynthesizer },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 0x20, 0), &Room::love2UseRedshirtOnSynthesizer },
	{ Action(ACTION_FINISHED_WALKING, 13, 0, 0), &Room::love2CrewmanReachedSynthesizer },
	{ Action(ACTION_FINISHED_ANIMATION, 17, 0, 0), &Room::love2CrewmanUsedSynthesizer },
	{ Action(ACTION_FINISHED_WALKING, 16, 0, 0), &Room::love2SpockReachedGasFeeds },
	{ Action(ACTION_FINISHED_ANIMATION, 18, 0, 0), &Room::love2SpockEnabledGasFeeds },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::love2SynthesizerDoorClosed },
	{ Action(ACTION_FINISHED_ANIMATION, 4, 0, 0), &Room::love2SynthesizerFinished },
	{ Action(ACTION_FINISHED_ANIMATION, 27, 0, 0), &Room::love2FinishedAnimation27 },

	// TODO: more

	{ Action(ACTION_USE, OBJECT_IPBC, 9, 0), &Room::love2UsePolyberylcarbonateOnSynthesizerDoor },
	{ Action(ACTION_FINISHED_WALKING, 6, 0, 0), &Room::love2KirkReachedSynthesizerWithPolyberylcarbonate },
	{ Action(ACTION_FINISHED_ANIMATION, 5, 0, 0), &Room::love2SynthesizerDoorOpenedWithPolyberylcarbonate },
	{ Action(ACTION_FINISHED_ANIMATION, 19, 0, 0), &Room::love2PutPolyberylcarbonateInSynthesizer },

	{ Action(ACTION_USE, OBJECT_IDISHES, 9, 0), &Room::love2UseDishesOnSynthesizerDoor },
	{ Action(ACTION_FINISHED_WALKING, 7, 0, 0), &Room::love2KirkReachedSynthesizerWithDishes },
	{ Action(ACTION_FINISHED_ANIMATION, 6, 0, 0), &Room::love2SynthesizerDoorOpenedWithDishes },
	{ Action(ACTION_FINISHED_ANIMATION, 20, 0, 0), &Room::love2PutDishesInSynthesizer },

	{ Action(ACTION_USE, OBJECT_ISAMPLE, 9, 0), &Room::love2UseSampleOnSynthesizerDoor },
	{ Action(ACTION_FINISHED_WALKING, 8, 0, 0), &Room::love2KirkReachedSynthesizerWithSample },
	{ Action(ACTION_FINISHED_ANIMATION, 7, 0, 0), &Room::love2SynthesizerDoorOpenedWithSample },
	{ Action(ACTION_FINISHED_ANIMATION, 21, 0, 0), &Room::love2PutSampleInSynthesizer },

	{ Action(ACTION_USE, -1, 9, 0), &Room::love2UseAnythingOnSynthesizerDoor },
	{ Action(ACTION_USE, -1, 0x20, 0), &Room::love2UseAnythingOnSynthesizer },
	{ Action(ACTION_GET, 13, 0, 0), &Room::love2GetCanister },
	{ Action(ACTION_GET, 12, 0, 0), &Room::love2GetCanister },

	{ Action(ACTION_GET, 14, 0, 0), &Room::love2GetAntigrav },
	{ Action(ACTION_FINISHED_WALKING, 9, 0, 0), &Room::love2ReachedAntigrav },
	{ Action(ACTION_FINISHED_ANIMATION, 22, 0, 0), &Room::love2GotAntigrav },

	{ Action(ACTION_GET, 16, 0, 0), &Room::love2GetPolyberylcarbonate },
	{ Action(ACTION_FINISHED_WALKING, 18, 0, 0), &Room::love2ReachedPolyberylcarbonate },
	{ Action(ACTION_FINISHED_ANIMATION, 26, 0, 0), &Room::love2GotPolyberylcarbonate },

	{ Action(ACTION_GET, 17, 0, 0), &Room::love2GetDishes },
	{ Action(ACTION_FINISHED_WALKING, 17, 0, 0), &Room::love2ReachedDishes },
	{ Action(ACTION_FINISHED_ANIMATION, 25, 0, 0), &Room::love2GotDishes },

	{ Action(ACTION_GET, 18, 0, 0), &Room::love2GetSample },
	{ Action(ACTION_FINISHED_WALKING, 19, 0, 0), &Room::love2ReachedSample },
	{ Action(ACTION_FINISHED_ANIMATION, 28, 0, 0), &Room::love2GotSample },

	{ Action(ACTION_GET, 15, 0, 0), &Room::love2GetSynthesizerOutput },
	{ Action(ACTION_FINISHED_WALKING, 10, 0, 0), &Room::love2ReachedSynthesizerOutput },
	{ Action(ACTION_FINISHED_ANIMATION, 23, 0, 0), &Room::love2GotSynthesizerOutput },

	// TODO: test these
	{ Action(ACTION_GET, 19, 0, 0), &Room::love2GetCure },
	{ Action(ACTION_FINISHED_WALKING, 11, 0, 0), &Room::love2ReachedCure },
	{ Action(ACTION_FINISHED_ANIMATION, 24, 0, 0), &Room::love2GotCure },

	// TODO: common code
};

RoomAction love3ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::love3Tick1 },
	{ Action(ACTION_TICK, 80, 0, 0), &Room::love3Tick80 },
	{ Action(ACTION_TOUCHED_WARP, 1, 0, 0), &Room::love3TouchedWarp1 },
	{ Action(ACTION_TIMER_EXPIRED, 3, 0, 0), &Room::love3Timer3Expired },
	{ Action(ACTION_LOOK, 8, 0, 0), &Room::love3LookAtServicePanel },
	{ Action(ACTION_LOOK, 0x21, 0, 0), &Room::love3LookAtMonitor },
	{ Action(ACTION_LOOK, 10, 0, 0), &Room::love3LookAtWrench },
	{ Action(ACTION_LOOK, OBJECT_KIRK, 0, 0), &Room::love3LookAtKirk },
	{ Action(ACTION_LOOK, OBJECT_MCCOY, 0, 0), &Room::love3LookAtMccoy },
	{ Action(ACTION_LOOK, OBJECT_SPOCK, 0, 0), &Room::love3LookAtSpock },
	{ Action(ACTION_LOOK, OBJECT_REDSHIRT, 0, 0), &Room::love3LookAtRedshirt },
	{ Action(ACTION_LOOK, -1, 0, 0), &Room::love3LookAnywhere },
	{ Action(ACTION_LOOK, 0x22, 0, 0), &Room::love3LookAtShaft },
	{ Action(ACTION_LOOK, 9, 0, 0), &Room::love3LookAtPanel },
	{ Action(ACTION_LOOK, 0x20, 0, 0), &Room::love3LookAtPanel },
	{ Action(ACTION_LOOK, 12, 0, 0), &Room::love3LookAtGasTank },
	{ Action(ACTION_LOOK, 0x23, 0, 0), &Room::love3LookAtTurbines },
	{ Action(ACTION_TALK, OBJECT_KIRK, 0, 0), &Room::love3TalkToKirk },
	{ Action(ACTION_TALK, OBJECT_SPOCK, 0, 0), &Room::love3TalkToSpock },
	{ Action(ACTION_TALK, OBJECT_MCCOY, 0, 0), &Room::love3TalkToMccoy },
	{ Action(ACTION_TALK, OBJECT_REDSHIRT, 0, 0), &Room::love3TalkToRedshirt },
	{ Action(ACTION_USE, OBJECT_IMTRICOR, -1, 0), &Room::love3UseMTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 0x23, 0), &Room::love3UseSTricorderOnTurbines },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, 9, 0), &Room::love3UseSTricorderOnInsulation },
	{ Action(ACTION_USE, OBJECT_ISTRICOR, -1, 0), &Room::love3UseSTricorderAnywhere },
	{ Action(ACTION_USE, OBJECT_KIRK, 8, 0), &Room::love3UseKirkOnServicePanel },
	{ Action(ACTION_USE, OBJECT_SPOCK, 8, 0), &Room::love3UseSpockOnServicePanel },
	{ Action(ACTION_USE, OBJECT_MCCOY, 8, 0), &Room::love3UseMccoyOnServicePanel },
	{ Action(ACTION_USE, OBJECT_REDSHIRT, 8, 0), &Room::love3UseRedshirtOnServicePanel },
	{ Action(ACTION_FINISHED_WALKING, 1, 0, 0), &Room::love3CrewmanReachedServicePanel },
	{ Action(ACTION_FINISHED_ANIMATION, 1, 0, 0), &Room::love3OpenedOrClosedServicePanel },
	{ Action(ACTION_USE, OBJECT_IWRENCH, 12, 0), &Room::love3UseWrenchOnGasTank },
	{ Action(ACTION_FINISHED_WALKING, 2, 0, 0), &Room::love3ReachedGasTankToUnscrew },
	{ Action(ACTION_FINISHED_ANIMATION, 2, 0, 0), &Room::love3ScrewedOrUnscrewedGasTank },
	{ Action(ACTION_USE, OBJECT_IWRENCH, OBJECT_IO2GAS, 0), &Room::love3UseWrenchOnO2OrH2Gas },
	{ Action(ACTION_USE, OBJECT_IWRENCH, OBJECT_IH2GAS, 0), &Room::love3UseWrenchOnO2OrH2Gas },
	{ Action(ACTION_USE, OBJECT_IWRENCH, OBJECT_IN2GAS, 0), &Room::love3UseWrenchOnN2Gas },
	{ Action(ACTION_FINISHED_WALKING, 15, 0, 0), &Room::love3ReachedGasTankToPutDown },
	{ Action(ACTION_FINISHED_ANIMATION, 3, 0, 0), &Room::love3PutN2TankBack },
};

RoomAction love4ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::love4Tick1 },
};

RoomAction love5ActionList[] = {
	{ Action(ACTION_TICK, 1, 0, 0), &Room::love5Tick1 },
};


}

#endif
