begin_section("AGS");
	add_person("Paul Gilbert", "dreammaster", "");
	add_person("Thierry Crozat", "criezy", "");
	add_person("Chris Jones", "Pumaman", "Creator");
	add_person("Alan Van Drake", "", "AGS");
	add_person("Benjamin Penney", "", "AGS");
	add_person("Benoit Pierre", "", "AGS");
	add_person("Bernhard Rosenkraenzer", "", "AGS");
	add_person("Cristian Morales Vega", "", "AGS");
	add_person("Edward Rudd", "", "AGS");
	add_person("Erico Vieira Porto", "", "AGS");
	add_person("Ferdinand Thiessen", "", "AGS");
	add_person("Francesco Ariis", "", "AGS");
	add_person("Gilad Shaham", "", "AGS");
	add_person("Ivan Mogilko", "", "AGS");
	add_person("Janet Gilbert", "", "AGS");
	add_person("Jochen Schleu", "", "AGS");
	add_person("Joe Lee", "", "AGS");
	add_person("John Steele Scott", "", "AGS");
	add_person("Martin Sedlak", "", "AGS");
	add_person("Matthew Gambrell", "", "AGS");
	add_person("Michael Rittenhouse", "", "AGS");
	add_person("Morgan Willcock", "", "AGS");
	add_person("Nick Sonneveld", "", "AGS");
	add_person("Ori Avtalion", "", "AGS");
	add_person("Paul Wilkinson", "", "AGS");
	add_person("Per Olav Flaten", "", "AGS");
	add_person("Piotr Wieczorek", "", "AGS");
	add_person("Ryan O'Connor", "", "AGS");
	add_person("Scott Baker", "", "AGS");
	add_person("Shane Stevens", "", "AGS");
	add_person("Shawn R. Walker", "", "AGS");
	add_person("Stefano Collavini", "", "AGS");
	add_person("Steve McCrea", "", "AGS");
	add_person("Steven Poulton", "", "AGS");
	add_person("Sunit Das", "", "AGS");
	add_person("Tobias Hansen", "", "AGS");
	add_person("Tom Vandepoele", "", "AGS");
	add_person("Tzach Shabtay", "", "AGS");
	add_person("", "rofl0r", "AGS");
	add_person("Berian Williams", "AGA", "AgsCreditz");
end_section();
